SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[USP_ASM_MC_RETAIL_REFRESH] AS
BEGIN
/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|					CHANGE DESCRIPTION					*/
/*--------------------------------------------------------------------------------------------------*/
/*	2024-09-20 	|	Nikita L		| ADDED First Source LeadType field        			*/
/*	2024-12-01 	|	Nikita L		| Added SalesPersonEmail in Retail Dim      			*/
/*	2025-08-04 	|	Ashwini Ahire		| Added CityBV and DPP update    			*/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/

--Retail Dim & Fact:
--Retail Dim:
--Truncate table ASM_MC_RETAIL_DIM
INSERT INTO ASM_MC_RETAIL_DIM
SELECT DISTINCT 
RH.HEADERID AS PK_RETAILHEADERID,
CAST(RH.DOCDATE AS DATE) AS RETAILDATE,
--RLE.FINANCECATEGORY AS RETAILFINANCIERCATEGORY, -- Comment on 07.03.2023
FM.FINANCECATEGORY AS RETAILFINANCIERCATEGORY, -- Added  on 07.03.2023
RH.MODEOFPURCHASE AS MODEOFPURCHASE,
ENQUIRY_HEADER.CUSTOMEROWNERSHIPPROFILEID AS ENQUIRYCUSTOMEROWNERSHIP,
--RH.FINANCECOMPANY AS FINANCECOMPANY, -- Commented on 27.02.2023
FM.FINANCECOMPANY AS FINANCECOMPANY, -- Added on 27.02.2023
--ENQUIRY_HEADER.EXCHANGEAPPLICABLE AS EXCHANGESTATUS, -- Comment on 07.03.2023
RH.ISEXCHANGEAPPLICABLE AS EXCHANGESTATUS,-- Added on 07.03.2023
RH.INSURANCECOMPANY AS INSURER_DETAIL,
Cast('' as varchar(200)) As EXCHANGED_MODEL,
GETDATE() AS CREATEDDATETIME,
RH.IMPORTEDDATE,
RH.CDMS_BATCHNO,
(CASE
	WHEN ISNULL(RETAIL_HEADER_EXT.IsInstitutionalSale,0) = 1
	AND RH.DocType NOT IN (441,1000088) THEN 'Institutional'
	WHEN ISNULL(RETAIL_HEADER_EXT.IsInstitutionalSale,0) = 0 AND Len(BRANCH_MASTER.Code) = 10 
	AND SUBSTRING(BRANCH_MASTER.Code,0,6) = '00000' 
	AND ((SUBSTRING(BRANCH_MASTER.Code,6,6) BETWEEN '10000' AND '14000') 
	OR (SUBSTRING(BRANCH_MASTER.Code,6,6) = '25669'))  AND RH.DocType NOT IN (441,1000088) THEN 'Showroom'
	ELSE 'Command Area' 
	END) AS SALESCHANNEL,
101 AS FLAG,
CASE WHEN RH.DOCTYPE = 441 THEN 'AVSI'
WHEN RH.DOCTYPE = 1012462 THEN 'ASDA'
ELSE Cast(NULL as varchar(500)) END As RETAIL_LEAD_TYPE,
NULL AS SalesPersonEmail
--INTO ASM_MC_RETAIL_DIM
FROM 
RETAIL_HEADER RH INNER JOIN COMPANY_MASTER ON (RH.COMPANYID=COMPANY_MASTER.COMPANYID AND COMPANY_MASTER.COMPANYTYPE IN (1,8))
INNER JOIN BRANCH_MASTER ON (RH.BRANCHID=BRANCH_MASTER.BRANCHID)
INNER JOIN RETAIL_LINE ON (RH.HEADERID=RETAIL_LINE.DOCID)
LEFT JOIN BOOKING_LINE ON (RETAIL_LINE.BOOKINGDATALINEID=BOOKING_LINE.LINEID)
LEFT JOIN ENQUIRY_LINE ON (BOOKING_LINE.ENQUIRYDATALINEID=ENQUIRY_LINE.LINEID)
LEFT JOIN ENQUIRY_HEADER ON (ENQUIRY_LINE.DOCID=ENQUIRY_HEADER.HEADERID)
LEFT JOIN RETAIL_LINE_EXT RLE ON (RETAIL_LINE.LINEID=RLE.LINEID)
LEFT JOIN FINANCER_MASTER FM ON (RLE.FINANCERCONTACTID=FM.FINANCERID AND FM.ID = (SELECT MAX(FM1.ID) FROM FINANCER_MASTER FM1 WHERE FM.FINANCERID = FM1.FINANCERID)) -- Added on 27.02.2023
LEFT OUTER JOIN RETAIL_HEADER_EXT ON (RH.HEADERID=RETAIL_HEADER_EXT.HEADERID)
WHERE
--CAST(RH.DOCDATE AS DATE) >= '2020-04-01' AND
RH.DOCTYPE IN(141,1000079,1000317,1012739,441,1012462)
--AND RH.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_MC_RETAIL_DIM)
AND CAST(RH.IMPORTEDDATE AS DATE) >=  CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_MC_RETAIL_DIM) AS DATE) --UPDATED ON 12/06



DELETE FROM ASM_MC_RETAIL_DIM WHERE RETAILDATE>Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date)

--Dedup

  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_RETAILHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_MC_RETAIL_DIM                   
 )
DELETE FROM CTE                  
 WHERE RNK<>1;   -- (15867 rows affected)

--************************************************************************************
--TRUNCATE table ASM_MC_RETAIL_EXCHANGE_MODEL

INSERT INTO ASM_MC_RETAIL_EXCHANGE_MODEL
SELECT DISTINCT
RH.HEADERID AS PK_RETAILHEADERID,
COMPETITOR_ITEM_MASTER.NAME AS EXCHANGED_MODEL,
GETDATE() AS CREATEDDATETIME,
RH.DOCDATE,
RH.IMPORTEDDATE
--INTO ASM_MC_RETAIL_EXCHANGE_MODEL
FROM 
RETAIL_HEADER RH
INNER JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
LEFT JOIN RETAIL_LINE_EXT RLE ON (RL.LINEID=RLE.LINEID)
INNER JOIN COMPETITOR_ITEM_MASTER ON (RLE.EXCHANGEMODELID = COMPETITOR_ITEM_MASTER.COMPETITORITEMID)
INNER JOIN COMPANY_MASTER ON (RH.COMPANYID=COMPANY_MASTER.COMPANYID AND COMPANY_MASTER.COMPANYTYPE IN (1,8))
WHERE
RH.DOCTYPE IN(141,1000079,1000317,1012739,441) 
--AND CAST(RH.DOCDATE AS DATE) >= '2020-04-01'
--AND RH.IMPORTEDDATE>( SELECT MAX(IMPORTEDDATE)  FROM ASM_MC_RETAIL_EXCHANGE_MODEL)
AND CAST(RH.IMPORTEDDATE AS DATE) >=   CAST((SELECT MAX(IMPORTEDDATE)  FROM ASM_MC_RETAIL_EXCHANGE_MODEL) AS DATE) --UPDATED ON 12/06


					  
DELETE FROM ASM_MC_RETAIL_EXCHANGE_MODEL WHERE Cast(DOCDATE As Date)>Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date)

--Dedup

  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_RETAILHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_MC_RETAIL_EXCHANGE_MODEL                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;   

--Update Retail Dim for Exchange Model:

UPDATE A SET A.EXCHANGED_MODEL=B.EXCHANGED_MODEL
FROM 
ASM_MC_RETAIL_EXCHANGE_MODEL B JOIN ASM_MC_RETAIL_DIM A ON A.PK_RETAILHEADERID=B.PK_RETAILHEADERID

--*************************************************************************************
--ASM_MC_INSTITUTIONAL_DIM
TRUNCATE TABLE ASM_MC_INSTITUTIONAL_DIM
INSERT INTO ASM_MC_INSTITUTIONAL_DIM
SELECT DISTINCT 
SB.BILLINGDOC AS PK_RETAILHEADERID,
CAST(SB.DOCDATE AS DATE) AS RETAILDATE,
Cast('' as varchar(50)) AS RETAILFINANCIERCATEGORY, -- Added  on 07.03.2023
Cast('' as varchar(50)) AS MODEOFPURCHASE,
NULL AS ENQUIRYCUSTOMEROWNERSHIP,
NULL AS FINANCECOMPANY,
Cast('' as varchar(50)) AS EXCHANGESTATUS,-- Added on 07.03.2023
Cast('' as varchar(50)) AS INSURER_DETAIL,
Cast('' as varchar(50)) As EXCHANGED_MODEL,
GETDATE() AS CREATEDDATETIME,
NULL AS IMPORTEDDATE,
NULL AS CDMS_BATCHNO,
'Institutional' AS SALESCHANNEL,
102 AS FLAG,
Cast('' as varchar(50)) As RETAIL_LEAD_TYPE,
NULL AS SalesPersonEmail
--INTO ASM_MC_INSTITUTIONAL_DIM
FROM SAP_BILLING SB
WHERE CAST(SB.DOCDATE AS DATE) >= '2020-04-01'
AND DIVISION='B2' and [Distr.Chnl] IN ('40') and CANCELLED<>'X'



--*************************************************************************************
--INSERT INSTITUTIONAL_DIM IN RETAIL_DIM
DELETE  FROM ASM_MC_RETAIL_DIM WHERE FLAG = 102

INSERT INTO ASM_MC_RETAIL_DIM
SELECT * FROM ASM_MC_INSTITUTIONAL_DIM

--*************************************************************************************

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--Retail Fact LOAD:
--truncate table ASM_MC_RETAIL_STG

INSERT INTO ASM_MC_RETAIL_STG
SELECT DISTINCT
CM.CODE AS DEALERCODE,
IM.CODE+IV.CODE As SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10002 As FK_TYPE_ID,
CAST(RH.DOCDATE as Date) AS DATE,
RL.LINEID AS RETAILLINEID,
RL.DOCID AS FK_RETAILDOCID,
CM.COMPANYTYPE AS COMPANYTYPE,
RH.BRANCHID,
Count(Distinct RL.SERIALNO) as ACTUALQUANTITY,
0 AS TARGETQUANTITY,  
getdate() as LASTUPDATEDDATETIME,
RH.IMPORTEDDATE,
RH.CDMS_BATCHNO,
(LEFT(DATENAME( MONTH,RH.DOCDATE),3)+'-'+Cast(Year(RH.DOCDATE) as varchar(4))) As PERIODNAME,
IV.CODE As COLOUR_CODE,
IM.CODE As MODELCODE,
Cast(0 as int) as FK_MODEL,
100021 As FLAG,
Cast(0 as int) as IsSaleReturn,
RH.TEHSIL3W AS TEHSILID,
COALESCE (REPLACE(NULLIF(RHE.SALESPERSONNAME,''),CHAR(160),''),CONCAT(TRIM(CN.FIRSTNAME),' ',TRIM(CN.LASTNAME))) AS SALES_PERSON,
CASE WHEN RH.DOCTYPE = 441 THEN 'AVSI'
     WHEN RH.DOCTYPE = 1012462 THEN 'ASDA'
ELSE Cast(NULL as varchar(40)) END  As LEADTYPE,
CM.CODE AS ASD_DEALERCODE,
CASE WHEN RH.DOCTYPE = 441 THEN 'AVSI'
	 WHEN RH.DOCTYPE = 141 THEN 'VSI'
     WHEN RH.DOCTYPE = 1012462 THEN 'ASDA'
     ELSE '' END  As Tran_Type,			  
Cast(null as decimal(19,0)) As ASD_BRANCHID										   
--INTO ASM_MC_RETAIL_STG
FROM
   RETAIL_HEADER RH JOIN COMPANY_MASTER CM ON (RH.COMPANYID=CM.COMPANYID AND CM.COMPANYTYPE IN (1,8))
   LEFT JOIN CONTACT_MASTER CN ON (RH.SALESPERSONID = CN.CONTACTID AND CN.ID = (SELECT MAX(CN1.ID) FROM CONTACT_MASTER CN1 WHERE CN.CONTACTID = CN1.CONTACTID))
   JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
   JOIN ITEM_MASTER IM ON (IM.ItemId=RL.ItemID)
   LEFT JOIN ITEMVARMATRIX_MASTER IV ON (RL.VARMATRIXID=IV.ITEMVARMATRIXID)
   LEFT JOIN SAP_ZDEALER_TARGET ON (CM.CODE=SAP_ZDEALER_TARGET.DEALER_CODE and MONTH(RH.DOCDATE)=SAP_ZDEALER_TARGET.ZMONTH and YEAR(RH.DOCDATE)=SAP_ZDEALER_TARGET.ZYEAR)
   LEFT JOIN RETAIL_HEADER_EXT RHE ON (RH.HEADERID = RHE.HEADERID)
 --SAP_ZDEALER_TARGET
WHERE 
    --CAST(RH.DOCDATE AS DATE) >= '2020-04-01'
	RH.DOCTYPE IN(141,1000079,1000317,1012739,441,1012462)
--AND RH.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_MC_RETAIL_STG)
AND CAST(RH.IMPORTEDDATE AS DATE) >= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_MC_RETAIL_STG) AS DATE)  --UPDATED ON 12/06
GROUP BY
   CM.CODE,
   IM.CODE+IV.CODE,
   CAST(RH.DOCDATE as Date),  
   RL.LINEID,
   RL.DOCID,
   CM.COMPANYTYPE,
   RH.BRANCHID,
   RH.IMPORTEDDATE,  
   RH.CDMS_BATCHNO,
   (LEFT(DATENAME( MONTH,RH.DOCDATE),3)+'-'+Cast(Year(RH.DOCDATE) as varchar(4))),
   IV.CODE,
   IM.CODE,
   RH.TEHSIL3W,
   COALESCE (REPLACE(NULLIF(RHE.SALESPERSONNAME,''),CHAR(160),''),CONCAT(TRIM(CN.FIRSTNAME),' ',TRIM(CN.LASTNAME))),
   RH.DOCTYPE

     --

DELETE FROM ASM_MC_RETAIL_STG WHERE DATE>Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date)


----Retaurn Logic:
--Alter table ASM_MC_RETAIL_STG add IsSaleReturn int
--update ASM_MC_RETAIL_STG set IsSaleReturn=0
--Return Data Preparation
SELECT RL.SALEINVOICELINEID,RL.SERIALNO INTO #ReturnData_MC 
FROM 
RETAIL_LINE_RETURN RL INNER JOIN ASM_MC_RETAIL_STG RD ON RD.RETAILLINEID=RL.SALEINVOICELINEID

--Return Data Flag Updation
UPDATE RD
SET RD.IsSaleReturn=1
FROM ASM_MC_RETAIL_STG RD INNER JOIN #ReturnData_MC RL ON RL.SALEINVOICELINEID=RD.RETAILLINEID

--select distinct IsSaleReturn,Count(1) from ASM_MC_RETAIL_STG Group By IsSaleReturn
 
 --Dedup Process:
   ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY FK_RETAILDOCID,RETAILLINEID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_MC_RETAIL_STG                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 
 --************************************************UPDATE DEALERCODE FOR ASD ALLOCATION RETAIL
 SELECT * INTO #DealerASDMapping FROM
(SELECT DISTINCT ZF_ASC ASD_DEALERCODE,DEALER_CODE DEALERCODE
FROM SAP_ZSD_ASC_DETAIL
WHERE SER_STATUS = 'OPERATIONAL')T

UPDATE B
SET B.Dealercode=A.DEALERCODE
FROM ASM_MC_RETAIL_STG B
INNER JOIN #DealerASDMapping A ON B.ASD_DealerCode=A.ASD_DEALERCODE
WHERE B.COMPANYTYPE IN (1,8)
--**************************************************UPDATE BRANCHID for ASD BILLING
SELECT DISTINCT RS.FK_RETAILDOCID,BM.BRANCHID
INTO #ASD_BILLING_BRANCH
FROM ASM_MC_RETAIL_STG RS
JOIN RETAIL_HEADER RH ON RH.HEADERID = RS.FK_RETAILDOCID
JOIN CONTACT_MASTER CM ON CM.CONTACTID = RH.CONTACTID
JOIN BRANCH_MASTER BM ON BM.CODE = CM.CODE
WHERE RH.DOCTYPE = 441 AND CM.CODE LIKE '00000[0-9][0-9][0-9][0-9][0-9]' AND
CAST(CM.CODE AS INT) > 20000 

UPDATE RS
SET ASD_BRANCHID = AB.BRANCHID
FROM ASM_MC_RETAIL_STG RS INNER JOIN #ASD_BILLING_BRANCH AB ON RS.FK_RETAILDOCID=AB.FK_RETAILDOCID

--***
--***************************************************************************************************************************
  -- Step 2:

-- Product Master and Dealer Master FK update: ASM_MC_RETAIL_STG
--update B set B.FK_SKU=C.PK_SKU from ASM_MC_RETAIL_STG B INNER JOIN ASM_MC_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE) -- (4976425 rows affected)
--update B set B.FK_MODEL=C.PK_Model_Code from ASM_MC_RETAIL_STG B INNER JOIN ASM_MC_PRODUCT_DIM C on (B.MODELCODE=C.MODELCODE) -- (4976425 rows affected)
--update B set B.FK_DEALERCODE=C.PK_DEALERCODE from[dbo].ASM_MC_RETAIL_STG B INNER JOIN ASM_MC_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE) -- (4976425 rows affected)


--****************************************************************************************************************************

--***************************************************************************
 -- Step 3 :

-- Target Data: RETAIL

TRUNCATE TABLE ASM_MC_RETAIL_TARGET

INSERT INTO ASM_MC_RETAIL_TARGET
SELECT Distinct 
DEALER AS DEALERCODE
,SAP_ZSD_SKU_PLAN.SKU
,Cast('' as int) as FK_DEALERCODE
,Cast('' as int) as FK_SKU
,10002 As FK_TYPE_ID
,Cast(convert(datetime, replace((LEFT(SAP_ZSD_SKU_PLAN.CMONTH,3)+' '+CAST(SAP_ZSD_SKU_PLAN.CYEAR AS VARCHAR(4))), '-', ' ')) as date) As DATE
,Cast(null as decimal(19,0)) As RETAILLINEID
,Cast(null as decimal(19,0)) As FK_RETAILDOCID
,Cast(null as decimal(19,0)) As COMPANYTYPE
,Cast(null as decimal(19,0)) As BRANCHID
,Cast(null as decimal(10,0)) As ACTUALQUANTITY
,Round(Sum(RET_SKU_QUANTITY),0) As TARGETQUANTITY
,getdate() as LASTUPDATEDDATETIME
,Cast(null as DATE) As IMPORTEDDATE
,Cast(0 as decimal(19,0)) As CDMS_BATCHNO
,(CAST(SAP_ZSD_SKU_PLAN.CMONTH as char(4))+''+CAST(SAP_ZSD_SKU_PLAN.CYEAR as char(4))) AS PERIODNAME
,RIGHT(SAP_ZSD_SKU_PLAN.SKU,2) As COLOUR_CODE
,LEFT(SAP_ZSD_SKU_PLAN.SKU,6) AS MODELCODE
,Cast('' as int) As FK_MODEL
,100022 As FLAG
,Cast(0 as int) as IsSaleReturn
,Cast(null as decimal(19,0)) As TEHSILID
,NULL AS SALESPERSON,
Cast('' as varchar(40)) As LEADTYPE
,'' AS Tran_Type
--INTO ASM_MC_RETAIL_TARGET
FROM
SAP_ZSD_SKU_PLAN
WHERE 
Cast(convert(datetime, replace((LEFT(SAP_ZSD_SKU_PLAN.CMONTH,3)+' '+CAST(SAP_ZSD_SKU_PLAN.CYEAR AS VARCHAR(4))), '-', ' ')) as date)< Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date)
--AND BU IN ('2WH') AND DEALER < '0000015000'
AND DEALER IN (SELECT DISTINCT DEALERCODE FROM ASM_MC_DEALER_MASTER_DIM)
GROUP BY
DEALER,
SAP_ZSD_SKU_PLAN.SKU,
Cast(convert(datetime, replace((LEFT(SAP_ZSD_SKU_PLAN.CMONTH,3)+' '+CAST(SAP_ZSD_SKU_PLAN.CYEAR AS VARCHAR(4))), '-', ' ')) as date),
DATALOADTIME,
(CAST(SAP_ZSD_SKU_PLAN.CMONTH as char(4))+''+CAST(SAP_ZSD_SKU_PLAN.CYEAR as char(4))),
RIGHT(SAP_ZSD_SKU_PLAN.SKU,2),
LEFT(SAP_ZSD_SKU_PLAN.SKU,6) -- (3831729 rows affected)


--************************************************************
-- Product Master and Dealer Master FK update: ASM_MC_RETAIL_TARGET

-- Step 4:
--update B set B.FK_SKU=C.PK_SKU from ASM_MC_RETAIL_TARGET B INNER JOIN ASM_MC_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE) -- (2492285 rows affected)
--update B set B.FK_MODEL=C.PK_Model_Code from ASM_MC_RETAIL_TARGET B INNER JOIN ASM_MC_PRODUCT_DIM C on (B.MODELCODE=C.MODELCODE) -- (2492285 rows affected)
--update B set B.FK_DEALERCODE=C.PK_DEALERCODE from ASM_MC_RETAIL_TARGET B INNER JOIN ASM_MC_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE) -- (2174576 rows affected)

--*******************************************************************************************************************
--Step 5:
TRUNCATE TABLE ASM_MC_INSTITUTIONAL_STG
INSERT INTO ASM_MC_INSTITUTIONAL_STG
SELECT DISTINCT
'0000'+SAP_BILLING.DEALERCODE AS DEALERCODE,
SAP_BILLING.MATERIAL as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10002 As FK_TYPE_ID,
SAP_BILLING.DOCDATE AS DATE,
Cast(null as decimal(19,0)) As RETAILLINEID,
SAP_BILLING.BILLINGDOC As FK_RETAILDOCID,
Cast(null as decimal(19,0)) As COMPANYTYPE,
Cast(null as decimal(19,0)) As BRANCHID,
Sum(SAP_BILLING.BILLQTY) as ACTUALQUANTITY,
0 AS TARGETQUANTITY,  
getdate() as LASTUPDATEDDATETIME,
Cast(null as DATE) As IMPORTEDDATE,
Cast(0 as decimal(19,0)) As CDMS_BATCHNO,
(LEFT(DATENAME( MONTH,DOCDATE),3)+'-'+Cast(Year(DOCDATE) as varchar(4))) As PERIODNAME,
RIGHT(SAP_BILLING.MATERIAL,2) As COLOUR_CODE,
LEFT(SAP_BILLING.MATERIAL,6) As MODELCODE,
Cast(0 as int) as FK_MODEL,
100023 As FLAG,
Cast(0 as int) as IsSaleReturn,
NULL AS TEHSILID,
NULL AS SALESPERSON,
Cast('' as varchar(40)) As LEADTYPE,
'INST' as Tran_Type
--INTO ASM_MC_INSTITUTIONAL_STG
FROM SAP_BILLING
WHERE 
SAP_BILLING.DOCDATE >= '2020-04-01' AND
DIVISION='B2' and [Distr.Chnl] IN('40') and CANCELLED<>'X'
GROUP BY SAP_BILLING.DEALERCODE,
SAP_BILLING.BILLINGDOC,
SAP_BILLING.MATERIAL,
SAP_BILLING.DOCDATE,
LEFT(SAP_BILLING.MATERIAL,6),
RIGHT(SAP_BILLING.MATERIAL,2),
LEFT(DATENAME( MONTH,DOCDATE),3)+'-'+Cast(Year(DOCDATE) as varchar(4))


--update B set B.FK_SKU=C.PK_SKU from ASM_MC_INSTITUTIONAL_STG B INNER JOIN ASM_MC_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE)
--update B set B.FK_MODEL=C.PK_Model_Code from ASM_MC_INSTITUTIONAL_STG B INNER JOIN ASM_MC_PRODUCT_DIM C on (B.MODELCODE=C.MODELCODE)
--update B set B.FK_DEALERCODE=C.PK_DEALERCODE from ASM_MC_INSTITUTIONAL_STG B INNER JOIN ASM_MC_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE)




--************************************************************************************************
-- Step 6:

TRUNCATE TABLE ASM_MC_RETAIL_FACT

INSERT INTO ASM_MC_RETAIL_FACT
SELECT
Distinct
DEALERCODE
,SKU
,FK_DEALERCODE
,FK_SKU
,FK_TYPE_ID
,DATE
,RETAILLINEID
,FK_RETAILDOCID
,COMPANYTYPE
,COALESCE(ASD_BRANCHID,BRANCHID) BRANCHID
,ACTUALQUANTITY
,TARGETQUANTITY
,LASTUPDATEDDATETIME
,IMPORTEDDATE
,CDMS_BATCHNO
,PERIODNAME
,COLOUR_CODE
,MODELCODE
,FK_MODEL
,FLAG
,IsSaleReturn
,TEHSILID
,SALESPERSON
,LEADTYPE
,TRAN_TYPE
,NULl as  First_Source_Lead_Type -- Post Update In Digital Leads SP
,NULl as  First_Mode_Source -- Post Update In Digital Leads SP
,NULl as  First_Mode_SubSource  -- Post Update In Digital Leads SP
,NULL as CityBV
,NULL As DPP
,NULL AS BU
,NULL as Grouped_dealercode
FROM ASM_MC_RETAIL_STG  
Where IsSaleReturn<>1
UNION
SELECT *,NULL as  First_Source_Lead_Type,Null As First_Mode_Source,Null As First_Mode_SubSource ,NULL as CityBV,NULL As DPP , NULL as BU, NULL as Grouped_dealercode
FROM ASM_MC_INSTITUTIONAL_STG
UNION
SELECT *,NULL as  First_Source_Lead_Type,Null As First_Mode_Source,Null As First_Mode_SubSource
,NULL as CityBV,NULL As DPP , NULL as BU, NULL as Grouped_dealercode
from ASM_MC_RETAIL_TARGET
--********************************************************************************************************************
--************************************RETAIL FACT & DIM: POST UPDATE FOR LEADTYPE*******************************************
SELECT DISTINCT PK_RETAILHEADERID,ISNULL(LEAD_TYPE_CDMS,LEAD_TYPE_LSQ) LEAD_TYPE, SalesPersonEmail,First_Source_Lead_Type,First_Mode_Source,First_Mode_SubSource
INTO #LEAD_TYPE_RETAIL
FROM
(SELECT DISTINCT PK_RETAILHEADERID,ISNULL(LEADTYPE1,LEADTYPE2) LEAD_TYPE_CDMS,ISNULL(LEADTYPE3,LEADTYPE4) LEAD_TYPE_LSQ, SalesPersonEmail,First_Source_Lead_Type,First_Mode_Source,First_Mode_SubSource
FROM
(SELECT DISTINCT PK_RETAILHEADERID,EH1.LEADTYPE LEADTYPE1,EH2.LEADTYPE LEADTYPE2,COALESCE(LSQ_PBASE1.mx_Enquiry_Mode,LSQ_PBASE1.mx_Mode_of_Enquiry) LEADTYPE3,COALESCE(LSQ_PBASE2.mx_Enquiry_Mode,LSQ_PBASE2.mx_Mode_of_Enquiry) LEADTYPE4,
 COALESCE (LU1.EmailAddress,LU2.EmailAddress,case when CN.MOBILE is not null then CONCAT(CN.MOBILE,'@bajajauto.co.in') end ) as SalesPersonEmail,
 CASE WHEN coalesce(CAST(PEX1.MX_DEALER_ASSIGNMENT_DATE AS DATE),CAST(PEX2.MX_DEALER_ASSIGNMENT_DATE AS DATE))>='2024-12-01' THEN coalesce(EH1.LEADTYPE,EH2.LEADTYPE,PE1.mx_Qualified_First_Source ,PE2.mx_Qualified_First_Source) END AS First_Source_Lead_Type,
  ISNULL( coalesce(PE1.mx_Qualified_Source_of_Enquiry,PE2.mx_Qualified_Source_of_Enquiry),'Not Available') AS First_Mode_Source,
  ISNULL (coalesce(PE1.mx_Qualified_Sub_Source,PE2.mx_Qualified_Sub_Source), 'Not Available') AS First_Mode_SubSource
FROM 
ASM_MC_RETAIL_DIM RETAIL_DIM
INNER JOIN  RETAIL_HEADER RH ON (RH.HEADERID=RETAIL_DIM.PK_RETAILHEADERID)
LEFT JOIN CONTACT_MASTER CN ON (RH.SALESPERSONID = CN.CONTACTID AND CN.ID = (SELECT MAX(CN1.ID) FROM CONTACT_MASTER CN1 WHERE CN.CONTACTID = CN1.CONTACTID))
LEFT JOIN RETAIL_LINE RL1 ON (RH.HEADERID=RL1.DOCID)
LEFT JOIN ALLOCATION_LINE AL ON (AL.LINEID=RL1.ALLOCATIONDATALINEID)
LEFT JOIN BOOKING_LINE BL1 ON  (BL1.LINEID=AL.BOOKINGDATALINEID)
LEFT JOIN RETAIL_LINE RL2 ON RL2.DOCID = RH.HEADERID
LEFT JOIN BOOKING_LINE BL2 ON RL2.BOOKINGDATALINEID = BL2.LINEID
LEFT JOIN ENQUIRY_LINE EL1 ON EL1.LINEID = BL1.ENQUIRYDATALINEID
LEFT JOIN ENQUIRY_LINE EL2 ON EL2.LINEID = BL2.ENQUIRYDATALINEID
LEFT JOIN ENQUIRY_HEADER EH1 ON EH1.HEADERID = EL1.DOCID
LEFT JOIN ENQUIRY_HEADER EH2 ON EH2.HEADERID = EL2.DOCID
LEFT JOIN BOOKING_HEADER_EXT BHE1 ON (BL1.HEADERID = BHE1.HEADERID)
LEFT JOIN BOOKING_HEADER_EXT BHE2 ON (BL2.HEADERID = BHE2.HEADERID)
LEFT JOIN LSQ_ProspectActivity_ExtensionBase PAE1 ON (Cast(PAE1.RelatedProspectId+','+PAE1.ProspectActivityExtensionId as varchar(8000))=BHE1.LMSBOOKINGID) and PAE1.ActivityEvent=12002 
--and PAE1.mx_Custom_48 IS NULL
LEFT JOIN LSQ_Prospect_Base LSQ_PBASE1 ON (LSQ_PBASE1.ProspectID=PAE1.RelatedProspectId)
LEFT JOIN LSQ_ProspectActivity_ExtensionBase PAE2 ON (Cast(PAE2.RelatedProspectId+','+PAE2.ProspectActivityExtensionId as varchar(8000))=BHE2.LMSBOOKINGID) and PAE2.ActivityEvent=12002 
--and PAE2.mx_Custom_48 IS NULL
LEFT JOIN LSQ_Prospect_Base LSQ_PBASE2 ON (LSQ_PBASE2.ProspectID=PAE2.RelatedProspectId)

LEFT JOIN LSQ_Prospect_ExtensionBase PEX1 ON (LSQ_PBASE1.ProspectId=PEX1.ProspectId)
LEFT JOIN LSQ_Prospect_ExtensionBase PEX2 ON (LSQ_PBASE2.ProspectId=PEX2.ProspectId)

LEFT JOIN LSQ_Prospect_Extension2Base PE1 ON (LSQ_PBASE1.ProspectId=PE1.ProspectId)
LEFT JOIN LSQ_Prospect_Extension2Base PE2 ON (LSQ_PBASE2.ProspectId=PE2.ProspectId)


LEFT JOIN LSQ_users LU1 ON LSQ_PBASE1.OwnerId= LU1.UserId
 LEFT JOIN LSQ_users LU2 ON LSQ_PBASE2.OwnerId= LU2.UserId
WHERE RH.DOCTYPE = 141) A)B

UPDATE RF 
SET RF.LEADTYPE = LD.LEAD_TYPE,
    RF.First_Source_Lead_Type=LD.First_Source_Lead_Type,
    RF.First_Mode_Source=LD.First_Mode_Source,
    RF.First_Mode_SubSource=LD.First_Mode_SubSource
FROM ASM_MC_RETAIL_FACT RF INNER JOIN #LEAD_TYPE_RETAIL LD ON RF.FK_RETAILDOCID=LD.PK_RETAILHEADERID

UPDATE RD 
SET RD.RETAIL_LEAD_TYPE = LD.LEAD_TYPE
,RD.SalesPersonEmail = LD.SalesPersonEmail
FROM ASM_MC_RETAIL_DIM RD INNER JOIN #LEAD_TYPE_RETAIL LD ON RD.PK_RETAILHEADERID=LD.PK_RETAILHEADERID


 --CityBV
UPDATE FT
SET FT.CityBV = CONCAT(DM.CityCode, SUBSTRING(PM.MODELCODE, 3, 4))
FROM ASM_MC_RETAIL_FACT FT
JOIN ASM_MC_DEALER_MASTER_DIM DM ON DM.DEALERCODE = FT.DEALERCODE --and DM.KREGIO
JOIN ASM_MC_PRODUCT_DIM PM ON PM.MODELCODE = FT.MODELCODE
WHERE FT.FK_TYPE_ID = 10002
and FT.CityBV is null

--DPP
update FT set FT.DPP =DP.DPP from
ASM_MC_RETAIL_FACT FT
JOIN ASM_MC_DEALER_MASTER_DIM DM on DM.DEALERCODE = FT.DEALERCODE
JOIN ASM_MC_UB_DPP_MASTER DP on DP.CityBV= FT.CityBV
WHERE FK_TYPE_ID = 10002
and FT.DPP is null


---BU and Grouped_dealercode
update FT
set FT.BU ='MC',
    FT.Grouped_dealercode = FT.Dealercode
FROM ASM_MC_RETAIL_FACT FT
WHERE FT.FK_TYPE_ID = 10002
and FT.BU is null
and FT.Grouped_dealercode is null


--********************************************************************************************************************


END
GO