SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_ASM_MC_BILLING_REFRESH] AS
BEGIN

--***********************************************************************
--Billing Data Query
--***********************************************************************
delete from SAP_BILLING Where BILLINGDOC IN (SELECT DISTINCT BILLINGDOC FROM SAP_BILLING_CANCELLED);

INSERT INTO ASM_MC_BILLING_STG
SELECT DISTINCT
'0000'+SAP_BILLING.DEALERCODE AS DEALERCODE,
SAP_BILLING.MATERIAL as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10003 As FK_TYPE_ID,
SAP_BILLING.DOCDATE AS DATE,
Sum(SAP_BILLING.BILLQTY) as ACTUALQUANTITY,
--Sum(ZMPSS_ORDERS.MPSSQTY) As TARGETQUANTITY,
0 As TARGETQUANTITY,
--Sum(cast(PO.ORDQTY as decimal(19,0))) As PENDING_ORDERS,
cast(0 as decimal(19,0)) As PENDING_ORDERS,
getdate() as LASTUPDATEDDATETIME,
SAP_BILLING.MATERIAL,
LEFT(SAP_BILLING.MATERIAL,6) As MODELCODE,
Cast(0 as int) as FK_MODEL,
100031 As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON,
SAP_BILLING.PLANT
FROM
SAP_BILLING
LEFT  JOIN SAP_ZSD_DEALER_REPOS SAP ON (SAP.KUNNR = '0000'+SAP_BILLING.DEALERCODE) 
AND SAP.KATR6 = 'MC'
WHERE 
--SAP_BILLING.DOCDATE BETWEEN '2020-04-01' AND  Cast(Getdate()-1 as date)  AND 
SAP_BILLING.DOCDATE> (SELECT MAX(DATE) from ASM_MC_BILLING_STG) AND
[Distr.Chnl] IN ('10','40') AND DIVISION='B2' AND SAP_BILLING.CANCELLED<>'X'
GROUP BY
    '0000'+SAP_BILLING.DEALERCODE,
    SAP_BILLING.MATERIAL,
    SAP_BILLING.DOCDATE,
    SAP_BILLING.MATERIAL,
	LEFT(SAP_BILLING.MATERIAL,6),
	SAP_BILLING.PLANT

--*************************************************************
--****************************************************************

TRUNCATE TABLE ASM_MC_BILLING_PLAN_STG
INSERT INTO ASM_MC_BILLING_PLAN_STG
SELECT DISTINCT
ZO.DEALERCODE,
ZO.MATERIAL as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10003 As FK_TYPE_ID,
ZO.DOCDATE AS DATE,
Cast(0 as decimal(19,0)) as ACTUALQUANTITY,
--Sum(ZMPSS_ORDERS.MPSSQTY) As TARGETQUANTITY,
Sum(ZO.MPSSQTY) As TARGETQUANTITY,
--Sum(cast(PO.ORDQTY as decimal(19,0))) As PENDING_ORDERS,
cast(0 as decimal(19,0)) As PENDING_ORDERS,
getdate() as LASTUPDATEDDATETIME,
ZO.MATERIAL,
LEFT(ZO.MATERIAL,6) As MODELCODE,
Cast(0 as int) as FK_MODEL,
100032 As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON,
ZO.PLANT
--INTO ASM_MC_BILLING_PLAN_STG
FROM 
SAP_ZMPSS_ORDERS ZO 
WHERE 
ZO.DEALERCODE IN (SELECT DISTINCT KUNNR FROM SAP_ZSD_DEALER_REPOS WHERE KATR6='MC') --(1946899 records affected)
Group By
	ZO.DEALERCODE,
	ZO.MATERIAL,
	ZO.DOCDATE,
	LEFT(ZO.MATERIAL,6),
	ZO.PLANT

--********************************************************

-- Order Qty:
/*
TRUNCATE TABLE ASM_MC_PENDING_ORDER_STG
INSERT INTO ASM_MC_PENDING_ORDER_STG
SELECT DISTINCT
'00000'+PO.SOLDTOPARTY As DEALERCODE,
PO.MATERIAL as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10003 As FK_TYPE_ID,
(CONVERT(date, ltrim(rtrim([DOCDATE])), 105)) AS DATE,
Cast(0 as decimal(19,0)) as ACTUALQUANTITY,
cast(0 as decimal(19,0)) As TARGETQUANTITY,
SUM(CAST((ORDQTY) as DECIMAL(19,0))) As PENDING_ORDERS,
getdate() as LASTUPDATEDDATETIME,
PO.MATERIAL,
LEFT(PO.MATERIAL,6) As MODELCODE,
Cast(0 as int) as FK_MODEL,
100033 As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON,
PO.PLANT
--INTO ASM_MC_PENDING_ORDER_STG -- (136 rows affected)
FROM 
SAP_PENDING_ORDERS PO 
WHERE 
'00000'+PO.SOLDTOPARTY IN (SELECT DISTINCT KUNNR from SAP_ZSD_DEALER_REPOS Where KATR6='MC') -- (429 records affected)
AND FUND='F' 
Group By
	'00000'+PO.SOLDTOPARTY,
	PO.MATERIAL,
	(CONVERT(date, ltrim(rtrim([DOCDATE])), 105)),
	LEFT(PO.MATERIAL,6),
	PO.PLANT
*/
---- pENDING orDERS SOURCE CHANGE -------------------------------
TRUNCATE TABLE ASM_MC_PENDING_ORDER_STG
INSERT INTO ASM_MC_PENDING_ORDER_STG
SELECT DISTINCT
PO.FLD16 As DEALERCODE,
PO.FLD22 as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
'10003' As FK_TYPE_ID,
left(TRY_CAST(FLD32 as date),10) As DATE,
Cast(0 as decimal(19,0)) as ACTUALQUANTITY,
cast(0 as decimal(19,0)) As TARGETQUANTITY,
SUM(CAST((FLD12) as DECIMAL(19,0))) As PENDING_ORDERS,
getdate() as LASTUPDATEDDATETIME,
PO.FLD22,
LEFT(PO.FLD22,6) As MODELCODE,
Cast(0 as int) as FK_MODEL,
'100033' As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON,
PO.FLD2 As PLANT
--INTO ASM_CV_PENDING_ORDER_STG
FROM
SAP_REPORT_ZBODS_ITEM_DATA PO
WHERE
TCODE='YOTDR_PENDING_ORD_PROCESS_REP' and
VARIANT='/BODSQLIK_NEW' AND FLD12<>'KWMENG' AND
PO.FLD16 IN (SELECT DISTINCT KUNNR from SAP_ZSD_DEALER_REPOS Where KATR6='MC')
Group By
    PO.FLD16,
    PO.FLD22,
    left(TRY_CAST(FLD32 as date),10),
    LEFT(PO.FLD22,6),
    PO.FLD2

	--*************************************************

TRUNCATE TABLE ASM_MC_BILLING_FACT
INSERT INTO ASM_MC_BILLING_FACT  -- (1962671 records affected)
SELECT * FROM ASM_MC_BILLING_STG
UNION
SELECT * FROM ASM_MC_BILLING_PLAN_STG
UNION 
SELECT * FROM ASM_MC_PENDING_ORDER_STG

--*******************************************************************


  --*******************************************************************
-- Billing :

-- Step 2:
-- Product Master and Dealer Master FK update: ASM_MC_BILLING_FACT
--update B set B.FK_SKU=C.PK_SKU from ASM_MC_BILLING_FACT B INNER JOIN ASM_MC_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE)
--update B set B.FK_MODEL=C.PK_Model_Code from ASM_MC_BILLING_FACT B INNER JOIN ASM_MC_PRODUCT_DIM C on (B.MODELCODE=C.MODELCODE) 
--update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].ASM_MC_BILLING_FACT B INNER JOIN ASM_MC_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE) 
--******************************************************************************
END
GO
