SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

----18-08-2025  -- Ashwini A  --- Addition of CityBv,Dpp,Bu,Grouped_dealercode for MC Chetak 

CREATE PROC [dbo].[USP_ASM_MC_STOCK_REFRESH] AS
BEGIN

--************** STOCK ***************************

INSERT INTO ASM_MC_STOCK_FACT
SELECT DISTINCT
VS.COMPANYCODE As DEALERCODE,
VS.MODELCODE+LEFT(RIGHT(VS.COLOR,3),2) as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10004 As FK_TYPE_ID,
CAST(VS.EXECUTIONDATE as Date) AS DATE,
CM.COMPANYTYPE AS COMPANYTYPE,
Cast('' as varchar(255)) AS FK_STOCKSTATUS,
VS.VEHICLESTATUS as STOCKSTATUS,
COUNT(VS.CHASSISNO) AS [Stock Quantity],
COUNT(VS.CHASSISNO) as ACTUALQUANTITY, 
getdate() as LASTUPDATEDDATETIME,
VS.IMPORTEDDATE,
VS.MODELCODE,
Cast(0 as int) As FK_MODEL,
CAST(VS.PURCHASEDATE as Date) AS STOCKDATE,
NULL as CityBV,
NULL as DPP,
NULL as BU,
NULL as grouped_dealercode

FROM
   VEHICLE_STOCK_DATA VS INNER JOIN COMPANY_MASTER CM ON (VS.COMPANYCODE=CM.CODE AND (CM.COMPANYTYPE=1))
    WHERE Cast(VS.EXECUTIONDATE as date) > (SELECT MAX(DATE) FROM ASM_MC_STOCK_FACT)
GROUP BY
  VS.COMPANYCODE,
  VS.MODELCODE+LEFT(RIGHT(VS.COLOR,3),2),
  CAST(VS.EXECUTIONDATE as Date),
  CM.COMPANYTYPE,
  VS.VEHICLESTATUS,
  VS.IMPORTEDDATE,
  VS.MODELCODE,
  VS.PURCHASEDATE


--*********************************************************************************************************
--Product Master and Dealer Master FK update: ASM_MC_STOCK_FACT
--update B set B.FK_SKU=C.PK_SKU from ASM_MC_STOCK_FACT B INNER JOIN ASM_MC_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE) 
--update B set B.FK_MODEL=C.PK_Model_Code from ASM_MC_STOCK_FACT B INNER JOIN ASM_MC_PRODUCT_DIM C on (B.ModelCode=C.MODELCODE) 
--update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].ASM_MC_STOCK_FACT B INNER JOIN ASM_MC_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE)

--CityBV and DPP update 

--for CityBV
UPDATE FT
SET FT.CityBV = CONCAT(DM.CityCode, SUBSTRING(PM.MODELCODE, 3, 4))
FROM ASM_MC_STOCK_FACT FT
JOIN ASM_MC_DEALER_MASTER_DIM DM ON DM.DEALERCODE = FT.DEALERCODE --and DM.KREGIO
JOIN ASM_MC_PRODUCT_DIM PM ON PM.MODELCODE = FT.MODELCODE
WHERE FT.FK_TYPE_ID = 10004
and FT.CityBV is null;



--for DPP
update FT 
SET FT.DPP =DP.DPP 
FROM ASM_MC_STOCK_FACT FT
JOIN ASM_MC_DEALER_MASTER_DIM DM on DM.DEALERCODE = FT.DEALERCODE
JOIN ASM_MC_UB_DPP_MASTER DP on DP.CityBV= FT.CityBV
WHERE FK_TYPE_ID = 10004
and FT.DPP is null;

--BU and grouped dealercode
update FT
set FT.BU ='MC',
    FT.Grouped_dealercode = FT.Dealercode
FROM ASM_MC_STOCK_FACT FT
WHERE FT.FK_TYPE_ID = 10004
and FT.BU is null
and FT.Grouped_dealercode is null;


---------------MC ASM_SAP_YACC_OD_FUNDS for bank outsatanding in Stock vs outsatanding screen----

TRUNCATE TABLE ASM_SAP_YACC_OD_FUNDS
INSERT INTO ASM_SAP_YACC_OD_FUNDS
SELECT DISTINCT
    KUNNR AS DealerCode,
    Cast(0 as int) as FK_DEALERCODE,
    Cast(0 as int) as FK_SKU,
    Cast(0 as int) as FK_Model_Code,
    10011 AS FK_TYPE,
	SALHW AS LC_Balance,
    KLIMK AS [Cred.limit],
	--CAST(ERDAT AS DATE) AS Created_ON,
	CONVERT(VARCHAR,
       CAST(LEFT(ERDAT, 4) AS VARCHAR(4)) + '-' + 
       CAST(SUBSTRING(ERDAT, 5, 2) AS VARCHAR(2)) + '-' + 
       CAST(RIGHT(ERDAT, 2) AS VARCHAR(2))
	) AS Created_ON,
    GETDATE() AS LASTUPDATEDDATETIME 
FROM SAP_YACC_OD_FUNDS YF
INNER JOIN ASM_MC_DEALER_MASTER_DIM DM on  YF.KUNNR = DM.DEALERCODE 
WHERE 
    YF.KKBER = 'BA02'
group by 
KUNNR,
SALHW,
KLIMK,
ERDAT

-- Dealer Master FK update: ASM_MC_TARGET_FACT
update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].ASM_SAP_YACC_OD_FUNDS B 
INNER JOIN ASM_MC_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE)



--***********************************************************************************************************
END
GO