SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[USP_ASM_MC_MASTER_REFRESH] AS
BEGIN

--******************************* START ******************************************
-- Dimensions:
--1. ASM_MC_PRODUCT_SKU_DIM 

TRUNCATE TABLE ASM_MC_PRODUCT_SKU_DIM
INSERT INTO ASM_MC_PRODUCT_SKU_DIM
SELECT  DISTINCT
        B.MATNR AS SKU_CODE,
        A.ZMKDT_Model as Model,
        B.MAKTX AS Model_Description,
        C.BEZEI AS Colour,
        getdate() as CREATEDATETIME
        --INTO ASM_MC_PRODUCT_SKU_DIM
FROM SAP_ZBRAND_V_DETAIL A JOIN SAP_MAKT B ON A.ZBRANDVARIANT=SUBSTRING(B.MATNR,3,4) and B.MATNR LIKE '00%'
JOIN SAP_TVM2T C ON (Right(B.MATNR,2)=C.MVGR2)
WHERE
A.ZBU_TYPE = 'MC' -- (2483 rows affected)

--*************************************************************************************************

--2. ASM_MC_PRODUCT_DIM 

TRUNCATE TABLE ASM_MC_PRODUCT_DIM

INSERT INTO ASM_MC_PRODUCT_DIM
SELECT  DISTINCT
        LEFT(B.MATNR,6) AS ModelCode,
		A.ZMKDT_Model AS Model,
        A.ZPRESUCC_STATUS as Mono_BI_Fuel,
        A.ZSUB_BRD AS Subcategory,
        A.VARIANT AS Category,
        A.ZSEGMENT as Segment,
        A.ZBRAND1 as Brand,
        A.MODEL_ACTIVATION as Primary_Usage,
        getdate() as CREATEDATETIME
        --INTO ASM_MC_PRODUCT_DIM
FROM SAP_ZBRAND_V_DETAIL A JOIN SAP_MAKT B ON A.ZBRANDVARIANT=SUBSTRING(B.MATNR,3,4) and B.MATNR LIKE '00%'
WHERE 
A.ZBU_TYPE = 'MC' -- (2585 rows affected)

--**************************************************************
--3.ASM_MC_DEALER_MASTER_DIM

TRUNCATE TABLE ASM_MC_DEALER_MASTER_DIM
INSERT INTO ASM_MC_DEALER_MASTER_DIM (
    DEALERCODE, 
    DEALERNAME, 
    REGION, 
    HUB, 
    CIRCLE, 
    CITY, 
    STATE, 
    STATE_NAME, 
    CityCode, 
    KREGION, 
    BU, 
    CREATEDDATETIME
)
SELECT DISTINCT
    D.KUNNR  As DEALERCODE, 
    D.NAME1 As DEALERNAME,
    CASE WHEN D.VTEXT1 = 'TN / AN /Pondicherry' THEN 'TAMIL NADU'
         WHEN D.VTEXT1 = 'MP / Chattisgarh' THEN 'MADHYA PRADESH' 
         WHEN D.VTEXT1 = 'Karnataka / Goa' THEN 'KARNATAKA'
         WHEN D.VTEXT1 = 'Andhra Pradesh / TG' THEN 'ANDHRA PRADESH'
         ELSE UPPER(D.VTEXT1) END As REGION,
    D.HUB as HUB,
    D.CIRCLE As CIRCLE,
    D.CITY1 As CITY,
    D.REGIO AS [STATE],
    D.BEZEI AS [STATE_NAME],
    K.CityC AS CityCode,
    K.Regio AS KREGION,
    D.KATR6 AS BU,
    GETDATE() as CREATEDDATETIME
FROM SAP_ZSD_DEALER_REPOS D
LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 K on K.KUNNR = D.KUNNR
WHERE D.KATR6 = 'MC' 
  AND D.T_DDIST = 'Veh. Dealer'
  AND D.KUNNR LIKE '00000[0-9][0-9][0-9][0-9][0-9]';



--******************************************************************************************
--4.ASM_MC_BRANCH_MASTER_DIM

TRUNCATE TABLE ASM_MC_BRANCH_MASTER_DIM

INSERT INTO ASM_MC_BRANCH_MASTER_DIM

SELECT DISTINCT 
BM.BRANCHID AS PK_BRANCHID,
BM.CODE AS [BRANCH_CODE],
BM.NAME AS [BRANCH_NAME],
ISNULL(BM.TypeOfOutlet,'Others') AS [TypeOfChannel],
CASE WHEN BM.CHANNEL=1 Then 'Rural' WHEN BM.CHANNEL=2 Then 'Urban' ELSE 'Other' END As BRANCHTYPE
FROM BRANCH_MASTER BM
JOIN COMPANY_MASTER CM ON CM.COMPANYID=BM.COMPANYID AND CM.COMPANYTYPE IN (1,8) AND CM.IMPORTEDDATE = (SELECT MAX(CM1.IMPORTEDDATE) FROM COMPANY_MASTER CM1 WHERE CM.COMPANYID = CM1.COMPANYID)

END
GO