SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_ASM_MC_ALLOCATION_REFRESH] AS
BEGIN

--Allocation Dim & Fact:

--------------------------------------------------------------------------------------------------------------------------
INSERT INTO ASM_MC_ALLOCATION_DIM
SELECT DISTINCT 
	ALLOCATION_HEADER.HEADERID AS PK_ALLOCATIONHEADERID,
	CAST(ALLOCATION_HEADER.DOCDATE AS DATE) AS ALLOCATIONDATE,
	GETDATE() AS CREATEDDATETIME,
	ALLOCATION_HEADER.IMPORTEDDATE,
	ALLOCATION_HEADER.CDMS_BATCHNO
	--INTO ASM_MC_ALLOCATION_DIM
FROM ALLOCATION_HEADER 
	INNER JOIN COMPANY_MASTER 
	ON (ALLOCATION_HEADER.COMPANYID=COMPANY_MASTER.COMPANYID AND
	COMPANY_MASTER.COMPANYTYPE IN (1,8))
where 
--CAST(ALLOCATION_HEADER.DOCDATE AS DATE) BETWEEN '2020-04-01' AND Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date)
--ALLOCATION_HEADER.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_MC_ALLOCATION_DIM)
CAST(ALLOCATION_HEADER.IMPORTEDDATE AS DATE ) >= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_MC_ALLOCATION_DIM) AS DATE)   -- UPDATED ON 12/06
--------------------------------------------------------------------------------------------------------------------------
DELETE FROM ASM_MC_ALLOCATION_DIM WHERE ALLOCATIONDATE>Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date)


--Dedup:

;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_ALLOCATIONHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_MC_ALLOCATION_DIM                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;   


--***************************************************************************
--AllCation Fact:
--Truncate table ASM_MC_ALLOCATION_FACT
INSERT INTO ASM_MC_ALLOCATION_FACT
SELECT 
DISTINCT
CM.CODE AS DEALERCODE,
IM.CODE+IV.CODE As SKU,
Cast(0 as int) AS FK_DealerCode,
Cast(0 as int) AS FK_SKU,
10007 AS FK_TYPE_ID,
CAST(AH.DOCDATE AS DATE) AS DATE,
AL.LINEID AS AllocationLineID,
AL.DOCID AS FK_AllocationDocID,
CM.COMPANYTYPE AS COMPANYTYPE,
AH.BRANCHID,
COUNT(AH.HEADERID) AS ACTUALQUANTITY,
getdate() as LASTUPDATEDDATETIME,
AH.IMPORTEDDATE,
IM.CODE As MODEL,
Cast(0 as int) As FK_MODEL,
Cast(0 As decimal(19,0)) As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON
FROM 
ALLOCATION_HEADER AH INNER JOIN COMPANY_MASTER CM ON (AH.COMPANYID=CM.COMPANYID AND CM.COMPANYTYPE IN (1,8))
INNER JOIN ALLOCATION_LINE AL ON (AH.HEADERID=AL.DOCID)
JOIN ITEM_MASTER IM ON (IM.ItemId=AL.ItemID)
LEFT JOIN ITEMVARMATRIX_MASTER IV ON (AL.VARMATRIXID=IV.ITEMVARMATRIXID)
WHERE 
--CAST(AH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date)
--CAST(AH.DOCDATE AS DATE) > '2023-03-15' AND  CAST(AH.DOCDATE AS DATE) <= '2023-03-20'
--AH.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_MC_ALLOCATION_FACT)
CAST(AH.IMPORTEDDATE AS DATE) >= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_MC_ALLOCATION_FACT) AS DATE)  --UPDATED ON 12/06
GROUP BY
CM.CODE,
IM.CODE+IV.CODE,
CAST(AH.DOCDATE AS DATE),
AL.LINEID,
AL.DOCID,
CM.COMPANYTYPE,
AH.BRANCHID,
AH.IMPORTEDDATE,
IM.CODE 
 
--
  DELETE FROM ASM_MC_ALLOCATION_FACT WHERE DATE>Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date)

--Dedup Process:


  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY FK_AllocationDocID,AllocationLineID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_MC_ALLOCATION_FACT                
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 


--**************************************************************************************************************

-- Product Master and Dealer Master FK update: ASM_MC_ALLOCATION_FACT 

--update B set B.FK_SKU=C.PK_SKU from ASM_MC_ALLOCATION_FACT B INNER JOIN ASM_MC_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE) -- (2086120 rows affected)
--update B set B.FK_MODEL=C.PK_Model_Code from ASM_MC_ALLOCATION_FACT B INNER JOIN ASM_MC_PRODUCT_DIM C on (B.MODEL=C.MODELCODE) -- (2086123 rows affected)
--update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].ASM_MC_ALLOCATION_FACT B INNER JOIN ASM_MC_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE) -- (2086123 rows affected)

--**************************************************************************************************************

END
GO