

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

alter PROC [dbo].[USP_ASM_PB_HKT_SALES_FACT_REFRESH] AS
BEGIN
	
TRUNCATE TABLE ASM_PB_HKT_SALES_FACT
--**************************START********************************
--***************************START************************************************
/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|					CHANGE DESCRIPTION					*/
/*--------------------------------------------------------------------------------------------------*/
/*	2024-06-19 	|	RICHA	| Added Sales view of Testrides    */  			
/*   2024-07-24 	|	RICHA	| Added Sales view of Followups */
/*   2024-12-27 	|	Nikita	| MX_QUALIFIED_FIRST_SOURCE Changes */
/*	2025-03-19 	|	Lachmanna		| First Mode Source and sub source  Addition	*/
/*	2025-05-23 	|	Lachmanna		| Ship-to Party (Branch Code) billing data from SAP	*/
/*  2025-07-18 	|	Lachmanna		        | Newly Added script for K+T        */
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*******************************************HISTORY**************************************************/
------------------------------------------------------------------------------------------------------------------------------------------
--1.Enquiry:
INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BOOKINGDAYSBUCKET, 
BaseFlag,
TEHSILID,
SALESPERSON,
LeadType,
First_source_Lead_type,
First_Mode_Source,
First_Mode_SubSource,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
CASE 
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 0 AND 30 THEN '0-30'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 31 AND 60 THEN '31-60'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 61 AND 90 THEN '61-90'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 91 AND 120 THEN '91-120'
ELSE '>120'
END as EnquiryDaysBucket,
'' As BOOKINGDAYSBUCKET,
BaseFlag,
TEHSILID,
SALESPERSON,
LeadType,
First_source_Lead_type,
First_Mode_Source,
First_Mode_SubSource,
'PB KTM' as Brand_New
FROM 
  ASM_PB_HK_ENQUIRY_FACT

INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
EnquiryDaysBucket,
BOOKINGDAYSBUCKET, 
BaseFlag,
SALESPERSON,
LEADTYPE,
First_source_Lead_type,
First_Mode_Source,
First_Mode_SubSource,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
CASE 
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 0 AND 30 THEN '0-30'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 31 AND 60 THEN '31-60'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 61 AND 90 THEN '61-90'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 91 AND 120 THEN '91-120'
ELSE '>120'
END,
'' As BOOKINGDAYSBUCKET,
BaseFlag,
SALESPERSON,
LEADTYPE,
First_source_Lead_type,
First_Mode_Source,
First_Mode_SubSource,
'PB TRM' as Brand_New
FROM  ASM_PB_T_ENQUIRY_FACT


INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
TEHSILID,
SALESPERSON,
LeadType,
BOOKINGDATE,
TESTRIDEDATE,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
''  AS EnquiryLineID,
''  AS FK_EnquiryDocID,
''  AS BookingLineID,
''  AS FK_BookingDocID,
''  AS AllocationLineID,
''  AS FK_AllocationDocID,
FK_MODEL,
COMPANYTYPE,
BRANCHID,
RETAILLINEID,
FK_RETAILDOCID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
'' AS EnquiryDaysBucket,
'' AS BookingDaysBucket,
0,
TEHSILID,
SALESPERSON,
LeadType,
BOOKINGDATE,
TESTRIDEDATE,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
'PB KTM' as Brand_New
FROM ASM_PB_HK_RETAIL_FACT


INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
TEHSILID,
SALESPERSON,
LEADTYPE,
BOOKINGDATE,
TESTRIDEDATE,
First_source_Lead_type,
First_Mode_Source,
First_Mode_SubSource,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
''  AS EnquiryLineID,
''  AS FK_EnquiryDocID,
''  AS BookingLineID,
''  AS FK_BookingDocID,
''  AS AllocationLineID,
''  AS FK_AllocationDocID,
FK_MODEL,
COMPANYTYPE,
BRANCHID,
RETAILLINEID,
FK_RETAILDOCID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
'' AS EnquiryDaysBucket,
'' AS BookingDaysBucket,
TEHSILID,
SALESPERSON,
ISNULL(LEADTYPE,'Not Available') LEADTYPE,
BOOKINGDATE,
TESTRIDEDATE,
First_source_Lead_type,
First_Mode_Source,
First_Mode_SubSource,
'PB TRM' as Brand_New
FROM ASM_PB_T_RETAIL_FACT

--3.BILLING :

INSERT INTO [ASM_PB_HKT_SALES_FACT]
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
TEHSILID,
SALESPERSON,
Brand_New
)
SELECT -- DISTINCT 
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
'' AS EnquiryLineID,
'' AS FK_EnquiryDocID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
'' AS COMPANYTYPE,
BRANCHCODE,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
PENDING_ORDERS,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
'' AS IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
'' AS EnquiryDaysBucket,
'' AS BookingDaysBucket,
0,
TEHSILID,
SALESPERSON,
'PB KTM' as Brand_New
FROM 
ASM_PB_HK_BILLING_FACT

INSERT INTO [ASM_PB_HKT_SALES_FACT]
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
TEHSILID,
SALESPERSON,
Brand_New
)
SELECT -- DISTINCT 
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
'' AS EnquiryLineID,
'' AS FK_EnquiryDocID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
'' AS COMPANYTYPE,
BRANCHCODE,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
PENDING_ORDERS,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
'' AS IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
'' AS EnquiryDaysBucket,
'' AS BookingDaysBucket,
0,
TEHSILID,
SALESPERSON,
'PB TRM' as Brand_New
FROM 
ASM_PB_T_BILLING_FACT

--4.STOCK :

INSERT INTO ASM_PB_HKT_SALES_FACT
(  
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
TEHSILID,
SALESPERSON,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
'' AS EnquiryLineID,
'' AS FK_EnquiryDocID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
COMPANYTYPE,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
STOCKSTATUS,
'' AS [Stock Value],
[Stock Quantity],
'' AS TARGETQUANTITY,
GETDATE() AS LASTUPDATEDDATETIME,
IMPORTEDDATE,
Cast(0 as decimal(19,0)) As FLAG,
CASE 
WHEN DATEDIFF(day,Date,GETDATE()) BETWEEN 0 AND 30 THEN '0-30'
WHEN DATEDIFF(day,Date,GETDATE()) BETWEEN 31 AND 60 THEN '31-60'
WHEN DATEDIFF(day,Date,GETDATE()) BETWEEN 61 AND 90 THEN '61-90'
ELSE '>90'
END AS StockAgeingBucket,
DATEDIFF(day,Date,GETDATE()) AS StockAgeing,
'' AS EnquiryDaysBucket,
'' AS BookingDaysBucket,
0,
TEHSILID,
SALESPERSON,
'PB KTM' as Brand_New
FROM 
ASM_PB_HK_STOCK_FACT


INSERT INTO ASM_PB_HKT_SALES_FACT
(  
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
TEHSILID,
SALESPERSON,
 Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
'' AS EnquiryLineID,
'' AS FK_EnquiryDocID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
COMPANYTYPE,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
STOCKSTATUS,
'' AS [Stock Value],
[Stock Quantity],
'' AS TARGETQUANTITY,
GETDATE() AS LASTUPDATEDDATETIME,
IMPORTEDDATE,
Cast(0 as decimal(19,0)) As FLAG,
CASE 
WHEN DATEDIFF(day,Date,GETDATE()) BETWEEN 0 AND 30 THEN '0-30'
WHEN DATEDIFF(day,Date,GETDATE()) BETWEEN 31 AND 60 THEN '31-60'
WHEN DATEDIFF(day,Date,GETDATE()) BETWEEN 61 AND 90 THEN '61-90'
ELSE '>90'
END AS StockAgeingBucket,
DATEDIFF(day,Date,GETDATE()) AS StockAgeing,
'' AS EnquiryDaysBucket,
'' AS BookingDaysBucket,
TEHSILID,
SALESPERSON,
'PB TRM' as Brand_New
FROM 
ASM_PB_T_STOCK_FACT
--***************************************************************
--5.BOOKING :

INSERT INTO [ASM_PB_HKT_SALES_FACT]
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
TEHSILID,
SALESPERSON,
LeadType,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
'' AS EnquiryLineID,
'' AS FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
0 AS TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
'' AS EnquiryDaysBucket,
CASE
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 0 and 30 THEN '0-30'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 31 and 60 THEN '31-60'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 61 and 90 THEN '61-90'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 91 and 120 THEN '91-120'
ELSE '>120'
END AS BookingDaysBucket,
0,
TEHSILID,
SALESPERSON,
LeadType,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
'PB KTM' as Brand_New
FROM 
ASM_PB_HK_BOOKING_FACT

INSERT INTO [ASM_PB_HKT_SALES_FACT]
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
SALESPERSON,
LEADTYPE,
First_source_Lead_type,
First_Mode_Source,
First_Mode_SubSource,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
'' AS EnquiryLineID,
'' AS FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
0 AS TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
'' AS EnquiryDaysBucket,
CASE
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 0 and 30 THEN '0-30'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 31 and 60 THEN '31-60'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 61 and 90 THEN '61-90'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 91 and 120 THEN '91-120'
ELSE '>120'
END AS BookingDaysBucket,
SALESPERSON,
LEADTYPE,
First_source_Lead_type,
First_Mode_Source,
First_Mode_SubSource,
'PB TRM' as Brand_New
FROM 
ASM_PB_T_BOOKING_FACT

----****************************************************************

--6.ALLOCATION :

INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
TEHSILID,
SALESPERSON,
Brand_New
)
SELECT --DISTINCT
FK_DealerCode,
FK_SKU,
FK_TYPE_ID,
[DATE],
'' AS EnquiryLineID,
'' AS FK_EnquiryDocID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
0 AS TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
'' AS EnquiryDaysBucket,
'' AS BookingDaysBucket,
0,
TEHSILID,
SALESPERSON,
'PB KTM' as Brand_New
FROM 
ASM_PB_HK_ALLOCATION_FACT



INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
StockAgeingBucket,
StockAgeing,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
TEHSILID,
SALESPERSON,
Brand_New
)
SELECT --DISTINCT
FK_DealerCode,
FK_SKU,
FK_TYPE_ID,
[DATE],
'' AS EnquiryLineID,
'' AS FK_EnquiryDocID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
0 AS TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
'' AS StockAgeingBucket,
'' AS StockAgeing,
'' AS EnquiryDaysBucket,
'' AS BookingDaysBucket,
0,
TEHSILID,
SALESPERSON,
'PB TRM' as Brand_New
FROM 
ASM_PB_T_ALLOCATION_FACT



----- TESTRIDE Transactions


INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
LeadType,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
CASE 
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 0 AND 30 THEN '0-30'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 31 AND 60 THEN '31-60'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 61 AND 90 THEN '61-90'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 91 AND 120 THEN '91-120'
ELSE '>120'
END,
'' As BOOKINGDAYSBUCKET,
BaseFlag,
LEADTYPE,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
'PB KTM' as Brand_New
FROM 
ASM_PB_HK_TEST_RIDE_FACT



INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
LeadType,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
CASE 
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 0 AND 30 THEN '0-30'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 31 AND 60 THEN '31-60'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 61 AND 90 THEN '61-90'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 91 AND 120 THEN '91-120'
ELSE '>120'
END,
'' As BOOKINGDAYSBUCKET,
BaseFlag,
LEADTYPE,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
'PB TRM' as Brand_New
FROM 
ASM_PB_T_TEST_RIDE_FACT


----- Followup Transactions


INSERT INTO ASM_PB_HKT_SALES_FACT
(
FK_DEALERCODE,
FK_SKU,
FK_TYPE,
[DATE],
EnquiryLineID,
FK_EnquiryDocID,
BookingLineID,
FK_BookingDocID,
AllocationLineID,
FK_AllocationDocID,
FK_Model_Code,
CompanyType,
BRANCHID,
RetailLineID,
FK_RetailDocID,
ACTUALQUANTITY,
Pending_Orders,
[BAL Outstanding (O/S)],
[Bank Outstanding (O/S)],
[Remittance (In Lakh)],
[Target Own Funds (OF)],
[Actual BG],
[Target BG],
StockStatus,
[Stock Value],
[Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
EnquiryDaysBucket,
BookingDaysBucket,
BaseFlag,
LeadType,
First_Source_Lead_Type,
 Brand_New
)
SELECT --DISTINCT
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
[DATE],
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
'' AS BookingLineID,
'' AS FK_BookingDocID,
'' AS AllocationLineID,
'' AS FK_AllocationDocID,
FK_MODEL,
CompanyType,
BRANCHID,
'' AS RetailLineID,
'' AS FK_RetailDocID,
ACTUALQUANTITY,
'' AS Pending_Orders,
'' AS [BAL Outstanding (O/S)],
'' AS [Bank Outstanding (O/S)],
'' AS [Remittance (In Lakh)],
'' AS [Target Own Funds (OF)],
'' AS [Actual BG],
'' AS [Target BG],
'' AS StockStatus,
'' AS [Stock Value],
'' AS [Stock Quantity],
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
FLAG,
CASE 
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 0 AND 30 THEN '0-30'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 31 AND 60 THEN '31-60'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 61 AND 90 THEN '61-90'
WHEN DATEDIFF(day,DATE,GETDATE()) BETWEEN 91 AND 120 THEN '91-120'
ELSE '>120'
END,
'' As BOOKINGDAYSBUCKET,
BaseFlag,
LEADTYPE,
First_Source_Lead_Type,
'PB KTM' as Brand_New
FROM 
ASM_PB_HK_FOLLOWUP_FACT  ;


--*************************************************************************************

END
GO