SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|					CHANGE DESCRIPTION					*/
/*--------------------------------------------------------------------------------------------------*/
/*	2024-05-06 	|	Aakash Kundu		| Adding Doctype filter for VSI & AVSI                            */
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*******************************************HISTORY**************************************************/




CREATE PROC [dbo].[USP_ASM_MC_SERVICE_AGE_WISE_RETENTION] AS

BEGIN

IF OBJECT_ID('AGE_WISE_RETENTION_MC', 'U') IS NOT NULL 
  DROP TABLE AGE_WISE_RETENTION_MC; 

SELECT * INTO [dbo].[AGE_WISE_RETENTION_MC] FROM
(SELECT DISTINCT BASE.CODE AS DEALERCODE,BASE.IBID,BASE.SALE_DATE,YEAR(BASE.SALE_DATE) AS YEAR, DATENAME(month,BASE.SALE_DATE) AS [MONTH],
CASE
WHEN SUM([1yrRetention])>=1 THEN 1 ELSE 0 END AS 'Year1',
CASE
WHEN SUM([2yrRetention])>=1 THEN 1 ELSE 0 END AS 'Year2',
CASE
WHEN SUM([3yrRetention])>=1 THEN 1 ELSE 0 END AS 'Year3',
CASE 
WHEN SUM([4yrRetention])>=1 THEN 1 ELSE 0 END AS 'Year4',
CASE 
WHEN SUM([5yrRetention])>=1 THEN 1 ELSE 0 END AS 'Year5'
FROM
(SELECT STG.CODE,STG.IBID,ISNULL(DATEOFSALE,RETAIL_DATE) SALE_DATE,
CASE WHEN SERVICE_DATE BETWEEN ISNULL(DATEOFSALE,RETAIL_DATE) AND DATEADD(DAY,365,ISNULL(DATEOFSALE,RETAIL_DATE)) THEN 1 ELSE 0 END AS '1yrRetention',
CASE WHEN SERVICE_DATE BETWEEN DATEADD(DAY,366,ISNULL(DATEOFSALE,RETAIL_DATE)) AND DATEADD(DAY,730,ISNULL(DATEOFSALE,RETAIL_DATE)) THEN 1 ELSE 0 END AS '2yrRetention',
CASE WHEN SERVICE_DATE BETWEEN DATEADD(DAY,731,ISNULL(DATEOFSALE,RETAIL_DATE)) AND DATEADD(DAY,1095,ISNULL(DATEOFSALE,RETAIL_DATE)) THEN 1 ELSE 0 END AS '3yrRetention',
CASE WHEN SERVICE_DATE BETWEEN DATEADD(DAY,1096,ISNULL(DATEOFSALE,RETAIL_DATE)) AND DATEADD(DAY,1460,ISNULL(DATEOFSALE,RETAIL_DATE)) THEN 1 ELSE 0 END AS '4yrRetention',
CASE WHEN SERVICE_DATE BETWEEN DATEADD(DAY,1461,ISNULL(DATEOFSALE,RETAIL_DATE)) AND DATEADD(DAY,1825,ISNULL(DATEOFSALE,RETAIL_DATE)) THEN 1 ELSE 0 END AS '5yrRetention'
FROM 
(SELECT DISTINCT CM.CODE,RL.IBID,CAST(RH.DOCDATE AS DATE) RETAIL_DATE,
CASE WHEN RH.DOCTYPE=441 THEN CAST(IBM.INVOICEDATE AS DATE)
     WHEN RH.DOCTYPE IN (141) THEN CAST(RH.DOCDATE AS DATE) END AS DATEOFSALE,
CAST(SH.DOCDATE AS DATE) [SERVICE_DATE]
FROM 
RETAIL_HEADER RH
JOIN RETAIL_LINE RL ON RL.DOCID = RH.HEADERID
JOIN COMPANY_MASTER CM ON CM.COMPANYID = RH.COMPANYID AND CM.COMPANYTYPE IN (1,8)
LEFT JOIN INSTALL_BASE_MASTER IBM ON RL.IBID = IBM.IBID
LEFT JOIN SERVICE_HEADER SH ON SH.IBID = RL.IBID
WHERE CAST(RH.DOCDATE AS DATE) >= '2019-04-01' AND RH.DOCTYPE IN (141,441)
AND RL.LINEID NOT IN (SELECT RRL.SALEINVOICELINEID FROM RETAIL_LINE_RETURN RRL JOIN RETAIL_LINE RL1 ON  RRL.SALEINVOICELINEID = RL1.LINEID)
AND SH.CANCELLATIONDATE IS NULL AND SH.CONTRACTTYPEID NOT IN (8,168))STG)BASE
GROUP BY BASE.CODE,BASE.IBID,BASE.SALE_DATE,YEAR(BASE.SALE_DATE), DATENAME(month,BASE.SALE_DATE))A

END
GO

