
/****** OBJECT:  STOREDPROCEDURE [DBO].[USP_ASM_CV_ALLOCATION_REFRESH]    SCRIPT DATE: 01-12-2023 15:03:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [DBO].[USP_ASM_CV_ALLOCATION_REFRESH] AS
BEGIN

/********************************************HISTORY********************************************/
/*---------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------*/
/*  DATE       |  CREATED BY/MODIFIED BY |              CHANGE DESCRIPTION                     */
/*---------------------------------------------------------------------------------------------*/
/*  19/07/2024 |  Sarvesh Kulkarni       |            UTC to IST change for schedule update    */
/*---------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------*/
/********************************************HISTORY********************************************/
--ALLOCATION DIM & FACT:
--TRUNCATE TABLE ASM_CV_ALLOCATION_DIM
INSERT INTO ASM_CV_ALLOCATION_DIM
SELECT DISTINCT 
ALLOCATION_HEADER.HEADERID AS PK_ALLOCATIONHEADERID,
CAST(ALLOCATION_HEADER.DOCDATE AS DATE) AS ALLOCATIONDATE,
DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS [CREATEDATETIME],-- --UTC_TO_IST_Changes_needed
ALLOCATION_HEADER.IMPORTEDDATE,
ALLOCATION_HEADER.CDMS_BATCHNO
--INTO ASM_CV_ALLOCATION_DIM
FROM ALLOCATION_HEADER INNER JOIN COMPANY_MASTER ON (ALLOCATION_HEADER.COMPANYID=COMPANY_MASTER.COMPANYID AND
COMPANY_MASTER.COMPANYTYPE = 7)
WHERE  --1=2
--CAST(ALLOCATION_HEADER.DOCDATE AS DATE) BETWEEN '2020-04-01' AND '2023-05-07' -- (501279 ROWS AFFECTED)
--CAST(ALLOCATION_HEADER.DOCDATE AS DATE)>'2022-11-24'
--ALLOCATION_HEADER.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_CV_ALLOCATION_DIM)
CAST(ALLOCATION_HEADER.IMPORTEDDATE AS DATE) >= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_ALLOCATION_DIM) AS DATE) --UPDATED ON 12/08
--

DELETE FROM ASM_CV_ALLOCATION_DIM WHERE ALLOCATIONDATE>CAST(DATEADD(mi,30,(DATEADD(hh,5,getdate())))-1 AS DATE)-- --UTC_TO_IST_Changes_needed


--DEDUP:

  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_ALLOCATIONHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ALLOCATION_DIM                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;   


--***************************************************************************
--ALLCATION FACT:

INSERT INTO ASM_CV_ALLOCATION_FACT
SELECT 
DISTINCT
CM.CODE AS DEALERCODE,
IM.CODE+IV.CODE AS SKU,
CAST(0 AS INT) AS FK_DEALERCODE,
CAST(0 AS INT) AS FK_SKU,
10007 AS FK_TYPE_ID,
CAST(AH.DOCDATE AS DATE) AS DATE,
AL.LINEID AS ALLOCATIONLINEID,
AL.DOCID AS FK_ALLOCATIONDOCID,
CM.COMPANYTYPE AS COMPANYTYPE,
COUNT(AH.HEADERID) AS ACTUALQUANTITY,
DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS LASTUPDATEDDATETIME,-- --UTC_TO_IST_Changes_needed
AH.IMPORTEDDATE,
IM.CODE AS MODEL,
CAST(0 AS INT) AS FK_MODEL,
CAST(0 AS DECIMAL(19,0)) AS FLAG
--INTO  ASM_CV_ALLOCATION_FACT
FROM 
ALLOCATION_HEADER AH INNER JOIN COMPANY_MASTER CM ON (AH.COMPANYID=CM.COMPANYID AND CM.COMPANYTYPE = 7)
INNER JOIN ALLOCATION_LINE AL ON (AH.HEADERID=AL.DOCID)
JOIN ITEM_MASTER IM ON (IM.ITEMID=AL.ITEMID)
LEFT JOIN ITEMVARMATRIX_MASTER IV ON (AL.VARMATRIXID=IV.ITEMVARMATRIXID)
WHERE 
  --CAST(AH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND '2023-05-07' -- (504749 ROWS AFFECTED
--CAST(AH.DOCDATE AS DATE)>'2022-11-24'
--AH.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_CV_ALLOCATION_FACT)
CAST(AH.IMPORTEDDATE AS DATE) >= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_ALLOCATION_FACT) AS DATE)  --UPDATED ON 12/08
GROUP BY
CM.CODE,
IM.CODE+IV.CODE,
CAST(AH.DOCDATE AS DATE),
AL.LINEID,
AL.DOCID,
CM.COMPANYTYPE,
AH.IMPORTEDDATE,
IM.CODE 


--
DELETE FROM ASM_CV_ALLOCATION_FACT WHERE DATE>CAST(DATEADD(mi,30,(DATEADD(hh,5,getdate())))-1 AS DATE)-- --UTC_TO_IST_Changes_needed

--DEDUP PROCESS:


  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY FK_ALLOCATIONDOCID,ALLOCATIONLINEID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ALLOCATION_FACT                
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 

--**************************************************************************************************************

UPDATE B SET B.FK_SKU=C.PK_SKU FROM ASM_CV_ALLOCATION_FACT B INNER JOIN ASM_CV_PRODUCT_SKU_DIM C ON (B.SKU=C.SKU_CODE) -- (504745 ROWS AFFECTED)
UPDATE B SET B.FK_MODEL=C.PK_MODEL_CODE FROM ASM_CV_ALLOCATION_FACT B INNER JOIN ASM_CV_PRODUCT_DIM C ON (B.MODELCODE=C.MODELCODE) -- (504745 ROWS AFFECTED)
UPDATE B SET B.FK_DEALERCODE=C.PK_DEALERCODE FROM [DBO].[ASM_CV_ALLOCATION_FACT] B INNER JOIN ASM_CV_DEALER_MASTER_DIM C ON (B.DEALERCODE=C.DEALERCODE) -- (504747 ROWS AFFECTED)

--**************************************************************************


END
GO


