SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[USP_ASM_CV_RETAIL_REFRESH] AS
BEGIN

/********************************************HISTORY********************************************/
/*---------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------*/
/*  DATE       |  CREATED BY/MODIFIED BY |              CHANGE DESCRIPTION                     */
/*---------------------------------------------------------------------------------------------*/
/*  19/07/2024 |  Sarvesh Kulkarni       |            UTC to IST change for schedule update    */
/*  23/04/2024 |  Robin Singh            |            LSQ  Leadtype logic change               */
/*  09/05/2024 |  Robin Singh            |   Same day retail flag added                        */
/*  07/01/2025 |  Nikita Lakhimale            |   Usage Details field addition against Retail  */

/*  12/03/2025 |  Lachmanna           |   Pincode and Aare  against Retail  */
/*  26/03/2025 |  Ashwini Ahire            |First_Source_Lead_Type, First_Mode_Source,   First_Mode_SubSource*/
/*    14/08/2025 |  Richa Mishra            |        Addition of LSQ Targets  */
/*---------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------*/
/********************************************HISTORY********************************************/




--RETAIL DIM & FACT:
--RETAIL DIM:
--TRUNCATE TABLE ASM_CV_RETAIL_DIM
INSERT INTO ASM_CV_RETAIL_DIM
SELECT DISTINCT 
PK_RETAILHEADERID,
RETAILDATE,
MODEOFPURCHASE,
FINANCECOMPANY,
ISNULL(SALES_PERSON2,SALES_PERSON1) AS [SALES_PERSON],
[CREATEDATETIME],
IMPORTEDDATE,
CDMS_BATCHNO,
FINANCECATEGORY,
EXCHANGESTATUS,
OWNERSHIP_PROFILE,
EXCHANGE_OEM,
PREVIOUSLYOWNEDVEHICLE,
FUEL_TYPE_EXCHANGE_OEM,
SOURCE_OF_RETAIL,
FINANCIER,
USAGEDETAILS
FROM
(SELECT DISTINCT
RH.HEADERID AS PK_RETAILHEADERID,
CAST(RH.DOCDATE AS DATE) AS RETAILDATE,
RH.MODEOFPURCHASE AS MODEOFPURCHASE,
FM.FINANCECOMPANY AS FINANCECOMPANY,
TRIM(UPPER(CN.NAME)) AS SALES_PERSON1,
RHE.SALESPERSONNAME AS SALES_PERSON2,
DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS [CREATEDATETIME],--UTC_TO_IST_Changes_needed?
RH.IMPORTEDDATE,
RH.CDMS_BATCHNO,
FM.FINANCECATEGORY,
RH.ISEXCHANGEAPPLICABLE AS EXCHANGESTATUS,
CAST('' AS VARCHAR(255)) AS OWNERSHIP_PROFILE,
CAST('' AS VARCHAR(200)) AS EXCHANGE_OEM,
CAST('' AS VARCHAR(255)) AS PREVIOUSLYOWNEDVEHICLE,
CAST('' AS VARCHAR(50)) AS FUEL_TYPE_EXCHANGE_OEM,
CAST ( '' AS VARCHAR(50)) AS SOURCE_OF_RETAIL,
FM.FINANCERNAME AS FINANCIER,
NULL AS USAGEDETAILS
-- INTO ASM_CV_RETAIL_DIM
FROM RETAIL_HEADER RH
INNER JOIN COMPANY_MASTER ON (RH.COMPANYID=COMPANY_MASTER.COMPANYID AND COMPANY_MASTER.COMPANYTYPE = 7)
LEFT JOIN CONTACT_MASTER CN ON (CN.CONTACTID = RH.SALESPERSONID AND CN.ID = (SELECT MAX(CN1.ID) FROM CONTACT_MASTER CN1 WHERE CN.CONTACTID = CN1.CONTACTID))
INNER JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
LEFT JOIN RETAIL_LINE_EXT RLE ON (RL.LINEID=RLE.LINEID)
LEFT JOIN RETAIL_HEADER_EXT RHE ON (RH.HEADERID = RHE.HEADERID)
LEFT JOIN FINANCER_MASTER FM ON (RLE.FINANCERCONTACTID=FM.FINANCERID)
WHERE
RH.DOCTYPE IN(141,1000079,1000317,1012739,441)
AND
--CAST(RH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND CAST(GETDATE()-1 AS DATE)) A; --FULL LOAD
CAST(RH.IMPORTEDDATE AS DATE)>= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_RETAIL_DIM) AS DATE))A;  --INCR LOAD

--

DELETE FROM ASM_CV_RETAIL_DIM WHERE RETAILDATE>CAST( DATEADD(mi,30,(DATEADD(hh,5,getdate())))-1 AS DATE);--UTC_TO_IST_Changes_needed

--DEDUP

  WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_RETAILHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_RETAIL_DIM                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 

---- FINANCE MASTER UPDATES : NEW CR--------------
UPDATE RD
SET RD.FINANCECOMPANY = FM.FINANCECOMPANY
, RD.FINANCECATEGORY = FM.FINANCECATEGORY
, RD.FINANCIER = FM.FINANCERNAME
FROM 
ASM_CV_RETAIL_DIM RD
INNER JOIN RETAIL_HEADER RH  ON (RH.HEADERID=RD.PK_RETAILHEADERID)
INNER JOIN COMPANY_MASTER ON (RH.COMPANYID=COMPANY_MASTER.COMPANYID AND COMPANY_MASTER.COMPANYTYPE = 7)
LEFT JOIN CONTACT_MASTER CN ON (CN.CONTACTID = RH.SALESPERSONID AND CN.ID = (SELECT MAX(CN1.ID) FROM CONTACT_MASTER CN1 WHERE CN.CONTACTID = CN1.CONTACTID))
INNER JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
LEFT JOIN RETAIL_LINE_EXT RLE ON (RL.LINEID=RLE.LINEID)
LEFT JOIN RETAIL_HEADER_EXT RHE ON (RH.HEADERID = RHE.HEADERID)
LEFT JOIN FINANCER_MASTER FM ON (RLE.FINANCERCONTACTID=FM.FINANCERID) 


--*********************************************************************
 --PREVIOUSLYOWN VEHICLE
 --DROP TABLE ASM_CV_RETAIL_OWNS_PRFL
-- TRUNCATE TABLE ASM_CV_RETAIL_PREV_OWNVEH
INSERT INTO ASM_CV_RETAIL_PREV_OWNVEH
SELECT
DISTINCT 
RH.HEADERID AS PK_RETAILHEADERID,
CASE WHEN EH.CUSTOMEROWNERSHIPPROFILEID IN ('FIRST TIME BUYER', 'FIRST TIME USER') THEN 'FTB'
	--WHEN EH.CUSTOMEROWNERSHIPPROFILEID='FIRST TIME USER' THEN 'FTU'
	WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE='BAJAJ' THEN 'RTB - BAJAJ'
	WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE IN ('ATUL', 'OTHER', 'BAXY', 'PIAGGIO', 'TVS', 'MAHINDRA & MAHINDRA', 'VIKRAM', 'E-RICKSHAW') THEN 'RTB - COMPETITION'
	---WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE IS NULL THEN 'RTB - COMPETITION'
	ELSE EH.CUSTOMEROWNERSHIPPROFILEID END  AS OWNERSHIP_PROFILE,
EH.PREVIOUSLYOWNEDVEHICLE,
RH.DOCDATE,
RH.IMPORTEDDATE,
DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS CREATEDDATETIME
--INTO ASM_CV_RETAIL_PREV_OWNVEH
FROM RETAIL_HEADER RH INNER JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
LEFT JOIN BOOKING_LINE ON (RL.BOOKINGDATALINEID=BOOKING_LINE.LINEID)
LEFT JOIN ENQUIRY_LINE ON (BOOKING_LINE.ENQUIRYDATALINEID=ENQUIRY_LINE.LINEID)
LEFT JOIN ENQUIRY_HEADER EH ON (ENQUIRY_LINE.DOCID=EH.HEADERID)
INNER JOIN COMPANY_MASTER ON (RH.COMPANYID=COMPANY_MASTER.COMPANYID AND COMPANY_MASTER.COMPANYTYPE = 7)
WHERE
RH.DOCTYPE IN(141,1000079,1000317,1012739,441) 
AND
--CAST(RH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND  CAST(GETDATE()-1 AS DATE) --FULL LOAD
CAST(RH.IMPORTEDDATE AS DATE)>= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_RETAIL_PREV_OWNVEH) AS DATE)  --INCR LOAD
UNION 
SELECT
DISTINCT 
RH.HEADERID AS PK_RETAILHEADERID,
CASE WHEN EH.CUSTOMEROWNERSHIPPROFILEID IN ('FIRST TIME BUYER', 'FIRST TIME USER') THEN 'FTB'
	---WHEN EH.CUSTOMEROWNERSHIPPROFILEID='FIRST TIME USER' THEN 'FTU'
	WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE='BAJAJ' THEN 'RTB - BAJAJ'
	WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE IN ('ATUL', 'OTHER', 'BAXY', 'PIAGGIO', 'TVS', 'MAHINDRA & MAHINDRA', 'VIKRAM', 'E-RICKSHAW') THEN 'RTB - COMPETITION'
	---WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE IS NULL THEN 'RTB - COMPETITION'
	ELSE EH.CUSTOMEROWNERSHIPPROFILEID END AS OWNERSHIP_PROFILE,
EH.PREVIOUSLYOWNEDVEHICLE,
RH.DOCDATE,
RH.IMPORTEDDATE,
DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS CREATEDDATETIME--UTC_TO_IST_Changes_needed?
--INTO ASM_CV_RETAIL_PREV_OWNVEH
FROM RETAIL_HEADER RH INNER JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
INNER JOIN ALLOCATION_LINE AL ON (RL.ALLOCATIONDATALINEID=AL.LINEID)
INNER JOIN BOOKING_LINE ON (AL.BOOKINGDATALINEID=BOOKING_LINE.LINEID)
INNER JOIN ENQUIRY_LINE ON (BOOKING_LINE.ENQUIRYDATALINEID=ENQUIRY_LINE.LINEID)
INNER JOIN ENQUIRY_HEADER EH ON (ENQUIRY_LINE.DOCID=EH.HEADERID)
INNER JOIN COMPANY_MASTER ON (RH.COMPANYID=COMPANY_MASTER.COMPANYID AND COMPANY_MASTER.COMPANYTYPE = 7)
WHERE
RH.DOCTYPE IN(141,1000079,1000317,1012739,441) 
AND
--CAST(RH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND  CAST(GETDATE()-1 AS DATE) -- FULL LOAD
CAST(RH.IMPORTEDDATE AS DATE)>= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_RETAIL_PREV_OWNVEH) AS DATE)   --INCR LOAD



DELETE FROM ASM_CV_RETAIL_PREV_OWNVEH WHERE CAST(DOCDATE AS DATE)>CAST( DATEADD(mi,30,(DATEADD(hh,5,getdate())))-1 AS DATE)--UTC_TO_IST_Changes_needed

--DEDUP

  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_RETAILHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_RETAIL_PREV_OWNVEH                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;  

--
-----------------------------------

--UPDATE RETAI DIM:
UPDATE A 
SET 
A.PREVIOUSLYOWNEDVEHICLE=B.PREVIOUSLYOWNEDVEHICLE
FROM 
ASM_CV_RETAIL_PREV_OWNVEH B JOIN ASM_CV_RETAIL_DIM A ON A.PK_RETAILHEADERID=B.PK_RETAILHEADERID

--***********************************************************************

--BOOKING:
UPDATE RD
SET RD.OWNERSHIP_PROFILE=CASE WHEN BHE.CUSTOMEROWNERSHIPPROFILE IN ('FIRST TIME BUYER', 'FIRST TIME USER') THEN 'FTB'
	--WHEN BHE.CUSTOMEROWNERSHIPPROFILE='FIRST TIME USER' THEN 'FTU'
	WHEN BHE.CUSTOMEROWNERSHIPPROFILE='REPEAT TIME BUYER' AND BHE.PREVIOUSLYOWNEDVEHICLE='BAJAJ' THEN 'RTB - BAJAJ'
	WHEN BHE.CUSTOMEROWNERSHIPPROFILE='REPEAT TIME BUYER' AND BHE.PREVIOUSLYOWNEDVEHICLE IN ('ATUL', 'OTHER', 'BAXY', 'PIAGGIO', 'TVS', 'MAHINDRA & MAHINDRA', 'VIKRAM', 'E-RICKSHAW') THEN 'RTB - COMPETITION'
	---WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE IS NULL THEN 'RTB - COMPETITION'
	ELSE BHE.CUSTOMEROWNERSHIPPROFILE END
FROM ASM_CV_RETAIL_DIM RD
INNER JOIN RETAIL_LINE RL ON (RD.PK_RETAILHEADERID=RL.DOCID)
INNER JOIN BOOKING_LINE BL ON (RL.BOOKINGDATALINEID=BL.LINEID)
INNER JOIN BOOKING_HEADER_EXT BHE ON (BHE.HEADERID=BL.HEADERID)



--ALLOCATION:
UPDATE RD
SET RD.OWNERSHIP_PROFILE=CASE WHEN BHE.CUSTOMEROWNERSHIPPROFILE IN ('FIRST TIME BUYER', 'FIRST TIME USER') THEN 'FTB'
	--WHEN BHE.CUSTOMEROWNERSHIPPROFILE='FIRST TIME USER' THEN 'FTU'
	WHEN BHE.CUSTOMEROWNERSHIPPROFILE='REPEAT TIME BUYER' AND BHE.PREVIOUSLYOWNEDVEHICLE='BAJAJ' THEN 'RTB - BAJAJ'
	WHEN BHE.CUSTOMEROWNERSHIPPROFILE='REPEAT TIME BUYER' AND BHE.PREVIOUSLYOWNEDVEHICLE IN ('ATUL', 'OTHER', 'BAXY', 'PIAGGIO', 'TVS', 'MAHINDRA & MAHINDRA', 'VIKRAM', 'E-RICKSHAW') THEN 'RTB - COMPETITION'
	---WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE IS NULL THEN 'RTB - COMPETITION'
	ELSE BHE.CUSTOMEROWNERSHIPPROFILE END
FROM ASM_CV_RETAIL_DIM RD
INNER JOIN RETAIL_LINE RL ON (RD.PK_RETAILHEADERID=RL.DOCID)
INNER JOIN ALLOCATION_LINE AL ON (AL.LINEID=RL.ALLOCATIONDATALINEID)
INNER JOIN BOOKING_LINE BL ON (AL.BOOKINGDATALINEID=BL.LINEID)
INNER JOIN BOOKING_HEADER_EXT BHE ON (BHE.HEADERID=BL.HEADERID)




--*************************************************************************

--EXCHANGE OEM:
--TRUNCATE TABLE ASM_CV_RETAIL_EXCHANGE_OEM

INSERT INTO ASM_CV_RETAIL_EXCHANGE_OEM
SELECT DISTINCT
RH.HEADERID AS PK_RETAILHEADERID,
COMPETITOR_ITEM_MASTER.NAME AS EXCHANGE_OEM,
DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS CREATEDDATETIME,--UTC_TO_IST_Changes_needed?
RH.DOCDATE,
RH.IMPORTEDDATE,
CASE
WHEN UPPER(COMPETITOR_ITEM_MASTER.NAME) LIKE '%LPG%' THEN 'LPG'
WHEN UPPER(COMPETITOR_ITEM_MASTER.NAME) LIKE '%CNG%' THEN 'CNG'
WHEN UPPER(COMPETITOR_ITEM_MASTER.NAME) LIKE '%PETROL%' THEN 'PETROL'  
WHEN UPPER(COMPETITOR_ITEM_MASTER.NAME) LIKE '%DIESEL%' OR UPPER(COMPETITOR_ITEM_MASTER.NAME) LIKE '%DSL%' OR UPPER(COMPETITOR_ITEM_MASTER.NAME) LIKE '%DSAL%' THEN 'DIESEL'  
WHEN UPPER(COMPETITOR_ITEM_MASTER.NAME) LIKE '%PETROL/LPG %' THEN 'PETROL/LPG'
ELSE 'OTHERS'
END AS FUEL_TYPE_EXCHANGE_OEM
--INTO ASM_CV_RETAIL_EXCHANGE_OEM
FROM 
RETAIL_HEADER RH
INNER JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
LEFT JOIN RETAIL_LINE_EXT RLE ON (RL.LINEID=RLE.LINEID)
INNER JOIN COMPETITOR_ITEM_MASTER ON (RLE.EXCHANGEMODELID = COMPETITOR_ITEM_MASTER.COMPETITORITEMID)
INNER JOIN COMPANY_MASTER ON (RH.COMPANYID=COMPANY_MASTER.COMPANYID AND COMPANY_MASTER.COMPANYTYPE = 7)
WHERE
RH.DOCTYPE IN(141,1000079,1000317,1012739,441) 
AND
--CAST(RH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND  CAST(GETDATE()-1 AS DATE)   --FULL LOAD
CAST(RH.IMPORTEDDATE AS DATE)>= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_RETAIL_EXCHANGE_OEM) AS DATE)  --INCR LOAD
--

DELETE FROM ASM_CV_RETAIL_EXCHANGE_OEM WHERE CAST(DOCDATE AS DATE)>CAST( DATEADD(mi,30,(DATEADD(hh,5,getdate())))-1 AS DATE) --UTC_TO_IST_Changes_needed

--DEDUP

  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_RETAILHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_RETAIL_EXCHANGE_OEM                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;   

--UPDATE RETAIL DIM FOR OEM EXCHAGE:

UPDATE A SET A.EXCHANGE_OEM=B.EXCHANGE_OEM,
A.FUEL_TYPE_EXCHANGE_OEM=B.FUEL_TYPE_EXCHANGE_OEM
FROM 
ASM_CV_RETAIL_EXCHANGE_OEM B JOIN ASM_CV_RETAIL_DIM A ON A.PK_RETAILHEADERID=B.PK_RETAILHEADERID

--***********************************************************************
--RETAIL FACT:
--TRUNCATE TABLE ASM_CV_RETAIL_STG

INSERT INTO ASM_CV_RETAIL_STG
SELECT DISTINCT 
DEALERCODE,
SKU,
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
DATE,
RETAILLINEID,
FK_RETAILDOCID,
COMPANYTYPE,
BRANCHID,
TEHSILID,
CASE
WHEN SALES_PERSON1='LEAD TEST ' AND SALES_PERSON2  IS NOT NULL THEN SALES_PERSON2 
WHEN SALES_PERSON2='LEAD TEST ' AND SALES_PERSON1  IS NOT NULL THEN SALES_PERSON1 
ELSE  ISNULL (SALES_PERSON1,SALES_PERSON2)  
END AS [SALES_PERSON],
ACTUALQUANTITY,
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
CDMS_BATCHNO,
PERIODNAME,
COLOUR_CODE,
MODELCODE,
FK_MODEL,
FLAG,
LOANTOVALUE,
DISTRICT_NAME
,NULL AS LEADTYPE
,CODE
,NULL AS Campaign_code
,NULL AS IS_SAMEDAYRETAIL
,RetailSalesperson_id
FROM
(SELECT DISTINCT
CM.CODE AS DEALERCODE,																																							
IM.CODE+IV.CODE AS SKU,
CAST(0 AS INT) AS FK_DEALERCODE,
CAST(0 AS INT) AS FK_SKU,
10002 AS FK_TYPE_ID,
CAST(RH.DOCDATE AS DATE) AS DATE,
RL.LINEID AS RETAILLINEID,
RL.DOCID AS FK_RETAILDOCID,
CM.COMPANYTYPE AS COMPANYTYPE,
RH.BRANCHID,
RH.TEHSIL3W AS TEHSILID,
REPLACE(CONCAT(TRIM(CN.FIRSTNAME),' ',TRIM(CN.LASTNAME)),'  ','') AS SALES_PERSON1,
REPLACE(REPLACE(RHE.SALESPERSONNAME,CHAR(160),''),'  ','') AS SALES_PERSON2,
COUNT(DISTINCT RL.SERIALNO) AS ACTUALQUANTITY,
0 AS TARGETQUANTITY,  
DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS LASTUPDATEDDATETIME,--UTC_TO_IST_Changes_needed?
RH.IMPORTEDDATE,
RH.CDMS_BATCHNO,
(LEFT(DATENAME( MONTH,RH.DOCDATE),3)+'-'+CAST(YEAR(RH.DOCDATE) AS VARCHAR(4))) AS PERIODNAME,
IV.CODE AS COLOUR_CODE,
IM.CODE AS MODELCODE,
CAST(0 AS INT) AS FK_MODEL,
100021 AS FLAG,
ISNULL(RL.FINANCEAMOUNT/NULLIF(RL.TOTALAMOUNT,0),0) AS LOANTOVALUE,
A2.NAME AS DISTRICT_NAME,
CN.CODE,
LU.USERID As RetailSalesperson_id
--INTO ASM_CV_RETAIL_STG
FROM
   RETAIL_HEADER RH JOIN COMPANY_MASTER CM ON (RH.COMPANYID=CM.COMPANYID AND CM.COMPANYTYPE = 7)
   LEFT JOIN CONTACT_MASTER CN ON (RH.SALESPERSONID = CN.CONTACTID AND CN.ID = (SELECT MAX(CN1.ID) FROM CONTACT_MASTER CN1 WHERE CN.CONTACTID = CN1.CONTACTID))
   JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
   JOIN ITEM_MASTER IM ON (IM.ITEMID=RL.ITEMID AND IM.CODE<>'999.') -- RCA FOR PRIMARY USAGE BLANK(153 ON SCREEN): EXCLUDED FROM IMTEM MASTER ON 10TH FEB 2023 AFTER CONFIRMATION OF MAHESK SIR
   LEFT JOIN CONTACT_MASTER CN2 ON (RH.CONTACTID = CN2.CONTACTID AND CN2.ID = (SELECT MAX(CN3.ID) FROM CONTACT_MASTER CN3 WHERE CN2.CONTACTID = CN3.CONTACTID))
   LEFT JOIN CONTACT_ADDRESS CA ON (CN2.CONTACTID = CA.CONTACTID AND ISNULL(CAST(CA.IMPORTEDDATE AS DATE) ,'01/01/1900') = (SELECT ISNULL(MAX(CAST(CNA2.IMPORTEDDATE AS DATE)),'01/01/1900') FROM CONTACT_MASTER CNA2 WHERE CA.CONTACTID = CNA2.CONTACTID))
   LEFT JOIN AREA_MASTER A2 ON ( CA.DISTRICTID = A2.AREAMASTERID AND ISNULL(CAST(A2.IMPORTEDDATE AS DATE),'01/01/1900') = (SELECT ISNULL(MAX(CAST(A12.IMPORTEDDATE AS DATE)),'01/01/1900') FROM AREA_MASTER A12 WHERE A2.AREAMASTERID = A12.AREAMASTERID) AND A2.LEVEL = 2)
   LEFT JOIN ITEMVARMATRIX_MASTER IV ON (RL.VARMATRIXID=IV.ITEMVARMATRIXID)
   LEFT JOIN SAP_ZDEALER_TARGET ON (CM.CODE=SAP_ZDEALER_TARGET.DEALER_CODE AND MONTH(RH.DOCDATE)=SAP_ZDEALER_TARGET.ZMONTH AND YEAR(RH.DOCDATE)=SAP_ZDEALER_TARGET.ZYEAR)
   LEFT JOIN RETAIL_HEADER_EXT RHE ON (RH.HEADERID = RHE.HEADERID)
   LEFT JOIN LSQ_USERS LU ON (LU.mx_custom_51=cast(RH.SALESPERSONID as Nvarchar))
WHERE 
	RH.DOCTYPE IN(141,1000079,1000317,1012739,441) 
  AND
--CAST(RH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND  CAST(GETDATE()-1 AS DATE) --FULL LOAD
CAST(RH.IMPORTEDDATE AS DATE)>= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_RETAIL_STG) AS DATE)   --INCR LOAD
GROUP BY
   CM.CODE,
   IM.CODE+IV.CODE,
   CAST(RH.DOCDATE AS DATE),  
   RL.LINEID,
   RL.DOCID,
   CM.COMPANYTYPE,
   RH.BRANCHID,
   RH.TEHSIL3W,
   CN.FIRSTNAME,
   CN.LASTNAME,
   RHE.SALESPERSONNAME,
   RH.IMPORTEDDATE,  
   RH.CDMS_BATCHNO,
   (LEFT(DATENAME( MONTH,RH.DOCDATE),3)+'-'+CAST(YEAR(RH.DOCDATE) AS VARCHAR(4))),
   IV.CODE,
   IM.CODE,
   ISNULL(RL.FINANCEAMOUNT/NULLIF(RL.TOTALAMOUNT,0),0),
   A2.NAME,
   CN.CODE, LU.USERID) BASE



  DELETE FROM ASM_CV_RETAIL_STG WHERE DATE>CAST( DATEADD(mi,30,(DATEADD(hh,5,getdate())))-1 AS DATE)--UTC_TO_IST_Changes_needed?
 
 --DEDUP PROCESS:
   ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY FK_RETAILDOCID,RETAILLINEID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_RETAIL_STG                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 



--**********************************************************************************
  --STEP 2:
--PRODUCT MASTER AND DEALER MASTER FK UPDATE: ASM_CV_RETAIL_STG
UPDATE B SET B.FK_SKU=C.PK_SKU FROM ASM_CV_RETAIL_STG B INNER JOIN ASM_CV_PRODUCT_SKU_DIM C ON (B.SKU=C.SKU_CODE) -- (517934 ROWS AFFECTED)
UPDATE B SET B.FK_MODEL=C.PK_MODEL_CODE FROM ASM_CV_RETAIL_STG B INNER JOIN ASM_CV_PRODUCT_DIM C ON (B.MODELCODE=C.MODELCODE) -- (517934 ROWS AFFECTED)
UPDATE B SET B.FK_DEALERCODE=C.PK_DEALERCODE FROM [DBO].[ASM_CV_RETAIL_STG] B INNER JOIN ASM_CV_DEALER_MASTER_DIM C ON (B.DEALERCODE=C.DEALERCODE) -- (518087 ROWS AFFECTED)

--********************************************************************


--***************************************************************************
--TARGET DATA:RETAIL

TRUNCATE TABLE ASM_CV_RETAIL_TARGET

INSERT INTO ASM_CV_RETAIL_TARGET
(DEALERCODE, SKU, FK_DEALERCODE, FK_SKU, FK_TYPE_ID, DATE, RETAILLINEID, FK_RETAILDOCID, COMPANYTYPE, BRANCHID, TEHSILID, SALES_PERSON, ACTUALQUANTITY, TARGETQUANTITY, LASTUPDATEDDATETIME, IMPORTEDDATE, CDMS_BATCHNO, PERIODNAME, COLOUR_CODE, MODELCODE, FK_MODEL, FLAG, LOANTOVALUE, DISTRICT_NAME, LEADTYPE, CODE, Campaign_Code, IS_SAMEDAYRETAIL)

SELECT DISTINCT 
DEALERCODE
,CAST('' AS VARCHAR(50)) AS SKU
,CAST('' AS INT) AS FK_DEALERCODE
,CAST('' AS INT) AS FK_SKU
,10002 AS FK_TYPE_ID
,CAST(CONVERT(DATETIME, REPLACE(PERIODNAME, '-', ' ')) AS DATE) AS DATE
,CAST(NULL AS DECIMAL(19,0)) AS RETAILLINEID
,CAST(NULL AS DECIMAL(19,0)) AS FK_RETAILDOCID
,CAST(NULL AS DECIMAL(19,0)) AS COMPANYTYPE
,CAST(NULL AS DECIMAL(19,0)) AS BRANCHID
,CAST(NULL AS DECIMAL(19,0)) AS TEHSILID
,CAST('' AS VARCHAR(50)) AS SALES_PERSON
,CAST(NULL AS DECIMAL(10,0)) AS ACTUALQUANTITY
,ROUND(SUM(CAST(VOLUMETARGET AS DECIMAL(19,0))),0) AS TARGETQUANTITY
,DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS LASTUPDATEDDATETIME--UTC_TO_IST_Changes_needed?
,IMPORTEDDATE
,CDMS_BATCHNO
,PERIODNAME
,CAST('' AS VARCHAR(25)) AS COLOUR_CODE
,MODELCODE
,CAST(NULL AS INT) AS FK_MODEL
,100022 AS FLAG
,CAST(0 AS DECIMAL(19,0)) AS LOANTOVALUE
,CAST('' AS VARCHAR(50)) AS DISTRICT_NAME
,NULL AS LEADTYPE
,NULL AS CODE
,NULL AS Campaign_Code
,NULL AS IS_SAMEDAYRETAIL

--INTO ASM_CV_RETAIL_TARGET_1
FROM
TARGET_SALES_3W	WHERE CAST(CONVERT(DATETIME, REPLACE(PERIODNAME, '-', ' ')) AS DATE)<CAST( DATEADD(mi,30,(DATEADD(hh,5,getdate()))) AS DATE) --UTC_TO_IST_Changes_needed
GROUP BY
DEALERCODE,
IMPORTEDDATE,
CDMS_BATCHNO,
PERIODNAME,
MODELCODE
----LSQ Data Target  --------------------------------------

SELECT CAST(userID AS VARCHAR(36)) AS userID,CAST(TemplateId AS VARCHAR(36)) AS TemplateId , CAST(RecurrenceId AS VARCHAR(36)) as RecurrenceId, CAST(RecurrenceStartDate AS DATE) as RecurrenceStartDate,
    CAST(RecurrenceEndDate AS DATE) as RecurrenceEndDate , CAST(RecurrenceStatus AS VARCHAR(36)) as RecurrenceStatus, 
	CAST(dealer_code AS VARCHAR(36)) as dealer_code, 
	CAST(branch AS VARCHAR(36))  as branch, 
	CAST(Firstname AS VARCHAR(36))  as Firstname, 
	CAST(PhoneMobile AS VARCHAR(36))  as PhoneMobile,
	CAST(Designation AS VARCHAR(36))  as Designation, 
	ISNULL(SUM(TRY_CAST(Target AS DECIMAL(10,2))), 0) AS Target,  CAST(TeamTarget AS VARCHAR(36))  as TeamTarget, 
	CAST(SubGoalCondition AS VARCHAR(36))  as SubGoalCondition, CAST(SubGoal AS VARCHAR(36))  as subgoal
INTO #LSQTarget --LSQTargettemp 
FROM 
(SELECT TR.*, Designation, mx_Custom_2 AS branch, mx_Custom_5 AS BU, mx_Custom_10 AS dealer_code, Firstname,PhoneMobile FROM (SELECT TemplateId, RecurrenceId, userID, SubGoalCondition, SUM(TRY_CAST(Target AS DECIMAL(10,2))) AS Target, TeamTarget,
RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, subgoal FROM LSQ_TARGET_DISTRIBUTION_DATA
 WHERE TemplateId = '6972c6b7-8f35-4baa-92f4-cb66ecdc7db6' 
 /*and RecurrenceId in ('e50b5dda-b024-4cd7-9cda-56bb5fdefcec', 'da595ee9-2a10-4b41-a793-c5cf3f9ca72c', 'b8a7e92d-fece-4151-94eb-cceceff53ab3', '7b6c5db5-f990-4b14-894b-f33bc3c7dac6', 'd5d3f278-29c0-4fed-be70-d2aee5a2a0d1', '0bdb3e25-e8a8-4248-a8be-6ab046ac33eb', '89add1a1-7eb4-402f-a6f6-2f361a535c66', '64011b45-3cae-41c3-a0ba-5f5f5b0def16', '205ca53d-f669-486f-8740-578cde5ed060', 
 '62b0fc18-9448-4010-9f0c-5ab6cad90ba6','2e4b2061-40b4-4b42-80e7-4fe2b1185fe9') */
 GROUP BY TemplateId, RecurrenceId, userID, RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, TeamTarget,
 SubGoalCondition, subgoal) TR 
 JOIN LSQ_Users LS ON LS.userID = TR.userID 
 WHERE mx_Custom_5 = 'CV' --AND Designation IN ('DSE', 'Sales Manager', 'M', 'GM')
 ) a 
 GROUP BY TemplateId, RecurrenceId, RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, dealer_code, branch, Designation, userID,
 Firstname, PhoneMobile, SubGoalCondition, subgoal,TeamTarget




INSERT INTO ASM_CV_RETAIL_TARGET
SELECT  
DEALERCODE,
SKU,
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
DATE,
RETAILLINEID,
FK_RETAILDOCID,
COMPANYTYPE,
BRANCHID,
TEHSILID,
SALES_PERSON,
ACTUALQUANTITY,
TARGETQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
CDMS_BATCHNO,
PERIODNAME,
COLOUR_CODE,
MODELCODE,
FK_MODEL,
FLAG,
LOANTOVALUE,
DISTRICT_NAME,
Leadtype,
CODE,
Campaign_Code,
IS_SAMEDAYRETAIL,--Pincode, Area,First_Source_Lead_Type, First_Mode_Source, First_Mode_SubSource
Salesperson_id,
Designation,
recurrence_id,
Subgoal,
PhoneMobile, Model, TeamTarget
from(
SELECT 
   
dealer_code as  DEALERCODE
,CAST('' AS VARCHAR(50)) AS SKU
,CAST('' AS INT) AS FK_DEALERCODE
,CAST('' AS INT) AS FK_SKU
,10002 AS FK_TYPE_ID
,RecurrenceStartDate AS DATE  ----------Convert
,TRY_CAST(TemplateId AS DECIMAL(18,0)) AS RETAILLINEID  --null  AS RETAILLINEID  --TemplateId
,TRY_CAST(RecurrenceId AS DECIMAL(18,0)) AS FK_RETAILDOCID   --null  AS FK_RETAILDOCID   --RecurrenceId
,CAST(NULL AS DECIMAL(19,0)) AS COMPANYTYPE
,BM.Branchid AS BRANCHID
,CAST(NULL AS DECIMAL(19,0)) AS TEHSILID
,Firstname AS SALES_PERSON
,CAST(NULL AS DECIMAL(10,0)) AS ACTUALQUANTITY
,ISNULL(TRY_CAST(Target AS DECIMAL(10,2)), 0) AS TARGETQUANTITY
,GETDATE() AS LASTUPDATEDDATETIME
,IMPORTEDDATE
,CDMS_BATCHNO
,null as PERIODNAME
,CAST('' AS VARCHAR(25)) AS COLOUR_CODE
,P.MODELCODE
,CAST(NULL AS INT) AS FK_MODEL
,100023 AS FLAG
,CAST(0 AS DECIMAL(19,0)) AS LOANTOVALUE
,CAST('' AS VARCHAR(50)) AS DISTRICT_NAME
,NULL AS LEADTYPE
,NULL AS CODE
,NULL AS Campaign_Code
,NULL AS IS_SAMEDAYRETAIL
--Null As Pincode,Null As Area, Null As First_Source_Lead_Type,Null As First_Mode_Source,Null As First_Mode_SubSource
,userID as Salesperson_id
,Designation as Designation
,RecurrenceId as recurrence_id,
Subgoal as Subgoal,
PhoneMobile as PhoneMobile,
LTRIM(RTRIM(REPLACE(LT.Subgoalcondition, 'Brand = ', ''))) as Model,
TeamTarget

--,Null As Pincode,Null As Area,Null As First_Source_Lead_Type,Null As First_Mode_Source,Null As First_Mode_SubSource 
FROM
#LSQTarget LT
left JOIN BRANCH_MASTER BM ON LT.BRANCH=BM.CODE
left JOIN (
    SELECT Model, 
           Modelcode, 
           FINANCE_CATEGORY, rn
    FROM (
        SELECT Model, 
               Modelcode, 
               FINANCE_CATEGORY,
               ROW_NUMBER() OVER (PARTITION BY finance_category ORDER BY Brand) AS rn
        FROM ASM_CV_PRODUCT_DIM P
    ) t
    WHERE rn = 1
) P  ON LTRIM(RTRIM(REPLACE(LT.Subgoalcondition, 'Brand = ', ''))) = P.FINANCE_CATEGORY

)B


--************************************************************
--PRODUCT MASTER AND DEALER MASTER FK UPDATE: ASM_CV_ENQUIRY_TARGET
--STEP 4:
UPDATE B SET B.FK_MODEL=C.PK_MODEL_CODE FROM ASM_CV_RETAIL_TARGET B INNER JOIN ASM_CV_PRODUCT_DIM C ON (B.MODELCODE=C.MODELCODE)
UPDATE B SET B.FK_DEALERCODE=C.PK_DEALERCODE FROM ASM_CV_RETAIL_TARGET B INNER JOIN ASM_CV_DEALER_MASTER_DIM C ON (B.DEALERCODE=C.DEALERCODE)

--********************************************************
--STEP 5:
TRUNCATE TABLE ASM_CV_RETAIL_FACT


INSERT INTO ASM_CV_RETAIL_FACT (DEALERCODE, SKU, FK_DEALERCODE, FK_SKU, FK_TYPE_ID, DATE, RETAILLINEID, FK_RETAILDOCID, COMPANYTYPE, BRANCHID, TEHSILID, SALES_PERSON, ACTUALQUANTITY, TARGETQUANTITY, LASTUPDATEDDATETIME, IMPORTEDDATE, CDMS_BATCHNO, PERIODNAME, COLOUR_CODE, MODELCODE, FK_MODEL, FLAG, LOANTOVALUE, DISTRICT_NAME, Leadtype, CODE, Campaign_Code, IS_SAMEDAYRETAIL, Pincode, Area, First_Source_Lead_Type, First_Mode_Source, First_Mode_SubSource, Salesperson_id, Designation, Recurrence_id, Subgoal,PhoneMobile,Model,RetailSalesperson_id, TeamTarget)
SELECT  DEALERCODE, SKU, FK_DEALERCODE, FK_SKU, FK_TYPE_ID, DATE, RETAILLINEID, FK_RETAILDOCID, COMPANYTYPE, BRANCHID, TEHSILID, SALES_PERSON, ACTUALQUANTITY, TARGETQUANTITY, LASTUPDATEDDATETIME, IMPORTEDDATE, CDMS_BATCHNO, PERIODNAME, COLOUR_CODE, MODELCODE, FK_MODEL, FLAG, LOANTOVALUE, DISTRICT_NAME, NULL AS Leadtype, CODE, NULL AS Campaign_Code, NULL AS IS_SAMEDAYRETAIL, NULL AS Pincode, NULL AS Area, NULL AS First_Source_Lead_Type, NULL AS First_Mode_Source, NULL AS First_Mode_SubSource, NULL AS Salesperson_id, NULL AS Designation, NULL AS Recurrence_id, NULL AS Subgoal, null as PhoneMobile, Null as Model, RetailSalesperson_id, NULL AS TeamTarget FROM ASM_CV_RETAIL_STG
union
SELECT DEALERCODE, SKU, FK_DEALERCODE, FK_SKU, FK_TYPE_ID, DATE, RETAILLINEID, FK_RETAILDOCID, COMPANYTYPE, BRANCHID, TEHSILID, SALES_PERSON, ACTUALQUANTITY, TARGETQUANTITY, LASTUPDATEDDATETIME, IMPORTEDDATE, CDMS_BATCHNO, PERIODNAME, COLOUR_CODE, MODELCODE, FK_MODEL, FLAG, LOANTOVALUE, DISTRICT_NAME, Leadtype, CODE, Campaign_Code, IS_SAMEDAYRETAIL, NULL, NULL, NULL, NULL, NULL, Salesperson_id, Designation, Recurrence_id, Subgoal,PhoneMobile,Model,null,TeamTarget FROM ASM_CV_RETAIL_TARGET;
--*****************************************************************************

----------------------- DELETION OF SALES RETURNED -------------------


TRUNCATE TABLE RETAIL_SALES_RETURN_STAGE;
INSERT INTO RETAIL_SALES_RETURN_STAGE
SELECT DISTINCT ASM_CV_RETAIL_FACT.FK_RETAILDOCID,
ASM_CV_RETAIL_FACT.RETAILLINEID, 
RETAIL_HEADER.DOCNAME

FROM ASM_CV_RETAIL_FACT
	JOIN ASM_CV_DEALER_MASTER_DIM
	ON ASM_CV_DEALER_MASTER_DIM.PK_DEALERCODE=ASM_CV_RETAIL_FACT.FK_DEALERCODE
	JOIN RETAIL_HEADER RETAIL_HEADER
	ON RETAIL_HEADER.HEADERID=ASM_CV_RETAIL_FACT.FK_RETAILDOCID
	JOIN RETAIL_LINE RETAIL_LINE
	ON RETAIL_LINE.LINEID=ASM_CV_RETAIL_FACT.RETAILLINEID
	JOIN RETAIL_LINE_RETURN --- SALES RETRUN TABLE
	ON RETAIL_LINE_RETURN.SALEINVOICELINEID=ASM_CV_RETAIL_FACT.RETAILLINEID;
	
DELETE A
FROM ASM_CV_RETAIL_FACT A 
INNER JOIN RETAIL_SALES_RETURN_STAGE B
ON A.FK_RETAILDOCID=B.FK_RETAILDOCID
AND A.RETAILLINEID=B.RETAILLINEID


------------------------- SOURCE OF RETAIL UPDATE ---------------------------------

UPDATE RETAIL_DIM
SET RETAIL_DIM.SOURCE_OF_RETAIL=SOURCE_OF_ENQUIRY.VALUENAME
FROM 
ASM_CV_RETAIL_DIM RETAIL_DIM
INNER JOIN  RETAIL_HEADER RH ON (RH.HEADERID=RETAIL_DIM.PK_RETAILHEADERID)
INNER JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
INNER JOIN BOOKING_LINE ON (RL.BOOKINGDATALINEID=BOOKING_LINE.LINEID)
INNER JOIN ENQUIRY_LINE ON (BOOKING_LINE.ENQUIRYDATALINEID=ENQUIRY_LINE.LINEID)
INNER JOIN ENQUIRY_HEADER EH ON (ENQUIRY_LINE.DOCID=EH.HEADERID)
LEFT JOIN ENQUIRY_HEADER_EXT EHE ON (EH.HEADERID = EHE.HEADERID)
LEFT OUTER JOIN SOURCE_OF_ENQUIRY ON (EHE.SOURCEOFENQUIRY=SOURCE_OF_ENQUIRY.VALUEID) 
;
---LSQ MAIN UPDATE----

UPDATE RETAIL_DIM
SET RETAIL_DIM.SOURCE_OF_RETAIL=LSQ_PBASE.MX_SOURCE_OF_ENQUIRY
FROM 
ASM_CV_RETAIL_DIM RETAIL_DIM
INNER JOIN  RETAIL_HEADER RH ON (RH.HEADERID=RETAIL_DIM.PK_RETAILHEADERID)
INNER JOIN RETAIL_LINE RL ON (RH.HEADERID=RL.DOCID)
INNER JOIN ALLOCATION_LINE AL ON (AL.LINEID=RL.ALLOCATIONDATALINEID)
INNER JOIN BOOKING_LINE ON  (BOOKING_LINE.LINEID=AL.BOOKINGDATALINEID)
INNER JOIN BOOKING_HEADER BH ON (BOOKING_LINE.HEADERID=BH.HEADERID)
INNER JOIN BOOKING_HEADER_EXT BHE ON (BH.HEADERID = BHE.HEADERID)
INNER JOIN LSQ_PROSPECTACTIVITY_EXTENSIONBASE PAE ON (CAST(PAE.RELATEDPROSPECTID+','+PAE.PROSPECTACTIVITYEXTENSIONID AS VARCHAR(8000))
=BHE.LMSBOOKINGID)
AND PAE.ACTIVITYEVENT=12003 
--AND PAE.MX_CUSTOM_48 IS NULL
INNER JOIN LSQ_PROSPECT_BASE LSQ_PBASE ON (LSQ_PBASE.PROSPECTID=PAE.RELATEDPROSPECTID)
WHERE BHE.LMSBOOKINGID IS NOT NULL;

/* ADDITION OF LEAD TYPE  LOGIC*/
SELECT DISTINCT PK_RETAILHEADERID,COALESCE(EH1.LEADTYPE,EH2.LEADTYPE,LSQ_PBASE1.MX_ENQUIRY_MODE , LSQ_PBASE1.mx_Mode_of_Enquiry,LSQ_PBASE2.MX_ENQUIRY_MODE,LSQ_PBASE2.mx_Mode_of_Enquiry) LEADTYPE, 
coalesce(LSQ_PEXTBASE1.mx_CV_Campaign_Code , LSQ_PEXTBASE2.mx_CV_Campaign_Code)Campaign_Code,RETAIL_DIM.RETAILDATE AS  RETAIL_DATE, coalesce(CAST(DATEADD(mi,30,(DATEADD(hh,5,LSQ_PEXTBASE1.mx_Dealer_Assignment_Date))) AS DATE),CAST(DATEADD(mi,30,(DATEADD(hh,5,LSQ_PEXTBASE2.mx_Dealer_Assignment_Date))) AS DATE ), Cast(EH1.DOCDATE As Date), Cast(EH2.DOCDATE As Date))	AS ENQUIRY_DATE	 ,
coalesce (EH1.USAGEDETAILS,EH2.USAGEDETAILS,PAE1.MX_CUSTOM_70,PAE2.MX_CUSTOM_70) AS USAGEDETAILS,
 coalesce(LSQ_PBASE1.MX_PINCODE , LSQ_PBASE2.MX_PINCODE) AS PINCODE, 
coalesce(LSQ_PBASE1.MX_AREA , LSQ_PBASE2.MX_AREA) AS AREA,

CASE WHEN coalesce(CAST(LSQ_PEXTBASE1.MX_DEALER_ASSIGNMENT_DATE AS DATE),CAST(LSQ_PEXTBASE2.MX_DEALER_ASSIGNMENT_DATE AS DATE))>='2024-12-01' THEN coalesce(EH1.LEADTYPE,EH2.LEADTYPE,PE1.mx_Qualified_First_Source ,PE2.mx_Qualified_First_Source) END AS First_Source_Lead_type,
ISNULL(COALESCE(PE1.mx_Qualified_Source_of_Enquiry,PE2.mx_Qualified_Source_of_Enquiry), 'Not Available')   AS First_Mode_Source,
ISNULL(COALESCE(PE1.mx_Qualified_Sub_Source,PE2.mx_Qualified_Sub_Source), 'Not Available') AS First_Mode_SubSource

INTO #CV_LEADTYPE_RETAIL
FROM 
ASM_CV_RETAIL_DIM RETAIL_DIM
INNER JOIN  RETAIL_HEADER RH ON (RH.HEADERID=RETAIL_DIM.PK_RETAILHEADERID)
LEFT JOIN RETAIL_LINE RL1 ON (RH.HEADERID=RL1.DOCID)
LEFT JOIN ALLOCATION_LINE AL ON (AL.LINEID=RL1.ALLOCATIONDATALINEID)
LEFT JOIN BOOKING_LINE BL1 ON  (BL1.LINEID=AL.BOOKINGDATALINEID)
LEFT JOIN RETAIL_LINE RL2 ON RL2.DOCID = RH.HEADERID
LEFT JOIN BOOKING_LINE BL2 ON RL2.BOOKINGDATALINEID = BL2.LINEID
LEFT JOIN ENQUIRY_LINE EL1 ON EL1.LINEID = BL1.ENQUIRYDATALINEID
LEFT JOIN ENQUIRY_LINE EL2 ON EL2.LINEID = BL2.ENQUIRYDATALINEID
LEFT JOIN ENQUIRY_HEADER EH1 ON EH1.HEADERID = EL1.DOCID
LEFT JOIN ENQUIRY_HEADER EH2 ON EH2.HEADERID = EL2.DOCID
LEFT JOIN BOOKING_HEADER_EXT BHE1 ON (BL1.HEADERID = BHE1.HEADERID)
LEFT JOIN BOOKING_HEADER_EXT BHE2 ON (BL2.HEADERID = BHE2.HEADERID)
LEFT JOIN LSQ_PROSPECTACTIVITY_EXTENSIONBASE PAE1 ON (CAST(PAE1.RELATEDPROSPECTID+','+PAE1.PROSPECTACTIVITYEXTENSIONID AS VARCHAR(8000))=BHE1.LMSBOOKINGID) AND PAE1.ACTIVITYEVENT=12003 
--AND PAE1.MX_CUSTOM_48 IS NULL
LEFT JOIN LSQ_PROSPECT_BASE LSQ_PBASE1 ON (LSQ_PBASE1.PROSPECTID=PAE1.RELATEDPROSPECTID)
LEFT JOIN LSQ_PROSPECTACTIVITY_EXTENSIONBASE PAE2 ON (CAST(PAE2.RELATEDPROSPECTID+','+PAE2.PROSPECTACTIVITYEXTENSIONID AS VARCHAR(8000))=BHE2.LMSBOOKINGID) AND PAE2.ACTIVITYEVENT=12003 
---AND PAE2.MX_CUSTOM_48 IS NULL
LEFT JOIN LSQ_PROSPECT_BASE LSQ_PBASE2 ON (LSQ_PBASE2.PROSPECTID=PAE2.RELATEDPROSPECTID)
LEFT JOIN LSQ_Prospect_ExtensionBase LSQ_PEXTBASE1 ON (LSQ_PBASE1.ProspectId = LSQ_PEXTBASE1.ProspectId) 
LEFT JOIN LSQ_Prospect_ExtensionBase LSQ_PEXTBASE2 ON (LSQ_PBASE2.ProspectId = LSQ_PEXTBASE2.ProspectId)


LEFT JOIN LSQ_Prospect_Extension2Base PE1 ON (LSQ_PBASE1.ProspectId=PE1.ProspectId)
LEFT JOIN LSQ_Prospect_Extension2Base PE2 ON (LSQ_PBASE2.ProspectId=PE2.ProspectId)

WHERE RH.DOCTYPE IN(141,1000079,1000317,1012739,441) 

UPDATE RF 
SET RF.LEADTYPE = LD.LEADTYPE, 
RF.Campaign_Code = LD.Campaign_Code,
RF.IS_SAMEDAYRETAIL= (CASE WHEN DATEDIFF(Day ,LD.ENQUIRY_DATE,LD.RETAIL_DATE) is not NULL THEN (CASE WHEN DATEDIFF(Day ,LD.ENQUIRY_DATE,LD.RETAIL_DATE)=0 THEN 'YES' ELSE 'NO' END ) END),
RF.Pincode=LD.Pincode,
RF.Area=LD.Area,
RF.First_Source_Lead_type=LD.First_Source_Lead_type,
RF.First_Mode_Source=LD.First_Mode_Source,
RF.First_Mode_SubSource=LD.First_Mode_SubSource
FROM ASM_CV_RETAIL_FACT RF INNER JOIN #CV_LEADTYPE_RETAIL LD ON RF.FK_RETAILDOCID=LD.PK_RETAILHEADERID


UPDATE RD 
SET RD.USAGEDETAILS=LD.USAGEDETAILS
FROM ASM_CV_RETAIL_DIM RD 
INNER JOIN #CV_LEADTYPE_RETAIL LD ON RD.PK_RETAILHEADERID=LD.PK_RETAILHEADERID
drop table #LSQTarget


END
GO