SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_ASM_CV_STOCK_REFRESH] AS
BEGIN

--Stock Fact:

--************** STOCK ***************************
--Truncate table  ASM_CV_STOCK_FACT
INSERT INTO ASM_CV_STOCK_FACT
SELECT DISTINCT
VS.COMPANYCODE As DEALERCODE,
VS.MODELCODE+LEFT(RIGHT(VS.COLOR,3),2) as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10004 As FK_TYPE_ID,
CAST(VS.EXECUTIONDATE as Date) AS DATE,
CM.COMPANYTYPE AS COMPANYTYPE,
Cast('' as varchar(255)) AS FK_STOCKSTATUS,
VS.VEHICLESTATUS as STOCKSTATUS,
COUNT(VS.CHASSISNO) AS [Stock Quantity],
COUNT(VS.CHASSISNO) as ACTUALQUANTITY, -- ACTUALQUANTITY & STOCKQUANTITY are same. 
getdate() as LASTUPDATEDDATETIME,
VS.IMPORTEDDATE,
VS.MODELCODE,
Cast(0 as int) As FK_MODEL,
CAST(VS.PURCHASEDATE as Date) AS STOCKDATE
--INTO ASM_CV_STOCK_FACT
FROM
   VEHICLE_STOCK_DATA VS INNER JOIN COMPANY_MASTER CM ON (VS.COMPANYCODE=CM.CODE AND CM.COMPANYTYPE = 7)
WHERE 
--CAST(VS.EXECUTIONDATE AS DATE) BETWEEN '2022-04-01'  AND Cast(Getdate()-1 as date)
--CAST(VS.EXECUTIONDATE AS DATE)>'2022-11-22'
Cast(VS.EXECUTIONDATE as date)>(SELECT CASE WHEN (SELECT COUNT(*) FROM ASM_CV_STOCK_FACT)=0 THEN 
'2022-04-01 00:00:00.0000' ELSE MAX(DATE) END FROM ASM_CV_STOCK_FACT)
  --(SELECT MAX(DATE) from ASM_CV_STOCK_FACT)
GROUP BY
  VS.COMPANYCODE,
  VS.MODELCODE+LEFT(RIGHT(VS.COLOR,3),2),
  CAST(VS.EXECUTIONDATE as Date),
  CM.COMPANYTYPE,
  VS.VEHICLESTATUS,
  VS.IMPORTEDDATE,
  VS.MODELCODE,
  VS.PURCHASEDATE


--Product Master and Dealer Master FK update: ASM_CV_STOCK_FACT
update B set B.FK_SKU=C.PK_SKU from ASM_CV_STOCK_FACT B INNER JOIN ASM_CV_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE)
update B set B.FK_MODEL=C.PK_Model_Code from ASM_CV_STOCK_FACT B INNER JOIN ASM_CV_PRODUCT_DIM C on (B.MODEL=C.MODELCODE)
update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].[ASM_CV_STOCK_FACT] B INNER JOIN ASM_CV_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE)



--*****************************************************************************


END
GO