SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[USP_ASM_UB_ALLOCATION_REFRESH] AS
BEGIN

--************************************START****************************************
--1.Allocation Dim
--TRUNCATE TABLE ASM_UB_ALLOCATION_DIM

INSERT INTO ASM_UB_ALLOCATION_DIM
SELECT DISTINCT 
ALLOCATION_HEADER.HEADERID AS PK_ALLOCATIONHEADERID,
CAST(ALLOCATION_HEADER.DOCDATE AS DATE) AS ALLOCATIONDATE,
GETDATE() AS CREATEDDATETIME,
ALLOCATION_HEADER.IMPORTEDDATE,
ALLOCATION_HEADER.CDMS_BATCHNO
--INTO ASM_UB_ALLOCATION_DIM
FROM ALLOCATION_HEADER INNER JOIN COMPANY_MASTER ON (ALLOCATION_HEADER.COMPANYID=COMPANY_MASTER.COMPANYID AND
COMPANY_MASTER.COMPANYTYPE = 10)
WHERE  
--CAST(ALLOCATION_HEADER.DOCDATE AS DATE) BETWEEN '2023-03-07' AND '2023-03-08' AND 
ALLOCATION_HEADER.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_UB_ALLOCATION_DIM)
--(SELECT CASE WHEN (SELECT COUNT(*) FROM ASM_UB_ALLOCATION_DIM)=0 THEN '1900-01-01 00:00:00.0000' ELSE MAX(IMPORTEDDATE) END FROM ASM_UB_ALLOCATION_DIM)

DELETE FROM ASM_UB_ALLOCATION_DIM WHERE ALLOCATIONDATE>Cast(Getdate()-1 as date)


--Dedup:
;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_ALLOCATIONHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_UB_ALLOCATION_DIM                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;
 
--***************************************************************************************
--2.Allocation Fact:

INSERT INTO ASM_UB_ALLOCATION_FACT
SELECT 
DISTINCT
CM.CODE AS DEALERCODE,
IM.CODE+IV.CODE As SKU,
Cast(0 as int) AS FK_DealerCode,
Cast(0 as int) AS FK_SKU,
10007 AS FK_TYPE_ID,
CAST(AH.DOCDATE AS DATE) AS DATE,
AL.LINEID AS AllocationLineID,
AL.DOCID AS FK_AllocationDocID,
CM.COMPANYTYPE AS COMPANYTYPE,
AH.BRANCHID,
COUNT(AH.HEADERID) AS ACTUALQUANTITY,
getdate() as LASTUPDATEDDATETIME,
AH.IMPORTEDDATE,
IM.CODE As MODEL,
Cast(0 as int) As FK_MODEL,
Cast(0 As decimal(19,0)) As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON
--INTO  ASM_UB_ALLOCATION_FACT
FROM 
ALLOCATION_HEADER AH INNER JOIN COMPANY_MASTER CM ON (AH.COMPANYID=CM.COMPANYID AND CM.COMPANYTYPE = 10)
INNER JOIN ALLOCATION_LINE AL ON (AH.HEADERID=AL.DOCID)
JOIN ITEM_MASTER IM ON (IM.ItemId=AL.ItemID)
LEFT JOIN ITEMVARMATRIX_MASTER IV ON (AL.VARMATRIXID=IV.ITEMVARMATRIXID)
WHERE 
--CAST(AH.DOCDATE AS DATE) BETWEEN '2023-03-07' AND '2023-03-08' AND 
AH.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_UB_ALLOCATION_FACT)
--(SELECT CASE WHEN (SELECT COUNT(*) FROM ASM_UB_ALLOCATION_FACT)=0 THEN '1900-01-01 00:00:00.0000' ELSE MAX(IMPORTEDDATE) END FROM ASM_UB_ALLOCATION_FACT)
GROUP BY
CM.CODE,
IM.CODE+IV.CODE,
CAST(AH.DOCDATE AS DATE),
AL.LINEID,
AL.DOCID,
CM.COMPANYTYPE,
AH.BRANCHID,
AH.IMPORTEDDATE,
IM.CODE 

DELETE FROM ASM_UB_ALLOCATION_FACT WHERE DATE>Cast(Getdate()-1 as date)

--Dedup Process:
;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY FK_AllocationDocID,AllocationLineID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_UB_ALLOCATION_FACT                
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 
 
--****************************************************************************************************
--Product Master and Dealer Master FK update: ASM_UB_ALLOCATION_FACT
update B set B.FK_SKU=C.PK_SKU from ASM_UB_ALLOCATION_FACT B INNER JOIN ASM_UB_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE)
update B set B.FK_MODEL=C.PK_Model_Code from ASM_UB_ALLOCATION_FACT B INNER JOIN ASM_UB_PRODUCT_DIM C on (B.MODEL=C.MODELCODE)
update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].ASM_UB_ALLOCATION_FACT B INNER JOIN ASM_UB_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE)

--**************************************************************************************************************

END
GO