SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[USP_ASM_UB_BILLING_REFRESH] AS
BEGIN

--***************************START***********************************
--1.Billing Stage


INSERT INTO ASM_UB_BILLING_STG
SELECT DISTINCT
CASE WHEN SAP_BILLING.DEALERCODE like '%C'  THEN SAP_BILLING.DEALERCODE ELSE '0000'+SAP_BILLING.DEALERCODE END AS DEALERCODE,
SAP_BILLING.MATERIAL as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10003 As FK_TYPE_ID,
SAP_BILLING.DOCDATE AS DATE,
Sum(SAP_BILLING.BILLQTY) as ACTUALQUANTITY,
0 As TARGETQUANTITY,
cast(0 as decimal(19,0)) As PENDING_ORDERS,
getdate() as LASTUPDATEDDATETIME,
SAP_BILLING.MATERIAL,
LEFT(SAP_BILLING.MATERIAL,6) As MODELCODE,
Cast(0 as int) as FK_MODEL,
100031 As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON
FROM
   SAP_BILLING 
WHERE 
SAP_BILLING.DOCDATE> (SELECT MAX(DATE) FROM ASM_UB_BILLING_STG)
AND [Distr.Chnl] IN ('65') AND DIVISION='B2' AND SAP_BILLING.CANCELLED<>'X'  
GROUP BY
    CASE WHEN SAP_BILLING.DEALERCODE like '%C'  THEN SAP_BILLING.DEALERCODE ELSE '0000'+SAP_BILLING.DEALERCODE END ,
    SAP_BILLING.MATERIAL,
    SAP_BILLING.DOCDATE,
    SAP_BILLING.MATERIAL,
	LEFT(SAP_BILLING.MATERIAL,6)

--**************************************************************************
--2.Billing Plan Stage
TRUNCATE TABLE ASM_UB_BILLING_PLAN_STG
INSERT INTO ASM_UB_BILLING_PLAN_STG
SELECT DISTINCT
ZO.DEALERCODE,
ZO.MATERIAL as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10003 As FK_TYPE_ID,
ZO.DOCDATE AS DATE,
Cast(0 as decimal(19,0)) as ACTUALQUANTITY,
Sum(ZO.MPSSQTY) As TARGETQUANTITY,
cast(0 as decimal(19,0)) As PENDING_ORDERS,
getdate() as LASTUPDATEDDATETIME,
ZO.MATERIAL,
LEFT(ZO.MATERIAL,6) As MODELCODE,
Cast(0 as int) as FK_MODEL,
100032 As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON
--INTO ASM_UB_BILLING_PLAN_STG
FROM 
SAP_ZMPSS_ORDERS ZO
WHERE 
ZO.DEALERCODE IN (SELECT DISTINCT KUNNR FROM SAP_ZSD_DEALER_REPOS WHERE KATR6='URB')
Group By
	ZO.DEALERCODE,
	ZO.MATERIAL,
	ZO.DOCDATE,
	LEFT(ZO.MATERIAL,6)
--********************************************************************************8
--3.Pending Orders Stage
TRUNCATE TABLE ASM_UB_PENDING_ORDER_STG
INSERT INTO ASM_UB_PENDING_ORDER_STG
SELECT DISTINCT
CASE WHEN PO.SOLDTOPARTY Like '%C' THEN PO.SOLDTOPARTY ELSE '00000'+PO.SOLDTOPARTY END As DEALERCODE,
PO.MATERIAL as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10003 As FK_TYPE_ID,
(CONVERT(date, ltrim(rtrim([DOCDATE])), 105)) AS DATE,
Cast(0 as decimal(19,0)) as ACTUALQUANTITY,
cast(0 as decimal(19,0)) As TARGETQUANTITY,
SUM(CAST((PO.ORDQTY) as DECIMAL(19,0))) As PENDING_ORDERS,
getdate() as LASTUPDATEDDATETIME,
PO.MATERIAL,
LEFT(PO.MATERIAL,6) As MODELCODE,
Cast(0 as int) as FK_MODEL,
100033 As FLAG,
NULL AS TEHSILID,
NULL AS SALESPERSON
--INTO ASM_UB_PENDING_ORDER_STG
FROM 
SAP_PENDING_ORDERS PO 
WHERE 
CASE WHEN PO.SOLDTOPARTY Like '%C' THEN PO.SOLDTOPARTY ELSE '00000'+PO.SOLDTOPARTY END IN (SELECT DISTINCT KUNNR from SAP_ZSD_DEALER_REPOS Where KATR6='URB') 
AND FUND='F' 
Group By
	CASE WHEN PO.SOLDTOPARTY Like '%C' THEN PO.SOLDTOPARTY ELSE '00000'+PO.SOLDTOPARTY END,
	PO.MATERIAL,
	(CONVERT(date, ltrim(rtrim([DOCDATE])), 105)),
	LEFT(PO.MATERIAL,6)

--**********************************************************************
--4.Billing Fact
TRUNCATE TABLE ASM_UB_BILLING_FACT

INSERT INTO ASM_UB_BILLING_FACT
SELECT * FROM ASM_UB_BILLING_STG
UNION
SELECT * FROM ASM_UB_BILLING_PLAN_STG
UNION 
SELECT * FROM ASM_UB_PENDING_ORDER_STG

--Product Master and Dealer Master FK update: ASM_UB_BILLING_FACT
update B set B.FK_SKU=C.PK_SKU from ASM_UB_BILLING_FACT B INNER JOIN ASM_UB_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE)
update B set B.FK_MODEL=C.PK_Model_Code from ASM_UB_BILLING_FACT B INNER JOIN ASM_UB_PRODUCT_DIM C on (B.MODELCODE=C.MODELCODE)
update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].ASM_UB_BILLING_FACT B INNER JOIN ASM_UB_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE)
--******************************************************************************
END
GO