SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_ASM_PB_SERVICE_RETAIL_INCLOAD] AS
/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|					CHANGE DESCRIPTION					*/
/*--------------------------------------------------------------------------------------------------*/
/*	2024-10-24 	|	Sarvesh Kulkarni		| Changes for Big Bikes Paid Screen  */
/*	2024-09-23 	|	Sarvesh Kulkarni		| added last servicde dealercode later used in paid due report  */
/*	2024-08-02 	|	Sarvesh Kulkarni		| Changes for Triumph FS and PS screen                  */
/*	2024-07-08 	|	Sarvesh Kulkarni		| FSR report duplicate row issue fixed.     */
/*	2024-06-17 	|	Sarvesh Kulkarni		| Added Last serviced brancid in ASM_PB_RETAIL_FLAGS_UNION  */
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*******************************************HISTORY**************************************************/

BEGIN

DECLARE @MAXDATESTG DATETIME2(7)= (SELECT MAX(IMPORTEDDATE) FROM ASM_PB_SERVICE_RETAIL_STG)

INSERT INTO [dbo].[ASM_PB_SERVICE_RETAIL_STG]
--Extracting raw data from source tables and adding Due Dates and Expiry Dates for FSR
SELECT DISTINCT
 RH.HEADERID AS [FK_Docid]
 ,RH.DOCNAME
 ,CAST(RH.DOCDATE AS DATE) as Docdate
 ,RH.COMPANYID AS [FK_Companyid]
 ,RL.LINEID AS Lineid
 ,RH.CONTACTID AS FK_Contactid
 ,RL.IBID AS [FK_Ibid]
 ,RH.BRANCHID AS [FK_Branchid]
 ,RL.ITEMID AS [FK_Modelid]
 ,RH.BU
 ,CM.COMPANYTYPE
 ,CM.CODE AS Dealercode
 ,(CASE WHEN ISNULL(RETAIL_HEADER_EXT.IsInstitutionalSale,0) = 1 AND RH.DocType NOT IN (441,1000088) THEN 'Institutional' 
       WHEN ISNULL(RETAIL_HEADER_EXT.IsInstitutionalSale,0) = 0 
            AND Len(BM.Code) = 10 
            AND SUBSTRING(BM.Code,0,6) = '00000' 
            AND ((SUBSTRING(BM.Code,6,6) BETWEEN '10000' AND '14000') 
            OR (SUBSTRING(BM.Code,6,6) = '25669'))  
            AND RH.DocType NOT IN (441,1000088) THEN 'Showroom'
      ELSE 'Command Area' 
    END) AS SALESCHANNEL
 ,DATEADD(DAY,45,cast(RH.Docdate as date)) AS [1stFS_EXPIRY1_Date]
 ,DATEADD(DAY,180,cast(RH.Docdate as date)) AS [2ndFS_EXPIRY1_Date]
 ,DATEADD(DAY,330,cast(RH.Docdate as date))AS [3rdFS_EXPIRY1_Date]
 ,DATEADD(DAY,90,cast(RH.Docdate as date)) AS [1stFS_EXPIRY2_Date]
 ,DATEADD(DAY,250,cast(RH.Docdate as date)) AS [2ndFS_EXPIRY2_Date]
 ,DATEADD(DAY,400,cast(RH.Docdate as date)) AS [3rdFS_EXPIRY2_Date]
 ,'NR' AS Return_Flag
 ,CAST(NULL AS DATE) AS FS_SERVICE_DATE
 ,CAST(NULL AS DATE) AS SS_SERVICE_DATE
 ,CAST(NULL AS DATE) AS TS_SERVICE_DATE
 ,NULL AS FS_COMPANYID
 ,NULL AS SS_COMPANYID
 ,NULL AS TS_COMPANYID
 ,RH.Importeddate       
 ,102 AS Service_Retail_TypeIdentifier
 ,GETDATE() AS Refresh_Date
  ,DATEADD(DAY,365,cast(RH.Docdate as date))AS [2ndFS_EXPIRY1_Date_TRM]
  ,DATEADD(DAY,400,cast(RH.Docdate as date)) AS [2ndFS_EXPIRY2_Date_TRM]
 ,DATEADD(DAY,45,cast(RH.Docdate as date)) AS [1stPS_EXPIRY1_Date_BB]--BB
 ,DATEADD(MONTH,11,cast(RH.Docdate as date))AS [2ndPS_EXPIRY1_Date_BB]
 ,DATEADD(DAY,60,cast(RH.Docdate as date)) AS [1stPS_EXPIRY2_Date_BB]
 ,DATEADD(MONTH,14,cast(RH.Docdate as date)) AS [2ndPS_EXPIRY2_Date_BB]
 ,CAST(NULL AS DATE) AS FPS_SERVICE_DATE_BB
 ,CAST(NULL AS DATE) AS SPS_SERVICE_DATE_BB
FROM RETAIL_HEADER RH
LEFT JOIN RETAIL_LINE RL ON RH.HEADERID=RL.DOCID
INNER JOIN COMPANY_MASTER CM ON (CM.COMPANYID=RH.COMPANYID AND CM.IMPORTEDDATE = (SELECT MAX(CM1.IMPORTEDDATE) FROM COMPANY_MASTER CM1 WHERE CM.COMPANYID = CM1.COMPANYID)
AND CM.COMPANYTYPE IN (2))
INNER JOIN BRANCH_MASTER BM ON RH.BRANCHID=BM.BRANCHID
LEFT OUTER JOIN RETAIL_HEADER_EXT ON RH.HEADERID=RETAIL_HEADER_EXT.HEADERID
WHERE RH.IMPORTEDDATE > @MAXDATESTG
AND RL.IBID IS NOT NULL
AND RH.DOCTYPE IN (141,441,1000079,1000317)

---------------------------------------
Delete from ASM_PB_SERVICE_RETAIL_STG Where DOCDATE>Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date);
---------------------------------------DEDUP

;WITH CTE AS                  
(                  
  SELECT *,                  
   DENSE_RANK()OVER(PARTITION BY FK_DOCID ORDER BY IMPORTEDDATE DESC)RNK                  
  FROM ASM_PB_SERVICE_RETAIL_STG              
)          
DELETE FROM CTE                  
WHERE RNK<>1;


------------------------------UPDATING RETURN FLAG

SELECT RL.SALEINVOICELINEID,RL.SERIALNO INTO #ReturnData_PB
FROM 
RETAIL_LINE_RETURN RL INNER JOIN ASM_PB_SERVICE_RETAIL_STG RD ON RD.LINEID=RL.SALEINVOICELINEID
 
--Return Data Flag Updation
UPDATE RD
SET RD.Return_Flag='R'
FROM ASM_PB_SERVICE_RETAIL_STG RD INNER JOIN #ReturnData_PB RL ON RL.SALEINVOICELINEID=RD.LINEID

------------------------------UPDATING FIRST FREE SERVICE DATE

SELECT SH.IBID
,CAST(SH.BILLEDDATETIME AS DATE) AS FS_SERVICE_DATE
,SH.COMPANYID AS FS_COMPANYID
INTO #FIRST_FS_DATA
FROM SERVICE_HEADER SH
JOIN COMPANY_MASTER CM ON (CM.COMPANYID = SH.COMPANYID AND CM.COMPANYTYPE = 2)
JOIN ASM_PB_SERVICE_RETAIL_STG RS ON RS.FK_IBID=SH.IBID
WHERE SH.CONTRACTTYPEID IN (38)
AND SH.CANCELLATIONDATE IS NULL
AND RS.RETURN_FLAG='NR'


UPDATE B
SET B.FS_SERVICE_DATE=A.FS_SERVICE_DATE
,B.FS_COMPANYID=A.FS_COMPANYID
FROM ASM_PB_SERVICE_RETAIL_STG B
JOIN #FIRST_FS_DATA A ON A.IBID=B.FK_IBID
WHERE B.FS_SERVICE_DATE IS NULL

------------------------------UPDATING SECOND FREE SERVICE DATE

SELECT SH.IBID
,CAST(SH.BILLEDDATETIME AS DATE) AS SS_SERVICE_DATE
,SH.COMPANYID AS SS_COMPANYID
INTO #SECOND_FS_DATA
FROM SERVICE_HEADER SH
JOIN COMPANY_MASTER CM ON (CM.COMPANYID = SH.COMPANYID AND CM.COMPANYTYPE = 2)
JOIN ASM_PB_SERVICE_RETAIL_STG RS ON RS.FK_IBID=SH.IBID
WHERE SH.CONTRACTTYPEID IN (39)
AND SH.CANCELLATIONDATE IS NULL
AND RS.RETURN_FLAG='NR'

UPDATE B
SET B.SS_SERVICE_DATE=A.SS_SERVICE_DATE
,B.SS_COMPANYID=A.SS_COMPANYID
FROM ASM_PB_SERVICE_RETAIL_STG B
JOIN #SECOND_FS_DATA A ON A.IBID=B.FK_IBID
WHERE B.SS_SERVICE_DATE IS NULL

------------------------------UPDATING THIRD FREE SERVICE DATE

SELECT SH.IBID
,CAST(SH.BILLEDDATETIME AS DATE) AS TS_SERVICE_DATE
,SH.COMPANYID AS TS_COMPANYID
INTO #THIRD_FS_DATA
FROM SERVICE_HEADER SH
JOIN COMPANY_MASTER CM ON (CM.COMPANYID = SH.COMPANYID AND CM.COMPANYTYPE = 2)
JOIN ASM_PB_SERVICE_RETAIL_STG RS ON RS.FK_IBID=SH.IBID
WHERE SH.CONTRACTTYPEID IN (40)
AND SH.CANCELLATIONDATE IS NULL
AND RS.RETURN_FLAG='NR'

UPDATE B
SET B.TS_SERVICE_DATE=A.TS_SERVICE_DATE
,B.TS_COMPANYID=A.TS_COMPANYID
FROM ASM_PB_SERVICE_RETAIL_STG B
JOIN #THIRD_FS_DATA A ON A.IBID=B.FK_IBID
WHERE B.TS_SERVICE_DATE IS NULL

------------------------------UPDATING FIRST PAID SERVICE DATE Big Bikes

SELECT
distinct SH.IBID
,CAST(SH.BILLEDDATETIME AS DATE) AS FPS_SERVICE_DATE_BB
--,SH.COMPANYID AS FS_COMPANYID
INTO #FIRST_FPS_DATA
FROM SERVICE_HEADER SH
JOIN COMPANY_MASTER CM ON (CM.COMPANYID = SH.COMPANYID AND CM.COMPANYTYPE = 2)
JOIN ASM_PB_SERVICE_RETAIL_STG RS ON RS.FK_IBID=SH.IBID
JOIN SERVICE_LINE SL ON (SL.DOCID = SH.HEADERID AND SL.IMPORTEDDATE = (SELECT MAX(SL1.IMPORTEDDATE) FROM SERVICE_LINE SL1 WHERE SL1.ITEMID = SL.ITEMID AND SL.DOCID = SL1.DOCID))
WHERE
cast(SH.Docdate as date)> '2022-01-01'
AND Sl.ITEMID = 1177061 -- TRXSL0001 "1st Service"
AND SH.CANCELLATIONDATE IS NULL
AND RS.RETURN_FLAG='NR'


UPDATE B
SET B.FPS_SERVICE_DATE_BB=A.FPS_SERVICE_DATE_BB
FROM ASM_PB_SERVICE_RETAIL_STG B
JOIN #FIRST_FPS_DATA A ON A.IBID=B.FK_IBID
where B.FPS_SERVICE_DATE_BB is NULL
------------------------------UPDATING SECOND PAID SERVICE DATE

SELECT
distinct SH.IBID
,CAST(SH.BILLEDDATETIME AS DATE) AS SPS_SERVICE_DATE_BB
--,SH.COMPANYID AS FS_COMPANYID
INTO #FIRST_SPS_DATA
FROM SERVICE_HEADER SH
JOIN COMPANY_MASTER CM ON (CM.COMPANYID = SH.COMPANYID AND CM.COMPANYTYPE = 2)
JOIN ASM_PB_SERVICE_RETAIL_STG RS ON RS.FK_IBID=SH.IBID
JOIN SERVICE_LINE SL ON (SL.DOCID = SH.HEADERID AND SL.IMPORTEDDATE = (SELECT MAX(SL1.IMPORTEDDATE) FROM SERVICE_LINE SL1 WHERE SL1.ITEMID = SL.ITEMID AND SL.DOCID = SL1.DOCID))
WHERE
cast(SH.Docdate as date)> '2022-01-01'
AND Sl.ITEMID = 1177062 -- TRXSL0002 "2nd Service"
AND SH.CANCELLATIONDATE IS NULL
AND RS.RETURN_FLAG='NR'


UPDATE B
SET B.SPS_SERVICE_DATE_BB=A.SPS_SERVICE_DATE_BB
FROM ASM_PB_SERVICE_RETAIL_STG B
JOIN #FIRST_SPS_DATA A ON A.IBID=B.FK_IBID
WHERE B.SPS_SERVICE_DATE_BB is NULL
------------------------------RETAIL FLAGS AND UPDATES

TRUNCATE TABLE ASM_PB_RETAIL_FLAGS


INSERT INTO ASM_PB_RETAIL_FLAGS

SELECT ARS.*
,CASE WHEN CAST(ARS.FS_SERVICE_DATE AS DATE)<=CAST([1stFS_EXPIRY1_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_1stFS_EXPIRY1
,CASE WHEN CAST(ARS.SS_SERVICE_DATE AS DATE)<=CAST([2ndFS_EXPIRY1_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_2ndFS_EXPIRY1
,CASE WHEN CAST(ARS.TS_SERVICE_DATE AS DATE)<=CAST([3rdFS_EXPIRY1_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_3rdFS_EXPIRY1
,CASE WHEN CAST(ARS.FS_SERVICE_DATE AS DATE)<=CAST([1stFS_EXPIRY2_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_1stFS_EXPIRY2
,CASE WHEN CAST(ARS.SS_SERVICE_DATE AS DATE)<=CAST([2ndFS_EXPIRY2_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_2ndFS_EXPIRY2
,CASE WHEN CAST(ARS.TS_SERVICE_DATE AS DATE)<=CAST([3rdFS_EXPIRY2_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_3rdFS_EXPIRY2
,CASE WHEN ARS.FS_SERVICE_DATE BETWEEN [1stFS_EXPIRY1_Date] AND [1stFS_EXPIRY2_Date]
 THEN 'Yes' ELSE 'No' END AS GRACE_PERIOD_1STFS
,CASE WHEN ARS.SS_SERVICE_DATE BETWEEN [2NDFS_EXPIRY1_Date] AND [2NDFS_EXPIRY2_Date]
 THEN 'Yes' ELSE 'No' END AS GRACE_PERIOD_2NDFS
,CASE WHEN ARS.TS_SERVICE_DATE BETWEEN [3RDFS_EXPIRY1_Date] AND [3RDFS_EXPIRY2_Date]
 THEN 'Yes' ELSE 'No' END AS GRACE_PERIOD_3RDFS

,CASE WHEN ARS.FS_COMPANYID IS NULL THEN NULL
   WHEN ARS.FS_COMPANYID=ARS.FK_COMPANYID THEN 'Self Done'
   WHEN ARS.FS_COMPANYID<>ARS.FK_COMPANYID THEN 'Not Done'
   END AS SELF_REDEEM_1STFS
,CASE WHEN ARS.SS_COMPANYID IS NULL THEN NULL
   WHEN ARS.SS_COMPANYID=ARS.FK_COMPANYID THEN 'Self Done'
   WHEN ARS.SS_COMPANYID<>ARS.FK_COMPANYID THEN 'Not Done'
   END AS SELF_REDEEM_2NDFS
,CASE WHEN ARS.TS_COMPANYID IS NULL THEN NULL
   WHEN ARS.TS_COMPANYID=ARS.FK_COMPANYID THEN 'Self Done'
   WHEN ARS.TS_COMPANYID<>ARS.FK_COMPANYID THEN 'Not Done'
   END AS SELF_REDEEM_3RDFS  

,DATEDIFF(M,DOCDATE,GETDATE()) AS VehicleAging

,DATEDIFF(D,GETDATE(),[1stFS_EXPIRY2_Date]) AS FFS_RemainingDaysForExpiry
,DATEDIFF(D,GETDATE(),[2NDFS_EXPIRY2_Date]) AS SFS_RemainingDaysForExpiry
,DATEDIFF(D,GETDATE(),[3RDFS_EXPIRY2_Date]) AS TFS_RemainingDaysForExpiry

,CASE --WHEN FS_SERVICE_DATE<=[1STFS_EXPIRY2_DATE] THEN 'Serviced'
      WHEN FS_SERVICE_DATE is not null THEN 'Serviced'
      WHEN FS_SERVICE_DATE IS NULL AND CAST(GETDATE() AS DATE)<[1STFS_EXPIRY2_DATE] THEN 'Unserviced'
      WHEN FS_SERVICE_DATE IS NULL OR FS_SERVICE_DATE>[1STFS_EXPIRY2_DATE] THEN 'Expired'
       END AS FSServicingStatus
,CASE --WHEN SS_SERVICE_DATE<=[2NDFS_EXPIRY2_DATE] THEN 'Serviced'
      WHEN SS_SERVICE_DATE is not null THEN 'Serviced'
      WHEN SS_SERVICE_DATE IS NULL AND CAST(GETDATE() AS DATE)<[2NDFS_EXPIRY2_DATE] THEN 'Unserviced'
      WHEN SS_SERVICE_DATE IS NULL OR SS_SERVICE_DATE>[2NDFS_EXPIRY2_DATE] THEN 'Expired'
       END AS SSServicingStatus
,CASE --WHEN TS_SERVICE_DATE<=[3RDFS_EXPIRY2_DATE] THEN 'Serviced'
      WHEN TS_SERVICE_DATE is not null THEN 'Serviced'
      WHEN TS_SERVICE_DATE IS NULL AND CAST(GETDATE() AS DATE)<[3RDFS_EXPIRY2_DATE] THEN 'Unserviced'
      WHEN TS_SERVICE_DATE IS NULL OR TS_SERVICE_DATE>[3RDFS_EXPIRY2_DATE] THEN 'Expired'
       END AS TSServicingStatus
,CASE WHEN FS_SERVICE_DATE<=[1STFS_EXPIRY1_DATE] THEN 0 ELSE 1 END AS FS_Grace_Flag
,CASE WHEN SS_SERVICE_DATE<=[2NDFS_EXPIRY1_DATE] THEN 0 ELSE 1 END AS SS_Grace_Flag
,CASE WHEN TS_SERVICE_DATE<=[3RDFS_EXPIRY1_DATE] THEN 0 ELSE 1 END AS TS_Grace_Flag

,CASE WHEN DATEDIFF(MM,LSD.LASTSERVICEDATE,GETDATE())>=12 THEN 'Lost 12 Months'
      WHEN DATEDIFF(MM,LSD.LASTSERVICEDATE,GETDATE())>=6 AND DATEDIFF(MM,LSD.LASTSERVICEDATE,GETDATE())<12  THEN 'Lost 6 Months'
	  ELSE NULL END AS Lost_Customer
,LSD.LastServiceDate
,LSD.LastServiceName
,LSD.LastKmReading
,LSD.LS_BRANCHID
,CASE WHEN ARS.SS_SERVICE_DATE BETWEEN [2NDFS_EXPIRY1_Date_TRM] AND [2NDFS_EXPIRY2_Date_TRM]
 THEN 'Yes' ELSE 'No' END AS GRACE_PERIOD_2NDFS_TRM
,DATEDIFF(D,GETDATE(),[2NDFS_EXPIRY2_Date_TRM]) AS SFS_RemainingDaysForExpiry_TRM
,CASE WHEN SS_SERVICE_DATE<=[2NDFS_EXPIRY2_DATE_TRM] THEN 'Serviced'
      WHEN SS_SERVICE_DATE IS NULL AND CAST(GETDATE() AS DATE)<[2NDFS_EXPIRY2_DATE_TRM] THEN 'Unserviced'
      WHEN SS_SERVICE_DATE IS NULL OR SS_SERVICE_DATE>[2NDFS_EXPIRY2_DATE_TRM] THEN 'Expired'
       END AS SSServicingStatus_TRM
,CASE WHEN SS_SERVICE_DATE<=[2NDFS_EXPIRY1_DATE_TRM] THEN 0 ELSE 1 END AS SS_Grace_Flag_TRM
,Ls_dealercode
,CASE WHEN FPS_SERVICE_DATE_BB<=[1stPS_EXPIRY2_Date_BB] THEN 'Serviced'
      WHEN FPS_SERVICE_DATE_BB IS NULL AND CAST(GETDATE() AS DATE)<[1stPS_EXPIRY2_Date_BB] THEN 'Unserviced'
      WHEN FPS_SERVICE_DATE_BB IS NULL OR FPS_SERVICE_DATE_BB>[1stPS_EXPIRY2_Date_BB] THEN 'Expired'
       END AS FPSServicingStatus_BB
,CASE WHEN SPS_SERVICE_DATE_BB<=[2ndPS_EXPIRY2_Date_BB] THEN 'Serviced'
      WHEN SPS_SERVICE_DATE_BB IS NULL AND CAST(GETDATE() AS DATE)<[2ndPS_EXPIRY2_Date_BB] THEN 'Unserviced'
      WHEN SPS_SERVICE_DATE_BB IS NULL OR FPS_SERVICE_DATE_BB>[2ndPS_EXPIRY2_Date_BB] THEN 'Expired'
       END AS SPSServicingStatus_BB

FROM ASM_PB_SERVICE_RETAIL_STG ARS
LEFT JOIN

(SELECT IBID
,LastServiceDate
,LastServiceName
,LastKmReading
,LS_BRANCHID
,Ls_dealercode
FROM
(SELECT DISTINCT IBID
,CAST(BILLEDDATETIME AS DATE) AS LastServiceDate
,SCM.NAME AS LastServiceName
,SH.UsageReading as LastKmReading
,SH.BRANCHID AS LS_BRANCHID
,CM.CODE as Ls_dealercode
,ROW_NUMBER() OVER(PARTITION BY IBID ORDER BY BILLEDDATETIME DESC) RNO
FROM SERVICE_HEADER SH
JOIN COMPANY_MASTER CM ON (CM.COMPANYID = SH.COMPANYID AND CM.COMPANYTYPE = 2)
JOIN SERVICE_CONTRACT_MASTER SCM ON SCM.SERVICECONTRACTID=SH.CONTRACTTYPEID
) LATEST_DATE
WHERE RNO=1) LSD on LSD.IBID=ARS.FK_Ibid

WHERE ARS.Return_Flag='NR' 

----------------------------FSR Report TABLE
TRUNCATE table ASM_PB_RETAIL_FLAGS_UNION;

INSERT INTO ASM_PB_RETAIL_FLAGS_UNION
SELECT * FROM
(SELECT 
    [FK_Docid],
    [DOCNAME],
    [Docdate],
    [FK_Companyid],
    [Lineid],
    [FK_Contactid],
    [FK_Ibid],
    [FK_Branchid],
    [FK_Modelid],
    [BU],
    PB.[Companytype],
    [Dealercode],
    [1stFS_EXPIRY1_Date] as Due_date,
    [1stFS_EXPIRY2_Date] as Expiry_date,
    'First' as Service_type,
    [FSServicingStatus] as Service_Status,
    [VehicleAging],
    [FFS_RemainingDaysForExpiry] AS [RemainingDaysForExpiry], 
    [LastServiceDate], 
    [LastServiceName],
    [LastKmReading],
	BD.BranchName as Last_Service_Branch,
    'PB_TRM' as Brand
    from ASM_PB_RETAIL_FLAGS PB
	LEFT JOIN ASM_SERVICE_BRANCH_MASTER_DIM BD ON PB.LS_BRANCHID = BD.BRANCHID

    UNION ALL
    SELECT 
    [FK_Docid],
    [DOCNAME],
    [Docdate],
    [FK_Companyid],
    [Lineid],
    [FK_Contactid],
    [FK_Ibid],
    [FK_Branchid],
    [FK_Modelid],
    [BU],
    PB.[Companytype],
    [Dealercode],
    [2ndFS_EXPIRY1_Date] as Due_date,
    [2ndFS_EXPIRY2_Date] as Expiry_date,
    'Second' as Service_type,
    SSServicingStatus as Service_Status,
    [VehicleAging],
    [SFS_RemainingDaysForExpiry] AS [RemainingDaysForExpiry], 
    [LastServiceDate], 
    [LastServiceName],
    [LastKmReading],
    BD.BranchName as Last_Service_Branch,
    'PB' as Brand
    from ASM_PB_RETAIL_FLAGS PB
	LEFT JOIN ASM_SERVICE_BRANCH_MASTER_DIM BD ON PB.LS_BRANCHID = BD.BRANCHID
-- Changes for TRM
    UNION ALL
    SELECT 
    [FK_Docid],
    [DOCNAME],
    [Docdate],
    [FK_Companyid],
    [Lineid],
    [FK_Contactid],
    [FK_Ibid],
    [FK_Branchid],
    [FK_Modelid],
    [BU],
    PB.[Companytype],
    [Dealercode],
    [2ndFS_EXPIRY1_Date_TRM] as Due_date,
    [2ndFS_EXPIRY2_Date_TRM] as Expiry_date,
    'Second' as Service_type,
    SSServicingStatus_TRM as Service_Status,
    [VehicleAging],
    [SFS_RemainingDaysForExpiry_TRM] AS [RemainingDaysForExpiry], 
    [LastServiceDate], 
    [LastServiceName],
    [LastKmReading],
    BD.BranchName as Last_Service_Branch,
    'TRM' as Brand
    from ASM_PB_RETAIL_FLAGS PB
	LEFT JOIN ASM_SERVICE_BRANCH_MASTER_DIM BD ON PB.LS_BRANCHID = BD.BRANCHID

    UNION ALL
    SELECT 
    [FK_Docid],
    [DOCNAME],
    [Docdate],
    [FK_Companyid],
    [Lineid],
    [FK_Contactid],
    [FK_Ibid],
    [FK_Branchid],
    [FK_Modelid],
    [BU],
    PB.[Companytype],
    [Dealercode],
    [3rdFS_EXPIRY1_Date] as Due_date,
    [3rdFS_EXPIRY2_Date] as Expiry_date,
    'Third' as Service_type,
    TSServicingStatus as Service_Status,
    [VehicleAging],
    [TFS_RemainingDaysForExpiry] AS [RemainingDaysForExpiry], 
    [LastServiceDate], 
    [LastServiceName],
    [LastKmReading],
    BD.BranchName as Last_Service_Branch,
    'PB' as Brand
    from ASM_PB_RETAIL_FLAGS PB
	LEFT JOIN ASM_SERVICE_BRANCH_MASTER_DIM BD ON PB.LS_BRANCHID = BD.BRANCHID) B
	
	
---------------------------------OVERALL FS Redemption

TRUNCATE Table ASM_PB_FREE_SERVICE;

INSERT INTO ASM_PB_FREE_SERVICE

SELECT A.*, 
CASE WHEN SERVICE_DATE <= DUE_DATE THEN 1 ELSE 0 END AS DUE_STATUS,
CASE WHEN SERVICE_DATE <= DUE_DATE_TRM THEN 1 ELSE 0 END AS DUE_STATUS_TRM
FROM 
(SELECT B.*,
CASE WHEN FS_IDENTIFIER IN (38) THEN DATEADD(DAY,90,cast(RETAIL_DATE as date))
WHEN FS_IDENTIFIER IN (39) THEN DATEADD(DAY,250,cast(RETAIL_DATE as date))
WHEN FS_IDENTIFIER IN (40) THEN DATEADD(DAY,400,cast(RETAIL_DATE as date))
ELSE NULL END AS EXPIRY_DATE,
CASE WHEN FS_IDENTIFIER IN (38) THEN DATEADD(DAY,45,cast(RETAIL_DATE as date))
WHEN FS_IDENTIFIER IN (39) THEN DATEADD(DAY,180,cast(RETAIL_DATE as date))
WHEN FS_IDENTIFIER IN (40) THEN DATEADD(DAY,330,cast(RETAIL_DATE as date))
ELSE NULL END AS DUE_DATE,
CASE WHEN FS_IDENTIFIER IN (38) THEN DATEADD(DAY,90,cast(RETAIL_DATE as date))
WHEN FS_IDENTIFIER IN (39) THEN DATEADD(DAY,400,cast(RETAIL_DATE as date))
ELSE NULL END AS EXPIRY_DATE_TRM,
CASE WHEN FS_IDENTIFIER IN (38) THEN DATEADD(DAY,45,cast(RETAIL_DATE as date))
WHEN FS_IDENTIFIER IN (39) THEN DATEADD(DAY,365,cast(RETAIL_DATE as date))
ELSE NULL END AS DUE_DATE_TRM
FROM 
(SELECT DISTINCT CM.CODE AS DEALERCODE,APB.DOCDATE AS RETAIL_DATE,CAST(SH.BILLEDDATETIME AS DATE) AS SERVICE_DATE,SH.HEADERID AS FK_DOCID,SH.IBID AS FK_IBID,SH.MODELId AS FK_MODELID,SH.CONTRACTTYPEID FS_IDENTIFIER,SH.BRANCHID AS FK_BRANCHID
FROM SERVICE_HEADER SH
JOIN COMPANY_MASTER CM ON (CM.COMPANYID = SH.COMPANYID AND CM.COMPANYTYPE IN (2) )
LEFT JOIN ASM_PB_RETAIL_FLAGS APB ON APB.FK_IBID = SH.IBID
WHERE SH.CONTRACTTYPEID IN (38,39,40) AND SH.CANCELLATIONDATE IS NULL
AND CAST(SH.DOCDATE AS DATE) >= '2020-04-01')B)A

-- Insert statement for Bigbikes paid service
INSERT INTO ASM_PB_FREE_SERVICE
 
SELECT A.*, 
CASE WHEN SERVICE_DATE <= DUE_DATE THEN 1 ELSE 0 END AS DUE_STATUS,
CASE WHEN SERVICE_DATE <= DUE_DATE_TRM THEN 1 ELSE 0 END AS DUE_STATUS_TRM
FROM 
(SELECT B.*,
CASE WHEN FS_IDENTIFIER IN (1177061) THEN DATEADD(DAY,60,cast(RETAIL_DATE as date))
WHEN FS_IDENTIFIER IN (1177062) THEN DATEADD(MONTH,14,cast(RETAIL_DATE as date))
ELSE NULL END AS EXPIRY_DATE,
CASE WHEN FS_IDENTIFIER IN (1177061) THEN DATEADD(DAY,45,cast(RETAIL_DATE as date))
WHEN FS_IDENTIFIER IN (1177062) THEN DATEADD(MONTH,11,cast(RETAIL_DATE as date))
ELSE NULL END AS DUE_DATE,
NULL AS EXPIRY_DATE_TRM,
NULL AS DUE_DATE_TRM
FROM 
(SELECT DISTINCT CM.CODE AS DEALERCODE,APB.DOCDATE AS RETAIL_DATE,CAST(SH.BILLEDDATETIME AS DATE) AS SERVICE_DATE,SH.HEADERID AS FK_DOCID,SH.IBID AS FK_IBID,SH.MODELId AS FK_MODELID,SL.ITEMID FS_IDENTIFIER,SH.BRANCHID AS FK_BRANCHID
FROM SERVICE_HEADER SH
JOIN COMPANY_MASTER CM ON (CM.COMPANYID = SH.COMPANYID AND CM.COMPANYTYPE = 2)
LEFT JOIN ASM_PB_RETAIL_FLAGS APB ON APB.FK_IBID = SH.IBID
JOIN SERVICE_LINE SL ON (SL.DOCID = SH.HEADERID AND SL.IMPORTEDDATE = (SELECT MAX(SL1.IMPORTEDDATE) FROM SERVICE_LINE SL1 WHERE SL1.ITEMID = SL.ITEMID AND SL.DOCID = SL1.DOCID))
WHERE Sl.ITEMID in (1177062,1177061) AND SH.CANCELLATIONDATE IS NULL
AND CAST(SH.DOCDATE AS DATE) >= '2022-04-01')B)A

-----------------------------------INSERT INTO FACT TABLE

DELETE FROM ASM_PB_SERVICE_FACT WHERE SERVICE_RETAIL_TYPEIDENTIFIER=102

INSERT INTO ASM_PB_SERVICE_FACT(FK_Docid,
DOCNAME,
Docdate,
FK_Companyid,
Lineid,
FK_Contactid,
FK_Ibid,
FK_Branchid,
FK_Modelid,
BU,
COMPANYTYPE,
Dealercode,
SALESCHANNEL,
[1stFS_EXPIRY1_Date],
[2ndFS_EXPIRY1_Date],
[3rdFS_EXPIRY1_Date],
[1stFS_EXPIRY2_Date],
[2ndFS_EXPIRY2_Date],
[3rdFS_EXPIRY2_Date],
Return_Flag,
FS_SERVICE_DATE,
SS_SERVICE_DATE,
TS_SERVICE_DATE,
Importeddate,
Service_Retail_TypeIdentifier,
STATUS_1stFS_EXPIRY1,
STATUS_2ndFS_EXPIRY1,
STATUS_3rdFS_EXPIRY1,
STATUS_1stFS_EXPIRY2,
STATUS_2ndFS_EXPIRY2,
STATUS_3rdFS_EXPIRY2,
GRACE_PERIOD_1STFS,
GRACE_PERIOD_2NDFS,
GRACE_PERIOD_3RDFS,
SELF_REDEEM_1STFS,
SELF_REDEEM_2NDFS,
SELF_REDEEM_3RDFS,
VehicleAging,
FFS_RemainingDaysForExpiry,
SFS_RemainingDaysForExpiry,
TFS_RemainingDaysForExpiry,
FSServicingStatus,
SSServicingStatus,
TSServicingStatus,
FS_Grace_Flag,
SS_Grace_Flag,
TS_Grace_Flag,
Lost_Customer,
LastServiceDate,
LastServiceName,
LastKmReading,
Refresh_Date,
GRACE_PERIOD_2NDFS_TRM,
SFS_RemainingDaysForExpiry_TRM,
SSServicingStatus_TRM,
SS_Grace_Flag_TRM,
[2ndFS_EXPIRY1_Date_TRM],
[2ndFS_EXPIRY2_Date_TRM],
[retail_fiscal_year],
[1stPS_EXPIRY1_Date_BB],
[2ndPS_EXPIRY1_Date_BB],
[1stPS_EXPIRY2_Date_BB],
[2ndPS_EXPIRY2_Date_BB],
[FPS_SERVICE_DATE_BB],
[SPS_SERVICE_DATE_BB],
[FPSServicingStatus_BB],
[SPSServicingStatus_BB])

SELECT 
FK_Docid,
DOCNAME,
Docdate,
FK_Companyid,
Lineid,
FK_Contactid,
FK_Ibid,
FK_Branchid,
FK_Modelid,
BU,
COMPANYTYPE,
Dealercode,
SALESCHANNEL,
[1stFS_EXPIRY1_Date],
[2ndFS_EXPIRY1_Date],
[3rdFS_EXPIRY1_Date],
[1stFS_EXPIRY2_Date],
[2ndFS_EXPIRY2_Date],
[3rdFS_EXPIRY2_Date],
Return_Flag,
FS_SERVICE_DATE,
SS_SERVICE_DATE,
TS_SERVICE_DATE,
Importeddate,
Service_Retail_TypeIdentifier,
STATUS_1stFS_EXPIRY1,
STATUS_2ndFS_EXPIRY1,
STATUS_3rdFS_EXPIRY1,
STATUS_1stFS_EXPIRY2,
STATUS_2ndFS_EXPIRY2,
STATUS_3rdFS_EXPIRY2,
GRACE_PERIOD_1STFS,
GRACE_PERIOD_2NDFS,
GRACE_PERIOD_3RDFS,
SELF_REDEEM_1STFS,
SELF_REDEEM_2NDFS,
SELF_REDEEM_3RDFS,
VehicleAging,
FFS_RemainingDaysForExpiry,
SFS_RemainingDaysForExpiry,
TFS_RemainingDaysForExpiry,
FSServicingStatus,
SSServicingStatus,
TSServicingStatus,
FS_Grace_Flag,
SS_Grace_Flag,
TS_Grace_Flag,
Lost_Customer,
LastServiceDate,
LastServiceName,
LastKmReading,
GETDATE() AS Refresh_Date,
GRACE_PERIOD_2NDFS_TRM,
SFS_RemainingDaysForExpiry_TRM,
SSServicingStatus_TRM,
SS_Grace_Flag_TRM,
[2ndFS_EXPIRY1_Date_TRM],
[2ndFS_EXPIRY2_Date_TRM],
CASE    WHEN ISNULL(CAST(DOCDATE AS DATE), '') = '' THEN NULL
        WHEN MONTH(CAST(DOCDATE AS DATE)) >= 4 THEN Concat('FY ',Cast(YEAR(CAST(DOCDATE AS DATE))+1 as varchar))
        ELSE Concat('FY ',Cast(YEAR(CAST(DOCDATE AS DATE)) as varchar))
END retail_fiscal_year,
[1stPS_EXPIRY1_Date_BB],
[2ndPS_EXPIRY1_Date_BB],
[1stPS_EXPIRY2_Date_BB],
[2ndPS_EXPIRY2_Date_BB],
[FPS_SERVICE_DATE_BB],
[SPS_SERVICE_DATE_BB],
[FPSServicingStatus_BB],
[SPSServicingStatus_BB]
FROM ASM_PB_RETAIL_FLAGS

drop table #THIRD_FS_DATA
drop table #SECOND_FS_DATA
drop table #FIRST_FS_DATA
drop table #ReturnData_PB
drop table #FIRST_FPS_DATA

end

GO