SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|					CHANGE DESCRIPTION					*/
/*--------------------------------------------------------------------------------------------------*/
/*	2024-05-06 	|	Aakash Kundu		| MBO/RSO BRANCHID logic update to club their due count under their resp. dealers*/
/*	2025-02-17 	|	Sarvesh Kulkarni		| Added logic to populate Aggregare_fact table   */
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*******************************************HISTORY**************************************************/


CREATE PROC [dbo].[USP_ASM_MC_SERVICE_RETAIL_INCLOAD] AS
BEGIN

DECLARE @MAXDATESTG DATETIME2(7)= (SELECT MAX(IMPORTEDDATE) FROM ASM_MC_SERVICE_RETAIL_STG)

INSERT INTO [dbo].[ASM_MC_SERVICE_RETAIL_STG]

SELECT BASE.*
,'NR' AS Return_Flag
,CAST(NULL AS DATE) AS FS_SERVICE_DATE
,CAST(NULL AS DATE) AS SS_SERVICE_DATE
,CAST(NULL AS DATE) AS TS_SERVICE_DATE
,NULL AS FS_COMPANYID
,NULL AS SS_COMPANYID
,NULL AS TS_COMPANYID
,GETDATE() AS Refresh_Date
,CAST(NULL AS decimal(19,0)) AS MD_BRANCHID
FROM
--Extracting raw data from source tables
(SELECT DISTINCT
 RH.HEADERID AS [FK_Docid]
 ,RH.DOCNAME
 ,RH.DOCTYPE
 ,CAST(RH.DOCDATE AS DATE) as Docdate
 ,RH.COMPANYID AS [FK_Companyid]
 ,RL.LINEID AS Lineid
 ,RH.CONTACTID AS FK_Contactid
 ,RL.IBID AS [FK_Ibid]
 ,RH.BRANCHID AS [FK_Branchid]
 ,RL.ITEMID AS [FK_Modelid]
 ,RH.BU
 ,CM.COMPANYTYPE
 ,CM.CODE AS Dealercode
 ,CM.CODE AS ASD_DealerCode
 ,(CASE WHEN ISNULL(RETAIL_HEADER_EXT.IsInstitutionalSale,0) = 1 AND RH.DocType NOT IN (441,1000088) THEN 'Institutional' 
       WHEN ISNULL(RETAIL_HEADER_EXT.IsInstitutionalSale,0) = 0 
            AND Len(BM.Code) = 10 
            AND SUBSTRING(BM.Code,0,6) = '00000' 
            AND ((SUBSTRING(BM.Code,6,6) BETWEEN '10000' AND '14000') 
            OR (SUBSTRING(BM.Code,6,6) = '25669'))  
            AND RH.DocType NOT IN (441,1000088) THEN 'Showroom'
      ELSE 'Command Area' 
    END) AS SALESCHANNEL
 ,RH.Importeddate       
 ,102 AS Service_Retail_TypeIdentifier
FROM RETAIL_HEADER RH
LEFT JOIN RETAIL_LINE RL ON RH.HEADERID=RL.DOCID
INNER JOIN COMPANY_MASTER CM ON (CM.COMPANYID=RH.COMPANYID AND CM.IMPORTEDDATE = (SELECT MAX(CM1.IMPORTEDDATE) FROM COMPANY_MASTER CM1 WHERE CM.COMPANYID = CM1.COMPANYID)
AND CM.COMPANYTYPE IN (1,8))
INNER JOIN BRANCH_MASTER BM ON RH.BRANCHID=BM.BRANCHID
LEFT OUTER JOIN RETAIL_HEADER_EXT ON RH.HEADERID=RETAIL_HEADER_EXT.HEADERID
WHERE RH.IMPORTEDDATE > @MAXDATESTG
AND RL.IBID IS NOT NULL
AND RH.DOCTYPE IN (141,441,1000079,1000317))BASE

------------------------------------------

Delete from ASM_MC_SERVICE_RETAIL_STG Where DOCDATE>Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) - 1 as date);
---------------------------------------DEDUP

;WITH CTE AS                  
(                  
  SELECT *,                  
   DENSE_RANK()OVER(PARTITION BY FK_DOCID ORDER BY IMPORTEDDATE DESC)RNK                  
  FROM ASM_MC_SERVICE_RETAIL_STG              
)          
DELETE FROM CTE                  
WHERE RNK<>1;


------------------------------UPDATE SALE RETURN FLAG

SELECT RL.SALEINVOICELINEID,RL.SERIALNO INTO #ReturnData_MC 
FROM 
RETAIL_LINE_RETURN RL INNER JOIN ASM_MC_SERVICE_RETAIL_STG RD ON RD.LINEID=RL.SALEINVOICELINEID
 
--Return Data Flag Updation
UPDATE RD
SET RD.Return_Flag='R'
FROM ASM_MC_SERVICE_RETAIL_STG RD INNER JOIN #ReturnData_MC RL ON RL.SALEINVOICELINEID=RD.LINEID

-------------------------------Update branchid for MBO/RSO,other branches

SELECT B.BRANCHID O_BRANCHID,BM1.BRANCHID MD_BRANCHID
INTO #OTHER_BRANCH1
FROM
(SELECT DISTINCT BD.BRANCHID,CM.CODE
FROM BRANCH_MASTER BM 
JOIN ASM_SERVICE_BRANCH_MASTER_DIM BD ON BD.BRANCHID = BM.BRANCHID
JOIN COMPANY_MASTER CM ON CM.COMPANYID = BM.COMPANYID AND CM.COMPANYTYPE IN (1,8)
WHERE BD.TYPEOFCHANNEL = 'OTHERS')B
JOIN BRANCH_MASTER BM1 ON BM1.CODE = B.CODE

UPDATE AR1
SET AR1.MD_BRANCHID = OB1.MD_BRANCHID
FROM ASM_MC_SERVICE_RETAIL_STG AR1 INNER JOIN #OTHER_BRANCH1 OB1 ON OB1.O_BRANCHID = AR1.FK_Branchid


SELECT DISTINCT B1.BRANCHID O_BRANCHID,BM1.BRANCHID MD_BRANCHID
INTO #OTHER_BRANCH2
FROM
(SELECT DISTINCT BD.BRANCHID,CM.CODE Company_code,BD.BRANCHCODE branch_code,LEN(BRANCHCODE) [LEN]
FROM BRANCH_MASTER BM 
JOIN ASM_SERVICE_BRANCH_MASTER_DIM BD ON BD.BRANCHID = BM.BRANCHID
JOIN COMPANY_MASTER CM ON CM.COMPANYID = BM.COMPANYID AND CM.COMPANYTYPE IN (1,8)
WHERE BD.TYPEOFCHANNEL = 'ASD')B1
JOIN BRANCH_MASTER BM1 ON BM1.CODE = B1.Company_code
WHERE [LEN]!=5


UPDATE AR2
SET AR2.MD_BRANCHID = OB2.MD_BRANCHID
FROM ASM_MC_SERVICE_RETAIL_STG AR2 INNER JOIN #OTHER_BRANCH2 OB2 ON OB2.O_BRANCHID = AR2.FK_Branchid


------------------------------UPDATE FIRST FREE SERVICE DATE

SELECT SH.IBID
,CAST(SH.DOCDATE AS DATE) AS FS_SERVICE_DATE
,SH.COMPANYID AS FS_COMPANYID
INTO #FIRST_FS_DATA
FROM SERVICE_HEADER SH
JOIN ASM_MC_SERVICE_RETAIL_STG RS ON RS.FK_IBID=SH.IBID
WHERE SH.CONTRACTTYPEID IN (38)
AND SH.CANCELLATIONDATE IS NULL
AND RS.RETURN_FLAG='NR'

UPDATE B
SET B.FS_SERVICE_DATE=A.FS_SERVICE_DATE
,B.FS_COMPANYID=A.FS_COMPANYID
FROM ASM_MC_SERVICE_RETAIL_STG B
JOIN #FIRST_FS_DATA A ON A.IBID=B.FK_IBID
WHERE B.FS_SERVICE_DATE IS NULL


------------------------------UPDATE SECOND FREE SERVICE DATE

SELECT SH.IBID
,CAST(SH.DOCDATE AS DATE) AS SS_SERVICE_DATE
,SH.COMPANYID AS SS_COMPANYID
INTO #SECOND_FS_DATA
FROM SERVICE_HEADER SH
JOIN ASM_MC_SERVICE_RETAIL_STG RS ON RS.FK_IBID=SH.IBID
WHERE SH.CONTRACTTYPEID IN (39)
AND SH.CANCELLATIONDATE IS NULL
AND RS.RETURN_FLAG='NR'

UPDATE B
SET B.SS_SERVICE_DATE=A.SS_SERVICE_DATE
,B.SS_COMPANYID=A.SS_COMPANYID
FROM ASM_MC_SERVICE_RETAIL_STG B
JOIN #SECOND_FS_DATA A ON A.IBID=B.FK_IBID
WHERE B.SS_SERVICE_DATE IS NULL

------------------------------UPDATE THIRD FREE SERVICE DATE

SELECT SH.IBID
,CAST(SH.DOCDATE AS DATE) AS TS_SERVICE_DATE
,SH.COMPANYID AS TS_COMPANYID
INTO #THIRD_FS_DATA
FROM SERVICE_HEADER SH
JOIN ASM_MC_SERVICE_RETAIL_STG RS ON RS.FK_IBID=SH.IBID
WHERE SH.CONTRACTTYPEID IN (40)
AND SH.CANCELLATIONDATE IS NULL
AND RS.RETURN_FLAG='NR'

UPDATE B
SET B.TS_SERVICE_DATE=A.TS_SERVICE_DATE
,B.TS_COMPANYID=A.TS_COMPANYID
FROM ASM_MC_SERVICE_RETAIL_STG B
JOIN #THIRD_FS_DATA A ON A.IBID=B.FK_IBID
WHERE B.TS_SERVICE_DATE IS NULL


------------------------------Retail Stg Final
--Calculating Due and Expiry Dates for free service
TRUNCATE TABLE ASM_MC_SERVICE_RETAIL_STG_FINAL
INSERT INTO ASM_MC_SERVICE_RETAIL_STG_FINAL

SELECT B.*
,DATEADD(DAY,45,cast(PaidDueDate as date)) AS '1stFS_EXPIRY1_Date'
,DATEADD(DAY,240,cast(PaidDueDate as date)) AS '2ndFS_EXPIRY1_Date'
,DATEADD(DAY,365,cast(PaidDueDate as date)) AS '3rdFS_EXPIRY1_Date'
,DATEADD(DAY,90,cast(PaidDueDate as date)) AS '1stFS_EXPIRY2_Date'
,DATEADD(DAY,300,cast(PaidDueDate as date)) AS '2ndFS_EXPIRY2_Date'
,DATEADD(DAY,425,cast(PaidDueDate as date)) AS '3rdFS_EXPIRY2_Date'
FROM
(SELECT DISTINCT RS.FK_Docid,
RS.DOCNAME,
RS.DOCTYPE,
RS.Docdate,
RS.FK_Companyid,
RS.Lineid,
RS.FK_Contactid,
RS.FK_Ibid,
ISNULL(RS.MD_Branchid,RS.FK_BRANCHID) FK_BRANCHID,
RS.FK_Modelid,
RS.BU,
RS.COMPANYTYPE,
RS.Dealercode,
RS.ASD_DealerCode,
RS.SALESCHANNEL,
RS.Importeddate,
RS.Service_Retail_TypeIdentifier,
RS.Return_Flag,
RS.FS_SERVICE_DATE,
RS.SS_SERVICE_DATE,
RS.TS_SERVICE_DATE,
RS.FS_COMPANYID,
RS.SS_COMPANYID,
RS.TS_COMPANYID,
RS.Refresh_Date,
CASE WHEN RS.DOCTYPE=441 THEN CAST(IBM.INVOICEDATE AS DATE)
     WHEN RS.DOCTYPE IN (141,1000079,1000317) THEN CAST(RS.DOCDATE AS DATE) END AS PaidDueDate
,ASD.BRANCHID AS ASDA_BRANCHID
,ASD.CONTACTID AS ASDA_CONTACT
FROM ASM_MC_SERVICE_RETAIL_STG RS
LEFT JOIN INSTALL_BASE_MASTER IBM ON IBM.IBID=RS.FK_IBID
LEFT JOIN
(SELECT DISTINCT RL.IBID,RH.BRANCHID,RH.CONTACTID
FROM RETAIL_HEADER RH
JOIN RETAIL_LINE RL ON RL.DOCID = RH.HEADERID
WHERE CAST(RH.DOCDATE AS DATE) >= '2016-04-01' AND RH.DOCTYPE = 1012462 AND 
RL.LINEID NOT IN (SELECT RRL.SALEINVOICELINEID FROM RETAIL_LINE_RETURN RRL JOIN RETAIL_LINE RL1 ON  RRL.SALEINVOICELINEID = RL1.LINEID)
)ASD ON ASD.IBID = RS.FK_IBID
WHERE RS.Return_Flag='NR')B

------------------------------RETAIL FLAGS AND UPDATES

TRUNCATE TABLE ASM_MC_RETAIL_FLAGS

INSERT INTO ASM_MC_RETAIL_FLAGS

SELECT ARS.*
,CASE WHEN CAST(ARS.FS_SERVICE_DATE AS DATE)<=CAST([1stFS_EXPIRY1_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_1stFS_EXPIRY1
,CASE WHEN CAST(ARS.SS_SERVICE_DATE AS DATE)<=CAST([2ndFS_EXPIRY1_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_2ndFS_EXPIRY1
,CASE WHEN CAST(ARS.TS_SERVICE_DATE AS DATE)<=CAST([3rdFS_EXPIRY1_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_3rdFS_EXPIRY1
,CASE WHEN CAST(ARS.FS_SERVICE_DATE AS DATE)<=CAST([1stFS_EXPIRY2_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_1stFS_EXPIRY2
,CASE WHEN CAST(ARS.SS_SERVICE_DATE AS DATE)<=CAST([2ndFS_EXPIRY2_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_2ndFS_EXPIRY2
,CASE WHEN CAST(ARS.TS_SERVICE_DATE AS DATE)<=CAST([3rdFS_EXPIRY2_Date] AS DATE)
THEN 'Done' ELSE NULL END AS STATUS_3rdFS_EXPIRY2
,CASE WHEN ARS.FS_SERVICE_DATE BETWEEN DATEADD(D,1,[1stFS_EXPIRY1_Date]) AND [1stFS_EXPIRY2_Date]
 THEN 'Yes' ELSE 'No' END AS GRACE_PERIOD_1STFS
,CASE WHEN ARS.SS_SERVICE_DATE BETWEEN DATEADD(D,1,[2NDFS_EXPIRY1_Date]) AND [2NDFS_EXPIRY2_Date]
 THEN 'Yes' ELSE 'No' END AS GRACE_PERIOD_2NDFS
,CASE WHEN ARS.TS_SERVICE_DATE BETWEEN DATEADD(D,1,[3RDFS_EXPIRY1_Date]) AND [3RDFS_EXPIRY2_Date]
 THEN 'Yes' ELSE 'No' END AS GRACE_PERIOD_3RDFS

,CASE WHEN SALESCHANNEL = 'Showroom' AND ARS.FS_COMPANYID IS NULL THEN NULL
   WHEN SALESCHANNEL = 'Showroom' AND  ARS.FS_COMPANYID=ARS.FK_COMPANYID THEN 'Self Done'
   WHEN SALESCHANNEL = 'Showroom' AND ARS.FS_COMPANYID<>ARS.FK_COMPANYID THEN 'Not Done'
   ELSE NULL
   END AS SELF_REDEEM_1STFS
,CASE WHEN SALESCHANNEL = 'Showroom' AND ARS.SS_COMPANYID IS NULL THEN NULL
   WHEN SALESCHANNEL = 'Showroom' AND ARS.SS_COMPANYID=ARS.FK_COMPANYID THEN 'Self Done'
   WHEN SALESCHANNEL = 'Showroom' AND ARS.SS_COMPANYID<>ARS.FK_COMPANYID THEN 'Not Done'
   ELSE NULL
   END AS SELF_REDEEM_2NDFS
,CASE WHEN SALESCHANNEL = 'Showroom' AND ARS.TS_COMPANYID IS NULL THEN NULL
   WHEN SALESCHANNEL = 'Showroom' AND ARS.TS_COMPANYID=ARS.FK_COMPANYID THEN 'Self Done'
   WHEN SALESCHANNEL = 'Showroom' AND ARS.TS_COMPANYID<>ARS.FK_COMPANYID THEN 'Not Done'
   ELSE NULL
   END AS SELF_REDEEM_3RDFS 

,CASE WHEN FS_SERVICE_DATE<=[1STFS_EXPIRY2_DATE] THEN 'Serviced'
      WHEN FS_SERVICE_DATE IS NULL AND CAST(GETDATE() AS DATE)<[1STFS_EXPIRY2_DATE] THEN 'Un-Serviced'
      WHEN FS_SERVICE_DATE IS NULL OR FS_SERVICE_DATE>[1STFS_EXPIRY2_DATE] THEN 'Service Expired'
       END AS FSServicingStatus
,CASE WHEN SS_SERVICE_DATE<=[2NDFS_EXPIRY2_DATE] THEN 'Serviced'
      WHEN SS_SERVICE_DATE IS NULL AND CAST(GETDATE() AS DATE)<[2NDFS_EXPIRY2_DATE] THEN 'Un-Serviced'
      WHEN SS_SERVICE_DATE IS NULL OR SS_SERVICE_DATE>[2NDFS_EXPIRY2_DATE] THEN 'Service Expired'
       END AS SSServicingStatus
,CASE WHEN TS_SERVICE_DATE<=[3RDFS_EXPIRY2_DATE] THEN 'Serviced'
      WHEN TS_SERVICE_DATE IS NULL AND CAST(GETDATE() AS DATE)<[3RDFS_EXPIRY2_DATE] THEN 'Un-Serviced'
      WHEN TS_SERVICE_DATE IS NULL OR TS_SERVICE_DATE>[3RDFS_EXPIRY2_DATE] THEN 'Service Expired'
       END AS TSServicingStatus
,CASE WHEN FS_SERVICE_DATE<=[1STFS_EXPIRY1_DATE] THEN 0 ELSE 1 END AS FS_Grace_Flag
,CASE WHEN SS_SERVICE_DATE<=[2NDFS_EXPIRY1_DATE] THEN 0 ELSE 1 END AS SS_Grace_Flag
,CASE WHEN TS_SERVICE_DATE<=[3RDFS_EXPIRY1_DATE] THEN 0 ELSE 1 END AS TS_Grace_Flag
,CASE WHEN DOCNAME LIKE 'VSI%' THEN 'VSI' ELSE 'AVSI' END AS RETAIL_TYPE
--INTO ASM_MC_RETAIL_FLAGS
FROM ASM_MC_SERVICE_RETAIL_STG_FINAL ARS


-----------------------------------INSERT INTO FACT TABLE
DELETE FROM ASM_MC_SERVICE_FACT WHERE SERVICE_RETAIL_TYPEIDENTIFIER=102

INSERT INTO ASM_MC_SERVICE_FACT(FK_Docid,
DOCNAME,
Docdate,
FK_Companyid,
Lineid,
FK_Contactid,
FK_Ibid,
FK_Branchid,
FK_Modelid,
COMPANYTYPE,
Dealercode,
ASD_DealerCode,
SALESCHANNEL,
PaidDueDate,
Importeddate,
Service_Retail_TypeIdentifier,
[1stFS_EXPIRY1_Date],
[2ndFS_EXPIRY1_Date],
[3rdFS_EXPIRY1_Date],
[1stFS_EXPIRY2_Date],
[2ndFS_EXPIRY2_Date],
[3rdFS_EXPIRY2_Date],
Return_Flag,
STATUS_1stFS_EXPIRY1,
STATUS_2ndFS_EXPIRY1,
STATUS_3rdFS_EXPIRY1,
STATUS_1stFS_EXPIRY2,
STATUS_2ndFS_EXPIRY2,
STATUS_3rdFS_EXPIRY2,
GRACE_PERIOD_1STFS,
GRACE_PERIOD_2NDFS,
GRACE_PERIOD_3RDFS,
SELF_REDEEM_1STFS,
SELF_REDEEM_2NDFS,
SELF_REDEEM_3RDFS,
FS_Grace_Flag,
SS_Grace_Flag,
TS_Grace_Flag,
Refresh_Date)

SELECT 
FK_Docid,
DOCNAME,
Docdate,
FK_Companyid,
Lineid,
FK_Contactid,
FK_Ibid,
FK_Branchid,
FK_Modelid,
COMPANYTYPE,
Dealercode,
ASD_DealerCode,
SALESCHANNEL,
PaidDueDate,
Importeddate,
Service_Retail_TypeIdentifier,
[1stFS_EXPIRY1_Date],
[2ndFS_EXPIRY1_Date],
[3rdFS_EXPIRY1_Date],
[1stFS_EXPIRY2_Date],
[2ndFS_EXPIRY2_Date],
[3rdFS_EXPIRY2_Date],
Return_Flag,
STATUS_1stFS_EXPIRY1,
STATUS_2ndFS_EXPIRY1,
STATUS_3rdFS_EXPIRY1,
STATUS_1stFS_EXPIRY2,
STATUS_2ndFS_EXPIRY2,
STATUS_3rdFS_EXPIRY2,
GRACE_PERIOD_1STFS,
GRACE_PERIOD_2NDFS,
GRACE_PERIOD_3RDFS,
SELF_REDEEM_1STFS,
SELF_REDEEM_2NDFS,
SELF_REDEEM_3RDFS,
FS_Grace_Flag,
SS_Grace_Flag,
TS_Grace_Flag,
GETDATE() AS Refresh_Date

FROM ASM_MC_RETAIL_FLAGS

DELETE FROM ASM_MC_SERVICE_FACT_AGR WHERE SERVICE_RETAIL_TYPEIDENTIFIER=102
Print('Delted data from ASM_MC_SERVICE_FACT_AGR table for SERVICE_RETAIL_TYPEIDENTIFIER=102')

INSERT INTO ASM_MC_SERVICE_FACT_AGR (FK_Docid,
DOCNAME,
Docdate,
FK_Contactid,
FK_Ibid,
FK_Branchid,
FK_Modelid,
Dealercode,
ASD_DealerCode,
SALESCHANNEL,
PaidDueDate,
Service_Retail_TypeIdentifier,
[1stFS_EXPIRY1_Date],
[2ndFS_EXPIRY1_Date],
[3rdFS_EXPIRY1_Date],
[1stFS_EXPIRY2_Date],
[2ndFS_EXPIRY2_Date],
[3rdFS_EXPIRY2_Date],
Return_Flag,
STATUS_1stFS_EXPIRY1,
STATUS_2ndFS_EXPIRY1,
STATUS_3rdFS_EXPIRY1,
STATUS_1stFS_EXPIRY2,
STATUS_2ndFS_EXPIRY2,
STATUS_3rdFS_EXPIRY2,
GRACE_PERIOD_1STFS,
GRACE_PERIOD_2NDFS,
GRACE_PERIOD_3RDFS,
SELF_REDEEM_1STFS,
SELF_REDEEM_2NDFS,
SELF_REDEEM_3RDFS,
FS_Grace_Flag,
SS_Grace_Flag,
TS_Grace_Flag,
Refresh_Date)

select FK_Docid,
DOCNAME,
Docdate,
FK_Contactid,
FK_Ibid,
FK_Branchid,
FK_Modelid,
Dealercode,
ASD_DealerCode,
SALESCHANNEL,
PaidDueDate,
Service_Retail_TypeIdentifier,
[1stFS_EXPIRY1_Date],
[2ndFS_EXPIRY1_Date],
[3rdFS_EXPIRY1_Date],
[1stFS_EXPIRY2_Date],
[2ndFS_EXPIRY2_Date],
[3rdFS_EXPIRY2_Date],
Return_Flag,
STATUS_1stFS_EXPIRY1,
STATUS_2ndFS_EXPIRY1,
STATUS_3rdFS_EXPIRY1,
STATUS_1stFS_EXPIRY2,
STATUS_2ndFS_EXPIRY2,
STATUS_3rdFS_EXPIRY2,
GRACE_PERIOD_1STFS,
GRACE_PERIOD_2NDFS,
GRACE_PERIOD_3RDFS,
SELF_REDEEM_1STFS,
SELF_REDEEM_2NDFS,
SELF_REDEEM_3RDFS,
FS_Grace_Flag,
SS_Grace_Flag,
TS_Grace_Flag,
GETDATE() AS Refresh_Date
FROM ASM_MC_RETAIL_FLAGS
Print('Data inserted in ASM_MC_SERVICE_FACT_AGR table')

END
GO