SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Alter PROC [dbo].[USP_ASM_SPARES_ICMC_WAREHOUSE_BO_ANALYSIS]
AS
BEGIN
/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|CHANGE DESCRIPTION			                            */
/*--------------------------------------------------------------------------------------------------*/
/*	2025-04-24 	|	 	Aswani	  |        Initiation of the SP                                     */ 
/*	2025-08-29 	|	 	Lachmanna	  |   Handled -value conversion                                      */ 
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*******************************************HISTORY**************************************************/

PRINT('LOADING DATA FROM Source TABLE')
TRUNCATE TABLE [dbo].[ASM_ICMC_SPARES_WAREHOUSE_BO_FACT];

--------------------------------------------------------------------------------------------------------------------------

DECLARE @CurrentDate DATE = CAST(GETDATE() AS DATE);
DECLARE @StartDate DATE = CAST(DATEADD(MONTH, DATEDIFF(MONTH,0,GETDATE()),0) AS DATE);

------------------------------------------------DATA LOAD FOR 3W--------------------------------------------------------------------------
WITH RANK_ITEMS AS ( 
SELECT ORDER_MATERIAL, BACKORDER_AMOUNT, RANKING, BU FROM (
SELECT ORDER_MATERIAL,MAX(BACKORDER_AMOUNT) AS BACKORDER_AMOUNT,ROW_NUMBER() OVER (ORDER BY MAX(BACKORDER_AMOUNT) DESC) AS RANKING, BU FROM (
SELECT
    ORDER_MATERIAL,BU,
    SUM(BACKORDER_AMOUNT) AS BACKORDER_AMOUNT 
FROM ASM_ICMC_SPARES_MATERIAL_BACKORDER_DIM_DAILY
WHERE CALENDAR_DATE = @CurrentDate
AND BU IN ('3W')
AND BACKORDER_AMOUNT>0 AND BACKORDER_QTY>0 --AND ORDER_MATERIAL='30151105'
GROUP BY ORDER_MATERIAL, BU
)A 
GROUP BY ORDER_MATERIAL, BU
)B WHERE RANKING <= 2000
),

BACKORDER_1ST_OF_MONTH AS (
SELECT
    ORDER_MATERIAL,
    CALENDAR_DATE, BU,
    MAX(BACKORDER_AMOUNT) AS BO_FIRSTOFMONTH,
	MAX(BACKORDER_QTY) AS BO_FIRSTOFMONTH_QTY
FROM ASM_ICMC_SPARES_MATERIAL_BACKORDER_DIM_DAILY
WHERE CALENDAR_DATE BETWEEN @StartDate AND @CurrentDate
AND DATEPART(DAY, CALENDAR_DATE) = 1 AND BU='3W' --AND ORDER_MATERIAL='01100342' 
GROUP BY ORDER_MATERIAL, CALENDAR_DATE, BU
),

STOCK_1ST_OF_MONTH AS(
SELECT ORDER_MATERIAL, STOCK_FIRSTOFMONTH FROM (
    SELECT FLD1 AS ORDER_MATERIAL,
    REFRESH_DATE,
    SUM(CAST(FLD18 AS FLOAT)) AS STOCK_FIRSTOFMONTH
FROM SLT_SAP_REPORT_YSD_ORDER_VS_ATP
WHERE FLD2 IN ('WA02','PT02') AND FLD3 IN ('SPR1', 'SPR2', 'SPR3', 'SP01', 'SP02', 'SP03') 
AND DATEPART(DAY, REFRESH_DATE) = 1
AND REFRESH_DATE BETWEEN @StartDate AND @CurrentDate --and FLD1='DK101755'
GROUP BY FLD1, REFRESH_DATE
)A
),

BACKORDER AS (
SELECT
CALENDAR_DATE,
ORDER_MATERIAL, 
SUM(BACKORDER_AMOUNT) AS BO_VALUE,
BU,
SUM(BACKORDER_QTY) AS BACKORDER_QTY
FROM ASM_ICMC_SPARES_MATERIAL_BACKORDER_DIM_DAILY
WHERE CALENDAR_DATE = @CurrentDate
AND BACKORDER_AMOUNT>0 AND BACKORDER_QTY>0 AND BU IN ('3W')
GROUP BY CALENDAR_DATE, ORDER_MATERIAL, BU
),

MAT_VALUE_PER_QTY AS (
SELECT ORDER_MATERIAL, BO_VALUE, BACKORDER_QTY, BU,
BO_VALUE/BACKORDER_QTY AS MAT_VALUE_PER_QTY
FROM BACKORDER
),

EOMONTH_SCH_GR as (
SELECT 
Material as MATERIAL_NUMBER, 
cast(Report_Date as date) as DATE_MONTH, 
Vendor as VENDOR, 
[Vendor Name] as VENDOR_NAME,
Plant as PLANT,
[Item Status] as schedule_type,
Item,
[Purchasing Document] as PO_NUMBER,
Try_cast(isnull([PO Rate],0) as float) as PO_RATE,
--cast([Open Sch Qty] as int) as PENDING_SCH_QTY,
CASE
    WHEN [Open Sch Qty] IS NULL OR LTRIM(RTRIM([Open Sch Qty])) = '' THEN NULL
    WHEN RIGHT(LTRIM(RTRIM([Open Sch Qty])), 1) = '-' AND 
         TRY_CAST(LEFT([Open Sch Qty], LEN([Open Sch Qty]) - 1) AS INT) IS NOT NULL
    THEN  -1 * CAST(LEFT([Open Sch Qty], LEN([Open Sch Qty]) - 1) AS INT)
    WHEN TRY_CAST([Open Sch Qty] AS INT) IS NOT NULL THEN 
        CAST([Open Sch Qty] AS INT)  ELSE 0 END AS PENDING_SCH_QTY,
cast([Month Schedule Quantity] as int)  as SCH_QTY,
cast([Month GR Quantity] as int) as GR_QTY,
[Material Description]
FROM SPARES_ICMC_YOTD38_SPP_EOM 
WHERE cast(Report_Date as date) =  (SELECT MAX(cast(Report_Date as date)) FROM SPARES_ICMC_YOTD38_SPP_EOM )), 

SOMONTH_SCH_GR as (
SELECT 
Material as MATERIAL_NUMBER, 
cast(Report_Date as date) as DATE_MONTH, 
Vendor as VENDOR, 
[Vendor Name] as VENDOR_NAME,
Plant as PLANT,
[Item Status] as schedule_type,
Item,
[Purchasing Document] as PO_NUMBER,
TRY_CAST(ISNULL([PO Rate], 0) AS FLOAT) AS PO_RATE,
--cast([Open Sch Qty] as int) as PENDING_SCH_QTY,
CASE
    WHEN [Open Sch Qty] IS NULL OR LTRIM(RTRIM([Open Sch Qty])) = '' THEN NULL
    WHEN RIGHT(LTRIM(RTRIM([Open Sch Qty])), 1) = '-' AND 
         TRY_CAST(LEFT([Open Sch Qty], LEN([Open Sch Qty]) - 1) AS INT) IS NOT NULL
    THEN 
        -1 * CAST(LEFT([Open Sch Qty], LEN([Open Sch Qty]) - 1) AS INT)

    WHEN TRY_CAST([Open Sch Qty] AS INT) IS NOT NULL THEN 
        CAST([Open Sch Qty] AS INT)

    ELSE 0 END AS PENDING_SCH_QTY,
cast([Month Schedule Quantity] as int)  as SCH_QTY,
cast([Month GR Quantity] as int) as GR_QTY,
[Material Description]
FROM SPARES_ICMC_YOTD38_SPP_SOM 
WHERE cast(Report_Date as date) = (SELECT MAX(cast(Report_Date as date)) FROM SPARES_ICMC_YOTD38_SPP_SOM)
and [Open Sch Qty]='-5400') ,

SCHEDULE AS (
SELECT DATE_MONTH as SCHEDULED_DATE, MATERIAL_NUMBER as ORDER_MATERIAL, SUM(PENDING_SCH_QTY + SCH_QTY) as SCHEDULED_QTY,COUNT(DISTINCT VENDOR) AS NO_OF_VENDORS,MAX(MATERIAL_DESCRIPTION) AS MATERIAL_DESC,'3W' as BU
FROM (
SELECT 
B.DATE_MONTH, 
B.MATERIAL_NUMBER, 
B.VENDOR, 
B.PLANT, 
B.PO_NUMBER, 
B.[Material Description] as MATERIAL_DESCRIPTION,
CASE WHEN A.PENDING_SCH_QTY is null THEN B.PENDING_SCH_QTY ELSE A.PENDING_SCH_QTY END as PENDING_SCH_QTY,
CASE WHEN A.SCH_QTY is null THEN B.SCH_QTY ELSE A.SCH_QTY END as SCH_QTY
FROM SOMONTH_SCH_GR B 
LEFT JOIN EOMONTH_SCH_GR A
ON B.DATE_MONTH = A.DATE_MONTH 
AND B.MATERIAL_NUMBER = A.MATERIAL_NUMBER 
AND B.VENDOR = A.VENDOR
AND B.PLANT = A.PLANT 
AND B.PO_NUMBER = A.PO_NUMBER ) A
GROUP BY DATE_MONTH, MATERIAL_NUMBER
),

GOODS_RECEIPT AS (
    SELECT CONVERT(date, GR_Y_M + '-01') as GR_MONTH, 
    MATERIAL_NUMBER as ORDER_MATERIAL, 
    SUM(MONTH_GR_QTY) as GR_QTY,
	'3W' as BU
    FROM SPD_GOODS_RECIPT
    WHERE CONVERT(date, GR_Y_M + '-01')  = DATEADD(month, DATEDIFF(month, 0,GETDATE()), 0) 
    GROUP BY CONVERT(date, GR_Y_M + '-01'), MATERIAL_NUMBER ),

ATP AS (
SELECT ORDER_MATERIAL, STOCK_QTY
FROM (
SELECT 
FLD1 AS ORDER_MATERIAL,
SUM(CAST(FLD18 AS FLOAT)) AS STOCK_QTY,
REFRESH_DATE 
FROM SLT_SAP_REPORT_YSD_ORDER_VS_ATP
WHERE FLD2 IN ('WA02','PT02') AND FLD3 IN ('SPR1', 'SPR2', 'SPR3', 'SP01', 'SP02', 'SP03') 
AND REFRESH_DATE = @CurrentDate
GROUP BY FLD1, REFRESH_DATE
)A 
), 

PUT_AWAY AS (
SELECT ORDER_MATERIAL, SUM(CAST(PUTAWAY_QTY AS FLOAT)) AS PUTAWAY_QTY, BU
FROM(
SELECT
A.MATNR AS ORDER_MATERIAL,
A.MENGE AS PUTAWAY_QTY,
A.BWART AS MOVEMENT_TYPE,
U.BU
FROM SAP_MSEG_PUTWAY A
INNER JOIN MAT_VALUE_PER_QTY U ON A.MATNR = U.ORDER_MATERIAL
WHERE BU = '3W' AND CAST(BUDAT_MKPF AS DATE) BETWEEN @StartDate AND @CurrentDate AND SHKZG='S'
)A GROUP BY ORDER_MATERIAL, BU
),

MAD AS (
SELECT SUM(MAD_VALUE) AS MAD_VALUE,SUM(MAD_QTY) AS MAD_QTY,ORDER_MATERIAL
FROM (
SELECT DISTINCT
MAD_VALUE,
MAD_QTY,
MATERIAL_CODE AS ORDER_MATERIAL,
MONTH_DEMAND
FROM ASM_ICMC_SPARES_WH_MAD_VALUE
WHERE MONTH_DEMAND BETWEEN @StartDate AND @CurrentDate
)A GROUP BY ORDER_MATERIAL
),

CTE_PD_QTY AS(
SELECT MATERIAL_NO, BU,  SUMM,  SCHEDULED_QTY, SCHEDULED_DATE_PD, SUM(PD_PER_MAT) AS PD_PER_MAT FROM (
SELECT MATERIAL_NO, BU,  SUMM,  SCHEDULED_QTY, SCHEDULED_DATE AS SCHEDULED_DATE_PD,
	CASE WHEN SUMM=0 THEN 0
		 ELSE ((PD_QTY * SCHEDULED_QTY)/SUMM)
		 END AS PD_PER_MAT FROM (
SELECT MATERIAL_NO, A.BU, SUMM, SCHEDULED_DATE, SCHEDULED_QTY,
CASE WHEN MONTH(CAST(SCHEDULED_DATE AS DATE)) IN (4,5,6) THEN PD_Q1
	 WHEN MONTH(CAST(SCHEDULED_DATE AS DATE)) IN (7,8,9) THEN PD_Q2
	 WHEN MONTH(CAST(SCHEDULED_DATE AS DATE)) IN (10,11,12) THEN PD_Q3
	 WHEN MONTH(CAST(SCHEDULED_DATE AS DATE)) IN (1,2,3) THEN PD_Q4
ELSE 0 END AS PD_QTY
FROM 
(SELECT MATERIAL_NO, 
CASE WHEN BU IN ('3W','COM','4W') THEN '3W' END AS BU, PD_Q1, PD_Q2, PD_Q3, PD_Q4
FROM SPARES_PROJECTED_DEMAND_FY25 
WHERE BU IN ('3W','COM','4W')) A
JOIN 
(SELECT ORDER_MATERIAL, SCHEDULED_QTY, SCHEDULED_DATE, BU,
SUM(SCHEDULED_QTY) OVER (PARTITION BY ORDER_MATERIAL,SCHEDULED_DATE) AS SUMM 
FROM SCHEDULE
GROUP BY ORDER_MATERIAL, SCHEDULED_QTY, SCHEDULED_DATE, BU
)B 
ON A.MATERIAL_NO = B.ORDER_MATERIAL AND A.BU = B.BU
)X
)Y
GROUP BY MATERIAL_NO, BU,  SUMM,  SCHEDULED_QTY, SCHEDULED_DATE_PD
),

DEMAND_VALUE AS (
SELECT ORDER_MATERIAL, SUM(DEMAND_VALUE) AS DEMAND_VALUE, SUM(DEMAND_QTY) AS DEMAND_QTY, KATR6
FROM (
SELECT DISTINCT
ORDER_NO,
SOLD_TO_DEALER_OR_DISTRIBUTOR,
ORDER_MATERIAL,ORDER_DATE, ITEM,
(GROSS_ORDER_AMOUNT) AS DEMAND_VALUE,
(ORDER_QUANTITY) AS DEMAND_QTY,
KATR6
FROM VW_SPARES_ICMC_ODI_DATA A
LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 CM ON A.SOLD_TO_DEALER_OR_DISTRIBUTOR=CM.KUNNR
WHERE SALES_ORGANIZATION='ZDOM' AND ORDER_DIVISION='B1'  AND DISTRIBUTION_CHANNEL IN (10,20)  
AND ORDER_TYPE IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPSH','ZPVR','ZSPD','ZSPD')
AND ORDER_REJECTION_REASON IN ('','A1') AND KATR6 IN ('3WH')
AND ORDER_DATE BETWEEN @StartDate AND @CurrentDate
)X GROUP BY ORDER_MATERIAL, KATR6
),

SUPPLY_VALUE AS (
SELECT SUM(INVOICE_QTY) AS SUPPLY_QTY, INVOICE_MATERIAL, BU FROM (
SELECT SUM(ACTUAL_BILLED_QTY) AS INVOICE_QTY, SOLD_TO_DEALER_OR_DISTRIBUTOR, BILLING_DATE, BU, INVOICE_MATERIAL
FROM  (
SELECT DISTINCT A.ORDER_NO, A.INVOICE_ITEM, A.INVOICE_MATERIAL, A.INVOICE_NUMBER, A.ACTUAL_BILLED_QTY, A.SOLD_TO_DEALER_OR_DISTRIBUTOR, A.BILLING_DATE, A.DISTRIBUTION_CHANNEL,
CASE WHEN CM.KATR6='2WH' THEN '2W'
     WHEN CM.KATR6='3WH' THEN '3W'
     ELSE NULL END AS BU
FROM VW_SPARES_ICMC_ODI_DATA A
LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 CM ON A.SOLD_TO_DEALER_OR_DISTRIBUTOR=CM.KUNNR 
WHERE A.SALES_ORGANIZATION='ZDOM' AND A.INVOICE_DIVISION='B1'  AND A.DISTRIBUTION_CHANNEL IN (10,20)  
AND A.BILLING_TYPE_ANALYTICS IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPSH','ZPVR','ZSPD','ZSPD') 
AND A.BILLING_DATE IS NOT NULL AND CM.KATR6 IN ('3WH') AND FKSTO<>'X'
AND BILLING_DATE BETWEEN @StartDate AND @CurrentDate
)P GROUP BY SOLD_TO_DEALER_OR_DISTRIBUTOR,BILLING_DATE,BU, INVOICE_MATERIAL
)Q GROUP BY INVOICE_MATERIAL, BU
),

CTE_PART_MASTER AS (
SELECT [MATERIAL] AS PART_CODE, CATEGORY, BU
FROM SPARES_ICMC_WH_PART_MASTER 
WHERE BU='3W'
),

CTE_PROC AS (
    SELECT
       DISTINCT R.ORDER_MATERIAL,
	   R.BU,
        RANKING,
        UPPER(P.CATEGORY) AS PCATEGORY,
        NO_OF_VENDORS,
        null as VENDOR_NAME,
        MATERIAL_DESC,
        NULL AS BUYER_NAME,
        PD_PER_MAT AS PD_QTY,
        DEMAND_QTY,
        MAD_QTY,
        S.SCHEDULED_QTY,
        GR_QTY,
        STOCK_QTY,
        B.BACKORDER_QTY,
		SUPPLY_QTY,
		FB.BO_FIRSTOFMONTH_QTY,
        (PD_PER_MAT * MAT_VALUE_PER_QTY) AS PD_VALUE,
        (DEMAND_QTY * MAT_VALUE_PER_QTY) AS DEMAND_VALUE,
        B.BO_VALUE,
        (S.SCHEDULED_QTY * MAT_VALUE_PER_QTY) AS SCH_VALUE,
        (GR_QTY * MAT_VALUE_PER_QTY) AS GR_VALUE,
        (STOCK_QTY * MAT_VALUE_PER_QTY) AS STOCK_VALUE,
		(SUPPLY_QTY * MAT_VALUE_PER_QTY) AS SUPPLY_VALUE,
        (MAD_QTY * MAT_VALUE_PER_QTY) AS MAD_VALUE,
        PUTAWAY_QTY,
        (PUTAWAY_QTY * MAT_VALUE_PER_QTY) AS PUTAWAY_VALUE,
        SF.STOCK_FIRSTOFMONTH,
        FB.BO_FIRSTOFMONTH,
        CASE WHEN (S.SCHEDULED_QTY * MAT_VALUE_PER_QTY) >= ((DEMAND_QTY * MAT_VALUE_PER_QTY) + FB.BO_FIRSTOFMONTH) THEN 1  ELSE 0 END AS SCHEDULE_SUFFICIENCY,
        CASE WHEN (GR_QTY * MAT_VALUE_PER_QTY) >= ((DEMAND_QTY * MAT_VALUE_PER_QTY) + FB.BO_FIRSTOFMONTH)  THEN 1 ELSE 0 END AS GRN_SUFFICIENCY,
        CASE WHEN (STOCK_QTY * MAT_VALUE_PER_QTY) >= FB.BO_FIRSTOFMONTH THEN 1 ELSE 0 END AS STOCK_SUFFICIENCY,
        CASE WHEN (PUTAWAY_QTY * MAT_VALUE_PER_QTY) >= ((DEMAND_QTY * MAT_VALUE_PER_QTY) + FB.BO_FIRSTOFMONTH) THEN 1 ELSE 0 END AS PUTAWAY_SUFFICIENCY,
        CASE WHEN (SUPPLY_QTY * MAT_VALUE_PER_QTY) >= ((DEMAND_QTY * MAT_VALUE_PER_QTY) + FB.BO_FIRSTOFMONTH) THEN 1 ELSE 0 END AS SUPPLY_SUFFICIENCY
    FROM RANK_ITEMS R
    LEFT JOIN DEMAND_VALUE V ON R.ORDER_MATERIAL = V.ORDER_MATERIAL AND R.BU=LEFT(V.KATR6,2)	
    LEFT JOIN MAT_VALUE_PER_QTY U ON R.ORDER_MATERIAL = U.ORDER_MATERIAL AND R.BU=U.BU
	LEFT JOIN SUPPLY_VALUE SV ON R.ORDER_MATERIAL = SV.INVOICE_MATERIAL AND R.BU = SV.BU
    LEFT JOIN STOCK_1ST_OF_MONTH SF ON R.ORDER_MATERIAL = SF.ORDER_MATERIAL
    LEFT JOIN BACKORDER_1ST_OF_MONTH FB ON R.ORDER_MATERIAL = FB.ORDER_MATERIAL AND R.BU = FB.BU
    LEFT JOIN BACKORDER B ON R.ORDER_MATERIAL = B.ORDER_MATERIAL AND R.BU=B.BU
    LEFT JOIN SCHEDULE S ON R.ORDER_MATERIAL = S.ORDER_MATERIAL --AND R.BU=S.BU
    LEFT JOIN GOODS_RECEIPT G ON R.ORDER_MATERIAL = G.ORDER_MATERIAL --AND R.BU=G.BU
    LEFT JOIN ATP A ON R.ORDER_MATERIAL = A.ORDER_MATERIAL
    LEFT JOIN PUT_AWAY E ON R.ORDER_MATERIAL = E.ORDER_MATERIAL AND R.BU = LEFT(E.BU,2)
    LEFT JOIN MAD M ON R.ORDER_MATERIAL = M.ORDER_MATERIAL
    LEFT JOIN CTE_PART_MASTER P ON R.ORDER_MATERIAL = P.[PART_CODE] AND R.BU=P.BU
    LEFT JOIN CTE_PD_QTY Q ON R.ORDER_MATERIAL = Q.MATERIAL_NO AND R.BU = Q.BU
	WHERE R.BU IN ('3W')
) --SELECT * FROM CTE_PROC
 

INSERT INTO [ASM_ICMC_SPARES_WAREHOUSE_BO_FACT]
(
RANKING,
ORDER_MATERIAL,
PCATEGORY,
NO_OF_VENDORS,
VENDOR_NAME,
MATERIAL_DESC,
BUYER_NAME,
PD_QTY,
DEMAND_QTY,
MAD_QTY,
SCHEDULED_QTY,
GR_QTY,
STOCK_QTY,
BACKORDER_QTY,
PD_VALUE,
DEMAND_VALUE,
BO_VALUE,
SCH_VALUE,
GR_VALUE,
STOCK_VALUE,
MAD_VALUE,
PUTAWAY_QTY,
PUTAWAY_VALUE,
SUPPLY_VALUE,
STOCK_FIRSTOFMONTH,
BO_FIRSTOFMONTH,
SCHEDULE_SUFFICIENCY,
GRN_SUFFICIENCY,
STOCK_SUFFICIENCY,
PUTAWAY_SUFFICIENCY,
SUPPLY_SUFFICIENCY,
BU,
SUPPLY_QTY,
BO_FIRSTOFMONTH_QTY
)

SELECT DISTINCT
RANKING,
ORDER_MATERIAL,
PCATEGORY,
NO_OF_VENDORS,
VENDOR_NAME,
MATERIAL_DESC,
BUYER_NAME,
PD_QTY,
DEMAND_QTY,
MAD_QTY,
SCHEDULED_QTY,
GR_QTY,
STOCK_QTY,
BACKORDER_QTY,
PD_VALUE,
DEMAND_VALUE,
BO_VALUE,
SCH_VALUE,
GR_VALUE,
STOCK_VALUE,
MAD_VALUE,
PUTAWAY_QTY,
PUTAWAY_VALUE,
SUPPLY_VALUE,
STOCK_FIRSTOFMONTH,
BO_FIRSTOFMONTH,
SCHEDULE_SUFFICIENCY,
GRN_SUFFICIENCY,
STOCK_SUFFICIENCY,
PUTAWAY_SUFFICIENCY,
SUPPLY_SUFFICIENCY,
BU,
SUPPLY_QTY,
BO_FIRSTOFMONTH_QTY
FROM CTE_PROC;


------------------------------------------------DATA LOAD FOR 2W--------------------------------------------------------------------------
WITH RANK_ITEMS AS ( 
SELECT ORDER_MATERIAL, BACKORDER_AMOUNT, RANKING, BU FROM (
SELECT ORDER_MATERIAL,MAX(BACKORDER_AMOUNT) AS BACKORDER_AMOUNT,ROW_NUMBER() OVER (ORDER BY MAX(BACKORDER_AMOUNT) DESC) AS RANKING, BU FROM (
SELECT
    ORDER_MATERIAL,BU,
    SUM(BACKORDER_AMOUNT) AS BACKORDER_AMOUNT 
FROM ASM_ICMC_SPARES_MATERIAL_BACKORDER_DIM_DAILY
WHERE CALENDAR_DATE = @CurrentDate
AND BU IN ('2W')
AND BACKORDER_AMOUNT>0 AND BACKORDER_QTY>0 --AND ORDER_MATERIAL='30151105'
GROUP BY ORDER_MATERIAL, BU
)A 
GROUP BY ORDER_MATERIAL, BU
)B WHERE RANKING <= 2000
),

BACKORDER_1ST_OF_MONTH AS (
SELECT
    ORDER_MATERIAL,
    CALENDAR_DATE, BU,
    MAX(BACKORDER_AMOUNT) AS BO_FIRSTOFMONTH,
	MAX(BACKORDER_QTY) AS BO_FIRSTOFMONTH_QTY
FROM ASM_ICMC_SPARES_MATERIAL_BACKORDER_DIM_DAILY
WHERE CALENDAR_DATE BETWEEN @StartDate AND @CurrentDate
AND DATEPART(DAY, CALENDAR_DATE) = 1 AND BU='2W' --AND ORDER_MATERIAL='01100342' 
GROUP BY ORDER_MATERIAL, CALENDAR_DATE, BU
),

STOCK_1ST_OF_MONTH AS(
SELECT ORDER_MATERIAL, STOCK_FIRSTOFMONTH FROM (
    SELECT FLD1 AS ORDER_MATERIAL,
    REFRESH_DATE,
    SUM(CAST(FLD18 AS FLOAT)) AS STOCK_FIRSTOFMONTH
FROM SLT_SAP_REPORT_YSD_ORDER_VS_ATP
WHERE FLD2 IN ('WA02','PT02') AND FLD3 IN ('SPR1', 'SPR2', 'SPR3', 'SP01', 'SP02', 'SP03') 
AND DATEPART(DAY, REFRESH_DATE) = 1
AND REFRESH_DATE BETWEEN @StartDate AND @CurrentDate --and FLD1='DK101755'
GROUP BY FLD1, REFRESH_DATE
)A
),

BACKORDER AS (
SELECT
CALENDAR_DATE,
ORDER_MATERIAL, 
SUM(BACKORDER_AMOUNT) AS BO_VALUE,
BU,
SUM(BACKORDER_QTY) AS BACKORDER_QTY
FROM ASM_ICMC_SPARES_MATERIAL_BACKORDER_DIM_DAILY
WHERE CALENDAR_DATE = @CurrentDate
AND BACKORDER_AMOUNT>0 AND BACKORDER_QTY>0 AND BU IN ('2W')
GROUP BY CALENDAR_DATE, ORDER_MATERIAL, BU
),

MAT_VALUE_PER_QTY AS (
SELECT ORDER_MATERIAL, BO_VALUE, BACKORDER_QTY, BU,
BO_VALUE/BACKORDER_QTY AS MAT_VALUE_PER_QTY
FROM BACKORDER
),

EOMONTH_SCH_GR as (
SELECT 
Material as MATERIAL_NUMBER, 
cast(Report_Date as date) as DATE_MONTH, 
Vendor as VENDOR, 
[Vendor Name] as VENDOR_NAME,
Plant as PLANT,
[Item Status] as schedule_type,
Item,
[Purchasing Document] as PO_NUMBER,
Try_cast(isnull([PO Rate],0) as float) as PO_RATE,
--cast([Open Sch Qty] as int) as PENDING_SCH_QTY,
CASE
    WHEN [Open Sch Qty] IS NULL OR LTRIM(RTRIM([Open Sch Qty])) = '' THEN NULL
    WHEN RIGHT(LTRIM(RTRIM([Open Sch Qty])), 1) = '-' AND 
         TRY_CAST(LEFT([Open Sch Qty], LEN([Open Sch Qty]) - 1) AS INT) IS NOT NULL
    THEN 
        -1 * CAST(LEFT([Open Sch Qty], LEN([Open Sch Qty]) - 1) AS INT)

    WHEN TRY_CAST([Open Sch Qty] AS INT) IS NOT NULL THEN 
        CAST([Open Sch Qty] AS INT)

    ELSE 0 END AS PENDING_SCH_QTY ,
cast([Month Schedule Quantity] as int)  as SCH_QTY,
cast([Month GR Quantity] as int) as GR_QTY,
[Material Description]
FROM SPARES_ICMC_YOTD38_SPP_EOM 
WHERE cast(Report_Date as date) =  (SELECT MAX(cast(Report_Date as date)) FROM SPARES_ICMC_YOTD38_SPP_EOM )), 

SOMONTH_SCH_GR as (
SELECT 
Material as MATERIAL_NUMBER, 
cast(Report_Date as date) as DATE_MONTH, 
Vendor as VENDOR, 
[Vendor Name] as VENDOR_NAME,
Plant as PLANT,
[Item Status] as schedule_type,
Item,
[Purchasing Document] as PO_NUMBER,
Try_cast(Isnull([PO Rate],0) as float) as PO_RATE,
--cast([Open Sch Qty] as int) as PENDING_SCH_QTY,
CASE
    WHEN [Open Sch Qty] IS NULL OR LTRIM(RTRIM([Open Sch Qty])) = '' THEN NULL
    WHEN RIGHT(LTRIM(RTRIM([Open Sch Qty])), 1) = '-' AND 
         TRY_CAST(LEFT([Open Sch Qty], LEN([Open Sch Qty]) - 1) AS INT) IS NOT NULL
    THEN         -1 * CAST(LEFT([Open Sch Qty], LEN([Open Sch Qty]) - 1) AS INT)

    WHEN TRY_CAST([Open Sch Qty] AS INT) IS NOT NULL THEN 
        CAST([Open Sch Qty] AS INT)

    ELSE 0 END AS PENDING_SCH_QTY ,
cast([Month Schedule Quantity] as int)  as SCH_QTY,
cast([Month GR Quantity] as int) as GR_QTY,
[Material Description]
FROM SPARES_ICMC_YOTD38_SPP_SOM 
WHERE cast(Report_Date as date) = (SELECT MAX(cast(Report_Date as date)) FROM SPARES_ICMC_YOTD38_SPP_SOM)) ,

SCHEDULE AS (
SELECT DATE_MONTH as SCHEDULED_DATE, MATERIAL_NUMBER as ORDER_MATERIAL, SUM(PENDING_SCH_QTY + SCH_QTY) as SCHEDULED_QTY,COUNT(DISTINCT VENDOR) AS NO_OF_VENDORS,MAX(MATERIAL_DESCRIPTION) AS MATERIAL_DESC,'2W' as BU
FROM (
SELECT 
B.DATE_MONTH, 
B.MATERIAL_NUMBER, 
B.VENDOR, 
B.PLANT, 
B.PO_NUMBER, 
B.[Material Description] as MATERIAL_DESCRIPTION,
CASE WHEN A.PENDING_SCH_QTY is null THEN B.PENDING_SCH_QTY ELSE A.PENDING_SCH_QTY END as PENDING_SCH_QTY,
CASE WHEN A.SCH_QTY is null THEN B.SCH_QTY ELSE A.SCH_QTY END as SCH_QTY
FROM SOMONTH_SCH_GR B 
LEFT JOIN EOMONTH_SCH_GR A
ON B.DATE_MONTH = A.DATE_MONTH 
AND B.MATERIAL_NUMBER = A.MATERIAL_NUMBER 
AND B.VENDOR = A.VENDOR
AND B.PLANT = A.PLANT 
AND B.PO_NUMBER = A.PO_NUMBER ) A
GROUP BY DATE_MONTH, MATERIAL_NUMBER
),

GOODS_RECEIPT AS (
    SELECT CONVERT(date, GR_Y_M + '-01') as GR_MONTH, 
    MATERIAL_NUMBER as ORDER_MATERIAL, 
    SUM(MONTH_GR_QTY) as GR_QTY,
	'2W' as BU
    FROM SPD_GOODS_RECIPT
    WHERE CONVERT(date, GR_Y_M + '-01')  = DATEADD(month, DATEDIFF(month, 0,GETDATE()), 0) 
    GROUP BY CONVERT(date, GR_Y_M + '-01'), MATERIAL_NUMBER ),

ATP AS (
SELECT ORDER_MATERIAL, STOCK_QTY
FROM (
SELECT 
FLD1 AS ORDER_MATERIAL,
SUM(CAST(FLD18 AS FLOAT)) AS STOCK_QTY,
REFRESH_DATE 
FROM SLT_SAP_REPORT_YSD_ORDER_VS_ATP
WHERE FLD2 IN ('WA02','PT02') AND FLD3 IN ('SPR1', 'SPR2', 'SPR3', 'SP01', 'SP02', 'SP03') 
AND REFRESH_DATE = @CurrentDate
GROUP BY FLD1, REFRESH_DATE
)A 
), 

PUT_AWAY AS (
SELECT ORDER_MATERIAL, SUM(CAST(PUTAWAY_QTY AS FLOAT)) AS PUTAWAY_QTY, BU
FROM(
SELECT
A.MATNR AS ORDER_MATERIAL,
A.MENGE AS PUTAWAY_QTY,
A.BWART AS MOVEMENT_TYPE,
U.BU
FROM SAP_MSEG_PUTWAY A
INNER JOIN MAT_VALUE_PER_QTY U ON A.MATNR = U.ORDER_MATERIAL
WHERE BU = '2W' AND CAST(BUDAT_MKPF AS DATE) BETWEEN @StartDate AND @CurrentDate AND SHKZG='S'
)A GROUP BY ORDER_MATERIAL, BU
),

MAD AS (
SELECT SUM(MAD_VALUE) AS MAD_VALUE,SUM(MAD_QTY) AS MAD_QTY,ORDER_MATERIAL
FROM (
SELECT DISTINCT
MAD_VALUE,
MAD_QTY,
MATERIAL_CODE AS ORDER_MATERIAL,
MONTH_DEMAND
FROM ASM_ICMC_SPARES_WH_MAD_VALUE
WHERE MONTH_DEMAND BETWEEN @StartDate AND @CurrentDate
)A GROUP BY ORDER_MATERIAL
),

CTE_PD_QTY AS(
SELECT MATERIAL_NO, BU,  SUMM,  SCHEDULED_QTY, SCHEDULED_DATE_PD, SUM(PD_PER_MAT) AS PD_PER_MAT FROM (
SELECT MATERIAL_NO, BU,  SUMM,  SCHEDULED_QTY, SCHEDULED_DATE AS SCHEDULED_DATE_PD,
	CASE WHEN SUMM=0 THEN 0
		 ELSE ((PD_QTY * SCHEDULED_QTY)/SUMM)
		 END AS PD_PER_MAT FROM (
SELECT MATERIAL_NO, A.BU, SUMM, SCHEDULED_DATE, SCHEDULED_QTY,
CASE WHEN MONTH(CAST(SCHEDULED_DATE AS DATE)) IN (4,5,6) THEN PD_Q1
	 WHEN MONTH(CAST(SCHEDULED_DATE AS DATE)) IN (7,8,9) THEN PD_Q2
	 WHEN MONTH(CAST(SCHEDULED_DATE AS DATE)) IN (10,11,12) THEN PD_Q3
	 WHEN MONTH(CAST(SCHEDULED_DATE AS DATE)) IN (1,2,3) THEN PD_Q4
ELSE 0 END AS PD_QTY
FROM 
(SELECT MATERIAL_NO, 
CASE WHEN BU IN ('2W','COM') THEN '2W' END AS BU, PD_Q1, PD_Q2, PD_Q3, PD_Q4
FROM SPARES_PROJECTED_DEMAND_FY25 
WHERE BU IN ('2W','COM')) A
JOIN 
(SELECT ORDER_MATERIAL, SCHEDULED_QTY, SCHEDULED_DATE, BU,
SUM(SCHEDULED_QTY) OVER (PARTITION BY ORDER_MATERIAL,SCHEDULED_DATE) AS SUMM 
FROM SCHEDULE
GROUP BY ORDER_MATERIAL, SCHEDULED_QTY, SCHEDULED_DATE, BU
)B 
ON A.MATERIAL_NO = B.ORDER_MATERIAL AND A.BU = B.BU
)X
)Y GROUP BY MATERIAL_NO, BU,  SUMM,  SCHEDULED_QTY, SCHEDULED_DATE_PD
),

DEMAND_VALUE AS (
SELECT ORDER_MATERIAL, SUM(DEMAND_VALUE) AS DEMAND_VALUE, SUM(DEMAND_QTY) AS DEMAND_QTY, KATR6
FROM (
SELECT DISTINCT
ORDER_NO,
SOLD_TO_DEALER_OR_DISTRIBUTOR,
ORDER_MATERIAL,ORDER_DATE, ITEM,
(GROSS_ORDER_AMOUNT) AS DEMAND_VALUE,
(ORDER_QUANTITY) AS DEMAND_QTY,
KATR6
FROM VW_SPARES_ICMC_ODI_DATA A
LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 CM ON A.SOLD_TO_DEALER_OR_DISTRIBUTOR=CM.KUNNR
WHERE SALES_ORGANIZATION='ZDOM' AND ORDER_DIVISION='B1'  AND DISTRIBUTION_CHANNEL IN (10,20)  
AND ORDER_TYPE IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPSH','ZPVR','ZSPD','ZSPD')
AND ORDER_REJECTION_REASON IN ('','A1') AND KATR6 IN ('2WH')
AND ORDER_DATE BETWEEN @StartDate AND @CurrentDate
)X GROUP BY ORDER_MATERIAL, KATR6
),

SUPPLY_VALUE AS (
SELECT SUM(INVOICE_QTY) AS SUPPLY_QTY, INVOICE_MATERIAL, BU FROM (
SELECT SUM(ACTUAL_BILLED_QTY) AS INVOICE_QTY, SOLD_TO_DEALER_OR_DISTRIBUTOR, BILLING_DATE, BU, INVOICE_MATERIAL
FROM  (
SELECT DISTINCT A.ORDER_NO, A.INVOICE_ITEM, A.INVOICE_MATERIAL, A.INVOICE_NUMBER, A.ACTUAL_BILLED_QTY, A.SOLD_TO_DEALER_OR_DISTRIBUTOR, A.BILLING_DATE, A.DISTRIBUTION_CHANNEL,
CASE WHEN CM.KATR6='2WH' THEN '2W'
     WHEN CM.KATR6='3WH' THEN '3W'
     ELSE NULL END AS BU
FROM VW_SPARES_ICMC_ODI_DATA A
LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 CM ON A.SOLD_TO_DEALER_OR_DISTRIBUTOR=CM.KUNNR 
WHERE A.SALES_ORGANIZATION='ZDOM' AND A.INVOICE_DIVISION='B1'  AND A.DISTRIBUTION_CHANNEL IN (10,20)  
AND A.BILLING_TYPE_ANALYTICS IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPSH','ZPVR','ZSPD','ZSPD') 
AND A.BILLING_DATE IS NOT NULL AND CM.KATR6 IN ('2WH') AND FKSTO<>'X'
AND BILLING_DATE BETWEEN @StartDate AND @CurrentDate
)P GROUP BY SOLD_TO_DEALER_OR_DISTRIBUTOR,BILLING_DATE,BU, INVOICE_MATERIAL
)Q GROUP BY INVOICE_MATERIAL, BU
),

CTE_PART_MASTER AS (
SELECT [MATERIAL] AS PART_CODE, CATEGORY, BU
FROM SPARES_ICMC_WH_PART_MASTER 
WHERE BU='2W'
),

CTE_PROC AS (
    SELECT
       DISTINCT R.ORDER_MATERIAL,
	   R.BU,
        RANKING,
        UPPER(P.CATEGORY) AS PCATEGORY,
        NO_OF_VENDORS,
        null as VENDOR_NAME,
        MATERIAL_DESC,
        NULL AS BUYER_NAME,
        PD_PER_MAT AS PD_QTY,
        DEMAND_QTY,
        MAD_QTY,
        S.SCHEDULED_QTY,
        GR_QTY,
        STOCK_QTY,
        B.BACKORDER_QTY,
		SUPPLY_QTY,
		FB.BO_FIRSTOFMONTH_QTY,
        (PD_PER_MAT * MAT_VALUE_PER_QTY) AS PD_VALUE,
        (DEMAND_QTY * MAT_VALUE_PER_QTY) AS DEMAND_VALUE,
        B.BO_VALUE,
        (S.SCHEDULED_QTY * MAT_VALUE_PER_QTY) AS SCH_VALUE,
        (GR_QTY * MAT_VALUE_PER_QTY) AS GR_VALUE,
        (STOCK_QTY * MAT_VALUE_PER_QTY) AS STOCK_VALUE,
		(SUPPLY_QTY * MAT_VALUE_PER_QTY) AS SUPPLY_VALUE,
        (MAD_QTY * MAT_VALUE_PER_QTY) AS MAD_VALUE,
        PUTAWAY_QTY,
        (PUTAWAY_QTY * MAT_VALUE_PER_QTY) AS PUTAWAY_VALUE,
        SF.STOCK_FIRSTOFMONTH,
        FB.BO_FIRSTOFMONTH,
        CASE WHEN (S.SCHEDULED_QTY * MAT_VALUE_PER_QTY) >= ((DEMAND_QTY * MAT_VALUE_PER_QTY) + FB.BO_FIRSTOFMONTH) THEN 1  ELSE 0 END AS SCHEDULE_SUFFICIENCY,
        CASE WHEN (GR_QTY * MAT_VALUE_PER_QTY) >= ((DEMAND_QTY * MAT_VALUE_PER_QTY) + FB.BO_FIRSTOFMONTH)  THEN 1 ELSE 0 END AS GRN_SUFFICIENCY,
        CASE WHEN (STOCK_QTY * MAT_VALUE_PER_QTY) >= FB.BO_FIRSTOFMONTH THEN 1 ELSE 0 END AS STOCK_SUFFICIENCY,
        CASE WHEN (PUTAWAY_QTY * MAT_VALUE_PER_QTY) >= ((DEMAND_QTY * MAT_VALUE_PER_QTY) + FB.BO_FIRSTOFMONTH) THEN 1 ELSE 0 END AS PUTAWAY_SUFFICIENCY,
        CASE WHEN (SUPPLY_QTY * MAT_VALUE_PER_QTY) >= ((DEMAND_QTY * MAT_VALUE_PER_QTY) + FB.BO_FIRSTOFMONTH) THEN 1 ELSE 0 END AS SUPPLY_SUFFICIENCY
    FROM RANK_ITEMS R
    LEFT JOIN DEMAND_VALUE V ON R.ORDER_MATERIAL = V.ORDER_MATERIAL AND R.BU=LEFT(V.KATR6,2)	
    LEFT JOIN MAT_VALUE_PER_QTY U ON R.ORDER_MATERIAL = U.ORDER_MATERIAL AND R.BU=U.BU
	LEFT JOIN SUPPLY_VALUE SV ON R.ORDER_MATERIAL = SV.INVOICE_MATERIAL AND R.BU = SV.BU
    LEFT JOIN STOCK_1ST_OF_MONTH SF ON R.ORDER_MATERIAL = SF.ORDER_MATERIAL
    LEFT JOIN BACKORDER_1ST_OF_MONTH FB ON R.ORDER_MATERIAL = FB.ORDER_MATERIAL AND R.BU = FB.BU
    LEFT JOIN BACKORDER B ON R.ORDER_MATERIAL = B.ORDER_MATERIAL AND R.BU=B.BU
    LEFT JOIN SCHEDULE S ON R.ORDER_MATERIAL = S.ORDER_MATERIAL --AND R.BU=S.BU
    LEFT JOIN GOODS_RECEIPT G ON R.ORDER_MATERIAL = G.ORDER_MATERIAL --AND R.BU=G.BU
    LEFT JOIN ATP A ON R.ORDER_MATERIAL = A.ORDER_MATERIAL
    LEFT JOIN PUT_AWAY E ON R.ORDER_MATERIAL = E.ORDER_MATERIAL AND R.BU = LEFT(E.BU,2)
    LEFT JOIN MAD M ON R.ORDER_MATERIAL = M.ORDER_MATERIAL
    LEFT JOIN CTE_PART_MASTER P ON R.ORDER_MATERIAL = P.[PART_CODE] AND R.BU=P.BU
    LEFT JOIN CTE_PD_QTY Q ON R.ORDER_MATERIAL = Q.MATERIAL_NO AND R.BU = Q.BU
	WHERE R.BU IN ('2W')
) --SELECT * FROM CTE_PROC
 

INSERT INTO [ASM_ICMC_SPARES_WAREHOUSE_BO_FACT]
(
RANKING,
ORDER_MATERIAL,
PCATEGORY,
NO_OF_VENDORS,
VENDOR_NAME,
MATERIAL_DESC,
BUYER_NAME,
PD_QTY,
DEMAND_QTY,
MAD_QTY,
SCHEDULED_QTY,
GR_QTY,
STOCK_QTY,
BACKORDER_QTY,
PD_VALUE,
DEMAND_VALUE,
BO_VALUE,
SCH_VALUE,
GR_VALUE,
STOCK_VALUE,
MAD_VALUE,
PUTAWAY_QTY,
PUTAWAY_VALUE,
SUPPLY_VALUE,
STOCK_FIRSTOFMONTH,
BO_FIRSTOFMONTH,
SCHEDULE_SUFFICIENCY,
GRN_SUFFICIENCY,
STOCK_SUFFICIENCY,
PUTAWAY_SUFFICIENCY,
SUPPLY_SUFFICIENCY,
BU,
SUPPLY_QTY,
BO_FIRSTOFMONTH_QTY
)

SELECT DISTINCT
RANKING,
ORDER_MATERIAL,
PCATEGORY,
NO_OF_VENDORS,
VENDOR_NAME,
MATERIAL_DESC,
BUYER_NAME,
PD_QTY,
DEMAND_QTY,
MAD_QTY,
SCHEDULED_QTY,
GR_QTY,
STOCK_QTY,
BACKORDER_QTY,
PD_VALUE,
DEMAND_VALUE,
BO_VALUE,
SCH_VALUE,
GR_VALUE,
STOCK_VALUE,
MAD_VALUE,
PUTAWAY_QTY,
PUTAWAY_VALUE,
SUPPLY_VALUE,
STOCK_FIRSTOFMONTH,
BO_FIRSTOFMONTH,
SCHEDULE_SUFFICIENCY,
GRN_SUFFICIENCY,
STOCK_SUFFICIENCY,
PUTAWAY_SUFFICIENCY,
SUPPLY_SUFFICIENCY,
BU,
SUPPLY_QTY,
BO_FIRSTOFMONTH_QTY
FROM CTE_PROC;

PRINT('BackOrder Analysis for 2W and 3W has been loaded successfully')

END
GO