SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_ASM_SPARES_ICMC_RETAIL_FULLLOAD]
AS
BEGIN
/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|CHANGE DESCRIPTION			                            */
/*--------------------------------------------------------------------------------------------------*/
/*	2025-01-03 	|	 	Aswani	  |        Initiation of the SP                             */ 
/*	2025-06-30	|		Aswani	  |		   Updated the BU column from company_master to             */ 
/*										   SAP_CUSTOMER_MASTER_KNA1									*/ 
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*******************************************HISTORY**************************************************/


PRINT('LOADING DATA FROM Source TABLE')
TRUNCATE TABLE [dbo].[ASM_ICMC_SPARES_RETAIL_SALES_STG];


---------------------------------------------------*RETAIL_SCREEN_DATA_LOAD*---------------------------------------------------
WITH RETAILER_MASTER AS (
SELECT C.CODE as SOLD_TO_DEALER_DISTRIBUTOR, 
CAST(A.FROMDATE AS DATE) as DATE_OF_ADDITION, 
A.TODATE as EXIT_DATE, 
B.CODE as RETAILER_CODE,
CASE WHEN B.GSTNumber IS NOT NULL AND TRIM(B.GSTNumber)<>''  THEN B.GSTNumber
     WHEN (B.GSTNumber IS NULL AND TRIM(B.GSTNumber)='') OR (B.PANCARDNO IS NOT NULL AND TRIM(B.PANCARDNO)<>'') THEN B.PANCARDNO
     WHEN (B.GSTNumber IS NULL AND TRIM(B.GSTNumber)='') AND (B.PANCARDNO IS NULL AND TRIM(B.PANCARDNO)='') OR (B.AADHARNO IS NOT NULL and TRIM(B.AADHARNO)<>'') THEN B.AADHARNO
     ELSE NULL END AS GOVT_ID
FROM CDMS_RETAILER_DATA A
LEFT JOIN  CONTACT_MASTER B ON A.CONTACTID = B.CONTACTID AND A.CONTACTIDENTIFIER = B.CONTACTIDENTIFIER
LEFT JOIN COMPANY_MASTER C on A.GCOMPANYID = C.COMPANYID
WHERE UPPER(A.CONTACTIDENTIFIER) IN ('RETAILER','CUSTOMER') AND UPPER(B.CONTACTIDENTIFIER) IN ('RETAILER','CUSTOMER')
AND A.TODATE IS NULL
),

RMTEST AS (
SELECT SOLD_TO_DEALER_DISTRIBUTOR,CONCAT_DLDB_GOVT_ID,KYC_REGISTERED,RETAILER_CODE,DATE_OF_ADDITION 
FROM (
SELECT SOLD_TO_DEALER_DISTRIBUTOR, CONCAT_DLDB_GOVT_ID,KYC_REGISTERED,RETAILER_CODE,DATE_OF_ADDITION,RANK() OVER(PARTITION BY SOLD_TO_DEALER_DISTRIBUTOR,RETAILER_CODE ORDER BY CONCAT_DLDB_GOVT_ID) as RANK1
FROM (
SELECT DISTINCT SOLD_TO_DEALER_DISTRIBUTOR,
       RETAILER_CODE,
       CONCAT(SOLD_TO_DEALER_DISTRIBUTOR,'_',GOVT_ID) AS CONCAT_DLDB_GOVT_ID,
       DATE_OF_ADDITION,
       CASE WHEN GOVT_ID IS NULL THEN '0' ELSE '1' END AS KYC_REGISTERED
       FROM RETAILER_MASTER M
  ) L WHERE KYC_REGISTERED=1
  ) P WHERE RANK1=1
),


GOV_ID_CONTACT_MASTER AS (
SELECT CODE, GOVT_ID
FROM (
SELECT CODE, GOVT_ID, RANK() OVER(PARTITION BY CODE ORDER BY GOVT_ID) as RNK 
FROM (
SELECT DISTINCT CODE, CASE WHEN B.GSTNumber IS NOT NULL AND TRIM(B.GSTNumber)<>''  THEN B.GSTNumber
     WHEN (B.GSTNumber IS NULL AND TRIM(B.GSTNumber)='') OR (B.PANCARDNO IS NOT NULL AND TRIM(B.PANCARDNO)<>'') THEN B.PANCARDNO
     WHEN (B.GSTNumber IS NULL AND TRIM(B.GSTNumber)='') AND (B.PANCARDNO IS NULL AND TRIM(B.PANCARDNO)='') OR (B.AADHARNO IS NOT NULL and TRIM(B.AADHARNO)<>'') THEN B.AADHARNO
     ELSE NULL END AS GOVT_ID
FROM CONTACT_MASTER B
WHERE UPPER(B.CONTACTIDENTIFIER) IN ('RETAILER','CUSTOMER') ) CMI
WHERE GOVT_ID is not null) A
WHERE RNK = 1),

CTE_CAL AS (
SELECT COMPANYCODE,BU,DOCDATE_SALES,CONTACTCODE,
KYC_REGISTERED,RETAIL_SALES,NEW_RETAILER_ADDED,CONCAT_WITH_GOVT_ID FROM
(
SELECT 
RSALES.COMPANYCODE,
RSALES.BU,
RSALES.DOCDATE_SALES,
RSALES.CONTACT_CODE as CONTACTCODE,
CASE WHEN GOV_CM.GOVT_ID is null THEN 0
	ELSE 1 END as KYC_REGISTERED,
RSALES.RETAIL_SALES,
NULL AS NEW_RETAILER_ADDED,
CASE WHEN GOV_CM.GOVT_ID is null THEN null
ELSE CONCAT(RSALES.COMPANYCODE,'_',GOV_CM.GOVT_ID) END as CONCAT_WITH_GOVT_ID
FROM 
ASM_ICMC_SPARES_RETSALES_STG RSALES
LEFT JOIN GOV_ID_CONTACT_MASTER GOV_CM 
ON RSALES.CONTACT_CODE=GOV_CM.CODE
where RSALES.BU IN ('2W','3W') 
) A
)

INSERT INTO [dbo].[ASM_ICMC_SPARES_RETAIL_SALES_STG]
(
    [SOLD_TO_DEALER_OR_DISTRIBUTOR],
    [BU],
       [RETAILER_CODE],
    [TOTAL_AMOUNT],
    [NEW_RETAILER_ADDITION_ACTUAL],
       [KYC_REGISTERED],
    [IMPORTED_DATE],
       [CONCAT_WITH_GOVT_ID],
       [FLAG],
       [CREATE_DATE]
)

SELECT 
COMPANYCODE,
BU,
CONTACTCODE AS CONTACT_CODE,
(RETAIL_SALES) AS RETAIL_SALES,
(NEW_RETAILER_ADDED) AS NEW_RETAILER_ADDED,
(KYC_REGISTERED) AS KYC_REGISTERED,
(DOCDATE_SALES) AS [IMPORTED_DATE],
CONCAT_WITH_GOVT_ID,
'SALES' AS FLAG,
CAST(GETDATE() AS DATE) AS CREATE_DATE
FROM CTE_CAL
where COMPANYCODE >= '0000015000' AND COMPANYCODE <='0000018000';

----------------------------------------------------NEW RETAILER ADDITION ADDED--------------------------------------------

WITH RETAILER_MASTER AS (
SELECT C.CODE as SOLD_TO_DEALER_DISTRIBUTOR, 
CAST(A.FROMDATE AS DATE) as DATE_OF_ADDITION, 
A.TODATE as EXIT_DATE, 
B.CODE as RETAILER_CODE,
CASE WHEN B.GSTNumber IS NOT NULL AND TRIM(B.GSTNumber)<>''  THEN B.GSTNumber
     WHEN (B.GSTNumber IS NULL AND TRIM(B.GSTNumber)='') OR (B.PANCARDNO IS NOT NULL AND TRIM(B.PANCARDNO)<>'') THEN B.PANCARDNO
     WHEN (B.GSTNumber IS NULL AND TRIM(B.GSTNumber)='') AND (B.PANCARDNO IS NULL AND TRIM(B.PANCARDNO)='') OR (B.AADHARNO IS NOT NULL and TRIM(B.AADHARNO)<>'') THEN B.AADHARNO
     ELSE NULL END AS GOVT_ID
FROM CDMS_RETAILER_DATA A
LEFT JOIN  CONTACT_MASTER B ON A.CONTACTID = B.CONTACTID AND A.CONTACTIDENTIFIER = B.CONTACTIDENTIFIER
LEFT JOIN COMPANY_MASTER C on A.GCOMPANYID = C.COMPANYID
WHERE UPPER(A.CONTACTIDENTIFIER) IN ('RETAILER','CUSTOMER') AND UPPER(B.CONTACTIDENTIFIER) IN ('RETAILER','CUSTOMER')
AND A.TODATE IS NULL
),

RMTEST AS (
SELECT SOLD_TO_DEALER_DISTRIBUTOR,CONCAT_DLDB_GOVT_ID,KYC_REGISTERED,RETAILER_CODE,DATE_OF_ADDITION 
FROM (
SELECT SOLD_TO_DEALER_DISTRIBUTOR, CONCAT_DLDB_GOVT_ID,KYC_REGISTERED,RETAILER_CODE,DATE_OF_ADDITION,RANK() OVER(PARTITION BY SOLD_TO_DEALER_DISTRIBUTOR,RETAILER_CODE ORDER BY CONCAT_DLDB_GOVT_ID) as RANK1
FROM (
SELECT DISTINCT SOLD_TO_DEALER_DISTRIBUTOR,
       RETAILER_CODE,
       CONCAT(SOLD_TO_DEALER_DISTRIBUTOR,'_',GOVT_ID) AS CONCAT_DLDB_GOVT_ID,
       DATE_OF_ADDITION,
       CASE WHEN GOVT_ID IS NULL THEN '0' ELSE '1' END AS KYC_REGISTERED
       FROM RETAILER_MASTER M
  ) L WHERE KYC_REGISTERED=1
  ) P WHERE RANK1=1
),


GOV_ID_CONTACT_MASTER AS (
SELECT CODE, GOVT_ID
FROM (
SELECT CODE, GOVT_ID, RANK() OVER(PARTITION BY CODE ORDER BY GOVT_ID) as RNK 
FROM (
SELECT DISTINCT CODE, CASE WHEN B.GSTNumber IS NOT NULL AND TRIM(B.GSTNumber)<>''  THEN B.GSTNumber
     WHEN (B.GSTNumber IS NULL AND TRIM(B.GSTNumber)='') OR (B.PANCARDNO IS NOT NULL AND TRIM(B.PANCARDNO)<>'') THEN B.PANCARDNO
     WHEN (B.GSTNumber IS NULL AND TRIM(B.GSTNumber)='') AND (B.PANCARDNO IS NULL AND TRIM(B.PANCARDNO)='') OR (B.AADHARNO IS NOT NULL and TRIM(B.AADHARNO)<>'') THEN B.AADHARNO
     ELSE NULL END AS GOVT_ID
FROM CONTACT_MASTER B
WHERE UPPER(B.CONTACTIDENTIFIER) IN ('RETAILER','CUSTOMER') ) CMI
WHERE GOVT_ID is not null) A
WHERE RNK = 1),

NEW_RETAILER_ADDITION AS (
SELECT SOLD_TO_DEALER_DISTRIBUTOR, BU,RETAILER_DATE, NEW_RETAILER_ADDED,RETAILER_CODE,KYC_REGISTERED FROM
(
    SELECT  SOLD_TO_DEALER_DISTRIBUTOR, CONCAT_DLDB_GOVT_ID AS NEW_RETAILER_ADDED, DATE_OF_ADDITION AS RETAILER_DATE,RETAILER_CODE,KYC_REGISTERED,
    CASE
    WHEN CM.KATR6='2WH' THEN '2W'
    WHEN CM.KATR6='3WH' THEN '3W'
        ELSE NULL END AS BU
    FROM RMTEST A
    LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 CM ON A.SOLD_TO_DEALER_DISTRIBUTOR=CM.KUNNR
    WHERE CM.KATR6 IN ('2WH','3WH')
       ) R
),

CTE_NEW_RET_ADD AS (
SELECT 
RADD.SOLD_TO_DEALER_DISTRIBUTOR AS COMPANYCODE,
RADD.BU AS BU,
RADD.RETAILER_DATE AS DOCDATE_SALES,
RADD.RETAILER_CODE AS CONTACTCODE,
CASE WHEN GOV_CM.GOVT_ID is null THEN 0
	ELSE 1 END as KYC_REGISTERED,
NULL AS RETAIL_SALES,
RADD.NEW_RETAILER_ADDED,
CASE WHEN GOV_CM.GOVT_ID is null THEN null
ELSE CONCAT(RADD.SOLD_TO_DEALER_DISTRIBUTOR,'_',GOV_CM.GOVT_ID) END as CONCAT_WITH_GOVT_ID
FROM NEW_RETAILER_ADDITION RADD
LEFT JOIN GOV_ID_CONTACT_MASTER GOV_CM 
ON RADD.RETAILER_CODE=GOV_CM.CODE
WHERE RADD.BU IN ('2W','3W') 
AND RADD.RETAILER_DATE>= '2022-04-01'
)

INSERT INTO [dbo].[ASM_ICMC_SPARES_RETAIL_SALES_STG]
(
    [SOLD_TO_DEALER_OR_DISTRIBUTOR],
    [BU],
       [RETAILER_CODE],
    [TOTAL_AMOUNT],
    [NEW_RETAILER_ADDITION_ACTUAL],
       [KYC_REGISTERED],
    [IMPORTED_DATE],
       [CONCAT_WITH_GOVT_ID],
       [FLAG],
       [CREATE_DATE]
)

SELECT 
COMPANYCODE,
BU,
(CONTACTCODE) AS CONTACT_CODE,
(RETAIL_SALES) AS RETAIL_SALES,
(NEW_RETAILER_ADDED) AS NEW_RETAILER_ADDED,
(KYC_REGISTERED) AS KYC_REGISTERED,
(DOCDATE_SALES) AS [IMPORTED_DATE],
CONCAT_WITH_GOVT_ID,
'NEW_RET' AS FLAG,
CAST(GETDATE() AS DATE) AS CREATE_DATE
FROM CTE_NEW_RET_ADD
where COMPANYCODE >= '0000015000' AND COMPANYCODE <='0000018000';

-------------------------------------DE-DUP SALES
WITH CTE AS                  
(                  
  SELECT *,                  
   DENSE_RANK()OVER(PARTITION BY SOLD_TO_DEALER_OR_DISTRIBUTOR,IMPORTED_DATE,RETAILER_CODE ORDER BY IMPORTED_DATE DESC)RNK                  
  FROM [ASM_ICMC_SPARES_RETAIL_SALES_STG] WHERE FLAG='SALES'          
)          
DELETE FROM CTE                  
WHERE RNK<>1;

-------------------------------------DE-DUP NEW_RET
WITH CTE AS                  
(                  
  SELECT *,                  
   DENSE_RANK()OVER(PARTITION BY SOLD_TO_DEALER_OR_DISTRIBUTOR,IMPORTED_DATE,RETAILER_CODE ORDER BY IMPORTED_DATE DESC)RNK                  
  FROM [ASM_ICMC_SPARES_RETAIL_SALES_STG] WHERE FLAG='NEW_RET'          
)          
DELETE FROM CTE                  
WHERE RNK<>1;

----------------------------------------------DIM TABLE DATA FULL LOAD------------------------------------------------
TRUNCATE TABLE [dbo].[ASM_ICMC_SPARES_RETAIL_SALES_FACT];

INSERT INTO [dbo].[ASM_ICMC_SPARES_RETAIL_SALES_FACT]
(
    [SOLD_TO_DEALER_OR_DISTRIBUTOR],
    [BU],
	[RETAILER_CODE],
    [TOTAL_AMOUNT],
    [NEW_RETAILER_ADDITION_ACTUAL],
	[KYC_REGISTERED],
    [IMPORTED_DATE],
    [CONCAT_WITH_GOVT_ID],
	[CREATE_DATE]
)
 
SELECT 
SOLD_TO_DEALER_OR_DISTRIBUTOR,
    [BU],
	[RETAILER_CODE],
    [TOTAL_AMOUNT],
    [NEW_RETAILER_ADDITION_ACTUAL],
	[KYC_REGISTERED],
    [IMPORTED_DATE],
    [CONCAT_WITH_GOVT_ID],
	CAST(GETDATE() AS DATE) AS CREATE_DATE
FROM [ASM_ICMC_SPARES_RETAIL_SALES_STG];


PRINT('Retail sales data full load is loaded for Retailer screen successfully')



END
GO