SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_ASM_SPARES_ICMC_WAREHOUSE_FULLLOAD]
AS
BEGIN
/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|CHANGE DESCRIPTION			                            */
/*--------------------------------------------------------------------------------------------------*/
/*	2025-03-24 	|	 	Aswani	  |        Initiation of the SP for warehouse                       */
/*	2025-06-30	|		Aswani	  |		   Updated the BU column from company_master to             */ 
/*										   SAP_CUSTOMER_MASTER_KNA1									*/  
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*******************************************HISTORY**************************************************/

PRINT('LOADING DATA FROM Source TABLE')
TRUNCATE TABLE [dbo].[ASM_ICMC_SPARES_WAREHOUSE_DIM];

--------------------------------------------------*GETTING FISCAL YEAR*--------------------------------------------------------------
DECLARE @FY DATE
DECLARE @FISCAL_YEAR DATE
 
SET @FY = GETDATE()

SELECT @FISCAL_YEAR= CAST(FISCAL_YEAR AS DATE) 
FROM (SELECT DISTINCT CAST(CAST(YEAR(@FY)-
 (CASE 
     WHEN MONTH(@FY) BETWEEN 1 AND 3 THEN 3
     ELSE 2
 END) AS VARCHAR)+'0401' AS DATE) AS FISCAL_YEAR FROM VW_SPARES_ICMC_ODI_DATA) AS DERIVED_TABLE;

------------------------------------------------**WH QUERY**-------------------------------------------------

WITH 
FIRSTFILLRATE AS (
SELECT DISTINCT
    O.ORDER_NO, ORDER_MATERIAL,
	CASE WHEN ORDER_QUANTITY = SUM(ACTUAL_BILLED_QTY) AND DELIVERY_DATE = MD.MIN_DELIVERY_DATE THEN 1 ELSE 0 
        END AS FIRST_FILL_RATE_FLAG
FROM (
SELECT DISTINCT
        ORDER_DATE,
        O.ORDER_NO,
        ORDER_MATERIAL,
        ORDER_QUANTITY,
        ACTUAL_BILLED_QTY,
        DELIVERY_NUMBER,
        DELIVERY_DATE 
FROM DBO.VW_SPARES_ICMC_ODI_DATA O
LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 CM ON SOLD_TO_DEALER_OR_DISTRIBUTOR = CM.KUNNR
WHERE SALES_ORGANIZATION = 'ZDOM' AND INVOICE_DIVISION = 'B1' 
AND DISTRIBUTION_CHANNEL IN (10, 20) AND BILLING_TYPE_ANALYTICS IN ('ZSTD', 'ZSCH', 'ZVOR', 'ZPSD', 'ZPVR') 
AND ORDER_PLANT IN ('WA02', 'PT02') AND (GROSS_INVOICE_AMOUNT > 0 OR GROSS_DELIVERY_AMOUNT > 0)
AND ORDER_REJECTION_REASON IN ('', 'A1') AND CM.KATR6 IN ('2WH', '3WH')
) O
JOIN (
SELECT 
      ORDER_NO,
      MIN(DELIVERY_DATE) AS MIN_DELIVERY_DATE
FROM DBO.VW_SPARES_ICMC_ODI_DATA
WHERE INVOICE_DIVISION = 'B1' AND DISTRIBUTION_CHANNEL IN (10, 20)  
AND BILLING_TYPE_ANALYTICS IN ('ZSTD', 'ZSCH', 'ZVOR', 'ZPSD', 'ZPVR') AND ORDER_PLANT IN ('WA02', 'PT02')
AND (GROSS_INVOICE_AMOUNT > 0 OR GROSS_DELIVERY_AMOUNT > 0) AND ORDER_REJECTION_REASON IN ('', 'A1')
GROUP BY ORDER_NO
) MD
ON O.ORDER_NO = MD.ORDER_NO
GROUP BY O.ORDER_NO, ORDER_MATERIAL, ORDER_QUANTITY, DELIVERY_DATE, MD.MIN_DELIVERY_DATE
),

DELIVERYQUANTITIES AS (
SELECT DISTINCT
		ORDER_NO,
		ORDER_MATERIAL,
		SUM(CASE WHEN DATEDIFF(DAY, ORDER_DATE, BILLING_DATE) <= 7 THEN ACTUAL_BILLED_QTY ELSE 0 END) AS SEVEN_DAY_DELIVERY_QTY
FROM (
SELECT DISTINCT ORDER_DATE, ORDER_NO, ORDER_MATERIAL, INVOICE_MATERIAL, INVOICE_NUMBER, ACTUAL_BILLED_QTY, BILLING_DATE
FROM DBO.VW_SPARES_ICMC_ODI_DATA 
WHERE SALES_ORGANIZATION='ZDOM'
AND INVOICE_DIVISION='B1' 
AND DISTRIBUTION_CHANNEL IN (10,20)  
AND BILLING_TYPE_ANALYTICS IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPVR')  
AND ORDER_PLANT IN ('WA02','PT02')
AND (GROSS_INVOICE_AMOUNT > 0 OR GROSS_DELIVERY_AMOUNT > 0)
AND ORDER_REJECTION_REASON IN ('', 'A1')
) A
GROUP BY ORDER_NO, ORDER_MATERIAL
),
 
OD_LEADTIME AS (
SELECT ORDER_NO, ORDER_MATERIAL, DATEDIFF(DAY, ORDER_DATE, DELIVERY_DATE) AS OD_LEAD_TIME FROM (
SELECT DISTINCT
              ORDER_NO,ORDER_MATERIAL,ORDER_DATE,
              MAX(DELIVERY_DATE) AS DELIVERY_DATE
FROM DBO.VW_SPARES_ICMC_ODI_DATA 
WHERE DELIVERY_DATE IS NOT NULL
AND SALES_ORGANIZATION='ZDOM' 
AND INVOICE_DIVISION='B1' 
AND DISTRIBUTION_CHANNEL IN (10,20)  
AND BILLING_TYPE_ANALYTICS IN ('ZSTD', 'ZSCH', 'ZVOR', 'ZPSD', 'ZPVR')
AND ORDER_PLANT IN ('WA02', 'PT02')
AND ORDER_REJECTION_REASON IN ('', 'A1')
GROUP BY ORDER_NO,ORDER_MATERIAL,ORDER_DATE)A
GROUP BY ORDER_NO, ORDER_MATERIAL,ORDER_DATE,DELIVERY_DATE
),
 
DI_LEADTIME AS (
SELECT ORDER_NO, ORDER_MATERIAL, DATEDIFF(DAY, DELIVERY_DATE,BILLING_DATE) AS DI_LEAD_TIME FROM (
SELECT DISTINCT
              ORDER_NO,ORDER_MATERIAL,ORDER_DATE,
              MAX(DELIVERY_DATE) AS DELIVERY_DATE,
              MAX(BILLING_DATE) AS BILLING_DATE
FROM DBO.VW_SPARES_ICMC_ODI_DATA 
WHERE DELIVERY_DATE IS NOT NULL AND BILLING_DATE IS NOT NULL
AND SALES_ORGANIZATION='ZDOM' 
AND INVOICE_DIVISION='B1' 
AND DISTRIBUTION_CHANNEL IN (10,20)  
AND BILLING_TYPE_ANALYTICS IN ('ZSTD', 'ZSCH', 'ZVOR', 'ZPSD', 'ZPVR')
AND ORDER_PLANT IN ('WA02', 'PT02')
AND ORDER_REJECTION_REASON IN ('', 'A1')
GROUP BY ORDER_NO,ORDER_MATERIAL,ORDER_DATE)A
GROUP BY ORDER_NO, ORDER_MATERIAL,DELIVERY_DATE,BILLING_DATE
),

IG_LEADTIME AS (
SELECT ORDER_NO, ORDER_MATERIAL,DATEDIFF(DAY,INVOICE_DATE,GATE_OUT_DATE) AS IG_LEAD_TIME,
INVOICE_DATE,GATE_OUT_DATE FROM (
SELECT  V.ORDER_NO, 
        V.ORDER_MATERIAL,
		MAX(CAST(S.[INVOICE DATE] AS DATE)) AS INVOICE_DATE,
		MAX(CAST(S.[GATE OUT DATE TIME] AS DATE)) AS GATE_OUT_DATE
FROM SSTS_SPARE_SHIPMENT_TRACKING S
INNER JOIN VW_SPARES_ICMC_ODI_DATA V ON S.[DEALER CODE] = V.SOLD_TO_DEALER_OR_DISTRIBUTOR AND
RIGHT('0' + CAST(S.[INVOICE NO] AS VARCHAR), 10) = V.INVOICE_NUMBER
WHERE V.SALES_ORGANIZATION='ZDOM' 
AND V.INVOICE_DIVISION='B1' 
AND V.DISTRIBUTION_CHANNEL IN (10,20)  
AND V.BILLING_TYPE_ANALYTICS IN ('ZSTD', 'ZSCH', 'ZVOR', 'ZPSD', 'ZPVR')
AND V.ORDER_PLANT IN ('WA02', 'PT02')
AND V.ORDER_REJECTION_REASON IN ('', 'A1')
AND S.[SEGMENT] IN ('2WH','3WH') AND CAST(S.[GATE OUT DATE TIME] AS DATE)>=CAST(S.[INVOICE DATE] AS DATE)
GROUP BY V.ORDER_NO,V.ORDER_MATERIAL
)A
GROUP BY ORDER_NO,ORDER_MATERIAL,INVOICE_DATE,GATE_OUT_DATE
),

OI_LEADTIME AS (
SELECT ORDER_NO, ORDER_MATERIAL, DATEDIFF(DAY, ORDER_DATE, BILLING_DATE) AS OI_LEAD_TIME FROM (
SELECT DISTINCT
	ORDER_NO,
    ORDER_MATERIAL,
    ORDER_DATE,
    MAX(BILLING_DATE) AS BILLING_DATE
FROM DBO.VW_SPARES_ICMC_ODI_DATA 
WHERE BILLING_DATE IS NOT NULL
AND SALES_ORGANIZATION='ZDOM' AND INVOICE_DIVISION='B1' AND DISTRIBUTION_CHANNEL IN (10,20)  
AND BILLING_TYPE_ANALYTICS IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPVR')  AND ORDER_PLANT IN ('WA02','PT02')
AND (GROSS_INVOICE_AMOUNT > 0 OR GROSS_DELIVERY_AMOUNT > 0) AND ORDER_REJECTION_REASON IN ('', 'A1')
GROUP BY ORDER_NO,ORDER_MATERIAL,ORDER_DATE)A
GROUP BY ORDER_NO, ORDER_MATERIAL,ORDER_DATE,BILLING_DATE
),

KPI_MATERIAL_FLAG AS (
SELECT DISTINCT ORDER_NO,ORDER_MATERIAL, OTD.ITEM
FROM dbo.VW_SPARES_ICMC_ODI_DATA AS OTD
where OTD.sales_organization='ZDOM' and OTD.invoice_division='B1'  and OTD.distribution_channel in (10,20)  
and otd.billing_type_analytics in ('ZSTD','ZSCH','ZVOR','ZPSD','ZPVR','ZSPD')
and OTD.order_rejection_reason in ('', 'A1')  AND ORDER_PLANT in ('WA02','PT02')
),

ORDER_DATA AS (
SELECT DISTINCT
ORDER_NO,
ITEM,
ORDER_DATE,
ORDER_MATERIAL,
ORDER_QUANTITY,
GROSS_ORDER_AMOUNT,
SOLD_TO_DEALER_OR_DISTRIBUTOR,
DISTRIBUTION_CHANNEL,
ORDER_PLANT,
BU,
ORDER_TYPE
FROM (
SELECT 
	ORDER_NO,
	ITEM,
	ORDER_DATE,
	ORDER_MATERIAL,
	ORDER_QUANTITY,
	GROSS_ORDER_AMOUNT,
	ORDER_CHANGE_DATE, 
	ORDER_VBAP_DATALOADTIME,
	ORDER_TYPE,
	SALES_ORGANIZATION,
	ORDER_DIVISION,
	ORDER_REJECTION_REASON,
	DISTRIBUTION_CHANNEL,
	ORDER_CANCELLATION, ORDER_PLANT,
	A.SOLD_TO_DEALER_OR_DISTRIBUTOR,
	CASE WHEN CM.KATR6='2WH' THEN '2W'
     WHEN CM.KATR6='3WH' THEN '3W'
     ELSE NULL END AS BU,
	ROW_NUMBER() OVER( PARTITION BY ORDER_NO,ITEM ORDER BY ORDER_CHANGE_DATE DESC, ORDER_VBAP_DATALOADTIME DESC, ORDER_VBAK_DATALOADTIME DESC) as RNK
	FROM VW_SPARES_ICMC_ODI_DATA A 
	LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 CM ON A.SOLD_TO_DEALER_OR_DISTRIBUTOR=CM.KUNNR
	WHERE  CM.KATR6 IN ('2WH','3WH') 
	and DISTRIBUTION_CHANNEL IN (10,20) AND SALES_ORGANIZATION='ZDOM' AND ORDER_DIVISION='B1' 
	AND ORDER_TYPE IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPSH','ZPVR','ZSPD','ZSPD')
	) A
WHERE RNK = 1 AND ORDER_REJECTION_REASON IN ('','A1')
),

CTE_PRE AS (
SELECT FINAL_GROUP, ORDER_DATE, ORDER_NO, ORDER_MATERIAL, ORDER_TYPE, ORDER_PLANT, SOLD_TO_DEALER_OR_DISTRIBUTOR, DLDB_CODE, CHANNEL, BU, 
CASE WHEN KPI_FLAG=1 THEN 1 ELSE 0 END AS KPI_MATERIAL_COUNT, FFR, ODLT, DILT, IGLT, OILT, SFR FROM ( 
    SELECT DISTINCT
        UPPER(P.CATEGORY) AS FINAL_GROUP,
        O.ORDER_DATE,
        O.ORDER_NO,
        O.ORDER_MATERIAL,
        O.ORDER_TYPE,
        O.ORDER_PLANT,
		O.SOLD_TO_DEALER_OR_DISTRIBUTOR,
        CASE WHEN DISTRIBUTION_CHANNEL = '10' AND O.BU='2W' THEN '99999_MC'
             WHEN DISTRIBUTION_CHANNEL = '10' AND O.BU='3W' THEN '99999_IC'
             ELSE O.SOLD_TO_DEALER_OR_DISTRIBUTOR END AS DLDB_CODE,
        CASE WHEN DISTRIBUTION_CHANNEL = '10' THEN 'DEALER'
             WHEN DISTRIBUTION_CHANNEL = '20' THEN 'DISTRIBUTOR' 
             END AS CHANNEL,
        O.BU,
        CASE WHEN O.ORDER_NO=KPI.ORDER_NO AND O.ORDER_MATERIAL=KPI.ORDER_MATERIAL AND O.ITEM=KPI.ITEM THEN 1 ELSE 0
			END AS KPI_FLAG,
        (F.FIRST_FILL_RATE_FLAG) AS FFR,
        (L.OD_LEAD_TIME) AS ODLT,
        (D.DI_LEAD_TIME) AS DILT,
        (I.IG_LEAD_TIME) AS IGLT,
        (OI.OI_LEAD_TIME) AS OILT,
        CASE WHEN O.ORDER_QUANTITY = DQ.SEVEN_DAY_DELIVERY_QTY THEN 1 ELSE 0 END AS [SFR]
    FROM ORDER_DATA O
    LEFT JOIN SPARES_ICMC_WH_PART_MASTER P ON O.ORDER_MATERIAL = P.MATERIAL AND O.BU=P.BU
    LEFT JOIN FIRSTFILLRATE F ON O.ORDER_NO = F.ORDER_NO AND O.ORDER_MATERIAL = F.ORDER_MATERIAL
    LEFT JOIN DELIVERYQUANTITIES DQ ON O.ORDER_NO = DQ.ORDER_NO AND O.ORDER_MATERIAL = DQ.ORDER_MATERIAL
    LEFT JOIN OD_LEADTIME L ON O.ORDER_NO = L.ORDER_NO AND O.ORDER_MATERIAL = L.ORDER_MATERIAL
    LEFT JOIN DI_LEADTIME D ON O.ORDER_NO = D.ORDER_NO AND O.ORDER_MATERIAL = D.ORDER_MATERIAL
    LEFT JOIN IG_LEADTIME I ON O.ORDER_NO = I.ORDER_NO AND O.ORDER_MATERIAL = I.ORDER_MATERIAL
    LEFT JOIN OI_LEADTIME OI ON O.ORDER_NO = OI.ORDER_NO AND O.ORDER_MATERIAL = OI.ORDER_MATERIAL
	LEFT JOIN KPI_MATERIAL_FLAG KPI ON O.ORDER_NO = KPI.ORDER_NO AND O.ORDER_MATERIAL = KPI.ORDER_MATERIAL AND O.ITEM = KPI.ITEM
)A
),
 
CTE_CAL AS (
    SELECT
    FINAL_GROUP,
    ORDER_DATE,
    ORDER_TYPE,
    ORDER_PLANT,
	SOLD_TO_DEALER_OR_DISTRIBUTOR,
    SUBSTRING(DLDB_CODE, PATINDEX('%[^0 ]%', DLDB_CODE + ' '),LEN(DLDB_CODE)) AS DL_DB_CODE,
	CHANNEL,
    BU,
    SUM(FFR) AS FFR_SUM,
    SUM(SFR) AS SFR_SUM,
    SUM(ODLT) AS ODLT_SUM,
    SUM(DILT) AS DILT_SUM,
    SUM(IGLT) AS IGLT_SUM,
    SUM(OILT) AS OILT_SUM,
    COUNT(ORDER_MATERIAL) AS MATERIAL_COUNT,
    SUM(KPI_MATERIAL_COUNT) AS KPI_MATERIAL_COUNT
    FROM CTE_PRE
	WHERE ORDER_DATE >= @FISCAL_YEAR
    GROUP BY FINAL_GROUP,DLDB_CODE,CHANNEL,BU,ORDER_DATE,ORDER_TYPE, ORDER_PLANT,SOLD_TO_DEALER_OR_DISTRIBUTOR
) 

INSERT INTO [ASM_ICMC_SPARES_WAREHOUSE_DIM]
(
[SOLD_TO_DEALER_OR_DISTRIBUTOR],
[PRODUCT_CATEGORY],
[ORDER_DATE],
[ORDER_TYPE],
[DL_DB_CODE],
[CHANNEL],
[BU],
[FIRST_FILL_RATE_FLAG],
[7_DAY_FILL_RATE_FLAG],
[ORDER_DELIVERY_LEAD_TIME],
[DELIVERY_INVOICE_LEAD_TIME],
[INVOICE_GATEOUT_LEAD_TIME],
[ORDER_INVOICE_LEAD_TIME],
[MATERIAL_COUNT],
[ORDER_PLANT],
[KPI_MATERIAL_COUNT]
)
 
SELECT 
[SOLD_TO_DEALER_OR_DISTRIBUTOR],
FINAL_GROUP AS PRODUCT_CATEGORY,
ORDER_DATE,
ORDER_TYPE,
DL_DB_CODE,
CHANNEL,
BU,
FFR_SUM AS FIRST_FILL_RATE_FLAG,
SFR_SUM AS [7_DAY_FILL_RATE_FLAG],
ODLT_SUM AS ORDER_DELIVERY_LEAD_TIME,
DILT_SUM AS DELIVERY_INVOICE_LEAD_TIME,
IGLT_SUM AS INVOICE_GATEOUT_LEAD_TIME,
OILT_SUM AS ORDER_INVOICE_LEAD_TIME,
MATERIAL_COUNT,
ORDER_PLANT,
KPI_MATERIAL_COUNT
FROM CTE_CAL;


--------------------------------------------------------**DELIVERY DATA---------------------------------------------------------

WITH DELIVERY_DATA AS (
SELECT DISTINCT DELIVERY_ITEM,
DELIVERY_NUMBER, DELIVER_MATERIAL,
A.DELIVERY_DATE,
A.GROSS_DELIVERY_AMOUNT,
CASE WHEN A.DISTRIBUTION_CHANNEL = '10' AND CM.KATR6 = '2WH' THEN '99999_MC'
     WHEN A.DISTRIBUTION_CHANNEL = '10' AND CM.KATR6 = '3WH' THEN '99999_IC'
     ELSE A.SOLD_TO_DEALER_OR_DISTRIBUTOR END AS DL_DB_CODE,
CASE WHEN A.DISTRIBUTION_CHANNEL = '10' THEN 'DEALER'
     WHEN A.DISTRIBUTION_CHANNEL = '20' THEN 'DISTRIBUTOR' END AS CHANNEL,
CASE WHEN CM.KATR6='2WH' THEN 'MC'
	 WHEN CM.KATR6='3WH' THEN 'IC' ELSE NULL END AS BU
FROM VW_SPARES_ICMC_ODI_DATA A
LEFT JOIN SAP_CUSTOMER_MASTER_KNA1 CM ON A.SOLD_TO_DEALER_OR_DISTRIBUTOR=CM.KUNNR
WHERE A.DISTRIBUTION_CHANNEL IN (10,20)
AND A.BILLING_TYPE_ANALYTICS IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPSH','ZPVR','ZSPD')
AND CM.KATR6 IN ('3WH', '2WH')
),

CTE_CAL AS (
SELECT 
DL_DB_CODE,
CHANNEL,
DELIVERY_DATE,
BU,
SUM(GROSS_DELIVERY_AMOUNT) AS DELIVERY_AMOUNT
FROM DELIVERY_DATA
WHERE DELIVERY_DATE >= @FISCAL_YEAR
GROUP BY DL_DB_CODE, CHANNEL, DELIVERY_DATE, BU
)

INSERT INTO ASM_ICMC_SPARES_DELIVERY_DATA_DIM
(
DL_DB_CODE,
CHANNEL,
DELIVERY_DATE,
BU,
DELIVERY_AMOUNT
)

SELECT
SUBSTRING(DL_DB_CODE,PATINDEX('%[^0 ]%', DL_DB_CODE + ' '),LEN(DL_DB_CODE)) AS DL_DB_CODE,
CHANNEL,
DELIVERY_DATE,
BU,
DELIVERY_AMOUNT
FROM CTE_CAL;

PRINT('Warehouse data has been loaded successfully')

END
GO