
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Alter PROC [dbo].[USP_ASM_SPARES_ICMC_WH_MAD_VALUE]
AS
BEGIN
/*******************************************HISTORY**************************************************/
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*    DATE   	|	CREATED/MODIFIED BY		|CHANGE DESCRIPTION			                            */
/*--------------------------------------------------------------------------------------------------*/
/*	2025-03-24 	|	 	Aswani	  |        Initiation of the SP for warehouse                       2025-09-25 	|	 	Richa	  |    Datatype cast Change in Gross order amout column        */  
/*--------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------*/
/*******************************************HISTORY**************************************************/

PRINT('LOADING DATA FROM Source TABLE')
TRUNCATE TABLE [dbo].[ASM_ICMC_SPARES_WH_MAD_VALUE];

------------------------------------------------------------------------------------------------------------

DECLARE @CurrentDate DATE = GETDATE();
DECLARE @StartDate DATE = DATEADD(MONTH, -7, @CurrentDate);

-------------------------------------------MAD CALCULATION MAIN----------------------------------------------
WITH VVBASE AS 
(
SELECT ORDER_MATERIAL, ORDER_PLANT, ORDER_DATE, ORDER_STORAGE_LOACTION, ORDER_NO, ORDER_QUANTITY, ORDER_CHANGE_DATE, GROSS_ORDER_AMOUNT,
ORDER_REJECTION_REASON, ORDER_DIVISION, DISTRIBUTION_CHANNEL, ORDER_TYPE, SALES_ORGANIZATION, TABLE_KEY FROM
(
SELECT DISTINCT ORDER_MATERIAL, ORDER_PLANT, ORDER_DATE, ORDER_STORAGE_LOACTION, ORDER_NO, ORDER_QUANTITY, ORDER_CHANGE_DATE, GROSS_ORDER_AMOUNT,
ORDER_REJECTION_REASON, ORDER_DIVISION, DISTRIBUTION_CHANNEL, ORDER_TYPE, SALES_ORGANIZATION,
CONCAT('999'+CAST(RIGHT('0000000000'+CAST(ORDER_NO AS VARCHAR(10)),10) AS VARCHAR(10)), CAST(RIGHT('000000'+CAST(ITEM AS VARCHAR(6)),6) AS VARCHAR(6))) AS TABLE_KEY 
FROM VW_SPARES_ICMC_ODI_DATA
WHERE ORDER_PLANT IN ('WA02','PT02') AND ORDER_DIVISION IN ('B1')
		AND SALES_ORGANIZATION IN ('ZDOM') AND ORDER_TYPE IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPSH','ZPVR','ZSPD','ZSPD')
		AND DISTRIBUTION_CHANNEL IN (10,20) AND ORDER_QUANTITY >0 --AND ORDER_REJECTION_REASON IN ('','A1')
		AND ORDER_DATE BETWEEN @StartDate AND @CurrentDate 
		--AND ORDER_MATERIAL='AP101292'
)A
),

VBRP_BASE AS   
(
    SELECT DISTINCT INVOICE_NUMBER, INVOICE_ORDER_NUMBER, INVOICE_MATERIAL, GROSS_INVOICE_AMOUNT, ACTUAL_BILLED_QTY, BILLING_DATE, INVOICE_ITEM 
	FROM VW_SPARES_ICMC_ODI_DATA
	WHERE INVOICE_DIVISION = 'B1' AND FKSTO <> 'X' AND BILLING_DATE IS NOT NULL
	AND SALES_ORGANIZATION IN ('ZDOM') AND DISTRIBUTION_CHANNEL IN (10,20)
	AND BILLING_TYPE_ANALYTICS IN ('ZSTD','ZSCH','ZVOR','ZPSD','ZPSH','ZPVR','ZSPD','ZSPD')
	AND BILLING_DATE BETWEEN @StartDate AND @CurrentDate
),

CANCELLED_BASE AS (
SELECT * FROM 
(
SELECT TABLE_KEY, PLANT, LOCATION, ORDER_MATERIAL, DEMAND_DATE, ACTIVITY_DATE_1, ACTIVITY_DATE_2, START_DATE, END_DATE, ORDER_QUANTITY, 
ROW_NUMBER() OVER(PARTITION BY TABLE_KEY ORDER BY ACTIVITY_DATE_1 ASC) AS RN
FROM
(
SELECT BASE1.TABLE_KEY,CAST(CL.Date AS DATE) as ACTIVITY_DATE_1,
        BASE1.ORDER_MATERIAL, BASE1.ORDER_PLANT AS PLANT, BASE1.ORDER_STORAGE_LOACTION AS LOCATION,
        ORDER_DATE AS DEMAND_DATE,
		TRY_CAST(CAST(YEAR(CONVERT(DATE, BASE1.ORDER_CHANGE_DATE, 112)) AS VARCHAR) + '-' + CAST(MONTH(CONVERT(DATE, BASE1.ORDER_CHANGE_DATE, 112)) AS VARCHAR) + '-' + CAST(DAY(CONVERT(DATE, BASE1.ORDER_CHANGE_DATE, 112)) AS VARCHAR) AS DATE) AS ACTIVITY_DATE_2,
        TRY_CAST(CAST(YEAR(CONVERT(DATE, BASE1.ORDER_DATE, 112)) AS VARCHAR)+'-'+CAST(MONTH(CONVERT(DATE, BASE1.ORDER_DATE, 112)) AS VARCHAR)+'-01' AS DATE) AS START_DATE,
        DATEADD(DAY,7,EOMONTH(CONVERT(DATE, BASE1.ORDER_DATE, 112))) AS END_DATE,
        BASE1.ORDER_QUANTITY
    FROM
        VVBASE BASE1
        LEFT JOIN CHANGELOG1 CL ON BASE1.TABLE_KEY = CL.[Table Key] AND CL.New_Value IS NOT NULL
    WHERE  
        BASE1.SALES_ORGANIZATION IN ('ZDOM')
        AND BASE1.ORDER_QUANTITY IS NOT NULL
        AND BASE1.ORDER_CHANGE_DATE IS NOT NULL
        AND BASE1.ORDER_DIVISION IN ('B1')
        AND BASE1.ORDER_PLANT IN ('WA02','PT02')
        AND BASE1.ORDER_TYPE IN ('ZVOR','ZSTD','ZSCH','ZPSD','ZPSH')
        AND BASE1.ORDER_REJECTION_REASON NOT IN ('','A1')
) C1
) C2 WHERE RN=1
), --SELECT * FROM CANCELLED_BASE

INVOICE_BASE AS (
SELECT * FROM 
(
SELECT * FROM
(SELECT TABLE_KEY, PLANT, LOCATION, ORDER_MATERIAL, DEMAND_DATE, ACTIVITY_DATE_1, ACTIVITY_DATE_2, START_DATE, END_DATE, ACTUAL_BILLED_QTY, 
ROW_NUMBER() OVER(PARTITION BY TABLE_KEY ORDER BY ACTIVITY_DATE_1 ASC) AS RN
FROM
(
SELECT BASE1.TABLE_KEY,CAST(CL.Date AS DATE) as ACTIVITY_DATE_1,
        BASE1.ORDER_MATERIAL, BASE1.ORDER_PLANT AS PLANT, BASE1.ORDER_STORAGE_LOACTION AS LOCATION,
        ORDER_DATE AS DEMAND_DATE,
		TRY_CAST(CAST(YEAR(CONVERT(DATE, BASE3.BILLING_DATE, 112)) AS VARCHAR) + '-' + CAST(MONTH(CONVERT(DATE, BASE3.BILLING_DATE, 112)) AS VARCHAR) + '-' + CAST(DAY(CONVERT(DATE, BASE3.BILLING_DATE, 112)) AS VARCHAR) AS DATE) AS ACTIVITY_DATE_2,
        TRY_CAST(CAST(YEAR(CONVERT(DATE, BASE1.ORDER_DATE, 112)) AS VARCHAR)+'-'+CAST(MONTH(CONVERT(DATE, BASE1.ORDER_DATE, 112)) AS VARCHAR)+'-01' AS DATE) AS START_DATE,
        DATEADD(DAY,0,EOMONTH(CONVERT(DATE, BASE1.ORDER_DATE, 112))) AS END_DATE,
        BASE3.ACTUAL_BILLED_QTY
    FROM
        VVBASE BASE1
        LEFT JOIN CHANGELOG1 CL ON BASE1.TABLE_KEY = CL.[Table Key] AND CL.New_Value IS NOT NULL
        LEFT JOIN VBRP_BASE BASE3 ON BASE1.ORDER_NO = BASE3.INVOICE_ORDER_NUMBER AND BASE1.ORDER_MATERIAL = BASE3.INVOICE_MATERIAL
    WHERE  
        BASE1.SALES_ORGANIZATION IN ('ZDOM')
        AND BASE1.ORDER_QUANTITY IS NOT NULL
        AND BASE1.ORDER_CHANGE_DATE IS NOT NULL
        AND BASE1.ORDER_DIVISION IN ('B1')
        AND BASE1.ORDER_PLANT IN ('WA02','PT02')
        AND BASE1.ORDER_TYPE IN ('ZVOR','ZSTD','ZSCH','ZPSD','ZPSH')
        AND BASE1.ORDER_REJECTION_REASON NOT IN ('','A1')
) C1 
) C2 --WHERE RN=1 
) C3 WHERE ACTIVITY_DATE_1 <= DATEADD(DAY,7,EOMONTH(CONVERT(DATE, DEMAND_DATE, 112)))
), --SELECT * FROM INVOICE_BASE

DEMAND_FINAL AS (
    SELECT 
        A.PLANT,
        A.LOCATION,
        A.MATERIAL_CODE,
        A.DEMAND_YEAR,
        A.DEMAND_MONTH,
        CAST(A.DEMAND_YEAR AS VARCHAR(4)) + '-' + RIGHT('0' + CAST(A.DEMAND_MONTH AS VARCHAR(2)), 2) + '-01' AS MONTH_DEMAND,
        A.ALL_QTY,
        ISNULL(B.CANCELLED_QTY, 0) AS CANCELLED_QTY,
        ISNULL(C.INVOICE_QTY, 0) AS INVOICE_QTY,
        A.VALUE,
        (A.ALL_QTY + ISNULL(C.INVOICE_QTY, 0) - ISNULL(B.CANCELLED_QTY, 0)) AS DEMAND_QTY
    FROM
        (SELECT
             CONCAT(MATERIAL_CODE, '-', PLANT, '-', LOCATION, '-', DEMAND_YEAR, '-', DEMAND_MONTH) AS KEY1,
             PLANT,
             LOCATION,
             MATERIAL_CODE,
             DEMAND_YEAR,
             DEMAND_MONTH,
             SUM(DOM_DEMAND_QTY) AS ALL_QTY,
             SUM(NETWR_PRICE) AS VALUE
         FROM
             (SELECT 
                  ORDER_MATERIAL AS MATERIAL_CODE,
                  ORDER_PLANT AS PLANT,
                  ORDER_STORAGE_LOACTION AS LOCATION,
                  ORDER_DATE AS DEMAND_DATE,
                  YEAR(CONVERT(DATE, ORDER_DATE, 112)) AS DEMAND_YEAR,
                  MONTH(CONVERT(DATE, ORDER_DATE, 112)) AS DEMAND_MONTH,
                  CAST(ORDER_QUANTITY AS INT) AS DOM_DEMAND_QTY,
                  CAST(GROSS_ORDER_AMOUNT AS DECIMAL(18, 2)) AS NETWR_PRICE   ---Datatype change due to integer limit error
              FROM VVBASE
              WHERE SALES_ORGANIZATION IN ('ZDOM')
                AND ORDER_QUANTITY IS NOT NULL
                AND ORDER_DIVISION IN ('B1')
                AND ORDER_PLANT IN ('WA02', 'PT02')
                AND ORDER_TYPE IN ('ZVOR', 'ZSTD', 'ZSCH', 'ZPSD', 'ZPSH')) MASTER
         GROUP BY MATERIAL_CODE, DEMAND_YEAR, DEMAND_MONTH, PLANT, LOCATION) A
    LEFT JOIN 
        (SELECT 
             CONCAT(ORDER_MATERIAL, '-', PLANT, '-', LOCATION, '-', YEAR(DEMAND_DATE), '-', MONTH(DEMAND_DATE)) AS KEY2,
             ORDER_MATERIAL,
             YEAR(DEMAND_DATE) AS DEMAND_YEAR,
             MONTH(DEMAND_DATE) AS DEMAND_MONTH,
             SUM(ORDER_QUANTITY) AS CANCELLED_QTY
         FROM CANCELLED_BASE
         WHERE ACTIVITY_DATE_1 BETWEEN START_DATE AND END_DATE
         GROUP BY ORDER_MATERIAL, YEAR(DEMAND_DATE), MONTH(DEMAND_DATE), PLANT, LOCATION) B
    ON A.KEY1 = B.KEY2
    LEFT JOIN 
        (SELECT 
             CONCAT(ORDER_MATERIAL, '-', PLANT, '-', LOCATION, '-', YEAR(DEMAND_DATE), '-', MONTH(DEMAND_DATE)) AS KEY3,
             ORDER_MATERIAL,
             YEAR(DEMAND_DATE) AS DEMAND_YEAR,
             MONTH(DEMAND_DATE) AS DEMAND_MONTH,
             SUM(ACTUAL_BILLED_QTY) AS INVOICE_QTY
         FROM INVOICE_BASE
         WHERE ACTIVITY_DATE_2 BETWEEN START_DATE AND END_DATE
         GROUP BY ORDER_MATERIAL, YEAR(DEMAND_DATE), MONTH(DEMAND_DATE), PLANT, LOCATION) C
    ON A.KEY1 = C.KEY3
), --SELECT * FROM DEMAND_FINAL

cte_final as(
SELECT 
    PLANT,
    LOCATION,
    MATERIAL_CODE,
    DEMAND_YEAR,
    DEMAND_MONTH,
    cast(MONTH_DEMAND as date) as month_demand_date,
    SUM(DEMAND_QTY) AS DEMAND_QTY,
    SUM(ALL_QTY) AS ALL_QTY,
    SUM(CANCELLED_QTY) AS CANCELLED_QTY,
    SUM(INVOICE_QTY) AS INVOICE_QTY,
    SUM(VALUE) AS VALUE
FROM DEMAND_FINAL
WHERE CAST(MONTH_DEMAND AS DATE) >= @StartDate
GROUP BY 
    PLANT, LOCATION, MATERIAL_CODE, DEMAND_YEAR, DEMAND_MONTH, cast(MONTH_DEMAND as date)
), --SELECT * FROM CTE_FINAL
 

cte_ranked AS (
    SELECT 
        PLANT,
        LOCATION,
        MATERIAL_CODE,
        MONTH_DEMAND_DATE,
        DEMAND_QTY,
        ROW_NUMBER() OVER (PARTITION BY PLANT, LOCATION, MATERIAL_CODE ORDER BY MONTH_DEMAND_DATE) AS RN
    FROM cte_final
), --SELECT * FROM cte_RANKED;

mad_calculation AS (
    SELECT 
       a.PLANT,
       a.LOCATION,
       a.MATERIAL_CODE,
       a.MONTH_DEMAND_DATE,
        Isnull(AVG(b.DEMAND_QTY),0) AS MAD_qty
   FROM cte_ranked a
    JOIN cte_ranked b
        ON a.PLANT = b.PLANT
        AND a.LOCATION = b.LOCATION
        AND a.MATERIAL_CODE = b.MATERIAL_CODE
        AND b.MONTH_DEMAND_DATE < a.MONTH_DEMAND_DATE -- Include only earlier months
        AND b.MONTH_DEMAND_DATE >= DATEADD(MONTH, -7, a.MONTH_DEMAND_DATE) -- Within 7 months
        AND b.MONTH_DEMAND_DATE < DATEADD(MONTH, -1, a.MONTH_DEMAND_DATE) -- Exclude the immediate previous month
    GROUP BY 
    a.PLANT,
       a.LOCATION,
   a.MATERIAL_CODE,
       a.MONTH_DEMAND_DATE
)

INSERT INTO ASM_ICMC_SPARES_WH_MAD_VALUE(
[PLANT],
    [LOCATION],
    [MATERIAL_CODE],
    [DEMAND_YEAR],
    [DEMAND_MONTH],
    [MONTH_DEMAND],
    [DEMAND_QTY],
    [ALL_QTY],
    [CANCELLED_QTY],
    [INVOICE_QTY],
    [VALUE],
    [MAD_QTY],
    [MAD_VALUE]
)

SELECT 
    f.PLANT,
    f.LOCATION,
    f.MATERIAL_CODE,
    f.DEMAND_YEAR,
    f.DEMAND_MONTH,
     f.MONTH_DEMAND_DATE,
    f.DEMAND_QTY,
    f.ALL_QTY,
    f.CANCELLED_QTY,
    f.INVOICE_QTY,
    f.[VALUE],
    m.MAD_qty,
    NULL AS MAD_VALUE
FROM cte_final f
LEFT JOIN mad_calculation m
    ON f.PLANT = m.PLANT
    AND f.LOCATION = m.LOCATION
    AND f.MATERIAL_CODE = m.MATERIAL_CODE
    AND f.MONTH_DEMAND_DATE = m.MONTH_DEMAND_DATE;


PRINT('MAD value has been loaded successfully')

END
