SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_Full_Load_ASM_UB_STOCK_REFRESH] AS
BEGIN
--*********************START************************
--Stock Fact:

Truncate table ASM_UB_STOCK_FACT
INSERT INTO ASM_UB_STOCK_FACT
SELECT DISTINCT
VS.COMPANYCODE As DEALERCODE,
VS.MODELCODE+LEFT(RIGHT(VS.COLOR,3),2) as SKU,
Cast(0 as int) as FK_DEALERCODE,
Cast(0 as int) as FK_SKU,
10004 As FK_TYPE_ID,
CAST(VS.EXECUTIONDATE as Date) AS DATE,
CM.COMPANYTYPE AS COMPANYTYPE,
Cast('' as varchar(255)) AS FK_STOCKSTATUS,
VS.VEHICLESTATUS as STOCKSTATUS,
COUNT(VS.CHASSISNO) AS [Stock Quantity],
COUNT(VS.CHASSISNO) as ACTUALQUANTITY,
getdate() as LASTUPDATEDDATETIME,
VS.IMPORTEDDATE,
VS.MODELCODE,
Cast(0 as int) As FK_MODEL,
NULL AS TEHSILID,
NULL AS SALESPERSON,
CAST(VS.PURCHASEDATE AS DATE) AS PURCHASE_DATE											  
--INTO ASM_UB_STOCK_FACT
FROM
   VEHICLE_STOCK_DATA VS INNER JOIN COMPANY_MASTER CM ON (VS.COMPANYCODE=CM.CODE AND CM.COMPANYTYPE = 10)
WHERE 

	Cast(VS.EXECUTIONDATE as date)>= '2020-04-01'

GROUP BY
  VS.COMPANYCODE,
  VS.MODELCODE+LEFT(RIGHT(VS.COLOR,3),2),
  CAST(VS.EXECUTIONDATE as Date),
  CAST(VS.PURCHASEDATE AS DATE),								
  CM.COMPANYTYPE,
  VS.VEHICLESTATUS,
  VS.IMPORTEDDATE,
  VS.MODELCODE
  
--Product Master and Dealer Master FK update: ASM_UB_STOCK_FACT
update B set B.FK_SKU=C.PK_SKU from ASM_UB_STOCK_FACT B INNER JOIN ASM_UB_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE)
update B set B.FK_MODEL=C.PK_Model_Code from ASM_UB_STOCK_FACT B INNER JOIN ASM_UB_PRODUCT_DIM C on (B.ModelCode=C.MODELCODE)
update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].ASM_UB_STOCK_FACT B INNER JOIN ASM_UB_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE)
--***********************************************************************************************************
END
GO