SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_Full_Load_ASM_CV_MARKET_SHARE_FACT_REFRESH] AS
BEGIN

-- ASM_CV_MARKET_SHARE_FACT :
TRUNCATE TABLE ASM_CV_MARKET_SHARE_FACT

INSERT INTO ASM_CV_MARKET_SHARE_FACT
SELECT
DISTINCT 
	CAST(convert(datetime, replace(CASE 
		WHEN MONTH=1 THEN 'Jan'
		WHEN MONTH=2 THEN 'Feb'
	    WHEN MONTH=3 THEN 'Mar'
		WHEN MONTH=4 THEN 'Apr'
		WHEN MONTH=5 THEN 'May'
		WHEN MONTH=6 THEN 'Jun'
		WHEN MONTH=7 THEN 'Jul'
		WHEN MONTH=8 THEN 'Aug'
		WHEN MONTH=9 THEN 'Sep'
		WHEN MONTH=10 THEN 'Oct'
		WHEN MONTH=11 THEN 'Nov'
		WHEN MONTH=12 THEN 'Dec'
	END+' '+CAST(YEAR as char(4)), '-', ' ')) as date) AS MS_DATE,
	ZSHARE_MASTER_CV.BU,
	ZMS_BRAND_CV.[MONTH],
	ZMS_BRAND_CV.[YEAR],
	ZSHARE_MASTER_CV.MANUFACTURER AS MANUFACTURERNAME,
	ZSHARE_MASTER_CV.SEGMENT AS SEGMENT,
	ZSHARE_MASTER_CV.BRAND AS BRAND,
	ZSHARE_MASTER_CV.MODEL AS [MODEL CODE],
	ZSHARE_MASTER_CV.CATEGORY AS CATEGORY,
    ZSHARE_MASTER_CV.SUB_CATEGORY AS SUB_CATEGORY,
	ZMS_BRAND_CV.TOTAL AS VOLUME,
	GETDATE() AS LASTUPDATEDTIMESTAMP,
	CASE WHEN ZRETDLR_CV.DEALER_CODE='VACANT' THEN UPPER(ZRETDLR_CV.ORT01) ELSE ZRETDLR_CV.DEALER_CODE END  AS DEALER_CODE,
	ZMS_BRAND_CV.CITYC,
	Cast(0 as int) As FK_DELAERCODE
	--INTO ASM_CV_MARKET_SHARE_FACT
FROM SAP_ZMS_BRAND_CV ZMS_BRAND_CV
LEFT JOIN SAP_ZSHARE_MASTER_CV ZSHARE_MASTER_CV ON ZMS_BRAND_CV.MANDT = ZSHARE_MASTER_CV.MANDT AND ZMS_BRAND_CV.SEGMENT = ZSHARE_MASTER_CV.SEGMENT AND
ZMS_BRAND_CV.COMP = ZSHARE_MASTER_CV.MANUFACTURER AND ZMS_BRAND_CV.BRAND = ZSHARE_MASTER_CV.MODEL
INNER JOIN SAP_ZRETDLR_CV ZRETDLR_CV ON ZMS_BRAND_CV.CITYC=ZRETDLR_CV.ORT01
WHERE 
CAST(convert(datetime, replace(CASE 
		WHEN MONTH=1 THEN 'Jan'
		WHEN MONTH=2 THEN 'Feb'
	    WHEN MONTH=3 THEN 'Mar'
		WHEN MONTH=4 THEN 'Apr'
		WHEN MONTH=5 THEN 'May'
		WHEN MONTH=6 THEN 'Jun'
		WHEN MONTH=7 THEN 'Jul'
		WHEN MONTH=8 THEN 'Aug'
		WHEN MONTH=9 THEN 'Sep'
		WHEN MONTH=10 THEN 'Oct'
		WHEN MONTH=11 THEN 'Nov'
		WHEN MONTH=12 THEN 'Dec'
	END+' '+CAST(YEAR as char(4)), '-', ' ')) as date)>=
	'2020-04-01'  -- (881118 rows affected)

-- SELECT MIN(MS_DATE),MAX(MS_DATE) FROM  ASM_CV_MARKET_SHARE_FACT 

update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].ASM_CV_MARKET_SHARE_FACT B INNER JOIN ASM_CV_DEALER_MASTER_DIM C on (B.DEALER_CODE=C.DEALERCODE) -- (518087 rows affected)

END
GO