--Master Changed SP 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[USP_Full_Load_ASM_CV_MASTER_REFRESH] AS
BEGIN

	--******************************* START ******************************************
--Dimensions:
--1.ASM_CV_PRODUCT_SKU_DIM (08.11.2022)

TRUNCATE TABLE ASM_CV_PRODUCT_SKU_DIM
INSERT INTO ASM_CV_PRODUCT_SKU_DIM
SELECT  DISTINCT
        B.MATNR AS SKU_CODE,
		A.BU_CATEGORY as Model,
        B.MAKTX AS Model_Description,
        C.BEZEI AS Colour,
        getdate() as CREATEDATETIME
        --INTO ASM_CV_PRODUCT_SKU_DIM
FROM SAP_ZBRAND_V_DETAIL A 
JOIN SAP_MAKT B ON A.ZBRANDVARIANT=SUBSTRING(B.MATNR,3,4) and B.MATNR LIKE '00%'
JOIN SAP_TVM2T C ON (Right(B.MATNR,2)=C.MVGR2)
WHERE A.ZBU_TYPE = 'CV'                       


--*************************************************************************************************

--2. ASM_CV_PRODUCT_DIM (08.11.2022)
TRUNCATE TABLE ASM_CV_PRODUCT_DIM
INSERT INTO ASM_CV_PRODUCT_DIM
SELECT  DISTINCT
        LEFT(B.MATNR,6) AS ModelCode,
        A.BU_CATEGORY as Model,
	    B.MAKTX AS Model_Description,
        A.ZPRESUCC_STATUS as Mono_BI_Fuel,
        A.ZSUB_BRD AS Subcategory,
        A.VARIANT AS Category,
        A.ZSEGMENT as Segment,
        A.ZBRAND1 as Brand,
        A.MODEL_ACTIVATION as Primary_Usage,
        getdate() as CREATEDATETIME,
			A.FINANCE_CATEGORY
        --INTO ASM_CV_PRODUCT_MODEL_DIM
FROM SAP_ZBRAND_V_DETAIL A 
JOIN SAP_MAKT B ON A.ZBRANDVARIANT=SUBSTRING(B.MATNR,3,4) and B.MATNR LIKE '00%'
WHERE A.ZBU_TYPE = 'CV'

--**************************************************************
--3.ASM_CV_DEALER_MASTER_DIM
Truncate table ASM_CV_DEALER_MASTER_DIM
INSERT INTO ASM_CV_DEALER_MASTER_DIM
SELECT
    Distinct
    KUNNR  As DEALERCODE,
    NAME1 As DEALERNAME,
    VTEXT1 As REGION,  -- Changed Region values after confirmation of BU 14th Oct 2022
    HUB as HUB,
    CIRCLE As CIRCLE,
    CITY1 As CITY,
    REGIO AS [STATE],  --Changed STATE values after confirmation of BU 14th Oct 2022
    Cast(BEZEI As varchar(100)) As STATE_NAME,  --Added new column after confirmation of BU on 14th Oct 2022
	CM.DISTRICTNAME AS DISTRICT,
    getdate() as CREATEDATETIME
	--INTO ASM_CV_DEALER_MASTER_DIM
FROM
SAP_ZSD_DEALER_REPOS
LEFT JOIN COMPANY_MASTER CM ON (CM.CODE = SAP_ZSD_DEALER_REPOS.KUNNR AND CM.COMPANYTYPE = 7)
WHERE
KATR6='CV' and KUNNR<'0000015000'


--*********************************
--Vaccant Dealer Data Insertation: 16.02.2023:
INSERT INTO ASM_CV_DEALER_MASTER_DIM
SELECT
    Distinct
    Upper(Z.ORT01)  As DEALERCODE,
    Z.DEALER_CODE As DEALERNAME,
    VTEXT1 As REGION,  -- Changed Region values after confirmation of BU 14th Oct 2022
    '' as HUB,
    CIRCLE As CIRCLE,
    Z.ORT01 As CITY,
    C.STATE AS [STATE],  --Changed STATE values after confirmation of BU 14th Oct 2022
    C.STATE As STATE_NAME,  --Added new column after confirmation of BU on 14th Oct 2022
    '' as DISTRICT,
    getdate() as CREATEDATETIME
	--INTO ASM_CV_DEALER_MASTER_DIM
FROM
SAP_ZRETDLR_CV Z 
JOIN SAP_ZSD_DEALER_REPOS B ON Z.BRACO=B.BRAN1
JOIN SAP_ZMS_BRAND_CV C ON Z.ORT01=C.CITYC and Z.BRACO=C.BRAN1
Where DEALER_CODE LIKE 'V%' and KATR6='CV' and B.KUNNR < '0000015000'

--*****************************
--4.ASM_CV_BRANCH_MASTER_DIM
TRUNCATE TABLE ASM_CV_BRANCH_MASTER_DIM
INSERT INTO ASM_CV_BRANCH_MASTER_DIM
SELECT 
DISTINCT BRANCHID [PK_BRANCHID],BM.CODE[BRANCH_CODE],BM.NAME[BRANCH_NAME] 
FROM BRANCH_MASTER BM
JOIN COMPANY_MASTER CM ON (BM.COMPANYID = CM.COMPANYID AND CM.COMPANYTYPE = 7
AND CM.IMPORTEDDATE = (SELECT MAX(CM1.IMPORTEDDATE) FROM COMPANY_MASTER CM1 WHERE CM.COMPANYID = CM1.COMPANYID))

--**********************************************
--5.ASM_CV_TALUKA_MASTER_DIM
TRUNCATE TABLE ASM_CV_TALUKA_MASTER_DIM
INSERT INTO ASM_CV_TALUKA_MASTER_DIM
SELECT 
DISTINCT TALUKAMASTERID [PK_TALUKAID],CODE [TALUKA_CODE],NAME [TALUKA_NAME] 
FROM TALUKA_MASTER


--**********************************************
--5.ASM_MANPOWER_MASTER

TRUNCATE TABLE dbo.ASM_MANPOWER_MASTER;
INSERT INTO dbo.ASM_MANPOWER_MASTER
(
[CDMSID],
[CompanyType],
[EmployeeCode],
[DEALERCODE],
[Department],
[SALES_PERSON],
[EmployeeGroup],
[Designation],
[CompanyID],
[Company],
[BranchID],
[Branch],
[IsActive],
[IsOTPVerified],
CREATEDDATETIME,
ISPRODUCTIVE
)
SELECT DISTINCT
[CDMSID],
CASE 
WHEN CM.COMPANYTYPE = 7 THEN 'CV'
WHEN CM.COMPANYTYPE IN (1,8)  THEN 'MC'
WHEN CM.COMPANYTYPE = 2 AND CM.COMPANYSUBTYPE IS NULL THEN 'PB'
WHEN CM.COMPANYTYPE = 2 AND CM.COMPANYSUBTYPE='Triumph' THEN 'TRIUMPH'
WHEN CM.COMPANYTYPE = 10 THEN 'UB'
END AS CompanyType,
[EmployeeCode],
CM.CODE AS DEALERCODE,
[Department],
CONCAT(TRIM(CMD.FIRSTNAME),' ',TRIM(CMD.LASTNAME)) AS SALES_PERSON,
[EmployeeGroup],
[Designation],
CMD.CompanyID,
[Company],
CMD.BranchID,
[Branch],
CMD.IsActive,
[IsOTPVerified],
GETDATE() AS CREATEDDATETIME,
CASE
WHEN RS.Code  IS NOT NULL THEN 'Yes'
ELSE 'No'
END AS ISPRODUCTIVE
--[ISPRODUCTIVE]
FROM CDMS_MANPOWER_DATA CMD     
LEFT JOIN COMPANY_MASTER CM ON (CMD.COMPANYID = CM.COMPANYID)
--LEFT JOIN CONTACT_MASTER COM ON (CMD.EmployeeCode = COM.CODE)
LEFT JOIN ASM_CV_RETAIL_STG RS ON (CMD.EmployeeCode= RS.CODE AND DATE > Getdate()-365)
WHERE CMD.IsActive = 'TRUE' AND CM.COMPANYTYPE IS NOT NULL AND CM.COMPANYTYPE NOT IN (4,5);
--AND CM.COMPANYTYPE=7



WITH CTE AS                  
 (                  
  SELECT *,                  
    ROW_NUMBER()OVER(PARTITION BY CompanyType, EmployeeCode, BranchID, CDMSID, [EmployeeGroup], [Designation]  ORDER BY IsOTPVerified DESC)RNK                   
  FROM ASM_MANPOWER_MASTER                 
 )     
DELETE FROM CTE                  
 WHERE RNK<>1; 

--******************************************************
/*
--1. ASM_LSQ_SALESPERSON_MASTER
TRUNCATE TABLE ASM_CV_LSQ_SALESPERSON_MASTER;
PRINT('ASM_CV_LSQ_SALESPERSON_MASTER table truncated');

INSERT INTO ASM_CV_LSQ_SALESPERSON_MASTER
SELECT DISTINCT 
    USERID AS LSQ_Salespersonid,
    FIRSTNAME AS NAME,
    DESIGNATION,
    mx_custom_10 AS Dealercode,
    mx_Custom_2 AS Branch_code,
    mx_custom_5 AS BU,
    mx_custom_51 AS CDMS_Salespersonid,
    StatusCode AS isinactive,
    [PhoneMobile],
    GETDATE() AS refresh_date
FROM LSQ_USERS
WHERE mx_custom_5 = 'CV'; 

PRINT('data loaded in ASM_CV_LSQ_SALESPERSON_MASTER table');
*/

--**********************************************
/*Product_SKU
(986 rows affected)
Product
(998 rows affected)
Dealer
(528 rows affected)
(51 rows affected) --VACANT
Branch
(3212 rows affected)
Taluka
(17708 rows affected)*/


--INSERT INTO ASM_CV_DEALER_MASTER_DIM VALUES ('VACANT','VACANT','','','','','','',getdate()) --Update VACANT Data in Dealer Master

--Update
--UPDATE D
--set
--D.REGION=ZM.VTEXT,
--D.CITY=ZM.ORT01,
--D.STATE_NAME=ZMS_BRAND_CV.STATE
--FROM ASM_CV_DEALER_MASTER_DIM D JOIN ZRETDLR_CV ZM ON (D.DEALERCODE=ZM.DEALER_CODE and D.DEALERCODE='VACANT')
--JOIN ZMS_BRAND_CV ON (ZMS_BRAND_CV.CITYC=ZM.ORT01)
 --JOIN ZSHARE_MASTER_CV ON 
 --ZMS_BRAND_CV.MANDT = ZSHARE_MASTER_CV.MANDT AND 
 --ZMS_BRAND_CV.SEGMENT = ZSHARE_MASTER_CV.SEGMENT AND
 --ZMS_BRAND_CV.COMP = ZSHARE_MASTER_CV.MANUFACTURER AND 
 --ZMS_BRAND_CV.BRAND = ZSHARE_MASTER_CV.MODEL

--**********************************************************************************
--4. Cal Dim: It will not be change frequently
--SELECT 
--CALENDAR_DATE,
--CALENDAR_MONTH,
--CALENDAR_DAY,
--CALENDAR_YEAR,
--CALENDAR_QUARTER,
--DAY_NAME,
--DAY_OF_WEEK,
--MONTH_NAME,
--
----//FISCAL WEEK
--CASE WHEN (MONTH(CALENDAR_DATE) BETWEEN 4 AND 12) AND YEAR(CALENDAR_DATE) = 2017  -- DATEPART(WEEK,CALENDAR_DATE) > 16
--THEN DATEPART(WEEK,CALENDAR_DATE) - 12
--
--WHEN (MONTH(CALENDAR_DATE) BETWEEN 1 AND 3 ) AND YEAR(CALENDAR_DATE) = 2018
--THEN DATEPART(WEEK,CALENDAR_DATE) + 40
--
--WHEN (MONTH(CALENDAR_DATE) BETWEEN 4 AND 12) AND YEAR(CALENDAR_DATE) < 2023  -- DATEPART(WEEK,CALENDAR_DATE) > 16
--THEN DATEPART(WEEK,CALENDAR_DATE) - 13
--WHEN (MONTH(CALENDAR_DATE) BETWEEN 1 AND 3 ) AND YEAR(CALENDAR_DATE) < 2023
--THEN DATEPART(WEEK,CALENDAR_DATE) + 39
--
--WHEN (MONTH(CALENDAR_DATE) BETWEEN 4 AND 12 ) AND YEAR(CALENDAR_DATE) = 2023
--THEN DATEPART(WEEK,CALENDAR_DATE) - 12
--WHEN (MONTH(CALENDAR_DATE) BETWEEN 1 AND 3 )  AND YEAR(CALENDAR_DATE) = 2023
--THEN DATEPART(WEEK,CALENDAR_DATE) + 40
--
--WHEN (MONTH(CALENDAR_DATE) BETWEEN 4 AND 12 ) AND YEAR(CALENDAR_DATE) = 2024
--THEN DATEPART(WEEK,CALENDAR_DATE) - 13
--WHEN (MONTH(CALENDAR_DATE) BETWEEN 1 AND 3 )  AND YEAR(CALENDAR_DATE) = 2024
--THEN DATEPART(WEEK,CALENDAR_DATE) + 40
--END AS FISCAL_WEEK,
--
----//FISCAL MONTH
--CASE WHEN MONTH(CALENDAR_DATE) BETWEEN 4 AND 12 THEN MONTH(CALENDAR_DATE) - 3
--WHEN MONTH(CALENDAR_DATE) BETWEEN 1 AND 3 THEN MONTH(CALENDAR_DATE) + 9
--END AS FISCAL_MONTH,
--
----//FISCAL QUARTER
--CASE WHEN DATEPART(QUARTER,CALENDAR_DATE) = 1 THEN 4
--WHEN DATEPART(QUARTER,CALENDAR_DATE) = 2 THEN 1
--WHEN DATEPART(QUARTER,CALENDAR_DATE) = 3 THEN 2
--WHEN DATEPART(QUARTER,CALENDAR_DATE) = 4 THEN 3
--END AS FISCAL_QUARTER,
--
----//FISCAL YEAR
--CASE WHEN MONTH(CAST(CALENDAR_DATE AS DATE)) < 4 THEN CAST(YEAR(CALENDAR_DATE)-1 AS INT) ELSE
--CAST(YEAR(CALENDAR_DATE)  AS INT) END AS FISCAL_YEAR,
--
--CREATEDATETIME
----INTO ASM_CV_CALENDAR_DIM
--FROM DateTempSB2

--***************************************************************

--5. Type Dim: It will not be change frequently

--CREATE TABLE [dbo].[ASM_CV_TYPE_DIM](
--	[TYPE_ID] [decimal](19, 0) NOT NULL,
--	[TYPE_NAME] [varchar](100) NULL,
--	[TYPE_DESCRIPTION] [varchar](255) NULL,
--	[CREATEDATETIME] [datetime] NULL,
--PRIMARY KEY CLUSTERED 
--(
--	[TYPE_ID] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
--) ON [PRIMARY]
--GO


--***************************************************************************************************



END
GO