
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[USP_FULL_LOAD_ASM_CV_ENQUIRY_REFRESH] AS
BEGIN

/********************************************HISTORY********************************************/
/*---------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------*/
/*  DATE       |  CREATED BY/MODIFIED BY |              CHANGE DESCRIPTION                     */
/*---------------------------------------------------------------------------------------------*/
/*  05/01/2023 |  Dhanraj Andhale        |              Created 							   */
/*  29/04/2023 |  Nikita Lakhimale       |             LSQ Integration IBU                     */
/*  23/04/2024 |  Robin Singh            |            LSQ  Leadtype logic change               */
/*  03/05/2024 |  Robin Singh            |   Enquiry Lost Fields addition in Dim   
    13/12/2024 |  Richa Mishra            |            Mapping change in Salesperson            */
/*  26/03/2025 |  Ashwini Ahire            |First_Source_Lead_Type, First_Mode_Source,   First_Mode_SubSource*/
/*    14/08/2025 |  Richa Mishra            |        Addition of LSQ Targets  */
/*---------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------*/
/********************************************HISTORY********************************************/

--1. ENQUIRY DIM & FACT:

--TRUNCATE TABLE ASM_CV_ENQUIRY_DIM
/**************************************************************************************************************************************/	
/********************************** STEP 1 : LOADING ENQUIRY DIMENSION TABLE FROM CDMS AND LSQ SOURCES ********************************/
/*************************************************************f*************************************************************************/

/* ------------------------------------------------------------------------------------------------------------------------------------
----------------------------STEP 1.1 LOADING ASM_CV_ENQUIRY_DIM_CDMS_STG CDMS STAGE TABLE----------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------*/
TRUNCATE TABLE ASM_CV_ENQUIRY_DIM_CDMS_STG
INSERT INTO ASM_CV_ENQUIRY_DIM_CDMS_STG
SELECT DISTINCT
	EH.HEADERID AS PK_ENQUIRYHEADERID,
	CAST(EH.DOCDATE AS DATE) AS ENQUIRYDATE,
	EH.LEADTYPE AS ENQUIRYMEDIUM,
	-- ENQUIRY_HEADER.SOURCETYPE AS ENQUIRYLEADSOURCE,
	SOURCE_OF_ENQUIRY.VALUENAME AS ENQUIRYLEADSOURCE,  -- ADDED ON 03.11.2022 AFTER DISCUSSION HAD WITH PBI TEAM.
	--CASE WHEN EH.LEADSTATUS='CLOSED' THEN 'INVOICED' ELSE EH.LEADSTATUS END AS ENQUIRYSTATUS,
	CASE WHEN EH.LEADSTATUS='CLOSED' THEN 'INVOICED' 
	WHEN EH.LEADSTATUS='LOST' THEN 'CLOSED' 
	ELSE EH.LEADSTATUS END AS ENQUIRYSTATUS,

	--EH.ISTESTRIDETAKEN AS ISTESTRIDETAKEN ,
	CASE WHEN EH.TESTRIDEOFFERED='TEST RIDE TAKEN' THEN 'YES' ELSE 'NO' END AS ISTESTRIDETAKEN ,
    NULL AS TESTRIDEOFFERED,
	--CASE WHEN EH.TESTRIDEOFFERED = 'CUSTOMER DECLINED' THEN 'CANCELLED BY CUSTOMER'
	--WHEN EH.TESTRIDEOFFERED='TEST RIDE TAKEN' THEN 'COMPLETED'
    --WHEN EH.TESTRIDEOFFERED='NO' THEN 'NO SHOW' ELSE EH.TESTRIDEOFFERED	END AS TESTRIDEOFFERED,
    CASE WHEN EH.CUSTOMEROWNERSHIPPROFILEID IN ('FIRST TIME BUYER', 'FIRST TIME USER') THEN 'FTB'
	---WHEN EH.CUSTOMEROWNERSHIPPROFILEID='FIRST TIME USER' THEN 'FTU' -- THIS VALUE IS DISCARDED IN LSQ
	WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE='BAJAJ' THEN 'RTB - BAJAJ'
	WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE IN ('ATUL', 'OTHER', 'BAXY', 'PIAGGIO', 'TVS', 'MAHINDRA & MAHINDRA', 'VIKRAM', 'E-RICKSHAW') THEN 'RTB - COMPETITION'
	--WHEN EH.CUSTOMEROWNERSHIPPROFILEID='REPEAT TIME BUYER' AND EH.PREVIOUSLYOWNEDVEHICLE IS NULL THEN 'RTB - COMPETITION'
	ELSE EH.CUSTOMEROWNERSHIPPROFILEID END
	AS CUSTOMEROWNERSHIPPROFILEID ,
	EH.MODEOFPURCHASE AS MODEOFPURCHASE,
	--SUBSOURCEOFENQUIRY AS SUBSOURCEOFENQUIRY,
	SM.[NAME] AS ENQUIRYSUBSOURCE,  
	EH.LEADLOSTREASON AS LEADLOSTREASON,
	CASE WHEN ISGOODSCARRIER=1 THEN 'CARGO' WHEN ISPASSENGERCARRIER=1 THEN 'PASSENGER' END  AS PRIMARYUSAGE,
	EH.LEADCLASSIFICATIONTYPE,
	EH.LOSTBYFINANCE,
	EH.LOSTBYCHANNEL,
	EH.LOSTBYPRODUCT,
	EH.LOSTTOCOMPETITION,
	EH.LOSTBYOTHERS,
	'' AS LOSTBYCATEGORY,
	GETDATE() AS CREATEDDATETIME,
	EH.IMPORTEDDATE,
	EH.CDMS_BATCHNO,
	CASE WHEN ENQUIRY_FOLLOWUP.FOLLOWUP IS NOT NULL THEN 'YES' ELSE 'NO' END  AS ENQUIRYFOLLOWUP,
	EH.LEADTYPE AS LEADTYPE,
	EH.SOURCETYPE AS SOURCETYPE,
	--CASE WHEN EH.LEADSTATUS='CLOSED' THEN 'INVOICED' ELSE EH.LEADSTATUS END AS  LEADSTATUS,
	CASE WHEN EH.LEADSTATUS='CLOSED' THEN 'INVOICED' 
	WHEN EH.LEADSTATUS='LOST' THEN 'CLOSED' 
	ELSE EH.LEADSTATUS END AS LEADSTATUS,
	CASE
	WHEN EH.LOSTTOCOMPETITION = 'YES' THEN 'COMPETITION'
	WHEN EH.LOSTBYOTHERS = 1 THEN 'OTHERS'
	END AS LOST_TO_COMPETITION_OTHERS,
	CASE
	WHEN EH.LOSTBYFINANCE=1 THEN 'LOST BY FINANCE'
	WHEN EH.LOSTBYPRODUCT=1 THEN 'LOST BY PRODUCT'
	WHEN EH.LOSTBYCHANNEL=1 THEN 'LOST BY CHANNEL'
	ELSE 'OTHERS'
	END AS LOST_CATEGORY,
	CAST('' AS VARCHAR(50)) AS LOST_PRIMARY_REASON,
	CAST('' AS VARCHAR(50)) AS LOST_SECONDARY_REASON,
	EH.FINANCECOMPANY AS FINANCECOMPANY,
	EH.COMPETITIONVEHICLE AS LOSTTOOEM,
	CAST(0 AS INT) AS RETAILCONVERSIONFLAG,
	EH.ISEXCHANGEAPPLICABLE AS ISEXCHANGEAPPLICABLE,
	EH.USAGEDETAILS,
	CASE WHEN ISNULL(EH.AREANAME,'') <> '' AND EH.LEADSTATUS IN ('OPEN','BOOKED','LOST','CANCELLED','CLOSED')
	THEN EH.AREANAME
	ELSE ''
	END AS AREA,
	CAST(0 AS INT) AS REASON_EXIST,
	0 AS BASEFLAG,
	NULL AS ISNEEDSASSESSMENT
,NULL AS ISDEMO
,NULL AS ISVISITED 
,NULL AS PINCODE 
--,NULL AS SALES_PERSON 
,CONCAT(TRIM(CN.FIRSTNAME),' ',TRIM(CN.LASTNAME)) AS SALES_PERSON 
,NULL AS FIRSTFOLLOWUPDATE  
,NULL AS FIRSTISCUSTOMERCONTACTED 
,'' AS FOLLOWUPSCHEDULEDATE1 
,NULL AS LATESTFOLLOWUPDATE 
,NULL AS LATESTFOLLOWUPSCHEDULEDATE  
,NULL AS LATESTISCUSTOMERCONTACTED
,'' AS FOLLOWUPBUCKET
,NULL AS LEADLOSTSECONDARYREASON  
,NULL AS FOLLOWUPLATESTDISPOSITION
					  
,ENQUIRY_FOLLOWUP.NO_OF_FOLLOWUPS AS NO_OF_FOLLOWUPS,
     NULL AS  ENQUIRY_STAGE,
     NULL AS OPPORTUNITY_STATUS,
     NULL AS REASON_FOR_CHOOSING_COMPETITION ,
     NULL AS IS_ANY_FOLLOWUP_OVERDUE,
     NULL AS ENQUIRY_ORIGIN,
	 NULL AS COMPETITION_BRAND,
	 NULL AS COMPETITION_MODEL
	--INTO ASM_CV_ENQUIRY_DIM
FROM
	ENQUIRY_HEADER EH 
	LEFT JOIN ENQUIRY_HEADER_EXT EHE 
	ON EH.HEADERID = EHE.HEADERID
	
	LEFT JOIN (SELECT LEADDOCID,FOLLOWUP, 
	ROW_NUMBER() OVER (PARTITION BY LEADDOCID ORDER BY COALESCE(ACTIVITYSTATUSDATE,DOCDATE) ASC) AS RANK_1,
    ROW_NUMBER() OVER (PARTITION BY LEADDOCID ORDER BY COALESCE(ACTIVITYSTATUSDATE,DOCDATE) DESC) AS NO_OF_FOLLOWUPS
	FROM ENQUIRY_FOLLOWUP)ENQUIRY_FOLLOWUP 
	ON EH.HEADERID=ENQUIRY_FOLLOWUP.LEADDOCID
	AND ENQUIRY_FOLLOWUP.RANK_1=1-- ADDED ON 01.11.2022


	
	LEFT JOIN CONTACT_MASTER CN ON (EH.OWNERCONTACTID = CN.CONTACTID AND CN.ID = (SELECT MAX(CN1.ID) FROM CONTACT_MASTER CN1 
	WHERE CN.CONTACTID = CN1.CONTACTID))
	
	LEFT JOIN SOURCE_MASTER SM 
	ON SM.SOURCEMASTERID=EHE.SUBSOURCE
	
	LEFT OUTER JOIN SOURCE_OF_ENQUIRY 
	ON EHE.SOURCEOFENQUIRY=SOURCE_OF_ENQUIRY.VALUEID -- ADDED JOIN ON 03.11.2022 HAD DISCUSSION WITH PBI TEAM.
	
	INNER JOIN COMPANY_MASTER 
	ON EH.COMPANYID=COMPANY_MASTER.COMPANYID
	AND COMPANY_MASTER.COMPANYTYPE = 7

WHERE CAST(EH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND CAST(GETDATE()-1 AS DATE)  
--WHERE CAST(EH.IMPORTEDDATE AS DATE) >= CAST((SELECT MAX(IMPORTEDDATE)  FROM ASM_CV_ENQUIRY_DIM_CDMS_STG) AS DATE)  --UPDATED ON 12/08

/* ------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------STEP 1.2 DEDUPLICATION OF CDMS DATA----------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------*/ 	
--- QUESTION : -- AS WE ARE CREATING INTERMEDIATE STAGE TABLES FOR UNION PURPOSE
--THIS DEDUPLICATION SHOULD ALWAYS BE PERFORMED ON DELTA (DATA FOR THAT DAY) OR FULL DATA ?

DELETE FROM ASM_CV_ENQUIRY_DIM_CDMS_STG WHERE CAST(ENQUIRYDATE AS DATE)>CAST(GETDATE()-1 AS DATE);

--DEDUP PROCESS:
  WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_ENQUIRYHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ENQUIRY_DIM_CDMS_STG                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;  

 --UPDATE ASM_CV_ENQUIRY_DIM_CDMS_STG SET ENQUIRYFOLLOWUP='YES' WHERE ENQUIRYFOLLOWUP IS NOT NULL AND BASEFLAG=0;
/* ------------------------------------------------------------------------------------------------------------------------------------
-----------------------------STEP 1.3 LOADING LEAD LOST REASONS FOR CDMS DATA----------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------*/ 
TRUNCATE TABLE ASM_CV_ENQUIRY_LOST_REASON
INSERT INTO ASM_CV_ENQUIRY_LOST_REASON
SELECT DISTINCT 
	EH.HEADERID,
	EH.DOCDATE,
	LBRP.VALUENAME AS PRIMARY_REASON,
	LBRS.VALUENAME AS SECONDARY_REASON,
	EH.IMPORTEDDATE,
	GETDATE() AS CREATEDDATETIME,
	ISNULL((CASE WHEN LBRS.VALUENAME IS NOT NULL AND LBRS.VALUENAME IS NOT NULL THEN 1 ELSE 0 END),0) AS REASON_EXIST
	--INTO ASM_CV_ENQUIRY_LOST_REASON  -- (10275898 ROWS AFFECTED)
FROM
	ENQUIRY_HEADER EH 
	JOIN COMPANY_MASTER CM 
	ON EH.COMPANYID=CM.COMPANYID 
	AND CM.COMPANYTYPE=7
	
	JOIN LOSTBY_REASON_DATA LBRP 
	ON LBRP.VALUEID = EH.LOSTREASON1 
	AND LBRP.MASTERID =(
						CASE 
						WHEN ISNULL(EH.LOSTBYFINANCE,0) = 1 THEN 1030062 
						WHEN ISNULL(EH.LOSTBYPRODUCT,0) = 1 THEN 1030063
						WHEN ISNULL(EH.LOSTBYCHANNEL,0) = 1 THEN 1030065
						WHEN ISNULL(EH.LOSTBYOTHERS,0) = 1 THEN 1051369 
						END  
						)
	LEFT OUTER JOIN LOSTBY_REASON_DATA LBRS 
	ON LBRS.VALUEID = EH.LOSTREASON2 
	AND LBRS.MASTERID =(
						CASE 
						WHEN ISNULL(EH.LOSTBYFINANCE,0) = 1 THEN 1030062 
						WHEN ISNULL(EH.LOSTBYPRODUCT,0) = 1 THEN 1030063
						WHEN ISNULL(EH.LOSTBYCHANNEL,0) = 1 THEN 1030065
						WHEN ISNULL(EH.LOSTBYOTHERS,0) = 1 THEN 1051369
						END
						) 
	WHERE --1=2
CAST(EH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND CAST(GETDATE()-1 AS DATE) 
--CAST(EH.IMPORTEDDATE AS DATE) >= CAST((SELECT  MAX(IMPORTEDDATE) FROM ASM_CV_ENQUIRY_LOST_REASON) AS DATE)  --UPDATED ON 12/08



UPDATE ED
SET ED.LOST_PRIMARY_REASON=EL.PRIMARY_REASON, ED.LOST_SECONDARY_REASON=EL.SECONDARY_REASON,
ED.REASON_EXIST=EL.REASON_EXIST
FROM ASM_CV_ENQUIRY_DIM_CDMS_STG ED JOIN ASM_CV_ENQUIRY_LOST_REASON EL  ON (ED.PK_ENQUIRYHEADERID=EL.HEADERID);


/* ------------------------------------------------------------------------------------------------------------------------------------
---------------------------STEP 1.4 LOADING LSQ DATA INTO LSQ STAGE TABLE (DIMENSION)--------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------*/ 
TRUNCATE TABLE ASM_CV_ENQUIRY_DIM_LSQ_STG
INSERT INTO ASM_CV_ENQUIRY_DIM_LSQ_STG
SELECT DISTINCT
	LSQ_PBASE.PROSPECTID AS PK_ENQUIRYHEADERID,
	--LTRIM (CAST(LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE AS DATE),10) AS ENQUIRYDATE,
	--DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE))) AS ENQUIRYDATE,
	LTRIM(CAST(DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE)))AS DATE),10) AS ENQUIRYDATE,
	
	
	ISNULL(LSQ_PBASE.MX_ENQUIRY_MODE, LSQ_PBASE.mx_Mode_of_Enquiry)AS ENQUIRYMEDIUM,
	-- ENQUIRY_HEADER.SOURCETYPE AS ENQUIRYLEADSOURCE,
	/*SOURCE_OF_ENQUIRY.NAME*/LSQ_PBASE.MX_SOURCE_OF_ENQUIRY AS ENQUIRYLEADSOURCE,  -- NO MAPPING IN MODEL -- LOGIC TO BE IMPLEMENTED
	CASE WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('BOOKED','ALLOCATED') THEN 'BOOKED'
	WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('INVOICED','DELIVERED') THEN 'INVOICED'
	WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('LOST' ,'AUTO - CLOSED' ,'CLOSED' ,'LOST TO COMPETITION' ,'LOST TO CO-DEALER','LOST TO CO-DEALER/CO- BRANCH') THEN 'LOST' 
	WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('VISITED' ,'CONTACTED' ,'OPEN' ,'TEST RIDE CANCELLED' ,'QUALIFIED' ,'PROSPECT' ,'TEST RIDE COMPLETED' ,'TEST RIDE BOOKED' ,'TEST RIDE RESCHEDULED') THEN 'OPEN'  END AS ENQUIRYSTATUS, --NOTE: ADDED 'LOST TO CO-DEALER/CO- BRANCH' FOR LOST CATEGPORY BECAUSE THERE WAS BLANK ENQUIRY STATUS WHEN RETAIL CONVERSIONFLAG IS SET TO 1 
	--/*EH.ISTESTRIDETAKEN*/ CAST(NULL AS INT) AS ISTESTRIDETAKEN ,-- NO MAPPING IN MODEL -- LOGIC TO BE IMPLEMENTED
	--LSQ_TESTRIDE.STATUS AS TESTRIDEOFFERED,
	CASE WHEN LSQ_TESTRIDE.RELATEDPROSPECTID IS NOT NULL THEN 'YES' ELSE 'NO' END AS ISTESTRIDETAKEN ,-- NO MAPPING IN MODEL -- LOGIC TO BE IMPLEMENTED
    NULL AS TESTRIDEOFFERED,
    --CASE WHEN LSQ_TESTRIDE.RELATEDPROSPECTID IS NOT NULL THEN 'YES' ELSE 'NO' END AS TESTRIDEOFFERED,
	LSQ_PBASE.MX_TYPE_OF_CUSTOMER AS CUSTOMEROWNERSHIPPROFILEID ,
	LSQ_PBASE.MX_PAYMENT_MODE AS MODEOFPURCHASE,
	--SUBSOURCEOFENQUIRY AS SUBSOURCEOFENQUIRY,
	LSQ_PBASE.MX_ENQUIRY_SUB_SOURCE AS ENQUIRYSUBSOURCE,  
	CASE WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('LOST' ,'AUTO - CLOSED' ,'CLOSED' ,'LOST TO COMPETITION' ,'LOST TO CO-DEALER','LOST TO CO-DEALER/CO- BRANCH') THEN  LSQ_PBASE.PROSPECTSTAGE END AS LEADLOSTREASON, --NOTE: ADDED 'LOST TO CO-DEALER/CO- BRANCH' FOR LOST CATEGPORY BECAUSE THERE WAS BLANK ENQUIRY STATUS WHEN RETAIL CONVERSIONFLAG IS SET TO 1 
	--LSQ_PBASE.PROSPECTSTAGE AS LEADLOSTREASON, -- LOGIC TO BE IMPLEMENTED
	LSQ_PACTEXTBASE.MX_CUSTOM_67  AS PRIMARYUSAGE, -- LOGIC TO BE IMPLEMENTED
	LSQ_PBASE.MX_ENQUIRY_CLASSIFICATION AS LEADCLASSIFICATIONTYPE,
	CAST(NULL AS INT) AS LOSTBYFINANCE, --- EXCLUSIVE TO CDMS
	CAST(NULL AS INT) AS LOSTBYCHANNEL,  --- EXCLUSIVE TO CDMS
	CAST(NULL AS INT) AS LOSTBYPRODUCT,  --- EXCLUSIVE TO CDMS
	CASE WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE)='LOST TO COMPETITION' THEN 'YES' END  AS LOSTTOCOMPETITION,
	--LSQ_PBASE.PROSPECTSTAGE AS LOSTTOCOMPETITION,   
	CAST(NULL AS INT) AS LOSTBYOTHERS,  --- EXCLUSIVE TO CDMS
	'' AS LOSTBYCATEGORY, --- EXCLUSIVE TO CDMS
	--GETDATE() AS CREATEDDATETIME,
	DATEADD(MI,30,(DATEADD(HH,5,GETDATE()))) AS CREATEDDATETIME,
	
	
	--LSQ_PBASE.MODIFIEDON AS IMPORTEDDATE,
	DATEADD(MI,30,(DATEADD(HH,5,LSQ_PBASE.MODIFIEDON))) AS IMPORTEDDATE,
	
	
	CAST(NULL AS INT) AS CDMS_BATCHNO, -- EXCLUSIVE TO CDMS
	CASE WHEN FIRST_FOLLOWUP.RELATEDPROSPECTID IS NOT NULL THEN 'YES' ELSE 'NO' END AS ENQUIRYFOLLOWUP, -- LOGIC TO BE IMPLEMENTED
	ISNULL(LSQ_PBASE.MX_ENQUIRY_MODE, LSQ_PBASE.mx_Mode_of_Enquiry) AS LEADTYPE,
	LSQ_PBASE.MX_SOURCE_OF_ENQUIRY AS SOURCETYPE, 
	CASE WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('BOOKED','ALLOCATED') THEN 'BOOKED'
	WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('INVOICED','DELIVERED') THEN 'INVOICED'
	WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('LOST' ,'AUTO - CLOSED' ,'CLOSED' ,'LOST TO COMPETITION' ,'LOST TO CO-DEALER') THEN 'LOST' 
	WHEN UPPER(LSQ_PBASE.PROSPECTSTAGE) IN ('VISITED' ,'CONTACTED' ,'OPEN' ,'TEST RIDE CANCELLED' ,'QUALIFIED' ,'PROSPECT' ,'TEST RIDE COMPLETED' ,'TEST RIDE BOOKED' ,'TEST RIDE RESCHEDULED') THEN 'OPEN' END AS LEADSTATUS, -- LOGIC TO BE IMPLEMENTED
	LSQ_PBASE.PROSPECTSTAGE AS LOST_TO_COMPETITION_OTHERS, -- LOGIC TO BE IMPLEMENTED
	'NA' AS LOST_CATEGORY, -- EXCLUSIVE TO CDMS
	CAST('' AS VARCHAR(50)) AS LOST_PRIMARY_REASON,
	CAST('' AS VARCHAR(50)) AS LOST_SECONDARY_REASON,
	NULL AS FINANCECOMPANY, -- EXCLUSIVE TO CDMS
	NULL AS LOSTTOOEM, -- EXCLUSIVE TO CDMS
	CAST(0 AS INT) AS RETAILCONVERSIONFLAG, --- UPDATE AT END
	LSQ_PBASE.MX_EXCHANGE AS ISEXCHANGEAPPLICABLE,
	LSQ_PACTEXTBASE.MX_CUSTOM_70 AS USAGEDETAILS,
	LSQ_PBASE.MX_AREA AS AREA,
	CAST(0 AS INT) AS REASON_EXIST, -- EXCLUSIVE TO CDMS
	1 AS BASEFLAG,
	--CASE WHEN LSQ_PBASE.MX_NEED_ASSESSMENT=1 THEN 'YES' WHEN LSQ_PBASE.MX_NEED_ASSESSMENT=0 THEN 'NO' ELSE LSQ_PBASE.MX_NEED_ASSESSMENT END AS ISNEEDSASSESSMENT,
	CASE WHEN LSQ_PBASE.MX_TYPE_OF_CUSTOMER IS NOT NULL  THEN 'YES' ELSE 'NO' END AS ISNEEDSASSESSMENT,
    --CASE WHEN LSQ_PBASE.MX_SALES_DEMO IS NOT NULL THEN 'YES' ELSE 'NO' END AS ISDEMO,
    CASE WHEN LSQ_SALES_DEMO.MX_CUSTOM_1='YES' THEN 'YES' ELSE 'NO' END AS ISDEMO,
    CASE WHEN LSQ_PEXTBASE.MX_VISITED = 'YES' THEN 'YES' ELSE 'NO' END AS ISVISITED,
    --NULL AS ISVISITED,
    LSQ_PBASE.MX_PINCODE AS PINCODE, 
    U.FirstName AS SALES_PERSON,
    --FIRST_FOLLOWUP.FIRSTFOLLOWUPDATE,
	
	DATEADD(MI,30,(DATEADD(HH,5,FIRST_FOLLOWUP.FIRSTFOLLOWUPDATE))) AS FIRSTFOLLOWUPDATE,
	
    --FIRST_FOLLOWUP.FIRSTISCUSTOMERCONTACTED,
	CASE WHEN FIRST_FOLLOWUP.FIRSTISCUSTOMERCONTACTED IN('YES','NO') THEN 'YES' ELSE 'NO' END  AS FIRSTISCUSTOMERCONTACTED,
	
	
    --FIRST_FOLLOWUP.FIRSTFOLLOWUPSCHEDULEDATE,
	DATEADD(MI,30,(DATEADD(HH,5,FIRST_FOLLOWUP.FIRSTFOLLOWUPSCHEDULEDATE))) AS FIRSTFOLLOWUPSCHEDULEDATE,
	
	
    --LATEST_FOLLOWUP.LATESTFOLLOWUPDATE,
	DATEADD(MI,30,(DATEADD(HH,5,LATEST_FOLLOWUP.LATESTFOLLOWUPDATE))) AS LATESTFOLLOWUPDATE,
	
	
    --LATEST_FOLLOWUP.LATESTFOLLOWUPSCHEDULEDATE,
	DATEADD(MI,30,(DATEADD(HH,5,LATEST_FOLLOWUP.LATESTFOLLOWUPSCHEDULEDATE))) AS LATESTFOLLOWUPSCHEDULEDATE,
	
	
    LATEST_FOLLOWUP.LATESTISCUSTOMERCONTACTED,
    CASE WHEN CAST( DATEDIFF(HOUR, LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE, FIRST_FOLLOWUP.FIRSTFOLLOWUPDATE) AS INT) <3 THEN  '<3 HRS'
     WHEN CAST( DATEDIFF(HOUR, LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE, FIRST_FOLLOWUP.FIRSTFOLLOWUPDATE) AS INT) BETWEEN 3 AND 24 THEN '3-24 HRS'
     WHEN CAST( DATEDIFF(HOUR, LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE, FIRST_FOLLOWUP.FIRSTFOLLOWUPDATE) AS INT) >24 THEN '>24 HRS'  END AS FOLLOWUPBUCKET,
     NULL AS LEADLOSTSECONDARYREASON ,
     COALESCE (LATEST_FOLLOWUP.MX_CUSTOM_14, LATEST_FOLLOWUP.MX_CUSTOM_15,FIRST_FOLLOWUP.MX_CUSTOM_14, FIRST_FOLLOWUP.MX_CUSTOM_15) AS  FOLLOWUPLATESTDISPOSITION,
													
     FIRST_FOLLOWUP.NOOFFOLLOWUPS AS NO_OF_FOLLOWUPS,
	 CASE WHEN LSQ_PBASE.ProspectStage IN ('Open','Qualified','Contacted','Test Ride Booked',
                           'Test Ride Cancelled','Test Ride Rescheduled' ,'Visited' ,
						   'Sales Demo','Test Ride Completed','Finance' ,'Exchange',
						   'Booking in progress','Booking failed','Booking InProgress')	THEN 'Open' 
	WHEN LSQ_PBASE.ProspectStage = 'Booked' THEN 'Booked'
	WHEN LSQ_PBASE.ProspectStage = 'Invoiced' THEN 'Invoiced'
	WHEN LSQ_PBASE.ProspectStage IN('Lost','Closed','Auto','Lost to Co-Dealer','Lost to Competition','Lost to Co-Dealer/Co- Branch','Auto - Closed') THEN 'Closed' END  ENQUIRY_STAGE,
     LSQ_PACTEXTBASE.mx_Custom_2 AS OPPORTUNITY_STATUS,
     COALESCE(LSQ_PBASE.mx_Financing, LSQ_PBASE.mx_Reason_for_Choosing_Competition) AS REASON_FOR_CHOOSING_COMPETITION ,
     LSQ_PEXT2BASE.mx_Is_any_Follow_up_overdue AS IS_ANY_FOLLOWUP_OVERDUE,
     LSQ_PBASE.Origin AS ENQUIRY_ORIGIN,
	 LSQ_PEXTBASE.mx_Competition_Brand_Followup as COMPETITION_BRAND,
	 LSQ_PEXTBASE.mx_Competition_Model_Followup as COMPETITION_MODEL
FROM
  LSQ_PROSPECT_BASE LSQ_PBASE 
  
  LEFT  JOIN LSQ_PROSPECT_EXTENSIONBASE LSQ_PEXTBASE 
  ON (LSQ_PBASE.PROSPECTID = LSQ_PEXTBASE.PROSPECTID)
                 
  INNER JOIN LSQ_PROSPECTACTIVITY_EXTENSIONBASE LSQ_PACTEXTBASE 
  ON (LSQ_PBASE.PROSPECTID = LSQ_PACTEXTBASE.RELATEDPROSPECTID) 
  AND LSQ_PACTEXTBASE.ACTIVITYEVENT=12003 

--------------- FIRST FOLLOWUP----------------

LEFT JOIN (SELECT RELATEDPROSPECTID,FIRSTFOLLOWUPDATE, FIRSTISCUSTOMERCONTACTED,FIRSTFOLLOWUPSCHEDULEDATE,MX_CUSTOM_14,MX_CUSTOM_15, NOOFFOLLOWUPS FROM (
SELECT RELATEDPROSPECTID,MX_CUSTOM_13 FIRSTISCUSTOMERCONTACTED,MX_CUSTOM_3 AS FIRSTFOLLOWUPSCHEDULEDATE,
CREATEDON FIRSTFOLLOWUPDATE, MX_CUSTOM_14 , MX_CUSTOM_15,
ROW_NUMBER()OVER(PARTITION BY RELATEDPROSPECTID ORDER BY CREATEDON ASC) AS RNK,
ROW_NUMBER() OVER(PARTITION BY RELATEDPROSPECTID ORDER BY CREATEDON DESC) AS NOOFFOLLOWUPS
FROM LSQ_PROSPECTACTIVITY_EXTENSIONBASE 
WHERE ACTIVITYEVENT=213
AND MX_CUSTOM_13 IS NOT NULL ) A WHERE RNK=1
) FIRST_FOLLOWUP
ON FIRST_FOLLOWUP.RELATEDPROSPECTID=LSQ_PBASE.PROSPECTID
--AND FIRST_FOLLOWUP.FIRSTFOLLOWUPDATE>LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE

AND DATEADD(MI,30,(DATEADD(HH,5,FIRST_FOLLOWUP.FIRSTFOLLOWUPDATE))) > DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE)))
 

---------------LATEST FOLLOWUP ------------------------------------------
LEFT JOIN (SELECT RELATEDPROSPECTID,LATESTFOLLOWUPDATE, LATESTISCUSTOMERCONTACTED,LATESTFOLLOWUPSCHEDULEDATE,MX_CUSTOM_14,MX_CUSTOM_15 FROM (
SELECT RELATEDPROSPECTID,MX_CUSTOM_13 LATESTISCUSTOMERCONTACTED,MX_CUSTOM_3 AS LATESTFOLLOWUPSCHEDULEDATE,
CREATEDON LATESTFOLLOWUPDATE,MX_CUSTOM_14 , MX_CUSTOM_15,
ROW_NUMBER()OVER(PARTITION BY RELATEDPROSPECTID ORDER BY CREATEDON DESC) AS RNK 
FROM LSQ_PROSPECTACTIVITY_EXTENSIONBASE 
WHERE ACTIVITYEVENT=213
AND MX_CUSTOM_13 IS NOT NULL ) B WHERE RNK=1
)LATEST_FOLLOWUP
ON LATEST_FOLLOWUP.RELATEDPROSPECTID=LSQ_PBASE.PROSPECTID

--AND LATEST_FOLLOWUP.LATESTFOLLOWUPDATE> LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE       
AND DATEADD(MI,30,(DATEADD(HH,5,LATEST_FOLLOWUP.LATESTFOLLOWUPDATE)))> DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE)))


 -------TESTRIDE LOGIC------------------------------------------------------
 LEFT JOIN (SELECT RELATEDPROSPECTID, ROW_NUMBER() OVER (PARTITION BY RELATEDPROSPECTID ORDER BY CREATEDON DESC) AS RANK1
  FROM 
  LSQ_PROSPECTACTIVITY_EXTENSIONBASE 
  WHERE ACTIVITYEVENT =202
  AND  STATUS='COMPLETED'
  )LSQ_TESTRIDE
  ON LSQ_TESTRIDE.RELATEDPROSPECTID=LSQ_PBASE.PROSPECTID
  AND LSQ_TESTRIDE.RANK1=1
  
  
  
 -- LEFT JOIN (SELECT RELATEDPROSPECTID,STATUS , ROW_NUMBER() OVER (PARTITION BY RELATEDPROSPECTID ORDER BY CREATEDON DESC) AS RANK1
  --FROM 
  --LSQ_PROSPECTACTIVITY_EXTENSIONBASE 
  --WHERE ACTIVITYEVENT IN (201,202) 
  --)LSQ_TESTRIDE
  --ON LSQ_TESTRIDE.RELATEDPROSPECTID=LSQ_PBASE.PROSPECTID
  --AND LSQ_TESTRIDE.RANK1=1
  -------SALES_DEMO LOGIC------------------------------------------------------
  LEFT JOIN (SELECT RELATEDPROSPECTID, MX_CUSTOM_1, ROW_NUMBER() OVER (PARTITION BY RELATEDPROSPECTID ORDER BY CREATEDON DESC) AS RANK2 
  FROM 
  LSQ_PROSPECTACTIVITY_EXTENSIONBASE 
  WHERE ACTIVITYEVENT = 231
  --AND MX_CUSTOM_1='YES'  
  )LSQ_SALES_DEMO
  ON LSQ_SALES_DEMO.RELATEDPROSPECTID=LSQ_PBASE.PROSPECTID
  AND LSQ_SALES_DEMO.RANK2=1
  
 LEFT JOIN LSQ_Prospect_Extension2Base LSQ_PEXT2BASE 
 ON LSQ_PEXT2BASE.ProspectId=LSQ_PBASE.PROSPECTID
  
 LEFT JOIN LSQ_users U on LSQ_PBASE.OwnerId=U.UserID
  
  WHERE LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE IS NOT NULL
AND CAST(DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE))) AS DATE ) BETWEEN '2020-04-01' AND CAST(GETDATE()-1 AS DATE) 
--AND DATEADD(MI,30,(DATEADD(HH,5,LSQ_PBASE.MODIFIEDON))) >= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_ENQUIRY_DIM_LSQ_STG) AS DATE)
   

--DEDUP PROCESS:
  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_ENQUIRYHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ENQUIRY_DIM_LSQ_STG                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 

/* ------------------------------------------------------------------------------------------------------------------------------------
---------------STEP 1.5 UNION OF CMDS STAGE AND LSQ STAGE TABLES AND LOAD INTO ASM_CV_ENQUIRY_DIM--------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------*/ 

TRUNCATE TABLE ASM_CV_ENQUIRY_DIM
INSERT INTO ASM_CV_ENQUIRY_DIM
	    
	SELECT DISTINCT
	[PK_ENQUIRYHEADERID] ,
	[ENQUIRYDATE] ,
	[ENQUIRYMEDIUM] ,
	[ENQUIRYLEADSOURCE] ,
	[ENQUIRYSTATUS] ,
	[ISTESTRIDETAKEN] ,
	[TESTRIDEOFFERED] ,
	[CUSTOMEROWNERSHIPPROFILEID] ,
	[MODEOFPURCHASE] ,
	[ENQUIRYSUBSOURCE] ,
	[LEADLOSTREASON] ,
	[PRIMARYUSAGE] ,
	[LEADCLASSIFICATIONTYPE] ,
	[LOSTBYFINANCE] ,
	[LOSTBYCHANNEL] ,
	[LOSTBYPRODUCT] ,
	[LOSTTOCOMPETITION] ,
	[LOSTBYOTHERS] ,
	[LOSTBYCATEGORY] ,
	[CREATEDDATETIME] ,
	[IMPORTEDDATE] ,
	[CDMS_BATCHNO] ,
	[ENQUIRYFOLLOWUP] ,
	[LEADTYPE] ,
	[SOURCETYPE] ,
	[LEADSTATUS] ,
	[LOST_TO_COMPETITION_OTHERS] ,
	[LOST_CATEGORY] ,
	[LOST_PRIMARY_REASON] ,
	[LOST_SECONDARY_REASON] ,
	[FINANCECOMPANY] ,
	[LOSTTOOEM] ,
	[RETAILCONVERSIONFLAG] ,
	[ISEXCHANGEAPPLICABLE],
	[USAGEDETAILS] ,
	[AREA] ,
	[REASON_EXIST] ,
	[BASEFLAG]
	,[ISNEEDSASSESSMENT]
	,[ISDEMO]
	,[ISVISITED]
	,[PINCODE] 
	,[SALES_PERSON] 
	,[FIRSTFOLLOWUPDATE]  
	,[FIRSTISCUSTOMERCONTACTED] 
	,[FOLLOWUPSCHEDULEDATE1] 
	,[LATESTFOLLOWUPDATE] 
	,[LATESTFOLLOWUPSCHEDULEDATE]
	,[LATESTISCUSTOMERCONTACTED]
	,[FOLLOWUPBUCKET]
  ,[LEADLOSTSECONDARYREASON],
  [FOLLOWUPLATESTDISPOSITION],		  
  	[NO_OF_FOLLOWUPS],
   	[ENQUIRY_STAGE],
	[OPPORTUNITY_STATUS],
	[REASON_FOR_CHOOSING_COMPETITION] ,
	[IS_ANY_FOLLOWUP_OVERDUE],
  	[ENQUIRY_ORIGIN],
	[COMPETITION_BRAND],
    [COMPETITION_MODEL]
    FROM ASM_CV_ENQUIRY_DIM_CDMS_STG
	
	UNION
	
	SELECT DISTINCT
	[PK_ENQUIRYHEADERID] ,
	[ENQUIRYDATE] ,
	[ENQUIRYMEDIUM] ,
	[ENQUIRYLEADSOURCE] ,
	[ENQUIRYSTATUS] ,
	[ISTESTRIDETAKEN] ,
	[TESTRIDEOFFERED] ,
	[CUSTOMEROWNERSHIPPROFILEID] ,
	[MODEOFPURCHASE] ,
	[ENQUIRYSUBSOURCE] ,
	[LEADLOSTREASON] ,
	[PRIMARYUSAGE] ,
	[LEADCLASSIFICATIONTYPE] ,
	[LOSTBYFINANCE] ,
	[LOSTBYCHANNEL] ,
	[LOSTBYPRODUCT] ,
	[LOSTTOCOMPETITION] ,
	[LOSTBYOTHERS] ,
	[LOSTBYCATEGORY] ,
	[CREATEDDATETIME] ,
	[IMPORTEDDATE] ,
	[CDMS_BATCHNO] ,
	[ENQUIRYFOLLOWUP] ,
	[LEADTYPE] ,
	[SOURCETYPE] ,
	[LEADSTATUS] ,
	[LOST_TO_COMPETITION_OTHERS] ,
	[LOST_CATEGORY] ,
	[LOST_PRIMARY_REASON] ,
	[LOST_SECONDARY_REASON] ,
	[FINANCECOMPANY] ,
	[LOSTTOOEM] ,
	[RETAILCONVERSIONFLAG] ,
	[ISEXCHANGEAPPLICABLE],
	[USAGEDETAILS] ,
	[AREA] ,
	[REASON_EXIST] ,
	[BASEFLAG] 
	,[ISNEEDSASSESSMENT]
	,[ISDEMO]
	,[ISVISITED]
	,[PINCODE] 
	,[SALES_PERSON] 
	,[FIRSTFOLLOWUPDATE]  
	,[FIRSTISCUSTOMERCONTACTED] 
	,[FOLLOWUPSCHEDULEDATE1] 
	,[LATESTFOLLOWUPDATE] 
	,[LATESTFOLLOWUPSCHEDULEDATE]
	,[LATESTISCUSTOMERCONTACTED]
	,[FOLLOWUPBUCKET]
    ,[LEADLOSTSECONDARYREASON],
     [FOLLOWUPLATESTDISPOSITION],
     [NO_OF_FOLLOWUPS],
	[ENQUIRY_STAGE],
	[OPPORTUNITY_STATUS],
	[REASON_FOR_CHOOSING_COMPETITION] ,
	[IS_ANY_FOLLOWUP_OVERDUE],
  	[ENQUIRY_ORIGIN],
	[COMPETITION_BRAND],
    [COMPETITION_MODEL]
	FROM ASM_CV_ENQUIRY_DIM_LSQ_STG
	

	--DEDUP PROCESS:
  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_ENQUIRYHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ENQUIRY_DIM                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 

/*TEST SELECT COUNT(*) FROM ASM_CV_ENQUIRY_DIM_CDMS_STG; --7956185
SELECT COUNT(*) FROM ASM_CV_ENQUIRY_DIM_LSQ_STG; --6776
SELECT COUNT(*) FROM ASM_CV_ENQUIRY_DIM; --0*/--7962961
/**************************************************************************************************************************************/	
/********************************** STEP 2: LOADING ENQUIRY FACT (ENQUIRY TRANSACTIONS) DATA ******************************************/
/**************************************************************************************************************************************/

/* ------------------------------------------------------------------------------------------------------------------------------------
---------------------------STEP 2.1 LOAD CDMS DATA INTO ENQUIRY FACT (COPY FROM MAIN SCRIPT)-------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------
------ A. LOADING FIRST STAGE TABLE FROM CDMS
------ B. DEDUPLICATION OF CDMS STAGE
------ C. PRODUCT MASTER AND DEALER MASTER FK UPDATE: ASM_CV_ENQUIRY_STG
------ D. LOAD ENQ TARGET FROM TARGET_SALES_3W TABLE 
------ E. PRODUCT MASTER AND DEALER MASTER FK UPDATE: ASM_CV_ENQUIRY_TARGET  */

--ENQUIRY TRNASACTION TABLE DATASET

--TRUNCATE TABLE ASM_CV_ENQUIRY_STG
--ENQUIRY TRNASACTION TABLE DATASET:

TRUNCATE TABLE ASM_CV_ENQUIRY_STG
INSERT INTO ASM_CV_ENQUIRY_STG
SELECT DEALERCODE, 
SKU,
FK_DEALERCODE, 
FK_SKU,  
FK_TYPE_ID,
DATE,
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
COMPANYTYPE,
BRANCHID,
TEHSILID,
SALES_PERSON,
ISNULL(COUNT(HEADERID),0) AS ACTUALQUANTITY ,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
CDMS_BATCHNO ,
TARGETQUANTITY,
PERIODNAME
,COLOUR_CODE, 
MODELCODE, 
FK_MODEL,FLAG, 
BASEFLAG,
LEADTYPE,
NULL AS Campaign_Code		
 FROM (
		 
					  
SELECT 
   DISTINCT
   CM.CODE AS DEALERCODE, --- NO MAPPING
   IM.CODE+IV.CODE AS SKU, -- NO MAPPING
   CAST(0 AS INT) AS FK_DEALERCODE, -- NO MAPPINGS
   CAST(0 AS INT) AS FK_SKU,  --- NO MAPPINGS
   10001 AS FK_TYPE_ID, 
   CAST(EH.DOCDATE AS DATE) AS DATE, --- MX DEALER ASSIGNMENT DATE
   EL.LINEID AS ENQUIRYLINEID, --- PROSPECT ACTIVITY EXTENSION BASE ID
   EL.DOCID AS FK_ENQUIRYDOCID,  ---- PROSPECT ID
   CM.COMPANYTYPE AS COMPANYTYPE, -- NO MAPPING
   EH.BRANCHID,
   EH.ADTEHSILID AS TEHSILID,
   CONCAT(TRIM(CN.FIRSTNAME),' ',TRIM(CN.LASTNAME)) AS SALES_PERSON,
   EH.HEADERID , -- COUNT(PROSPECT ID)
   GETDATE() AS LASTUPDATEDDATETIME, --- CURRENT DATE
   EH.IMPORTEDDATE, -- HEADER MODIFIED ON
   EH.CDMS_BATCHNO, -- NO MAPPING  CAN WE MAP IT TO NULL ? AS ITS RELATED TO CDMS?
   CAST(0 AS DECIMAL(19,0)) AS TARGETQUANTITY, --- AS IS
   (LEFT(DATENAME( MONTH,EH.DOCDATE),3)+'-'+CAST(YEAR(EH.DOCDATE) AS VARCHAR(4))) AS PERIODNAME, --- MX_DEALER_ASSIGNMENT_DATE
   IV.CODE AS COLOUR_CODE, -- NO MAPPING
   IM.CODE AS MODELCODE, -- NO MAPPING
   CAST(0 AS INT) AS FK_MODEL, -- NO MAPPING
   100011 AS FLAG,
   0 AS BASEFLAG,
   ISNULL(EH.LEADTYPE,'KAM') AS LEADTYPE, --LEADTYPE CHANGES 
   NULL AS Campaign_Code		
   
FROM 
   ENQUIRY_HEADER EH INNER JOIN COMPANY_MASTER CM ON (EH.COMPANYID=CM.COMPANYID AND CM.COMPANYTYPE = 7)
   LEFT JOIN CONTACT_MASTER CN ON (EH.OWNERCONTACTID = CN.CONTACTID AND CN.ID = (SELECT MAX(CN1.ID) FROM CONTACT_MASTER CN1 WHERE CN.CONTACTID = CN1.CONTACTID))
   INNER JOIN ENQUIRY_LINE EL ON (EH.HEADERID=EL.DOCID)
   JOIN ITEM_MASTER IM ON (IM.ITEMID=EL.ITEMID) 
   LEFT JOIN ITEMVARMATRIX_MASTER IV ON (EL.VARMATRIXID=IV.ITEMVARMATRIXID) 
   
WHERE  
CAST(EH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND CAST(GETDATE()-1 AS DATE) 
--CAST(EH.IMPORTEDDATE AS DATE) >= CAST((SELECT  MAX(IMPORTEDDATE)  FROM ASM_CV_ENQUIRY_STG) AS DATE)   --UPDATED ON 12/08
   ) BASE
GROUP BY 
DEALERCODE, SKU,FK_DEALERCODE, FK_SKU,  FK_TYPE_ID,DATE,ENQUIRYLINEID,
 FK_ENQUIRYDOCID,COMPANYTYPE,BRANCHID,TEHSILID,SALES_PERSON,LASTUPDATEDDATETIME,IMPORTEDDATE,CDMS_BATCHNO ,TARGETQUANTITY,PERIODNAME
,COLOUR_CODE, MODELCODE, FK_MODEL,FLAG, BASEFLAG,LEADTYPE

--

DELETE FROM ASM_CV_ENQUIRY_STG WHERE DATE>CAST(GETDATE()-1 AS DATE)

--DEDUP PROCESS:
  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY FK_ENQUIRYDOCID,ENQUIRYLINEID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ENQUIRY_STG                 
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;  


  --*****************************************************
  --*******************************************************
  --STEP 2:
--PRODUCT MASTER AND DEALER MASTER FK UPDATE: ASM_CV_ENQUIRY_STG
UPDATE B SET B.FK_SKU=C.PK_SKU FROM ASM_CV_ENQUIRY_STG B INNER JOIN ASM_CV_PRODUCT_SKU_DIM C ON (B.SKU=C.SKU_CODE)
UPDATE B SET B.FK_MODEL=C.PK_MODEL_CODE FROM ASM_CV_ENQUIRY_STG B INNER JOIN ASM_CV_PRODUCT_DIM C ON (B.MODELCODE=C.MODELCODE)
UPDATE B SET B.FK_DEALERCODE=C.PK_DEALERCODE FROM [DBO].[ASM_CV_ENQUIRY_STG] B INNER JOIN ASM_CV_DEALER_MASTER_DIM C ON (B.DEALERCODE=C.DEALERCODE)

--********************************************************************
--STEP 3:

------ENQUIRY TARGET---------------------------------------

TRUNCATE TABLE ASM_CV_ENQUIRY_TARGET


INSERT INTO ASM_CV_ENQUIRY_TARGET
(DEALERCODE, SKU, FK_DEALERCODE, FK_SKU, FK_TYPE_ID, DATE, ENQUIRYLINEID, FK_ENQUIRYDOCID, COMPANYTYPE, BRANCHID, TEHSILID, SALES_PERSON,
ACTUALQUANTITY, LASTUPDATEDDATETIME, IMPORTEDDATE, CDMS_BATCHNO, TARGETQUANTITY, PERIODNAME, COLOUR_CODE, MODELCODE, FK_MODEL, FLAG, BaseFlag,
LEADTYPE, Campaign_Code)
SELECT DISTINCT 
DEALERCODE
,Cast('' as varchar(50)) As SKU
,Cast('' as int) as FK_DEALERCODE
,Cast('' as int) as FK_SKU
,10001 As FK_TYPE_ID
--,Cast(null As Date) As DATE
,Cast(convert(datetime, replace(PERIODNAME, '-', ' ')) as date) As DATE
,Cast(null as decimal(19,0)) As ENQUIRYLINEID
,Cast(null as decimal(19,0)) As FK_ENQUIRYDOCID
,Cast(null as decimal(19,0)) As COMPANYTYPE
,Cast(null as decimal(19,0)) As BRANCHID
,Cast(null as decimal(19,0)) As TEHSILID
,Cast('' as varchar(50)) As SALES_PERSON
,Cast(null as decimal(10,0)) As ACTUALQUANTITY
,DATEADD(mi,30,(DATEADD(hh,5,getdate()))) as LASTUPDATEDDATETIME -- UTC_TO_IST_Changes_needed?
,IMPORTEDDATE
,CDMS_BATCHNO
,Round(Sum(ENQUIRYTARGET),0) As TARGETQUANTITY
,PERIODNAME
,Cast('' as varchar(25)) As COLOUR_CODE
,MODELCODE
,Cast(null as int) As FK_MODEL
,100012 As FLAG
,0 AS BaseFlag
,'KAM' as LEADTYPE 
,NULL AS Campaign_Code								   
--INTO ASM_CV_ENQUIRY_TARGET
FROM
TARGET_SALES_3W	Where Cast(convert(datetime, replace(PERIODNAME, '-', ' ')) as date)<Cast(DATEADD(mi,30,(DATEADD(hh,5,getdate()))) As date)-- UTC_TO_IST_Changes_needed?
GROUP BY
DEALERCODE,
IMPORTEDDATE,
CDMS_BATCHNO,
PERIODNAME,
MODELCODE

-----------------LSQ---------------------------


SELECT CAST(userID AS VARCHAR(36)) AS userID,CAST(TemplateId AS VARCHAR(36)) AS TemplateId , CAST(RecurrenceId AS VARCHAR(36)) as RecurrenceId, CAST(RecurrenceStartDate AS DATE) as RecurrenceStartDate,
    CAST(RecurrenceEndDate AS DATE) as RecurrenceEndDate , CAST(RecurrenceStatus AS VARCHAR(36)) as RecurrenceStatus, 
	CAST(dealer_code AS VARCHAR(36)) as dealer_code, 
	CAST(branch AS VARCHAR(36))  as branch, 
	CAST(Firstname AS VARCHAR(36))  as Firstname, 
	CAST(PhoneMobile AS VARCHAR(36))  as PhoneMobile,
	CAST(Designation AS VARCHAR(36))  as Designation, 
	ISNULL(SUM(TRY_CAST(Target AS DECIMAL(10,2))), 0) AS Target, CAST(TeamTarget AS VARCHAR(36)) as TeamTarget,
	CAST(SubGoalCondition AS VARCHAR(36))  as SubGoalCondition, CAST(Subgoal AS VARCHAR(36)) as Subgoal
INTO #LSQTargetENQ --LSQTargettemp 
FROM 
(SELECT TR.*, Designation, mx_Custom_2 AS branch, mx_Custom_5 AS BU, mx_Custom_10 AS dealer_code, Firstname,PhoneMobile FROM (SELECT TemplateId, RecurrenceId, userID, SubGoalCondition, SUM(TRY_CAST(Target AS DECIMAL(10,2))) AS Target,TeamTarget,
RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, Subgoal FROM LSQ_TARGET_DISTRIBUTION_DATA
 WHERE TemplateId = '5d01a5fc-0023-4e68-b85e-c6dc794454b7' 
 /*and RecurrenceId in ('15f1f5e8-faea-4018-9dcb-1b8d2245b996', 'e06542f6-1229-4fcf-8753-0bb1947b66f7', 'a0b1489f-51d9-4dc9-9a34-7750b3ab022d', '457041f5-ebd6-4750-ac47-63dd9e798711', 'eefdb943-dfce-47c1-88e7-1f501d0e4b7d', '9d180dc3-5440-47d5-9854-11ffba54b7c5', '08253de6-7a2e-4f30-98ec-58f521493009', '95d357ae-3f27-4882-83a1-34cede0792ef', '40514481-ff52-4c49-805d-84490d5ecc5e', '974450b2-457a-4a0c-86f3-199f5e8c8101', '262cf96d-81c6-4c40-82ea-1279c9a3f083'
)*/
 GROUP BY TemplateId, RecurrenceId, userID, RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, TeamTarget,
 SubGoalCondition, Subgoal) TR 
 JOIN LSQ_Users LS ON LS.userID = TR.userID 
 WHERE mx_Custom_5 = 'CV' --AND Designation IN ('DSE', 'Sales Manager', 'M', 'GM')
 ) a 
 GROUP BY TemplateId, RecurrenceId, RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, dealer_code, branch, Designation, userID, TeamTarget,
 Firstname, PhoneMobile, SubGoalCondition, Subgoal;
 
 
INSERT INTO ASM_CV_ENQUIRY_TARGET
SELECT  
DEALERCODE,
SKU,
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
DATE,
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
COMPANYTYPE,
BRANCHID,
TEHSILID,
SALES_PERSON,
ACTUALQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
CDMS_BATCHNO,
TARGETQUANTITY,
PERIODNAME,
COLOUR_CODE,
MODELCODE,
FK_MODEL,
FLAG,
BaseFlag,
Leadtype,
Campaign_Code,
Salesperson_id,
Designation,
recurrence_id,
Subgoal,
PhoneMobile, Model, TeamTarget
from(
SELECT 
dealer_code as  DEALERCODE
,CAST('' AS VARCHAR(50)) AS SKU
,CAST('' AS INT) AS FK_DEALERCODE
,CAST('' AS INT) AS FK_SKU
,10001 AS FK_TYPE_ID
,RecurrenceStartDate AS DATE  ----------Convert
,TemplateId  AS ENQUIRYLINEID  --null  AS RETAILLINEID  --TemplateId
,Null AS FK_ENQUIRYDOCID   --null  AS FK_RETAILDOCID   --RecurrenceId
,CAST(NULL AS DECIMAL(19,0)) AS COMPANYTYPE
,BM.Branchid AS BRANCHID
,CAST(NULL AS DECIMAL(19,0)) AS TEHSILID
,Firstname AS SALES_PERSON
,CAST(NULL AS DECIMAL(10,0)) AS ACTUALQUANTITY
,GETDATE() AS LASTUPDATEDDATETIME
,null as IMPORTEDDATE
,null as CDMS_BATCHNO
,ISNULL(TRY_CAST(Target AS DECIMAL(10,2)), 0) AS TARGETQUANTITY
,null as PERIODNAME
,CAST('' AS VARCHAR(25)) AS COLOUR_CODE
,P.MODELCODE
,CAST(NULL AS INT) AS FK_MODEL
,100013 As FLAG
,0 AS BaseFlag
,'KAM' as LEADTYPE 
,NULL AS Campaign_Code 
,userID as Salesperson_id
,Designation as Designation
,RecurrenceId as recurrence_id,
Subgoal as Subgoal,
PhoneMobile as PhoneMobile,
LTRIM(RTRIM(REPLACE(LT.Subgoalcondition, 'Brand = ', ''))) as Model, 
TeamTarget
FROM
#LSQTargetENQ LT
left JOIN BRANCH_MASTER BM ON LT.BRANCH=BM.CODE
left JOIN (
    SELECT Model, Modelcode,
    
           ROW_NUMBER() OVER (PARTITION BY finance_category order by Brand ) AS rn
    FROM ASM_CV_PRODUCT_DIM P
) P ON LTRIM(RTRIM(REPLACE(LT.Subgoalcondition, 'Brand = ', ''))) = P.Model

)B


------------------------TESTRIDE TARGET -------------------------------------------

SELECT CAST(userID AS VARCHAR(36)) AS userID,CAST(TemplateId AS VARCHAR(36)) AS TemplateId , CAST(RecurrenceId AS VARCHAR(36)) as RecurrenceId, CAST(RecurrenceStartDate AS DATE) as RecurrenceStartDate,
    CAST(RecurrenceEndDate AS DATE) as RecurrenceEndDate , CAST(RecurrenceStatus AS VARCHAR(36)) as RecurrenceStatus, 
	CAST(dealer_code AS VARCHAR(36)) as dealer_code, 
	CAST(branch AS VARCHAR(36))  as branch, 
	CAST(Firstname AS VARCHAR(36))  as Firstname, 
	CAST(PhoneMobile AS VARCHAR(36))  as PhoneMobile,
	CAST(Designation AS VARCHAR(36))  as Designation, 
	ISNULL(SUM(TRY_CAST(Target AS DECIMAL(10,2))), 0) AS Target, CAST(TeamTarget AS VARCHAR(36)) as TeamTarget,
	CAST(SubGoalCondition AS VARCHAR(36))  as SubGoalCondition, CAST(Subgoal AS VARCHAR(36)) as Subgoal
INTO #LSQTargetTestRide --LSQTargettemp 
FROM 
(SELECT TR.*, Designation, mx_Custom_2 AS branch, mx_Custom_5 AS BU, mx_Custom_10 AS dealer_code, Firstname,PhoneMobile FROM (SELECT TemplateId, RecurrenceId, userID, SubGoalCondition, SUM(TRY_CAST(Target AS DECIMAL(10,2))) AS Target,TeamTarget,
RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, Subgoal FROM LSQ_TARGET_DISTRIBUTION_DATA
 WHERE TemplateId = '6281ca46-98cc-4521-9d45-2f1bdfd0e7b4' 

 GROUP BY TemplateId, RecurrenceId, userID, RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, TeamTarget,
 SubGoalCondition, Subgoal) TR 
 JOIN LSQ_Users LS ON LS.userID = TR.userID 
 WHERE mx_Custom_5 = 'CV' --AND Designation IN ('DSE', 'Sales Manager', 'M', 'GM')
 ) a 
 GROUP BY TemplateId, RecurrenceId, RecurrenceStartDate, RecurrenceEndDate, RecurrenceStatus, dealer_code, branch, Designation, userID, TeamTarget,
 Firstname,PhoneMobile, SubGoalCondition, Subgoal;
 
 
 
INSERT INTO ASM_CV_ENQUIRY_TARGET
SELECT  
DEALERCODE,
SKU,
FK_DEALERCODE,
FK_SKU,
FK_TYPE_ID,
DATE,
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
COMPANYTYPE,
BRANCHID,
TEHSILID,
SALES_PERSON,
ACTUALQUANTITY,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
CDMS_BATCHNO,
TARGETQUANTITY,
PERIODNAME,
COLOUR_CODE,
MODELCODE,
FK_MODEL,
FLAG,
BaseFlag,
Leadtype,
Campaign_Code,
Salesperson_id,
Designation,
recurrence_id,
Subgoal,
PhoneMobile, Model, TeamTarget
from(
SELECT 
dealer_code as  DEALERCODE
,CAST('' AS VARCHAR(50)) AS SKU
,CAST('' AS INT) AS FK_DEALERCODE
,CAST('' AS INT) AS FK_SKU
,10010 AS FK_TYPE_ID
,RecurrenceStartDate AS DATE  ----------Convert
,TemplateId  AS ENQUIRYLINEID  --null  AS RETAILLINEID  --TemplateId
,Null AS FK_ENQUIRYDOCID   --null  AS FK_RETAILDOCID   --RecurrenceId
,CAST(NULL AS DECIMAL(19,0)) AS COMPANYTYPE
,BM.Branchid AS BRANCHID
,CAST(NULL AS DECIMAL(19,0)) AS TEHSILID
,Firstname AS SALES_PERSON
,CAST(NULL AS DECIMAL(10,0)) AS ACTUALQUANTITY
,GETDATE() AS LASTUPDATEDDATETIME
,null as IMPORTEDDATE
,null as CDMS_BATCHNO
,ISNULL(TRY_CAST(Target AS DECIMAL(10,2)), 0) AS TARGETQUANTITY
,null as PERIODNAME
,CAST('' AS VARCHAR(25)) AS COLOUR_CODE
,P.MODELCODE
,CAST(NULL AS INT) AS FK_MODEL
,100012 As FLAG
,0 AS BaseFlag
,'KAM' as LEADTYPE 
,NULL AS Campaign_Code 
,userID as Salesperson_id
,Designation as Designation
,RecurrenceId as recurrence_id,
Subgoal as Subgoal,
PhoneMobile as PhoneMobile,
LTRIM(RTRIM(REPLACE(LT.Subgoalcondition, 'Brand = ', ''))) as Model,
TeamTarget
FROM
#LSQTargetTestRide LT
left JOIN BRANCH_MASTER BM ON LT.BRANCH=BM.CODE
left JOIN (
    SELECT Model, Modelcode,
    
           ROW_NUMBER() OVER (PARTITION BY finance_category order by Brand ) AS rn
    FROM ASM_CV_PRODUCT_DIM P
) P ON LTRIM(RTRIM(REPLACE(LT.Subgoalcondition, 'Brand = ', ''))) = P.Model

)B



--************************************************************
--PRODUCT MASTER AND DEALER MASTER FK UPDATE: ASM_CV_ENQUIRY_TARGET
--STEP 4:
UPDATE B SET B.FK_MODEL=C.PK_MODEL_CODE FROM ASM_CV_ENQUIRY_TARGET B INNER JOIN ASM_CV_PRODUCT_DIM C ON (B.MODELCODE=C.MODELCODE)
UPDATE B SET B.FK_DEALERCODE=C.PK_DEALERCODE FROM ASM_CV_ENQUIRY_TARGET B INNER JOIN ASM_CV_DEALER_MASTER_DIM C ON (B.DEALERCODE=C.DEALERCODE)



/* ------------------------------------------------------------------------------------------------------------------------------------
---------------------------STEP 2.2 LOAD LSQ DATA INTO ENQUIRY FACT LSQ TRANSACTIONS DATA----------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------- */
TRUNCATE TABLE ASM_CV_ENQUIRY_FACT_LSQ_STG
INSERT INTO ASM_CV_ENQUIRY_FACT_LSQ_STG

SELECT DEALERCODE, 
SKU,
FK_DEALERCODE, 
FK_SKU,  
FK_TYPE_ID,
DATE,
ENQUIRYLINEID,
FK_ENQUIRYDOCID,
COMPANYTYPE,
BRANCHID,
TEHSILID,
REPLACE(SALES_PERSON,CHAR(160),'') SALES_PERSON,
ISNULL(COUNT(PROSPECTID),0) AS ACTUALQUANTITY ,
LASTUPDATEDDATETIME,
IMPORTEDDATE,
CDMS_BATCHNO ,
TARGETQUANTITY,
PERIODNAME
,COLOUR_CODE, 
MODELCODE, 
FK_MODEL,
FLAG, 
BaseFlag,
LeadType,
Campaign_Code,
PINCODE, 
AREA,
First_Source_Lead_Type,
First_Mode_Source,
First_Mode_SubSource,
Salesperson_id, PhoneMobile
 FROM 
(SELECT
	DISTINCT
	CM.CODE AS DEALERCODE,
	CASE WHEN LSQ_PACTEXTBASE.MX_CUSTOM_18 IS NULL THEN COALESCE (LSQ_PACTEXTBASE.MX_CUSTOM_12,(CASE WHEN LSQ_PACTEXTBASE.MX_CUSTOM_25 LIKE '%00%' THEN
    SUBSTRING (LSQ_PACTEXTBASE.MX_CUSTOM_25,1,6)END))  ELSE IM.CODE END +CASE WHEN LSQ_PACTEXTBASE.MX_CUSTOM_26 IS NULL AND LSQ_PACTEXTBASE.MX_CUSTOM_25 LIKE '%00%'  THEN SUBSTRING (LSQ_PACTEXTBASE.MX_CUSTOM_25,7,2) ELSE IV.CODE 
	END SKU, 
	CAST(0 AS INT) AS FK_DEALERCODE,
	CAST(0 AS INT) AS FK_SKU,
	10001 AS FK_TYPE_ID,
	--CAST(LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE AS DATE) AS DATE,
	
	DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE))) AS DATE,
	
	LSQ_PACTEXTBASE.PROSPECTACTIVITYEXTENSIONID AS ENQUIRYLINEID,
	LSQ_PBASE.PROSPECTID AS FK_ENQUIRYDOCID,
	7 AS COMPANYTYPE,
	BM.BRANCHID,
	CAST(NULL AS DECIMAL(19,0)) AS TEHSILID,
	
REPLACE(REPLACE(REPLACE( U.FirstName,' ',' |'),'| ',''),' |',' ') AS SALES_PERSON,	
    ISNULL((LSQ_PBASE.PROSPECTID),0) AS PROSPECTID,
	--GETDATE() AS LASTUPDATEDDATETIME,
	DATEADD(MI,30,(DATEADD(HH,5,GETDATE()))) AS LASTUPDATEDDATETIME,
	
	--LSQ_PBASE.MODIFIEDON AS IMPORTEDDATE,
	DATEADD(MI,30,(DATEADD(HH,5,LSQ_PBASE.MODIFIEDON ))) AS IMPORTEDDATE,
	
	NULL AS CDMS_BATCHNO,
	CAST(0 AS DECIMAL(19,0)) AS TARGETQUANTITY,
	--(LEFT(DATENAME( MONTH,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE),3)+'-'+CAST(YEAR(LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE) AS VARCHAR(4))) AS   	   PERIODNAME,
	 (LEFT(DATENAME( MONTH,DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE)))),3)+'-'+CAST(YEAR(DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE)))) AS VARCHAR(4))) AS PERIODNAME,
	
	CASE WHEN LSQ_PACTEXTBASE.MX_CUSTOM_26 IS NULL AND LSQ_PACTEXTBASE.MX_CUSTOM_25 LIKE '%00%'  THEN SUBSTRING (LSQ_PACTEXTBASE.MX_CUSTOM_25,7,2) ELSE IV.CODE 
	END AS COLOUR_CODE, -- NO MAPPING
    CASE WHEN LSQ_PACTEXTBASE.MX_CUSTOM_18 IS NULL THEN COALESCE (LSQ_PACTEXTBASE.MX_CUSTOM_12,(CASE WHEN LSQ_PACTEXTBASE.MX_CUSTOM_25 LIKE '%00%' THEN
    SUBSTRING (LSQ_PACTEXTBASE.MX_CUSTOM_25,1,6)END))  ELSE IM.CODE END AS MODELCODE,
	CAST(0 AS INT) AS FK_MODEL,
	100011 AS FLAG,
	1 AS BASEFLAG,
	ISNULL(LSQ_PBASE.MX_ENQUIRY_MODE, LSQ_PBASE.mx_Mode_of_Enquiry) AS LEADTYPE, 
	LSQ_PEXTBASE.mx_CV_Campaign_Code as Campaign_Code,
	 LSQ_PBASE.MX_PINCODE AS PINCODE, 
     LSQ_PBASE.MX_AREA AS AREA,
   CASE WHEN CAST(LSQ_PEXTBASE.mx_Dealer_Assignment_Date AS DATE)>='2024-12-01' THEN COALESCE(PE.mx_Qualified_First_Source,     	LSQ_PBASE.mx_Enquiry_Mode,LSQ_PBASE.MX_MODE_OF_ENQUIRY,'KAM')
   ELSE COALESCE(LSQ_PBASE.mx_Enquiry_Mode, LSQ_PBASE.MX_MODE_OF_ENQUIRY,'KAM') END  AS First_Source_Lead_Type,
   ISNULL(PE.mx_Qualified_Source_of_Enquiry,'Not Available') AS First_Mode_Source,
   ISNULL(PE.mx_Qualified_Sub_Source,'Not Available') AS First_Mode_SubSource,
   U.Userid AS Salesperson_id,
   U.PhoneMobile as PhoneMobile
														 
FROM
	LSQ_PROSPECT_BASE LSQ_PBASE
	
	INNER JOIN DBO.BRANCH_MASTER BM ON LSQ_PBASE.MX_BRANCH_CODE=BM.CODE
	
	INNER JOIN DBO.COMPANY_MASTER CM ON CM.COMPANYID=BM.COMPANYID
	
	LEFT JOIN LSQ_PROSPECT_EXTENSIONBASE LSQ_PEXTBASE
	ON (LSQ_PBASE.PROSPECTID = LSQ_PEXTBASE.PROSPECTID) 
	
	LEFT JOIN LSQ_Prospect_Extension2Base PE
        ON (LSQ_PBASE.ProspectId = PE.ProspectId) 


	INNER JOIN LSQ_PROSPECTACTIVITY_EXTENSIONBASE LSQ_PACTEXTBASE
	ON (LSQ_PBASE.PROSPECTID = LSQ_PACTEXTBASE.RELATEDPROSPECTID) 

	
	LEFT JOIN ITEM_MASTER IM
	ON CAST(IM.ITEMID AS VARCHAR(50))=LSQ_PACTEXTBASE.MX_CUSTOM_18
	
	LEFT JOIN ITEMVARMATRIX_MASTER IV
	ON CAST(IV.ITEMVARMATRIXID AS VARCHAR(50))=LSQ_PACTEXTBASE.MX_CUSTOM_26
	
	LEFT JOIN LSQ_users U on LSQ_PBASE.OwnerId=U.UserID
	
	WHERE LSQ_PACTEXTBASE.ACTIVITYEVENT=12003
	AND LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE IS NOT NULL
	
	
	
	
AND CAST (DATEADD(MI,30,(DATEADD(HH,5,LSQ_PEXTBASE.MX_DEALER_ASSIGNMENT_DATE))) AS DATE )  BETWEEN '2020-04-01' AND CAST(GETDATE()-1 AS DATE) 
--AND DATEADD(MI,30,(DATEADD(HH,5,LSQ_PBASE.MODIFIEDON))) >= CAST((SELECT MAX(IMPORTEDDATE) FROM ASM_CV_ENQUIRY_FACT_LSQ_STG) AS DATE) --UPDATED ON 12/08
	) TMP
	GROUP BY 
DEALERCODE, SKU,FK_DEALERCODE, FK_SKU,  FK_TYPE_ID,DATE,ENQUIRYLINEID,
 FK_ENQUIRYDOCID,COMPANYTYPE,BRANCHID,TEHSILID,SALES_PERSON,LASTUPDATEDDATETIME,IMPORTEDDATE,CDMS_BATCHNO ,TARGETQUANTITY,PERIODNAME
,COLOUR_CODE, MODELCODE, FK_MODEL,FLAG, BASEFLAG,LEADTYPE,Campaign_Code,PINCODE,AREA,First_Source_Lead_Type,First_Mode_Source,First_Mode_SubSource,Salesperson_id,
PhoneMobile;




DELETE FROM ASM_CV_ENQUIRY_FACT_LSQ_STG WHERE DATE>CAST(GETDATE()-1 AS DATE)  ;
--DEDUP PROCESS:
WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY FK_ENQUIRYDOCID,ENQUIRYLINEID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ENQUIRY_FACT_LSQ_STG                 
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;  

  --*****************************************************
  --*******************************************************
  --STEP 2:
--PRODUCT MASTER AND DEALER MASTER FK UPDATE: ASM_CV_ENQUIRY_STG
UPDATE B SET B.FK_SKU=C.PK_SKU FROM ASM_CV_ENQUIRY_FACT_LSQ_STG B INNER JOIN ASM_CV_PRODUCT_SKU_DIM C ON (B.SKU=C.SKU_CODE)
UPDATE B SET B.FK_MODEL=C.PK_MODEL_CODE FROM ASM_CV_ENQUIRY_FACT_LSQ_STG B INNER JOIN ASM_CV_PRODUCT_DIM C ON (B.MODELCODE=C.MODELCODE)
UPDATE B SET B.FK_DEALERCODE=C.PK_DEALERCODE FROM [DBO].[ASM_CV_ENQUIRY_FACT_LSQ_STG] B INNER JOIN ASM_CV_DEALER_MASTER_DIM C ON (B.DEALERCODE=C.DEALERCODE)



/* ------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------STEP 2.3  UNION OF CDMS AND LSQ DATA---------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------- */

TRUNCATE TABLE ASM_CV_ENQUIRY_FACT

INSERT INTO ASM_CV_ENQUIRY_FACT( DEALERCODE, SKU, FK_DEALERCODE, FK_SKU, FK_TYPE_ID, DATE, ENQUIRYLINEID, FK_ENQUIRYDOCID, COMPANYTYPE, BRANCHID, TEHSILID, SALES_PERSON, ACTUALQUANTITY, LASTUPDATEDDATETIME, IMPORTEDDATE, CDMS_BATCHNO, TARGETQUANTITY, PERIODNAME, COLOUR_CODE, MODELCODE, FK_MODEL, FLAG, BaseFlag, LEADTYPE, Campaign_Code, Pincode, Area, First_Source_Lead_Type, First_Mode_Source, First_Mode_SubSource, Salesperson_id, Designation, recurrence_id, Subgoal,PhoneMobile, Model,TeamTarget)
SELECT *,Null As Pincode,Null As Area, Null As First_Source_Lead_Type,Null As First_Mode_Source,Null As First_Mode_SubSource, Null As Salesperson_id, Null As Designation, null as Recurrence_id, null as Subgoal, null as PhoneMobile, null as Model, null as TeamTarget FROM ASM_CV_ENQUIRY_STG
UNION
SELECT DEALERCODE, SKU, FK_DEALERCODE, FK_SKU, FK_TYPE_ID, DATE, ENQUIRYLINEID, FK_ENQUIRYDOCID, COMPANYTYPE, BRANCHID, TEHSILID, SALES_PERSON, ACTUALQUANTITY, LASTUPDATEDDATETIME, IMPORTEDDATE, CDMS_BATCHNO, TARGETQUANTITY, PERIODNAME, COLOUR_CODE, MODELCODE, FK_MODEL, FLAG, BaseFlag, LEADTYPE, Campaign_Code, Null as Pincode, Null as  Area,Null as First_Source_Lead_Type,Null as First_Mode_Source, Null as First_Mode_SubSource, Salesperson_id, Designation, recurrence_id, Subgoal,PhoneMobile, Model, TeamTarget
FROM ASM_CV_ENQUIRY_TARGET
UNION						   	 
SELECT DEALERCODE, SKU, FK_DEALERCODE, FK_SKU, FK_TYPE_ID, DATE, ENQUIRYLINEID, FK_ENQUIRYDOCID, COMPANYTYPE, BRANCHID,
    TEHSILID, SALES_PERSON, ACTUALQUANTITY, LASTUPDATEDDATETIME, IMPORTEDDATE, CDMS_BATCHNO, TARGETQUANTITY,
    PERIODNAME, COLOUR_CODE, MODELCODE, FK_MODEL, FLAG, BaseFlag, LEADTYPE, Campaign_Code,
    PINCODE, AREA, First_Source_Lead_Type, First_Mode_Source, First_Mode_SubSource, Salesperson_id
, Null As Designation, null as Recurrence_id,  null as Subgoal,  PhoneMobile, null as Model, null as TeamTarget  FROM ASM_CV_ENQUIRY_FACT_LSQ_STG



/* ------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------STEP 2.4  UPDATE RETAILCONVERSIONFLAG FOR CDMS-----------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------- */

--RETAILCONVERSION FLAG:

--LOGIC COMMENT ON 09TH FEB 2023: UPDATED LOGIC
--INSERT INTO ASM_CV_ENQTORET_CONVERSION
--SELECT DISTINCT 
--EL.FK_ENQUIRYDOCID,
--EL.DATE,
--RETAILCONVERSIONFLAG=1,
--EL.IMPORTEDDATE,
--GETDATE() AS CREATEDDATETIME
----**INTO ASM_CV_ENQTORET_CONVERSION
--FROM 
--ASM_CV_ENQUIRY_FACT EL 
--JOIN BOOKING_LINE BL ON (EL.ENQUIRYLINEID=BL.ENQUIRYDATALINEID)  
--JOIN RETAIL_LINE RL ON (BL.LINEID=RL.BOOKINGDATALINEID) 
--WHERE
----[DATE] BETWEEN '2023-01-03' AND '2023-01-03'
--[DATE]>(SELECT MAX(DATE) FROM ASM_CV_ENQTORET_CONVERSION)

--UPDATE ED
--SET ED.RETAILCONVERSIONFLAG=ERC.RETAILCONVERSIONFLAG
--FROM ASM_CV_ENQUIRY_DIM ED  JOIN ASM_CV_ENQTORET_CONVERSION ERC  ON (ED.PK_ENQUIRYHEADERID=ERC.FK_ENQUIRYDOCID)



--BOOKING:
--LOGIC COMMENT ON 09TH FEB 2023: UPDATED LOGIC
UPDATE ED
SET ED.RETAILCONVERSIONFLAG=1
FROM ASM_CV_ENQUIRY_DIM ED 
JOIN ENQUIRY_LINE EL ON (ED.PK_ENQUIRYHEADERID=EL.DOCID)
INNER JOIN BOOKING_LINE BL ON (EL.LINEID=BL.ENQUIRYDATALINEID)
INNER JOIN RETAIL_LINE RL ON (BL.LINEID=RL.BOOKINGDATALINEID) 
WHERE ED.BASEFLAG=0 

--- RETAIL CONVERSION FLAG UPDATE FOR LSQ ----
UPDATE ED
SET ED.RETAILCONVERSIONFLAG=1
FROM ASM_CV_ENQUIRY_DIM ED 
JOIN  LSQ_PROSPECT_BASE LSQ_PBASE ON (LSQ_PBASE.PROSPECTID=ED.PK_ENQUIRYHEADERID)
JOIN  LSQ_PROSPECTACTIVITY_EXTENSIONBASE PAE ON (LSQ_PBASE.PROSPECTID=PAE.RELATEDPROSPECTID AND PAE.ACTIVITYEVENT=12003)-- AND PAE.MX_CUSTOM_48 IS NULL)--NOTE:COMMENTING THIS CONDITION BECAUSE THE COUNT OF E2R SEEMED LESS BY THIS CONDITION
JOIN BOOKING_HEADER_EXT BHE ON (CAST(LSQ_PBASE.PROSPECTID+','+PAE.PROSPECTACTIVITYEXTENSIONID AS VARCHAR(8000))=BHE.LMSBOOKINGID)
JOIN BOOKING_HEADER BH ON (BH.HEADERID = BHE.HEADERID)
INNER JOIN BOOKING_LINE BL ON (BL.HEADERID=BH.HEADERID)
INNER JOIN RETAIL_LINE RL ON (BL.LINEID=RL.BOOKINGDATALINEID)
WHERE ED.BASEFLAG=1
AND LMSBOOKINGID IS NOT NULL;

--- RETAIL CONVERSION FLAG UPDATE FOR CDMS ----
UPDATE ED
SET ED.RETAILCONVERSIONFLAG=1
FROM ASM_CV_ENQUIRY_DIM ED JOIN ENQUIRY_LINE EL ON (ED.PK_ENQUIRYHEADERID=EL.DOCID)
INNER JOIN BOOKING_LINE BL ON (EL.LINEID=BL.ENQUIRYDATALINEID)
INNER JOIN ALLOCATION_LINE AL ON (BL.LINEID=AL.BOOKINGDATALINEID)
INNER JOIN RETAIL_LINE RL ON (AL.LINEID=RL.ALLOCATIONDATALINEID)
WHERE ED.BASEFLAG=0

--- RETAIL CONVERSION FLAG UPDATE FOR LSQ ----
UPDATE ED
SET ED.RETAILCONVERSIONFLAG=1
FROM ASM_CV_ENQUIRY_DIM ED 
JOIN  LSQ_PROSPECT_BASE LSQ_PBASE ON (LSQ_PBASE.PROSPECTID=ED.PK_ENQUIRYHEADERID)
JOIN  LSQ_PROSPECTACTIVITY_EXTENSIONBASE PAE ON (LSQ_PBASE.PROSPECTID=PAE.RELATEDPROSPECTID AND PAE.ACTIVITYEVENT=12003 )--AND PAE.MX_CUSTOM_48 IS NULL)--NOTE:COMMENTING THIS CONDITION BECAUSE THE COUNT OF E2R SEEMED LESS BY THIS CONDITION
JOIN BOOKING_HEADER_EXT BHE ON (CAST(LSQ_PBASE.PROSPECTID+','+PAE.PROSPECTACTIVITYEXTENSIONID AS VARCHAR(8000))=BHE.LMSBOOKINGID)
JOIN BOOKING_HEADER BH ON (BH.HEADERID = BHE.HEADERID)
INNER JOIN BOOKING_LINE BL ON (BL.HEADERID=BH.HEADERID)
INNER JOIN ALLOCATION_LINE AL ON (BL.LINEID=AL.BOOKINGDATALINEID)
INNER JOIN RETAIL_LINE RL ON (AL.LINEID=RL.ALLOCATIONDATALINEID)
WHERE ED.BASEFLAG=1
AND LMSBOOKINGID IS NOT NULL;
/*SELECT BHE.LMSBOOKINGID , BH.HEADERID, BL.LINEID
FROM BOOKING_HEADER_EXT BHE
JOIN BOOKING_HEADER BH ON (BH.HEADERID=BHE.HEADERID)
JOIN BOOKING_LINE BL ON (BL.HEADERID=BH.HEADERID)
WHERE (LMSBOOKINGID IS NOT NULL AND LMSBOOKINGID <>'')*/


--- > IT WILL WORK FOR 
/*SELECT DISTINCT LMSBOOKINGID FROM BOOKING_HEADER_EXT; -- PROSPECTID,OPPORTUNITYID*/
--- DHANRAJ TO SHARE DETAILS
--ALLOCATION:

/*SELECT DISTINCT LMSBOOKINGID FROM BOOKING_HEADER_EXT; -- PROSPECTID,OPPORTUNITYID*/
--ALLOCATION:


-- JOIN WITH LSQ EXT BASE FIRST
-- THEN JOIN EXT BASE WITH USING BELOW
/*SELECT
CAST(PB.PROSPECTID+','+PAE.PROSPECTACTIVITYEXTENSIONID AS VARCHAR(8000)) AS LMSBOOKINGID
FROM
LSQ_PROSPECT_BASE PB 
INNER JOIN LSQ_PROSPECTACTIVITY_EXTENSIONBASE PAE ON (PB.PROSPECTID=PAE.RELATEDPROSPECTID AND PAE.ACTIVITYEVENT=12003 AND PAE.MX_CUSTOM_48 IS NULL)*/
--JOIN WITH LMSBOOKINGID FROM BOOKING_HEADER_EXT
--JOIN BOOKING HEADER EXT  TO BOOKING LINE 
-- JOIN BOOKING LINE WITH RETAIL AS IS 


-- OR--
--UPDATE ED
--SET ED.RETAILCONVERSIONFLAG=1
--FROM ASM_CV_ENQUIRY_DIM ED JOIN ENQUIRY_LINE EL ON (ED.PK_ENQUIRYHEADERID=EL.DOCID)
--INNER JOIN BOOKING_LINE BL ON (EL.LINEID=BL.ENQUIRYDATALINEID)
--INNER JOIN ALLOCATION_LINE AL ON (BL.LINEID=AL.BOOKINGDATALINEID)
--INNER JOIN RETAIL_LINE RL ON (AL.LINEID=RL.ALLOCATIONDATALINEID)
--WHERE ED.BASEFLAG=0;



END
GO


