
/****** Object:  StoredProcedure [dbo].[USP_ASM_CV_ALLOCATION_REFRESH]    Script Date: 01-12-2023 15:03:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_Full_Load_ASM_CV_ALLOCATION_REFRESH] AS
BEGIN

--Allocation Dim & Fact:
Truncate table ASM_CV_ALLOCATION_DIM
Truncate table ASM_CV_ALLOCATION_FACT

INSERT INTO ASM_CV_ALLOCATION_DIM
SELECT DISTINCT 
ALLOCATION_HEADER.HEADERID AS PK_ALLOCATIONHEADERID,
CAST(ALLOCATION_HEADER.DOCDATE AS DATE) AS ALLOCATIONDATE,
GETDATE() AS [CREATEDATETIME],
ALLOCATION_HEADER.IMPORTEDDATE,
ALLOCATION_HEADER.CDMS_BATCHNO
--INTO ASM_CV_ALLOCATION_DIM
FROM ALLOCATION_HEADER INNER JOIN COMPANY_MASTER ON (ALLOCATION_HEADER.COMPANYID=COMPANY_MASTER.COMPANYID AND
COMPANY_MASTER.COMPANYTYPE = 7)
WHERE  --1=2
--CAST(ALLOCATION_HEADER.DOCDATE AS DATE) BETWEEN '2020-04-01' AND '2023-05-07' -- (501279 rows affected)
--CAST(ALLOCATION_HEADER.DOCDATE AS DATE)>'2022-11-24'
CAST(ALLOCATION_HEADER.DOCDATE AS DATE) BETWEEN '2020-04-01' AND  Cast(Getdate()-1 as date)
--ALLOCATION_HEADER.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_CV_ALLOCATION_DIM)

--

DELETE FROM ASM_CV_ALLOCATION_DIM WHERE ALLOCATIONDATE>Cast(Getdate()-1 as date)


--Dedup:

  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY PK_ALLOCATIONHEADERID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ALLOCATION_DIM                  
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1;   


--***************************************************************************
--AllCation Fact:

INSERT INTO ASM_CV_ALLOCATION_FACT
SELECT 
DISTINCT
CM.CODE AS DEALERCODE,
IM.CODE+IV.CODE As SKU,
Cast(0 as int) AS FK_DealerCode,
Cast(0 as int) AS FK_SKU,
10007 AS FK_TYPE_ID,
CAST(AH.DOCDATE AS DATE) AS DATE,
AL.LINEID AS AllocationLineID,
AL.DOCID AS FK_AllocationDocID,
CM.COMPANYTYPE AS COMPANYTYPE,
COUNT(AH.HEADERID) AS ACTUALQUANTITY,
getdate() as LASTUPDATEDDATETIME,
AH.IMPORTEDDATE,
IM.CODE As MODEL,
Cast(0 as int) As FK_MODEL,
Cast(0 As decimal(19,0)) As FLAG
--INTO  ASM_CV_ALLOCATION_FACT
FROM 
ALLOCATION_HEADER AH INNER JOIN COMPANY_MASTER CM ON (AH.COMPANYID=CM.COMPANYID AND CM.COMPANYTYPE = 7)
INNER JOIN ALLOCATION_LINE AL ON (AH.HEADERID=AL.DOCID)
JOIN ITEM_MASTER IM ON (IM.ItemId=AL.ItemID)
LEFT JOIN ITEMVARMATRIX_MASTER IV ON (AL.VARMATRIXID=IV.ITEMVARMATRIXID)
WHERE 
  --CAST(AH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND '2023-05-07' -- (504749 rows affected
--CAST(AH.DOCDATE AS DATE)>'2022-11-24'
CAST(AH.DOCDATE AS DATE) BETWEEN '2020-04-01' AND  Cast(Getdate()-1 as date)
--AH.IMPORTEDDATE>(SELECT MAX(IMPORTEDDATE) FROM ASM_CV_ALLOCATION_FACT)
GROUP BY
CM.CODE,
IM.CODE+IV.CODE,
CAST(AH.DOCDATE AS DATE),
AL.LINEID,
AL.DOCID,
CM.COMPANYTYPE,
AH.IMPORTEDDATE,
IM.CODE 


--
DELETE FROM ASM_CV_ALLOCATION_FACT WHERE DATE>Cast(Getdate()-1 as date)

--Dedup Process:


  ;WITH CTE AS                  
 (                  
  SELECT *,                  
   ROW_NUMBER()OVER(PARTITION BY FK_AllocationDocID,AllocationLineID ORDER BY IMPORTEDDATE DESC)RNK                   
  FROM ASM_CV_ALLOCATION_FACT                
 )                  
DELETE FROM CTE                  
 WHERE RNK<>1; 

--**************************************************************************************************************

update B set B.FK_SKU=C.PK_SKU from ASM_CV_ALLOCATION_FACT B INNER JOIN ASM_CV_PRODUCT_SKU_DIM C on (B.SKU=C.SKU_CODE) -- (504745 rows affected)
update B set B.FK_MODEL=C.PK_Model_Code from ASM_CV_ALLOCATION_FACT B INNER JOIN ASM_CV_PRODUCT_DIM C on (B.MODELCODE=C.MODELCODE) -- (504745 rows affected)
update B set B.FK_DEALERCODE=C.PK_DEALERCODE from [dbo].[ASM_CV_ALLOCATION_FACT] B INNER JOIN ASM_CV_DEALER_MASTER_DIM C on (B.DEALERCODE=C.DEALERCODE) -- (504747 rows affected)

--**************************************************************************


END
GO


